apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: controller-observability
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RXyDYyvgWezS17fr3lgxZMaumyNBfahUKPBchIH1Hgg=,iv:tUlpMb0cRID9C1sOvvQTuP8y2nEIGcvaIbF3BrAsmik=,tag:nSRDXTk6tvIut0wONHkZ1Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KmOEgtyXrFm7erdkjC1klGlqqiHDBIwIbBpQFlfN9U8=,iv:I5a9sAwNNJnTpfaRw4+xzcvUMs5BlQlmoVspKsYPz4U=,tag:coDKn0u3GMIOLwv03xGfBg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSlgxRTJja3dWM1Exbkw0
            a0xHOWxwaTlRa2Y4T000ODM3NElLdUNvS3lFClM4a2krUVFEMGt5Q3BDNUpQT1Jm
            M0JpL0gzYTlmL1VNdGkwUGhnREw0b0EKLS0tIHNtMHhlWm01Vi9nOHZxVHZzalV0
            VXZHODNKam9PTkNqcDJkTVJFRUkvd1kKf2xrheVg29pxNFlmiLR+5LBkym4ZHCBD
            DeWz28l9DHAa2dBXdvKu67OPfnPUdfj68rYOnRAoOyVMRB6vUTl1BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM3VLNjg4QkdKeGJ4Q01F
            bGl4R0xIYTJNb1VqOVlWZVhTZDJsbFZRU2tzClYyZ24zaCsxMXVrbzl4Mmh1eUc1
            TjhibXVGWmNiVE5FVVpnN00weVBRSm8KLS0tIEgwVzFxTHgwUjFOY21DMWZqdVVJ
            VEg4dzZtZ3RSME9QUTQyaFZEcmFZV3MKWk+UfIhpd4mbgk//RgLlsb5GbaAOLwBp
            cMwzx/yQQgyrGrPyga7cvpvOH/qivu/xFh5F7hzgQzrWGVgMO6tDxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T11:53:24Z"
    mac: ENC[AES256_GCM,data:RK38khUw9Q2GDpwbxnID+anA/iflJ8vjnp+VZVwMhH/OIHnBS8mn4BAeeInodnPWVTrT9vGdhFxZ9/O9E6u6tYpkgHhMVNTZ6aAnt7lpG1hcFUMuTiSIfIAIASpIxcFqPFCCqdBY+uXgT8QLVXbJVZo3NHHjOMYs2YHCEoPyRpk=,iv:yhpjWgeniJwLPnehjlZlA0itXx3reEOC+Zw0EPH2kpU=,tag:yevM6133ZIjDpHE3uYaSxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
