apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: nextcloud
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  podSecurityContext:
    fsGroup: 33
    fsGroupChangePolicy: "OnRootMismatch"
  backend:
    repoPasswordSecretRef:
      name: s3-ovh
      key: RESTIC_PASSWORD
    s3:
      endpoint: https://s3.sbg.io.cloud.ovh.net 
      bucket: ""
      accessKeyIDSecretRef:
        name: s3-ovh
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: s3-ovh
        key: AWS_SECRET_ACCESS_KEY
  backup:
    schedule: '0 2 * * *' # tous les jours à 02h00
  check:
    schedule: '0 3 * * 1' # vérification chaque lundi
  prune:
    schedule: '0 4 * * 1' # nettoyage chaque lundi
    retention:
      keepDaily: 7    # 1 snapshot par jour pendant 7 jours
      keepWeekly: 4   # 1 snapshot par semaine pendant 4 semaines
      keepMonthly: 6  # 1 snapshot par mois pendant 6 mois


---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: pre-backup
  annotations:
    k8up.io/backup: "true"
spec:
  backupCommand: sh -c 'mysqldump --no-tablespaces --skip-set-charset --set-gtid-purged=OFF --single-transaction -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u $NEXTCLOUD_MYSQL_USER -p"$NEXTCLOUD_MYSQL_PASSWORD" $NEXTCLOUD_MYSQL_DATABASE'
  fileExtension: .sql
  pod:
    spec:
      containers:
        - name: nextcloud-db-dump
          image: mysql:8.4.3
          command: ["sleep", "infinity"]
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: NEXTCLOUD_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: mariadb-username
            - name: NEXTCLOUD_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: mariadb-password
            - name: NEXTCLOUD_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: mariadb-database