---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  url: nextcloud https://nextcloud.github.io/helm/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${TENANT}-nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 5m
  timeout: 3m
  install:
    remediation:
      retries: 3