---
apiVersion: v1
kind: Namespace
metadata:
  name: ${tenant}-dolibarr
  labels:
    alter-it.eu/tenant: "${tenant}"
    alter-it.eu/app: "dolibarr"
    alter-it.eu/managed-by: "fluxcd"
    reflector/k8up-credentials: "true"
    reflector/database: "true"