apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  # # shared
  # - catalog/wordpress

  # by-tenant
  #
  - ../../../applications/tenants/le-portail/sync.yaml
  - ../../../applications/tenants/le-portail/components/subdomain/sync.yaml
  - ../../../applications/tenants/le-portail/dolibarr/overrides/production/sync.yaml

  - ../../../applications/tenants/ferme-du-jointout/sync.yaml
  - ../../../applications/tenants/ferme-du-jointout/components/subdomain/sync.yaml
  - ../../../applications/tenants/ferme-du-jointout/dolibarr/overrides/production/sync.yaml

