apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources: []
  # # shared
  # - catalog/wordpress

  # # by-tenant
  # - tenants/le-portail/alterconso
  # - tenants/le-portail/dolibarr

  # # by-tenant
  # - tenants/ferme-du-jointout/nextcloud
  # - tenants/ferme-du-jointout/dolibarr