apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:cY767WujOkOL5QJ7UBr1gSOsOjv6XJ+mAKaGz0WnLPsNeCjJIeu6qw4IG23og+puzqORpxmM9Z0OkfcngqfIkh7GkjERJjQqfFoWLcrssQu4vuQIta8tgA==,iv:ygxWTeVPJrxamkqG0GxM2dtRu9z//9HNLd2wL13uhGA=,tag:UEYlFoHBrJesF2Sjd82BVQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2K3JqMmtyS20ybWxyS2s3
            YU03UTNjZWJSN0FtdmV4aGQ2QlpwZitsSURJCnlOZWE5eUhHaHBMbS9BbnUwUDlu
            SEd4QVBpY0RITHVYSXNhU3dHWHQ0VHMKLS0tIG9YTHlGTGVucFNVbCt3a01oZmxI
            RE1MbHJzcGMyUkRZQ3hpU3BGK0NVSzQKTuP1S1UhElkLyjiqz2s8f9C6O53XmihR
            NPiGHss+g86TMRcC8A5mESwUDRrFD1hulTzLwAcyVj01LKiQBaEZIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T19:31:02Z"
    mac: ENC[AES256_GCM,data:WSDqt8WpY3oBcXddw4DsVvpJhI1kz7ZmrjF+yimT5hGkg978BPgb7LoLGXfw30Q8NuDlGIjvtqduAE1j4sYdGFaUy+2lxXl/EEgkCeymfpjBz+h8KCjoyaaanGAkR7FJok/0Ak7huM8VMMWDgGE3Giz7eaezc9Zxl/SSpdskkI4=,iv:zuE8SX4k60Twn+S2rAE0sfx0Wy9lga97laNi6tFRklY=,tag:fQ9gcENURp6zbyEpHLafEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
