apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:ypgB9IUocPzUcOLKonMs9/ZhOU0y5Gzshp3aG4qN7Tyl0RmEm6wyV2BYB9SvlcB+AZjJ96x+qisNsB41Vxs2mUfQx1uzkoche5Quirl3zQ/H5SwVpoKXXQ==,iv:z5v8lBj2VfVadjd31rAEeB1oLgofaQNtYF+2F0Aq+PE=,tag:ovsSg0diNpeXSnAimF8CxQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRUNwZ0Qrd1hhZVBqV3ZM
            YzRkUm4yS2VGbUdnUVFqcDhKcUF6Nnh6R0gwCmprMW9BbE0zL1Q0UkJDc0JyMkJ3
            UndGU1lKbTg2NXVxL1lGMlY4aXhNZlkKLS0tIDdQR2dMUHFHYTExUURPSUFjODcz
            VGNRakVPcmVocmpXY2lBZWJXUFd3RmMKWHMSUCJEjNvYk/nL48P32U9uXYSih1Il
            7/hUUwGWu0ePY9BN00jUNm6EFEJlv0Tinyt0f04jJWKBGN39GfyfRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T07:46:19Z"
    mac: ENC[AES256_GCM,data:7BnENWn4Wk2IYTXj/zd9M35y02ne1yToZUMFbcWJinAzTr45Vsw0OFIJK73ZtK56ncRC9UGUrsIQVZ8g7wt4ShwVNklLTqqjZPMcTXl2g+fxlJwDiIIP+tYmKSCixwqjmnqRGRdnmyu7H4+7XDmULYk+KXECI0ldmRvdNYOUz8c=,iv:RA3VkgSjN5QKl3BO4wgURoBFPipC6ovFRSf7XUOjNog=,tag:65j96RB3EPd2zUyUsqc0ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
