apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:318aEIsL1RF37S6sXnkVztN4ChwP/NKRr5AJ4H4R/IuJMqVk1RCqtxTcA/xUjptuZlFL9dkQjMwyzfbcbLUOj1GFynSW1h9V0wt2VVXZeXtv2fRctlIRFg==,iv:OxtNGWtve2aXr3XEvPqt2+zSEUbhPGEOEPMbtWAcX/E=,tag:SCrLt7pjgcwT/8Mn+beHxA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcS8zaVNlVGdnUlVTWElX
            cU5ad1lQcW02eUJZQnRLOS9hempJWld6WVZ3CkYycWh4SXRhdnFjYVJmMHRVVzZM
            R2d6eVFqNzA2eE5IN0dBQU1jTjlYK28KLS0tIE5NSExGWXpyWDNXc3RtVm5aaVZJ
            TitFRkpmdXl1eWdvenlBQzY1RmZCbncKTDfCW3VH9bg67DCRG3INoM0ozWn7wa+V
            UkR3+LLi8heXq1FlQSUczPVy/ck6oYM1lUZReeH3U9FayE8cvMO7aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T09:09:55Z"
    mac: ENC[AES256_GCM,data:TDn0nyDqkdcP1C9R4NICSt7tVDPFvOtE33x26a+fiWBO93rLyJjZM8WwrP3Q+nqiXWom6UzQxvN/NpJYvCDszb4STHititrfjySqDUALzBexfr4Y1dwjjANpTMAk1Wb0BaRpRvQemplzLoTVpkC2EXePAfOChwd38uMqArdIOVc=,iv:q6BcMaCIbf6mR2iUMOzr48AOthiY0PvUOokmwD6g5to=,tag:OHsvHdQRWpEYJ4VFZqn0Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
