apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-certificate
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
stringData:
    applicationKey: ENC[AES256_GCM,data:P5Aldn44KAQSjWZekj4t0g==,iv:EYz8I0jrK6CTYJvdn2z6z/qNhpWNWUQfq6W7IYi9k7o=,tag:hhDv9JLtrMYcOLYUIN3yyA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:b0tUFm+YUaIy1kClf5RaDjyKWcHqnzI1pv3qEu0XTKM=,iv:+vO3ngxziJy26F4WlKJDQCdzLFUra0IdDIHlw3A5wSc=,tag:hO5zOSSfYwNraOBBoPltqg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:VV5aTFTNL0X7XUAwtfmyYIYsfnOnHHM0EolNFhLt1S8=,iv:7aipDFZp4bGF5xc5sNoial4C8QcQJwG9Ylu26yc629o=,tag:7S1LBYlWyb8/7g/nPDGPFw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEZkSjg4Wkt4NUM0am14
            cVdYK0RpdTFSVFNPK1dYRUFWWll3dDZWa1IwCnMwY25DcWFSLzJ3bU9qZFkzdnRs
            elR0ZkJwMjE3dThtZGlRVVNtL3ZDZDAKLS0tIDFCelIveWZZU1BoZ1Y3bXJMY3ZB
            cEU0MUdWRHBsYlIraC9MVFlIZlB0bE0K7T4y6jExz7GEGShug2IEkzNddpKbo1rA
            xXWtvrLkJJGctz35jQfufMIq5mzQVwNP3Dzkes/Zy9x14ALDS9lhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:03:44Z"
    mac: ENC[AES256_GCM,data:edLPCn+ijNsymsVcoDof3nZQsPkNSWCwZRuKhv22IOPM5udFOY/O5lgYRBCgCoUZRKDJs3WKG06UhUrFuGJKASm9NMBIDDrZELaodcv93N5TdaQAx/T62DE+nedFuGZf04eNkzArfg9osaHu9gdCNUZAqqJuO1hD/ok0eeCe+RQ=,iv:yk86WsIHkKYkA85NilrQ80x8yDBfx0LFiQJaav6Fbhk=,tag:yUhh5MGsMSJR6urU0cZOtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:JVb9ckOI97FYo5DWLyv6BQ==,iv:ZmJrH4X72m7Ipt1x4Tb+6uvyqVThvsbDa/sSCnM8LSo=,tag:nd0C3M9R2wYTYntlJ44x3g==,type:str]
    applicationSecret: ENC[AES256_GCM,data:NyeqpQbd6+rAHHSy8svjVb7b88Q9UG2NVEPJFqqz/oU=,iv:cvFhpJVis4z3Vphm6tw8h5Nfpj2i8pi8uhJYL3GlVpU=,tag:OZd9mBBxPN/ebz0uTzag0g==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:/EX5EyK7RbCZtVsk/8OHHz5baA/MMxVdcUyI49HjYLo=,iv:DeZfJuTcc6DgH5aX/tJfpVK3Q8tVGvKYlslLlAoplTw=,tag:V+gf4UXNUge1hRO5qK4/hw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEZkSjg4Wkt4NUM0am14
            cVdYK0RpdTFSVFNPK1dYRUFWWll3dDZWa1IwCnMwY25DcWFSLzJ3bU9qZFkzdnRs
            elR0ZkJwMjE3dThtZGlRVVNtL3ZDZDAKLS0tIDFCelIveWZZU1BoZ1Y3bXJMY3ZB
            cEU0MUdWRHBsYlIraC9MVFlIZlB0bE0K7T4y6jExz7GEGShug2IEkzNddpKbo1rA
            xXWtvrLkJJGctz35jQfufMIq5mzQVwNP3Dzkes/Zy9x14ALDS9lhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:03:44Z"
    mac: ENC[AES256_GCM,data:edLPCn+ijNsymsVcoDof3nZQsPkNSWCwZRuKhv22IOPM5udFOY/O5lgYRBCgCoUZRKDJs3WKG06UhUrFuGJKASm9NMBIDDrZELaodcv93N5TdaQAx/T62DE+nedFuGZf04eNkzArfg9osaHu9gdCNUZAqqJuO1hD/ok0eeCe+RQ=,iv:yk86WsIHkKYkA85NilrQ80x8yDBfx0LFiQJaav6Fbhk=,tag:yUhh5MGsMSJR6urU0cZOtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:enRijWlJvmnFjHJRg9AvVw==,iv:qgiyOsHOFt+uBhQFzfcIJtrbDEblLdrSaQjU5f0NCqA=,tag:j9P1W3vyD9uS8GaIGQZqwA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:8Vs2xIy8se2GheUPrZyZEGv66Asc8DzA+pmddpLgNQM=,iv:I7E3knUqeMWTiJMHJgzJjhMpMvZjOxi7CxS/w1EL+io=,tag:29sk6NFWshNtE1i5Z3l0zA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:zxCoy79y/eEtknIonSWpZH3SNms3p539qwhCaEkz/qk=,iv:g2G0nKjY59n4RlX7t4N76ux45Wj+r0UzOydH409dvys=,tag:YwI9IQ6ZEHlwa3APs2bxhw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEZkSjg4Wkt4NUM0am14
            cVdYK0RpdTFSVFNPK1dYRUFWWll3dDZWa1IwCnMwY25DcWFSLzJ3bU9qZFkzdnRs
            elR0ZkJwMjE3dThtZGlRVVNtL3ZDZDAKLS0tIDFCelIveWZZU1BoZ1Y3bXJMY3ZB
            cEU0MUdWRHBsYlIraC9MVFlIZlB0bE0K7T4y6jExz7GEGShug2IEkzNddpKbo1rA
            xXWtvrLkJJGctz35jQfufMIq5mzQVwNP3Dzkes/Zy9x14ALDS9lhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:03:44Z"
    mac: ENC[AES256_GCM,data:edLPCn+ijNsymsVcoDof3nZQsPkNSWCwZRuKhv22IOPM5udFOY/O5lgYRBCgCoUZRKDJs3WKG06UhUrFuGJKASm9NMBIDDrZELaodcv93N5TdaQAx/T62DE+nedFuGZf04eNkzArfg9osaHu9gdCNUZAqqJuO1hD/ok0eeCe+RQ=,iv:yk86WsIHkKYkA85NilrQ80x8yDBfx0LFiQJaav6Fbhk=,tag:yUhh5MGsMSJR6urU0cZOtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:mvxfuD5NVTDbmydgC3g2Qg==,iv:2gNCeFZAiEMj/4O1qj/bCuQCVprY/VFpozVX9HTL1D0=,tag:oWlUa7HQMtTtU6EFN/O4OA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:Xz4ebjXjhCzWKkL5tpsfbVD2JwEKYskRoCZrVcI0qAY=,iv:04TJuM+DUEzDy/oamlPVnfIt+57Z7+Ura6S1rHoVZ8g=,tag:4sUQIO2Sv5LOnWuEQ9pCGQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:C8K4bCkCgpUIoS8toBXImQk6F8EPsDvBiHkOGJMiKQM=,iv:g2/Soj5HQxx+mx5Ytk27zxpHaNXI6cSf56rYbHqJz4c=,tag:GzQ3DgwOUl4ilxA/6eJXXQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEZkSjg4Wkt4NUM0am14
            cVdYK0RpdTFSVFNPK1dYRUFWWll3dDZWa1IwCnMwY25DcWFSLzJ3bU9qZFkzdnRs
            elR0ZkJwMjE3dThtZGlRVVNtL3ZDZDAKLS0tIDFCelIveWZZU1BoZ1Y3bXJMY3ZB
            cEU0MUdWRHBsYlIraC9MVFlIZlB0bE0K7T4y6jExz7GEGShug2IEkzNddpKbo1rA
            xXWtvrLkJJGctz35jQfufMIq5mzQVwNP3Dzkes/Zy9x14ALDS9lhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:03:44Z"
    mac: ENC[AES256_GCM,data:edLPCn+ijNsymsVcoDof3nZQsPkNSWCwZRuKhv22IOPM5udFOY/O5lgYRBCgCoUZRKDJs3WKG06UhUrFuGJKASm9NMBIDDrZELaodcv93N5TdaQAx/T62DE+nedFuGZf04eNkzArfg9osaHu9gdCNUZAqqJuO1hD/ok0eeCe+RQ=,iv:yk86WsIHkKYkA85NilrQ80x8yDBfx0LFiQJaav6Fbhk=,tag:yUhh5MGsMSJR6urU0cZOtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-jardinsvedas-com
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:pg2ovKa1p/LZhnFUwgoKag==,iv:XJUBMF2r0CoWxfmr9uRiifRLG9whZaqVESsPMIyWGWI=,tag:+P+3jCwxHsWXHD/GN6bbyg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:qC5HuK16Y8XMv4OBNTdPtxP+P7vfho1ebp15+cBYEiQ=,iv:8LxdXiPIpCEXIEERvTmD0cVE7fvS1CYCGzoZmz2O+TM=,tag:kG439hE008t8CwwmE34Rmg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:X4z0+OdyXIDJaP2L/aIZmL16AIVN+1ZzqVwEAIhQSRU=,iv:mgVEN6R0oxYS9MX6pEQ03BIKYOhktB/PD4DG1d9W08I=,tag:yUbgHUAAckj6cDG06upWNw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEZkSjg4Wkt4NUM0am14
            cVdYK0RpdTFSVFNPK1dYRUFWWll3dDZWa1IwCnMwY25DcWFSLzJ3bU9qZFkzdnRs
            elR0ZkJwMjE3dThtZGlRVVNtL3ZDZDAKLS0tIDFCelIveWZZU1BoZ1Y3bXJMY3ZB
            cEU0MUdWRHBsYlIraC9MVFlIZlB0bE0K7T4y6jExz7GEGShug2IEkzNddpKbo1rA
            xXWtvrLkJJGctz35jQfufMIq5mzQVwNP3Dzkes/Zy9x14ALDS9lhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:03:44Z"
    mac: ENC[AES256_GCM,data:edLPCn+ijNsymsVcoDof3nZQsPkNSWCwZRuKhv22IOPM5udFOY/O5lgYRBCgCoUZRKDJs3WKG06UhUrFuGJKASm9NMBIDDrZELaodcv93N5TdaQAx/T62DE+nedFuGZf04eNkzArfg9osaHu9gdCNUZAqqJuO1hD/ok0eeCe+RQ=,iv:yk86WsIHkKYkA85NilrQ80x8yDBfx0LFiQJaav6Fbhk=,tag:yUhh5MGsMSJR6urU0cZOtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
