apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-certificate
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
stringData:
    applicationKey: ENC[AES256_GCM,data:9I8N76wHY8UhihZidfnKyA==,iv:rCfaFlmi/CozD1iyck3IHZNhRh3Crx1hWiaXpj3CIVI=,tag:hcE5mRoP5FI3WjppuZyI8g==,type:str]
    applicationSecret: ENC[AES256_GCM,data:X+6zvSU1YsZXsCMUJmYs7cu+i1/rsyXuZCW52LlN/CY=,iv:9Hqmec3FGn10gsTCvT/wefh9CIzlbdXgAhqXCCEIfxU=,tag:HqFyYxVlK88y1H4yypS9TQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:y7bZUjO4IDIBYRkMNTRYIVA8uUIXfiLk8sIL5lunkQQ=,iv:EYn+iAMJM1hg5raIX77lHoHo13GwpdfiDEolj3czD+w=,tag:NvJ6ISAqgXnPXmg8lMlVLA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3VzNUttN1FKd2MzaDFG
            OGVIRVRHNUpoTE45ZXp3QzJwaEJSd1lCT2dnClNQdWFnRkcvL2RjYXp2MFBmUEgw
            ZzlZWXhGSkhUVXlVNTF6dmNQOWxQejAKLS0tIFJ4ejFyUGZSdnQxQ09uTjFBMDN4
            MUZHOUdMSDRwUkRwak1CL2FWNy9tUTAKSK2r85Fl0KZu0S6jeMFxNusOeyXJY0S3
            2wWT6Dx/TqMoX0qh/2MMejvnfgynstSx522oA3JDxzuPsZzmLi/u0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:43:31Z"
    mac: ENC[AES256_GCM,data:KMFhhmfPM14rhtUxKPg8U7RP/usrR2T405vNEpr2vmsca4iK421F0st8qeXomnf5OZDbEWpF2ijhAZRQGThi2Lij9mIZwX5dm3LmbWEJ/R1Gsu8jBwBJD2s5jkQKO5yDcQmrc0cNb/VKKtCL8f1OvHcHMbAUU6Ekyep2RvxIliY=,iv:7dAnuf3dHhDsupEyy2hdW1qNjY0yIME56rTCY+0w0vE=,tag:Hs69/FneEalznPVobvgy0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:40Y460VRPXTIjvX8988f/A==,iv:Ht90iKjaWmBuVe68Bl48ehyA/evXJKXS+WoJqfgrQkU=,tag:Jx6qaINVkuXvEZAHq3pP2Q==,type:str]
    applicationSecret: ENC[AES256_GCM,data:VykdlCrVCA+k/3YEQJQzLryheOu/1e8aLXUAi32HjdU=,iv:8L290Tts+HubuG8v8ypQgZuidqBYnJJ5s4LF95WAWfc=,tag:8QsYW6zeMPYwE2h+KmVY2A==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:+7DsgA6tilUev11xbqOt7RjDrJ0PmBCorGbayW1aNgQ=,iv:RK1tZixFGS35E397FQbWBOsrXL+q7hDRitDK08YWaqM=,tag:x790cX2kleUrXOVo8fnptw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3VzNUttN1FKd2MzaDFG
            OGVIRVRHNUpoTE45ZXp3QzJwaEJSd1lCT2dnClNQdWFnRkcvL2RjYXp2MFBmUEgw
            ZzlZWXhGSkhUVXlVNTF6dmNQOWxQejAKLS0tIFJ4ejFyUGZSdnQxQ09uTjFBMDN4
            MUZHOUdMSDRwUkRwak1CL2FWNy9tUTAKSK2r85Fl0KZu0S6jeMFxNusOeyXJY0S3
            2wWT6Dx/TqMoX0qh/2MMejvnfgynstSx522oA3JDxzuPsZzmLi/u0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:43:31Z"
    mac: ENC[AES256_GCM,data:KMFhhmfPM14rhtUxKPg8U7RP/usrR2T405vNEpr2vmsca4iK421F0st8qeXomnf5OZDbEWpF2ijhAZRQGThi2Lij9mIZwX5dm3LmbWEJ/R1Gsu8jBwBJD2s5jkQKO5yDcQmrc0cNb/VKKtCL8f1OvHcHMbAUU6Ekyep2RvxIliY=,iv:7dAnuf3dHhDsupEyy2hdW1qNjY0yIME56rTCY+0w0vE=,tag:Hs69/FneEalznPVobvgy0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:cFa6IX4R8llNTC7n066Aug==,iv:nbbF936vbxVnFdzJ+84vY2JIfi9FvuBhpFDBB1+iySo=,tag:UbBx9hlsTkBsPkUGf1JEBw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:FBqle0DKMk+EA3jgGBP/YZjmb/g3YPH+yIOYT66WNgo=,iv:Xma1Jn2Qrp78eCtQfFJ72Y7y3MtdmsCmOD4VZZdQ5tY=,tag:In6Vnm8WVmGEIZ6z4O5N4A==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:AA1VRKepN75X1bd5iL5eeRAv8/Yxk6GWTYWcBXzZpBw=,iv:9dsoSl6yewVUljKU8NMLd39MnxkQxjEO3+o6QJ0UdHU=,tag:nf3DeitwhIFy8wG6T0G2Pw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3VzNUttN1FKd2MzaDFG
            OGVIRVRHNUpoTE45ZXp3QzJwaEJSd1lCT2dnClNQdWFnRkcvL2RjYXp2MFBmUEgw
            ZzlZWXhGSkhUVXlVNTF6dmNQOWxQejAKLS0tIFJ4ejFyUGZSdnQxQ09uTjFBMDN4
            MUZHOUdMSDRwUkRwak1CL2FWNy9tUTAKSK2r85Fl0KZu0S6jeMFxNusOeyXJY0S3
            2wWT6Dx/TqMoX0qh/2MMejvnfgynstSx522oA3JDxzuPsZzmLi/u0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:43:31Z"
    mac: ENC[AES256_GCM,data:KMFhhmfPM14rhtUxKPg8U7RP/usrR2T405vNEpr2vmsca4iK421F0st8qeXomnf5OZDbEWpF2ijhAZRQGThi2Lij9mIZwX5dm3LmbWEJ/R1Gsu8jBwBJD2s5jkQKO5yDcQmrc0cNb/VKKtCL8f1OvHcHMbAUU6Ekyep2RvxIliY=,iv:7dAnuf3dHhDsupEyy2hdW1qNjY0yIME56rTCY+0w0vE=,tag:Hs69/FneEalznPVobvgy0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:o/KJ5iyI2RDET6WyPwDO8w==,iv:zDhFcgoL3SjYI5kSBwrthuykzD8RNnyYpLnZf10wCJw=,tag:wbiY4pT4OoPSvsbqkbNe0A==,type:str]
    applicationSecret: ENC[AES256_GCM,data:HK/bSKRfUwFjtTBAfsK7nNdItWGbtJZEgu/sZbj0oCQ=,iv:DGSOfeb3vbhPpKe7KHIjT+Rq6puJBeKNpJeqmGw1AmQ=,tag:+ybQCCHi58xgOzWT2v95hQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:MFrx8iehJ8TjpXgHmKb1tXT45h96JEBYQqBC1z5CSR0=,iv:qRmEFej56VQFW3rikG3jj2APBvMazEb/lscfMSxaa4c=,tag:XyyXomYqC/S4jYwn/KtfzA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3VzNUttN1FKd2MzaDFG
            OGVIRVRHNUpoTE45ZXp3QzJwaEJSd1lCT2dnClNQdWFnRkcvL2RjYXp2MFBmUEgw
            ZzlZWXhGSkhUVXlVNTF6dmNQOWxQejAKLS0tIFJ4ejFyUGZSdnQxQ09uTjFBMDN4
            MUZHOUdMSDRwUkRwak1CL2FWNy9tUTAKSK2r85Fl0KZu0S6jeMFxNusOeyXJY0S3
            2wWT6Dx/TqMoX0qh/2MMejvnfgynstSx522oA3JDxzuPsZzmLi/u0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:43:31Z"
    mac: ENC[AES256_GCM,data:KMFhhmfPM14rhtUxKPg8U7RP/usrR2T405vNEpr2vmsca4iK421F0st8qeXomnf5OZDbEWpF2ijhAZRQGThi2Lij9mIZwX5dm3LmbWEJ/R1Gsu8jBwBJD2s5jkQKO5yDcQmrc0cNb/VKKtCL8f1OvHcHMbAUU6Ekyep2RvxIliY=,iv:7dAnuf3dHhDsupEyy2hdW1qNjY0yIME56rTCY+0w0vE=,tag:Hs69/FneEalznPVobvgy0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-jardinsvedas-com
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:B77H8LWSTbgEBxQ6ThocQA==,iv:U+M1IgwYN1kSf8lHRcz+F0Uuj/ye5nCVxCnyLULTpCk=,tag:GocHkVeYtAiJ/aViDWhLmQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:2ZMBARPfLTMIwN9XZq7afwtdfjIsVvJt0A1SSYddiIU=,iv:uvnKDZ4q/yZvyVXdRSH8byJHnDJmm/ldvsBhGZx895Q=,tag:GxSsSrSRaGQt7fSmh+JZWQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:BwKHuhiOExQz9EwNIxz4VkUC5RRZWrVWHFI4lrKJZ0g=,iv:CoHVrfTQttxT8wurEfZmcDVc9vpWrglNnxN/NnX/108=,tag:4OBdmW+nbidVi2yFsxFUtQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3VzNUttN1FKd2MzaDFG
            OGVIRVRHNUpoTE45ZXp3QzJwaEJSd1lCT2dnClNQdWFnRkcvL2RjYXp2MFBmUEgw
            ZzlZWXhGSkhUVXlVNTF6dmNQOWxQejAKLS0tIFJ4ejFyUGZSdnQxQ09uTjFBMDN4
            MUZHOUdMSDRwUkRwak1CL2FWNy9tUTAKSK2r85Fl0KZu0S6jeMFxNusOeyXJY0S3
            2wWT6Dx/TqMoX0qh/2MMejvnfgynstSx522oA3JDxzuPsZzmLi/u0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:43:31Z"
    mac: ENC[AES256_GCM,data:KMFhhmfPM14rhtUxKPg8U7RP/usrR2T405vNEpr2vmsca4iK421F0st8qeXomnf5OZDbEWpF2ijhAZRQGThi2Lij9mIZwX5dm3LmbWEJ/R1Gsu8jBwBJD2s5jkQKO5yDcQmrc0cNb/VKKtCL8f1OvHcHMbAUU6Ekyep2RvxIliY=,iv:7dAnuf3dHhDsupEyy2hdW1qNjY0yIME56rTCY+0w0vE=,tag:Hs69/FneEalznPVobvgy0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
