apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-certificate
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
stringData:
    applicationKey: ENC[AES256_GCM,data:U8H19uHReSXsd8x1hVSjqQ==,iv:wd6V2RI/r/bkitEnPKEs+UBVGvrLJD/3Yj21jneds4s=,tag:tIJ/G+rUt5BvlsJaRIx9yA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:2GkWMuDZTkobfM1vcOSqiY1Dq0+heGAFcCdn3vvtC4M=,iv:jB+jCBF8aa5MOyL4Qnw7tjaEl5ZGsJEZwapFAms9EDI=,tag:cPWJjQITIWOFTV7rMLKvBg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:+KtH5Sms9synOdUu9ixxsofLKLYMPcdqWj6c7ty5fLw=,iv:mLn1FMVgd/lKHn+7KKwxismzPhYyQV/qRABrF0JgM14=,tag:mYigN1RC/9iBUKW8EqzEGQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnIvVVZkS05RNUw4QVJR
            UEJkWDRFcE80eDQ2OUR3b2pUWis3UEdSOG44Cnh0ZVBnU2FmcWVzbHI2b09Gbmlk
            UlcyQnpTanN4MFE1d0ZueS8zakJEWjAKLS0tIGt1TmtCUlhGQ0FGZnNKMU9hVnVU
            TkoyQndhTllZYVN3WU5lYjlEKzFTb0UKMs9nrLGVwwExUYZ/H503LePgYB2KNxRE
            0FChUOPXHLByGnXpyskI7edAgOi31LvyYPZ1er79Jvm5FDJogEGYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:48:13Z"
    mac: ENC[AES256_GCM,data:74PU+ZaSbeE8ZV53SWfqTf+95+HRXcae/K3iMU2zj1VZ3TAw04EQFC9KmGUHMy26xtmY7pu0RNqUmWJGeLNDa753pcn458mYQOPBQ1YinlPSWQIA/Y2qLz9/MUK1AzN0ioeEdvr9rHy4epiJSteN0HfCuh36ZYrbUUgkBtFhcm4=,iv:zH1nhxN6l78uc3Ys8hbrSXfTEAU5aShIR2F/F3kgtbk=,tag:PWouq7PyWwvFhUzKuM0oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:vgNpvQen+JaOG8fbjYv/6Q==,iv:oOt71ZInfuyXLvzLFLame5ThFNkkFrUsBRyuGiXTAyM=,tag:wVI3aNwmn9duPPylXtXs5w==,type:str]
    applicationSecret: ENC[AES256_GCM,data:KDtIMk5XxSG63hdBTjKUW05DtDUQAxRgsaarfIls6Bg=,iv:Z1QPxUIvsqhKv8kv5+46W6TGHVQJVmvLXpxX4r/7O8g=,tag:/4w3qmJ+kMz9IK60rf/OxA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:w9iOY66O90fT1H6NeKJBOup4sUx7kHhXKMp9wTz3BOs=,iv:Oo1BDCPVCgRdHt5RvcL8aTvE4qk5qjLAoCMlnr31lH0=,tag:OSTPSIJneXcCSyfPzj43ig==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnIvVVZkS05RNUw4QVJR
            UEJkWDRFcE80eDQ2OUR3b2pUWis3UEdSOG44Cnh0ZVBnU2FmcWVzbHI2b09Gbmlk
            UlcyQnpTanN4MFE1d0ZueS8zakJEWjAKLS0tIGt1TmtCUlhGQ0FGZnNKMU9hVnVU
            TkoyQndhTllZYVN3WU5lYjlEKzFTb0UKMs9nrLGVwwExUYZ/H503LePgYB2KNxRE
            0FChUOPXHLByGnXpyskI7edAgOi31LvyYPZ1er79Jvm5FDJogEGYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:48:13Z"
    mac: ENC[AES256_GCM,data:74PU+ZaSbeE8ZV53SWfqTf+95+HRXcae/K3iMU2zj1VZ3TAw04EQFC9KmGUHMy26xtmY7pu0RNqUmWJGeLNDa753pcn458mYQOPBQ1YinlPSWQIA/Y2qLz9/MUK1AzN0ioeEdvr9rHy4epiJSteN0HfCuh36ZYrbUUgkBtFhcm4=,iv:zH1nhxN6l78uc3Ys8hbrSXfTEAU5aShIR2F/F3kgtbk=,tag:PWouq7PyWwvFhUzKuM0oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:SBCgpEn5Eb/L7jJb6f9QAQ==,iv:xvMTqQQxkm1Pt3zCkoKLVV36gk7Q+g1wTqdkftcML8s=,tag:fO61hzfdfWCKxeciGulnfA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:LUywHPN3u+dFcsYsPTTghiK8BoB8lSGGHVg3C1i0Fxw=,iv:synVYqYbVq5UEVwiK3219xuJbf1qJAZmHqGrt6pEJHY=,tag:JkHJC+Kpnvxs7CM6CCPtAA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:XZue+vNDwhJx7h9KRxRC5HhZQZrSPzvrUwfLo//N40U=,iv:e8t81mLyscHKbAqiujtpcMXDb83A1H30SHlf+7k1+Xo=,tag:102WV8M1nDuIoYmjRpiMPw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnIvVVZkS05RNUw4QVJR
            UEJkWDRFcE80eDQ2OUR3b2pUWis3UEdSOG44Cnh0ZVBnU2FmcWVzbHI2b09Gbmlk
            UlcyQnpTanN4MFE1d0ZueS8zakJEWjAKLS0tIGt1TmtCUlhGQ0FGZnNKMU9hVnVU
            TkoyQndhTllZYVN3WU5lYjlEKzFTb0UKMs9nrLGVwwExUYZ/H503LePgYB2KNxRE
            0FChUOPXHLByGnXpyskI7edAgOi31LvyYPZ1er79Jvm5FDJogEGYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:48:13Z"
    mac: ENC[AES256_GCM,data:74PU+ZaSbeE8ZV53SWfqTf+95+HRXcae/K3iMU2zj1VZ3TAw04EQFC9KmGUHMy26xtmY7pu0RNqUmWJGeLNDa753pcn458mYQOPBQ1YinlPSWQIA/Y2qLz9/MUK1AzN0ioeEdvr9rHy4epiJSteN0HfCuh36ZYrbUUgkBtFhcm4=,iv:zH1nhxN6l78uc3Ys8hbrSXfTEAU5aShIR2F/F3kgtbk=,tag:PWouq7PyWwvFhUzKuM0oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:ZfXi/nYAIaCpPMjF8bO5Ew==,iv:6qCZP3XiqNWjuKk1MXgrUye9iH72huxj3sxvinub1EE=,tag:LJkIKb0Ek726nJFgaCLvBA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:7WVO9ruwBYBrrGuf+l7pA5siordA4tXZRV8PK12FNJk=,iv:29yn3qTXt2VdjLzeXlHbbyxCvrup5HhWn8b/x8u/x/A=,tag:Rm1MRlEx2EziMbiszP/AWg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:B6IwrV/2Tpz4tJAGWSUrT8f+57L42oI6/vD2EfHuaAI=,iv:BZadApof1rmttOJdnm2CyK8A9/vKwHzc7fBtUXiCsLA=,tag:SkVTJuoygHdqH98LwZx5nA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnIvVVZkS05RNUw4QVJR
            UEJkWDRFcE80eDQ2OUR3b2pUWis3UEdSOG44Cnh0ZVBnU2FmcWVzbHI2b09Gbmlk
            UlcyQnpTanN4MFE1d0ZueS8zakJEWjAKLS0tIGt1TmtCUlhGQ0FGZnNKMU9hVnVU
            TkoyQndhTllZYVN3WU5lYjlEKzFTb0UKMs9nrLGVwwExUYZ/H503LePgYB2KNxRE
            0FChUOPXHLByGnXpyskI7edAgOi31LvyYPZ1er79Jvm5FDJogEGYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:48:13Z"
    mac: ENC[AES256_GCM,data:74PU+ZaSbeE8ZV53SWfqTf+95+HRXcae/K3iMU2zj1VZ3TAw04EQFC9KmGUHMy26xtmY7pu0RNqUmWJGeLNDa753pcn458mYQOPBQ1YinlPSWQIA/Y2qLz9/MUK1AzN0ioeEdvr9rHy4epiJSteN0HfCuh36ZYrbUUgkBtFhcm4=,iv:zH1nhxN6l78uc3Ys8hbrSXfTEAU5aShIR2F/F3kgtbk=,tag:PWouq7PyWwvFhUzKuM0oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-jardinsvedas-com
    namespace: controller-certificate
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:fFpfbNDhDLCDjFX4ME76+A==,iv:ezkUoogccTxRuMnEm2yqxGFj4aKjH2rYxLNitgx0Ufw=,tag:fER/u8ZBWC6eZNX0qlaxyQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:yjn2BClPU5vD9Dt6/B6p5ULqpmdv+40fY0HW9fxbRyc=,iv:rokfySeUtHhGEEEBYbepslJX5Ihyvs5TqWsmDCg3QhQ=,tag:KZSRF/9HeuZ18fFh9kZ3VA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:NBN22Bv9QJIoB1DMjKELvagG3BwmlcmSXIBQgePOxvE=,iv:vDCgdq2E9JA4sexHnU9D+Z1jJCoEnyHtwvYbLTGECHQ=,tag:guZaIjUn35kxbdEA0fU/Dg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnIvVVZkS05RNUw4QVJR
            UEJkWDRFcE80eDQ2OUR3b2pUWis3UEdSOG44Cnh0ZVBnU2FmcWVzbHI2b09Gbmlk
            UlcyQnpTanN4MFE1d0ZueS8zakJEWjAKLS0tIGt1TmtCUlhGQ0FGZnNKMU9hVnVU
            TkoyQndhTllZYVN3WU5lYjlEKzFTb0UKMs9nrLGVwwExUYZ/H503LePgYB2KNxRE
            0FChUOPXHLByGnXpyskI7edAgOi31LvyYPZ1er79Jvm5FDJogEGYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:48:13Z"
    mac: ENC[AES256_GCM,data:74PU+ZaSbeE8ZV53SWfqTf+95+HRXcae/K3iMU2zj1VZ3TAw04EQFC9KmGUHMy26xtmY7pu0RNqUmWJGeLNDa753pcn458mYQOPBQ1YinlPSWQIA/Y2qLz9/MUK1AzN0ioeEdvr9rHy4epiJSteN0HfCuh36ZYrbUUgkBtFhcm4=,iv:zH1nhxN6l78uc3Ys8hbrSXfTEAU5aShIR2F/F3kgtbk=,tag:PWouq7PyWwvFhUzKuM0oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
