apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: k8up-credentials
    namespace: controller-backup
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/k8up-credentials=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/k8up-credentials=true
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lJWfsoncjoPI8Su9H/zcPqgF0+Y/1f4XgcJ2U13REII=,iv:N9+2g+u8kP1agl4x/DguCOxy53x5pMUTOTfV1aS7Fzo=,tag:aFVixoeBBUBQF0Zgkhlezw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s4fCyZk8CDr9AMsyoiUceK9gexvUhfXUE1EHGbGJsWs=,iv:1N600bq1aJj10GoUDMPGEQzI+wViCRstsmyKhncbLS0=,tag:/qVflq5/oDd6yULCdd8Y+g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:GHaez1qu5uNVJapeBEvA2N/ltS94xmumqnVYfwRsZVs=,iv:sMQHSJGKkSwm+FHjQgZIOmCdadr4awCtYqnYwe9Q3s0=,tag:B6WaS6PCl7bMN7QL/46eYA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQUlyNkZlbFBlTGRJNUlK
            VUJkVkwyYmxkb3dyYnNsdk9oOXhldDBDOG1zClZJTHJTVlo2R2pHNy9wTGlPU3Vu
            cGdmN1IxNmFsQWdqUEo0WmpTTGNnUXMKLS0tIHRISjlvZ29kS0RWKzNYQUhkbUZU
            ckViRm1ValZicWtsL1ZvVTJSb1FDSVkKDQCkrEaAgAvZUgKAM0WnOyK3xzLi1nKb
            1jmH3ID2BOpn6zd9iBaxsI8GLdSae+cnFLmhRI3lTSYC3cFxFAppDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRUZ4ZlVLQThCM0xVTG55
            NlhHeWRBa05LMThEaCs4Z2dRVnQxM3BhZ2dvCnJpUEh0aFpkaWE1LzNQdUNPNjdB
            VGw1bmh1Zll3ZHcwQitJQTF2bTB5cGMKLS0tIDJQM0ZvZUxacjJVaGt6eFJsV3B4
            SW9xRkVXbHVrMEEyM0hvdU1DbTZSeWcK5pLrnal3Hr8PoEfSt1FFfPO48M0QPcjL
            iD4oqAJy6ha21l964FAkOOiEYoqqag8vC6oRF8ABQm/4hy/O+77BUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T09:11:29Z"
    mac: ENC[AES256_GCM,data:FG56Ez+4JFAoYX3aARI8b+tb4+jpi2XF8RQelFqA10QyIGHamzpRGIiW28ymyz1buZdCQqVXUSG+j6FfstPNckFDhR3rmc8fyP/djhBkHsJxMWt7aYM2nTW/gjjaDEbOjSlRutQ2aap+JiiRuYqfPGyY6hHE3j6cfoWupgVOaYw=,iv:qZq5/rAQJEzaJFiMvRUdkQl+KrJxmtPluNtcYdFNLlI=,tag:PjZaK9FW5C905idB0mJJMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
