
apiVersion: v1
kind: Service
metadata: 
  name: traefik-internal
  namespace: controller-ingress
spec:
  type: ClusterIP
  clusterIP: 10.244.0.100
  selector: 
    app: traefik
  ports: 
    - port: 443
      targetPort: 8444