
apiVersion: v1
kind: Service
metadata: 
  name: traefik-internal
  namespace: controller-ingress
spec:
  type: ClusterIP
  clusterIP: ${internal_service_ip}
  selector:     
    app.kubernetes.io/instance: traefik-controller-ingress
    app.kubernetes.io/name: traefik
  ports: 
    - port: 443
      targetPort: 8444