apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controller-authentication-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controller-storage
    - name: infrastructure-controller-directory-ldap
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/components/authentication/authelia
  prune: true
  wait: true