
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - create-k8up-restore.clusterworkflowtemplate.yaml
  - resolve-snapshot-id.clusterworkflowtemplate.yaml
  - scale.clusterworkflowtemplate.yaml
  - wait-for-k8up-restore.clusterworkflowtemplate.yaml
  - restore-database.clusterworkflowtemplate.yaml