apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:DUxP6V4hOuAt2W6TyH3eQyfvLX/xr1pOGQ0TsUNPRdXi6T6RpBp2WPVVOGmKTmvr8b56YsuZi/oM8fMhwRB4+/3u7N6poobkXCMOw23iRD+65rCh6xtViw==,iv:nnr4eHV0yDTcq+WphtTOmKLyux+xHrjSXw78K+WrUfw=,tag:sl/YSwppWKZ8qifsMrCCCg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob0toYmowcWVBNXNrT09j
            UHgzY0lpSkZzci9YMXJvYWNzaVhZQjFFVEIwCjhUL2U4bS9NczVBcUk4VC9nalQ5
            dzVoVlhhelJHNWQ4TTlxcldRZm91ZUkKLS0tIGZvdE5tTmxCQXZ0RUhjblBNQWc3
            dXAvMnZwWkVmcFNnZldOU1JKelE3M00Ka1f2dLRKf8MiVF9Y2ZQAExqa7E4kQx5B
            bN2AEKOck2Zjzm+7/pJ5XBPgVCTvaI1J+c0RbL6Gsyr4VBu9mFkPGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T08:25:16Z"
    mac: ENC[AES256_GCM,data:gf9Vj6B2kch2RS+tWSbx+qDKWBika6uBu5gPIHINFoas7+/dRumV95854huY6falCFS3ITFJHw4gr4VBmBxQJKmI6tK6/n/lI4SDRoHGbmfEVVZUMnnXW/aCKElgMS1TCwKsToHOBY7g8RRmi/4s/nqO7tkv1vAzttC/pBr5ZhI=,iv:ksEWQmR6IW4eWlicYM2t/IYz02hzZv0bFAh6VzjR/hY=,tag:b+WvGwLHWkO0ZVk3Mta7lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
