apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:GfL0dpsrK8XM40I58u8y08m7BOMiI00PRh8nvYbVve/NncemoChQvJ55PUXv7CyoEIazAqyd6iWKRO89bzWGviCiC5WL8/TWC+mOITgTm9KpIfTq9EKeWg==,iv:4NJPYABnWV/7VNgDUBsgbhsOH6feJnpNG1Y/GE1YGfA=,tag:M04pEpAx9rmwaVy+dV4+5Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc3RNd0MrTnd2TkgvU0V0
            VCtvM3hOdVFscDliMXJLYTFyVHpDT2JxdFNNCmwxQ0t1UHo1UzRDV0J1dWhXN3Zm
            ME5ITUNzUGtKWFoySG9uZW1Hd0hNUHcKLS0tIGN6eGFyRzlJQU1HMnUxRWVMd21W
            Mms5SndTQ3YrRTZ6SEsrd3J1ZmhNUHMK8lQl+fHDoGXbtCrzpOX5oo5R3BI+rIcZ
            4LeAZLd6F7ckFUxli/pug4AabaQs38pQg76oJi0y6M0Ir842MJ4zyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T08:53:11Z"
    mac: ENC[AES256_GCM,data:tD4IqG/fafk0O2h54TLWz19615Lccp6UHc7GKyYmpqtLjvUBBbbp7SMX7+tzEwJFfT09RpTXRCWQS1B53FiJmXZJqVXxe2a3sT/2tJ0gq3RuZhBQ391g8y9WUicz7OG/IugmCsWnWPPoQ3HNcZIT2N9hN23FZyYQanl1RDb4aHc=,iv:W6uUH0XeMmPnfwAf4bkQ7ketEJKDwAQ68FvNz542KPI=,tag:R708n7zR87S9uL8GqD677g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
