apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: controller-vpn
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:zzgtCu7h63UPUxUfQFfy3GeryXqzN+2YLjMyw6r8y2DIp8/bGWqhAzi98gRtSoz0/ncC97W4+3YUUzlkA0b6eZvYuDdcM9eF208/4HeKS7joTuPA2qfbOA==,iv:18dOiC45sHaC/+z7k3F1IZ7OSCS8thhvusEMNEArvnU=,tag:yT7oUdGa0k+P5J8kmCw3iA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSkFyQi9neFpnUm12VzlO
            ZHB6MmptZUxHS09oUWFJaHpTT3I4NUcvMWtRClQ5MTZoaFFaRVM1U1o4K0VtVmda
            WmdjZHg5ZDdrMXFwWjlOOXZKWDZPN3MKLS0tIGhtL0ZUOVM2eVd2Y2FCZDNOeDVE
            TWl2eFdxVDVxVlU2alhpM3RKQ0tSSG8KUJalU5FGWPoPfqQevm53FRaOPPsKLGv+
            iIWhhzYpNzCeaT1TGo6HqYp8hpg2dsLJr1yspiYp3e8GmX+Mt5kBLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T07:41:05Z"
    mac: ENC[AES256_GCM,data:Z9nTFCW0NZYmlsnCpdg1udvH+Xjg6xD0hkzyn6UOhLx5J29SdcNOX730InmkVZeU8Rva7f3j3NzyP3evWFsYYRdaZdT6fIHyWKsbUMgp8aacYelDrivVqCToYwmDSlGnVwE2AKRhyr2Hbev5+wP/2+SDhD9hRL0eXDNMr3TTN64=,iv:UtZvqIasRNDY6EAM8P8xmtKHfKxnwtfbunDA//rDJEU=,tag:h+xcE9KVytBQlwIQ5sfbeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
