apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controller-vpn-subnet-router
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controller-storage
    - name: infrastructure-controller-vpn
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/components/vpn/subnet-router
  prune: true
  wait: true
