---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${capacitor_fqdn}`)
      kind: Rule
      services:
        - name: capacitor
  tls:
    secretName: capacitor-cert