apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: controller-reflector
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/regcred=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/regcred=true
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nDeTVnziWS+zvGvOKCbaS1bKQyz+cLb0DI2PEimIOc6xV3xRTCsYFv3mJ1H+/88J/hD1l+Fyfter2TSSeuRZuyh+sFkyB9DFvMIByk5mkwnTH+28ObthN3tAebamgmaJpOCTctydHBbLtuOCF7m0MXRtPk7f4Ln4sIeAR5ShsnhJXz/hJDN7KKs9nEomf+baCY6H4lw51gwUh39X,iv:OdejuO0xmmckkXY2SFTObDIXIxD9W76zXFPUXN3zrvY=,tag:lI95Yq68qac2YulwtJy+LQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN3RxMVZXeEV4dDR4Tm1U
            dVJ6aXpUN3pjVG9sMDVNUDZ2UEl4eHNSd3pjClN5Nzh2ZDBHLzdzOUxsejJtNzdl
            TDliUWE1a2svMWpNK1JjUTZWV290SVEKLS0tIFU0YXBMaTdRTUtJMzBWMlBUTWdT
            Tnc3anJFalA2NHFOdFVtN1VtRTRVTzgKgh8NL4Roqlxz5SdOR5baVbwqOtVb8IjK
            x9ibiUVbdIRKgv40HFnT37VGbtKshK555I1oIO0uxuEacUex8qZW5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T09:10:59Z"
    mac: ENC[AES256_GCM,data:GEg8xkIeemxAhlhJpNCS9fO5P853mTHH6xqzOs9MQIRjySdYFNNzTu9mJ1rDR0Y3ranTooGo8icoKv2jM4mnflrTSl+4uwbw7j/EimaYwJoi3NyGtZ0btG4hjH0QUtb0DHv7WjYGKciFTHJ6f7TXo5BzA2LVLZSxuLnfge0dK+o=,iv:NtvrLd4xFjraI7fe8QdL7eOhJg0lYFl/d9RlYHbhjj4=,tag:10d3yYIGzO8lJ8fcWi1zOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
