---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring.internal.${cluster}.${domain}
  namespace: controller-observability
spec:
  secretName: monitoring.internal.${cluster}.${domain}.tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "monitoring.internal.${cluster}.${domain}"
  dnsNames:
    - "monitoring.internal.${cluster}.${domain}"