apiVersion: v1
kind: Secret
metadata:
    name: neo-alterconso
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ssGdD4o2dtQfVPqcj+Y=,iv:93y/FDrkj1zrdncy1SQZwEYfYV9TLLVs6bdscSsZhyY=,tag:DzQ/iXmc6Bnm39Q1edd3eQ==,type:str]
    #ENC[AES256_GCM,data:+EZEaWXTs0yU4IGfXLNDHcEfwa+R,iv:uX6bGxIsv8MkQ44W43BtUc0Wc5SSPTL5OItZE9gXOJY=,tag:xzy/3fHB2yiHKZ581AhGsA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:AXBj7XcyPqRI6MGuEQBIewakYfTyjAbZfVYy2VhgoRSxJGgqE608/1WnUw5FStAsQjOJr9DBfwBaowzfx2QwOg==,iv:V9iViBkeEHB02taVLzRtCrptZWpXRcPsvtwNbG4+RPw=,tag:kIpiw6KyPWcx7EzQy07mng==,type:str]
    #ENC[AES256_GCM,data:bg8NYC4F3ETYYbUdItfdflu6FrtF,iv:9btGO1+s1hoD/k54iFNJK2g+VIxgm0lxIkg7ebz6QbE=,tag:TmaIoYPtKkMPzB1eut+mXA==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:g398FGfFNuXuvv2QRJjMBeLxWq3h2jepmVf9KsrST4tgsB9M75llZ4dnt4F333hNP7NR+ilaRtyXeUUtu3sfsg==,iv:vlifd8e1FXwSxggDbrsxNTy5YhiKCujFPCaCeSA5dLY=,tag:04dfZYzUkj637BqqcMBeFA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3L7ARHInfL/lkZs6AlXLx/WAgdIKprr0YUTMkqgMEQOuEN0Myv0oTP8myGWuTsQstoH1CRlpwA24TKzmpjwQXlnykhGpKc/yRH4ioUsomsBTwFXG4nFA5CXS,iv:iIazFiqyr6WR50/7qiWEfqSp5dJQEahwoR6XKEMZleY=,tag:k87H/3jAR+020xMHffKJng==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:CN0B48m754tm9VfZNR/u3VPPnlxcRHoJZfQH7UQqVMtaYo1hS9oeoTh8BABgTkgnWChSD/NSCacjIPpHuucIs4uyP6a4D+NTdo2jfp3gubNPgtGOnNdMg/s=,iv:Oj9AEs+lUhgV6AjujkZchmMNJ4PkHbY9n0iF1USFHGg=,tag:fuLhT4hugqQKgnBgpEFu6A==,type:str]
    SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:WXco1KK1ONhmiXSZTtM=,iv:B85x6JxvfNnBBXbdNdEmWDmGhBtmCTkUFFpKARLg190=,tag:gGpm1BcAI5HyiRcwCscqng==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMHhPT1VRNS8rRjczZ2VK
            eFVEUEdlR01nbnpvd3pMNXVOQlRza1NienlRCkdQZ2NnMHRoenJONjZWUWhHZlJU
            eEtsV3ovYXFHd0RmZ212czl5YWRtdFEKLS0tIG9xK3R4RTF3V3Y1ZS8reWdpZmhp
            ZVFhbzFsZGZWRkwycWxMaGJaZFgzWDQKZk3cTtehL5nO7G9zmxzHSLT0wLsGqr/l
            Bv5jc6z3QS9VXvGI5lkvRY897S6MnaIMZgByH3ms3+RvJAZQQjNmdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T11:18:58Z"
    mac: ENC[AES256_GCM,data:pKXdN6o0Fd32N6i3tIIBJMC3wWv50yFPrjU98W9/m/WPOLBn4N1xF1oHIIYB9awhO+Vn6vl72Ueh6GvZxZkS8pZdz8JHjfccubCpxzvzgFliJ+CAXoJvnFjftgm08FtKpDYF777IMIbjv8nu9L72xeZObugx7Wu9nabMpzVpwVY=,iv:QH1IJUvEXB2oswM1ClesCZZzcJeldbngZzV56WD8+CM=,tag:WVErnzAXoXWokbN6VHSsYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
