
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: tailscale-router-bootstrap
  namespace: controller-vpn
spec:
  schedule: "*/10 * * * *"
  timezone: "Europe/Paris"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    workflowTemplateRef:
      name: tailscale-router-bootstrap
    arguments:
      parameters:
        - name: headscale_user_name
          value: gpenaud