apiVersion: v1
kind: Secret
metadata:
    name: grist-basic-auth
stringData:
    auth-file: ENC[AES256_GCM,data:PcmaK9RKYeyzBRA1LKiv4WMehJT40kdC7ePywGMStdWGqSASTHRVOmH5gM8TrvsR,iv:Wqgrii/3b4oR+pTYRFslszZW5i5E2dW/qwDouCvsVRQ=,tag:UFhmnKrMT+ZD5Upe9T1UrQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNVo4dHJjWm1vK2JpNkR5
            ZW5JSHBLOUtMVE1yaWhYWjhiclROTzNTVVJjCm5GUmRZdDRGaEpWK25uWHI1RlBT
            TW02NFVZTUg5ZkxBTkpYdUtmRUlBRXcKLS0tIHhsQ1cxaEU3MXQyWWRONWdhT0R4
            YXE2MmtZb1lqeFhDU1NvaXY5TzNyOTQKZS2ALmy6oey5fKNeOvv6XhDIQbRgntSa
            wwMqfJAUZHDCONJpunj2jFVVGc3pnnuwGOajxAzdaV+SM8hT9lO82w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T07:55:14Z"
    mac: ENC[AES256_GCM,data:8AJpIeldCrb/x21PXD2UFPRv//d+kbD4AHhvdIaDXQ0wdWA14YFH3/Ra2NNaIcjSWj0sBjXwZROziN+3CA0VkciBr9iH4vvvQpgw+PQlcYFxYizuxqnwBnXmIWrkYo+23s7CZf1DlyrclAs1xFaVhz7Du4wZt+I+f2PBY/t6+sY=,iv:DBH86EIzjOt4+jc3oO+Axxz2CbnhQYdJ8jtDtLxOwxI=,tag:zvarTln00Bf142YrWstrnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
