apiVersion: v1
kind: Secret
metadata:
    name: grist-basic-auth
type: Opaque
data:
    auth-file: ENC[AES256_GCM,data:lB7Q2qw4h2L79UOEDWoYfN5SrbOxSjsrZhSBj8BfxPbXilLvxLTbnxupQbnBnKSd,iv:TqhCSJy6gwItOAezH6/c8bBsqn/L5BAqcltf6IZEieE=,tag:IebtbPQ2R4HR47FTQfNhUQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUVZnMUlFY2tGT1JLZXhw
            Zi9ZUjRWS0ZkbStrVG01RFdFVFc5aW80THo4ClhLRHhDY1orc1k5QUduazMrTG9Q
            MDg3WEF1b0Jid0pmT0tOMXRCZUFuSFUKLS0tIEJVVkNmeCtiRzVzdU9ldXBiUk0z
            ZFJLMlFhdTBPbms3R0FtYUxBMytDWDgKi0d1yUyso9y1ZpP1/o8Vv+eSg7ChoHxT
            XfygO8iz00ho0hryjPlkh9GRVKEjoj2o3BkUHJ8k0YebEMZEHhKmzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T07:32:24Z"
    mac: ENC[AES256_GCM,data:clm+D5rOqaD32Z4/cRuS5MQeIJ3VdflURFJu+TxIhDmDJeve2UQmAsQIgVKxouawoB8zpaZXJZXAxxoNqe4WwVLvsHizZ21QbgWgb3nqS+9c/DHwCbjPlS60wazB21xp/4l7sTzvgMHnLaLOMmKLFE9QE5E6O4ff/SPFKLdYGtY=,iv:kxX+mHws8ea4nFXS8++T+H8b46a2CWtOUV90nsteHZM=,tag:mYbZL/vkyr4LyGbDlGSptA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
