apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-grist
spec:
  values:
    image:
      tag: "1.7.11"
    loadBalancer: 
      enabled: false
    homeWorker:
      envVars:
        GRIST_DB_URL: "sqlite:////persist/home.sqlite3"
      probes:
        liveness:
          path: /status?db=1
          initialDelaySeconds: 10
        startup:
          path: /status?db=1
          initialDelaySeconds: 10
    docWorker:
      replicas: 1
      useVolume:
        enabled: false
      persistence: {}
      podSecurityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      envVars:
        GRIST_DATA_DIR: "/persist/docs"
        GRIST_DB_URL: "sqlite:////persist/home.sqlite3"
        GRIST_SANDBOX_FLAVOR: "unsandboxed"
      extraVolumes:
        - name: grist-persist
          persistentVolumeClaim:
            claimName: grist-data
      extraVolumeMounts:
        - name: grist-persist
          mountPath: /persist 
      probes:
        liveness:
          path: /status?db=1&docWorkerRegistered=1
          initialDelaySeconds: 10
        startup:
          path: /status?db=1&docWorkerRegistered=1
          initialDelaySeconds: 10
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: mkcert-issuer
        traefik.ingress.kubernetes.io/router.middlewares: le-portail-grist-grist-basic-auth@kubernetescrd
      hosts:
        - host: grist.gpenaud.localhost
          paths:
            - path: /
              pathType: Prefix
      tls:
        enabled: true
        additional:
          - secretName: grist.gpenaud.localhost-tls
            hosts:
              - grist.gpenaud.localhost