apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:rNbVZyNNZu828zlfLP8=,iv:thBH/ntCF1ro1SPMQKABHKTFQHe9WDLBic1FMB/D+bk=,tag:/rMzd6pffHOA8oBLRFAt+Q==,type:str]
    mariadb-user: ENC[AES256_GCM,data:U+asFW07VN1H/qWFQTeZ,iv:7Y9ZWe/gtsUd/uja55JmMGTO7g25JtOZdUfFENKdzzU=,tag:qyia+hqGij/tw2qA32Eyuw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:vTNf700B6i0B,iv:7e1QV7TUs8Kf/HejJJ6Gp+Soy9nWtdITeK5Zc2HsKIs=,tag:RGKF/m0PWbl0HQZIXjcRVw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:gSSt7Jg=,iv:tIZpvNWQxS1ABG/YVd6YwE91e3vL46VWAnJJ80mBZEo=,tag:pucwRQmQN191hYAb2x2uow==,type:str]
    mariadb-password: ENC[AES256_GCM,data:iO6y91d5g5beF27GPhg=,iv:nj6bXGNLgIXaAFqlCqpGI8PVbH39LS6kDkKs7zqfb/M=,tag:xAg591guaeW/zUFwLBIfzg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:MBF6eW4=,iv:khFl3baQhASwxHI0se+givC4aIodJc5gh5bwzRKJtSQ=,tag:g57FwJDLvgQ0r2Rm/fsnrQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TStoZU1zZG9DaUZSTHo4
            RE1VdXpsNTdWVTNiWjg2b0toT0pBdDZYT0ZVCk1jckduRVZzaWs2dTlYenZDNG02
            blllQXowREZTamFSTzF5ZEpWa0tPRzAKLS0tIHNHZXc4YXJuWHZmbWFPbjkyOGd3
            K082VjBUOTNvcmxpRm15Q1pNVjFzN2MK3X4BjeROEa41YP/oTlc7mWcJUMZw259S
            zglUA2Xp0Zb9AZDANAJ5aUjzxPPhfRXn/gyQ0HndDU9TGK0FDOCZbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:10:05Z"
    mac: ENC[AES256_GCM,data:GD/Bu+8udvMzXXOaoamO5a4k7q7TwWG+jtzp+f7MTP7nd6ezAJ47Ry8zf65E76G7J6IVOFIJTRYzJf9TkSwunrLRXd8MydMFrFf0Be7kXRhmbQWLgiiduFUmbcTW3+Pz2vBbkN20Cs4L1NqLobg8gfyTyFbC4Gn6BgjOUYrxeq8=,iv:frlZAkmW7BxnlCGSfc/HRlqudtUAxDh81UhSeUav+d0=,tag:L6IND3Ixlim3oeVywj86MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
