
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant}-wordpress-epilibres

resources:
  - ../../../../../../applications/wordpress
  - ../../../../../../applications/wordpress/components/init
  - ../../../../../../applications/wordpress/components/backup
  - ingressroute.yaml
  - secrets.enc.yaml
  # workflows
  # - ../../../../../../workflows/restore/applications/wordpress

patches:
  - target:
      kind: HelmRelease
    path: values.yaml