apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    wordpress-password: ENC[AES256_GCM,data:6AjJlXj6yVPiBdioth8=,iv:zoV9lO+U3yelg4KQ0Uh+jOUXPByChAsjhpqkeEcMhQM=,tag:JKMrsPNRukP1PvTbcUKyPg==,type:str]
    mariadb-user: ENC[AES256_GCM,data:nrdSdRVjqKjZ,iv:8wXtPa+UtUGCHIDQDbbxUR6/ty6+UE+ZITH3faZgCLs=,tag:OKvpd7gnZHP3pFMg9zvx0w==,type:str]
    mariadb-database: ENC[AES256_GCM,data:Q8VsCnq7N0RY,iv:hRi3OfzWb8pkOi2D5/NpzdEs5ollVWeDPqR0Ys7O7Ds=,tag:C35AQ8H4Bf0OG7euN+a7uA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:U1SK7FY=,iv:JiKIyxm6YuduJ2nKk0lmX3aFrciOai/Rvc/tWGZ2bRo=,tag:aZIaU7RQvvtqYJ7rvoAt9w==,type:str]
    mariadb-password: ENC[AES256_GCM,data:gHSCzMNc/RgQndrW66c=,iv:DG5wieqIjhgNTLubX/obKttX3Zay9a0Iy/dijEOwBkw=,tag:eN6z7ysQjXaaoUOmbC34KA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:Cbrwa40=,iv:qcwiQD32fI5pnTqq3n/XHR/KQ3gy3mp6Cv3vW+yhTcM=,tag:GHJMbQhmZGw2RDJjg+gZZw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWXQ0ZExLR1JmZkVKK2JU
            em4wcTFQV1JOS1Z0U21ONnVUWlJaVXBtbkJnCkVoZkRybStEeldyUzcwbzlJL2ov
            Zm5rMEZjaHNDb3FmczQzMzlKQ1dVd00KLS0tIHFjb0drWlpqQUVtY3NGdGllZS9p
            bjIwblQydUt6bDljWjI3QWRHV3lwYzAKVjJN8JJrXc+AeVqdO8ftUY8LDKh3psf8
            sHTPfMbWCSbsYllA1nkBh653maC6GlI5VGl4ZnbQDEl4mLngD6C6Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T16:28:47Z"
    mac: ENC[AES256_GCM,data:bPdEh7PM/YQXSc57gRcHsMqgy0plcLrbRVkkevsw+TOxdegnaB8gxlXtQiyvYFKVOPvlUanHH2cCN4S16vfv7mbhybLnPdEdN1pNEwGppRdfyLZR5BXGibDBEPSIm2NoTraD9r0kkeDo/AloKeiwI6+DL7B2qxsg6YSVFpQqrOI=,iv:5T9QGXNfwT6R841vdF0ZYQP4m50yK9zOt0LEKQgVou8=,tag:m2xXVhnkLswgiB2jBDD1ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
