apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-epilibres
spec:
  values:
    wordpressUsername: epilibres
    wordpressExistingSecret: wordpress
    wordpressEmail: epilibres@${domain}
    wordpressHostname: epilibres.${domain}
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql-version-8-lts.controller-database.svc.cluster.local
      port: 3306
      user: epilibres
      database: epilibres
      existingSecret: wordpress
    wordpressPlugins: []
    extraEnvVars:
      - name: WORDPRESS_SKIP_BOOTSTRAP
        value: "true"
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: longhorn-ext4
      size: 7Gi
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      extraTls:
        - hosts:
            - epilibres.${domain}
            - epi-libres.${domain}
            - epis-libres.${domain}
          secretName: wildcard.${domain}.tls
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    initContainers: []
    volumePermissions:
      enabled: false
      resourcesPreset: "none"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

