---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.${cluster}.${domain}
  namespace: controller-certificate
spec:
  secretName: wildcard.${cluster}.${domain}.tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "controller-.*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "controller-.*"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${cluster}.${domain}"
  dnsNames:
    - "${cluster}.${domain}"
    - "*.${cluster}.${domain}"
    - "*.internal.${cluster}.${domain}"