apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh
  namespace: controller-certificate
spec:
  interval: 24h
  url: https://aureq.github.io/cert-manager-webhook-ovh

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: controller-certificate
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: controller-certificate
  values:
    groupName: acme.alter-it.eu
    certManager:
      namespace: controller-certificate
      serviceAccountName: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh-secrets
  namespace: controller-certificate
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ovh-dns-zone-alter-it-eu", "ovh-dns-zone-leportail-org", "ovh-dns-zone-fermedujointout-fr", "ovh-dns-zone-labergeronnette-org", "ovh-dns-zone-jardinsvedas-com" ]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-ovh-secrets
  namespace: controller-certificate
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-ovh
    namespace: controller-certificate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-ovh-secrets