apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    wordpress-password: ENC[AES256_GCM,data:lexkhqNensAqvlFJ,iv:YRuY4xGilfgEgpYsgn9o7xlYIgjCj1HWlAZWOIO7JiY=,tag:5ShQu45xixETtrRUroKPIQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:ta5GsO6JlVfRiP9i,iv:7z8slxXtW0OyhI1FncwF2uIPONI2qw+6H8Irp4rpcMw=,tag:bFL7/dgP3Vp4URDMmyR2ug==,type:str]
    mariadb-database: ENC[AES256_GCM,data:QLZNrYxtRw==,iv:wHcpTGzHtfVEgVntiUy/IFs1vj/cn+LEP2P6GSQyUdg=,tag:2Zk/BD6KXu9EsPkEi4Ro+g==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:Ai1k+mWVSgXB4oLa,iv:EQA4Lp0dJoEF+aTt+cCJwL6USXPCqyYo1ydBncTOujA=,tag:lqxGdTQ0sMAnOHf0RlDt2A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:XDGMG/uNW78MJRJM,iv:vBt5gMKzoLdE/yb0oiuYdQDEn9NTSjb2JlaU6KT/iIY=,tag:iMYo+zABrD8lHJMSQkQ+rg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:X6DW0wLmNS0lg4br,iv:HpFHouDHwY57V5dnaBg27piFtIYOpiPbSdcJ4cdzpR8=,tag:ZmQ+yWIdLpYR4gFaGpyUHw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNXMzQ0hPMTE4cW1ESzlR
            YWJhcGF1QW0rMEFvaU5FSnByeWt1YmIwQ2tZCm1JRzlxV1dpRGluVlhCdlBhMmhU
            bGhONktMcDVjcVlCYkVXN0hpY09RdDAKLS0tIDllOUpYOU90RWRpYXE3MjZrdGNo
            TE9qTU5UdVN0TXYwRFg5bEszTTBNRlUKYDaz5AsomN+z7ceprlTm+BQM40mguWB1
            GMB3vJnsc/AAwc6d5aBqyzgXgt4fjEn6CzSgqqKcuvjoRVWJlMyGAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T06:31:08Z"
    mac: ENC[AES256_GCM,data:bh2pQpB/v4rY6yMvGIpgAalOe9b7hpJCgHdCsRdHOUWwCVr8tBuPhOj9CQSWvXTsIrXVjdGQF9ZUQiuA5As5AY9A+47EV/UQZfEBqER0Pqdoz2cIO0gFnEUUrSTujbgD/1/+JFwvA0Yet4pbhX/wICw5bu1DlzvyXmq4fh1k2k4=,iv:qHF98aZHDtGqXLKvYWQViYXg24+9wy47D5jnHkYVCWo=,tag:OipB0P0FiT4bmjtRsuU2/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
