apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../base
  - ../../../components/storage/sync.yaml
  - ../../../components/dns/sync.yaml
  - ../../../components/vpn/sync.yaml
  - ../../../components/ingress/traefik/sync.yaml
  - ../../../components/directory/lldap/sync.yaml
  - ../../../components/authentication/authelia/sync.yaml
  - ../../../components/backup/k8up/sync.yaml
  - ../../../components/tenant/sync.yaml
  - ../../../components/database/sync.yaml
 
components: []
  # - ../../../components/database
  # - ../../../components/observability
