apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../base
  - ../../../components/storage/sync.yaml
  - ../../../components/ingress/traefik/sync.yaml
  - ../../../components/directory/lldap/sync.yaml
  - ../../../components/authentication/authelia/sync.yaml

 
components: []
  # - ../../../components/storage
  # - ../../../components/dns
  # - ../../../components/ingress/traefik
  # - ../../../components/vpn
  # - ../../../components/backup/k8up
  # - ../../../components/directory/lldap
  # - ../../../components/authentication/authelia
  # - ../../../components/tenants
  # - ../../../components/database
  # - ../../../components/observability
