apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:c7XtWORutZGcbhZQpJuUQw==,iv:OLkMRBld1DndUcuAKuRhebsCl1wKB1NyBMLsUpcsogU=,tag:SGLXDcjz27cPQlXQv3GOkA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:FaCNEMAJuA/zfVFNQn1fJcb78PFmoU7rwrvyHkNugso=,iv:LvEzDqhOELK6oWIWdUNgPd/DHYVpiBcRrNmH6UMIBVs=,tag:4iKeClEzjgd89Cx738LDDg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:oBPd760kCG1K8XZnwIjIesKYNw25eQNm9YFti8U0mwg=,iv:wIeb9Exq7SHwMIE6sUOI21wXoaPUWk5gR6f5C6EWeas=,tag:Z2aD8yQVcLpEBPBfJNgY6g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFNjTHpsbmUxc1NjbG93
            RU03amlQSEpEK2FQSHRjWWxCa0t0Umk5NkEwCjV5Z1loVVdlZmVDYUdMSTBIekdZ
            Z3UzaWZwbENEWVZDYU9KdE85QlJYY2MKLS0tIFF4d2tPVGE3SStBcDl4NmdTV1FB
            dnhsU0o0dm11ZnNIMzR3UTRFdStIT3cKZ0MCAN9SqUiVdVxzTERzEwFi74TWjkqL
            zxlrkmfyKU3t0WFc57RtfSmOBqxB9DArW2j2PMbBGsLaRvcZUWzQzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUlI5THZXR0ZaV3B3Z3h3
            c0h0aGdRY0tEWlI0T0pVbnhiVDdBNWhZVUd3CmNyQ044bWVwR2kxRi92TVBZQ0Ni
            aWxCeEtqbzdFa2JrbXQ5TEE5aWs2bnMKLS0tIG54bzJrNjVrSW92VGtMc3llbm9U
            dThVeFI0eUVkUGR6c0pJbUk1MEE4Zk0Kj020hhsPZgy0GOFfd8TCiXQ45nge5iax
            Uae0xX7Mh7NMoIa1x7/uEFYsVXUjFCT82LRzsoatAdc8MCpSOpFlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T09:23:12Z"
    mac: ENC[AES256_GCM,data:N4sRJ19b6tBbFtASd/6CbgLfUD0D7vFwvLd+QbEmwNSQPRhad5hRBYmXR8Mi9RFQHMNRPuO9kRDdqdGXgcUhKRBjXUCliifbsNkFtT3KF/oK59k/qAozD7AuluFwCj2UT+lRPkqkEKlWYEXX3xy0sQEwTG6+FfyulMjhCmOhhuI=,iv:WtmXN1C33Huti6ZLJEZEaoJkMNh8TZoqlFUpgwd/bKI=,tag:mdv0ViLJfAYBh/W8qfTwow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:AAbJM03lLoMwloS5Yly7BA==,iv:0G/9e3ekq5xJLFQ+stWV6DVJ4jG3ZNKJaX5JQ7zkvfU=,tag:JK16lEBxz3CJxV37CnZMQw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:P0QpeoHfu1wBxFwNE4C47JVEox/h/OhWJ8t9U8sseG4=,iv:MhkIC0Kw/ce2sMnUqo6jqhShcs3i5k32Gdp7tmaCplA=,tag:3HonPhhAbtbhyAlTIqEzFA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:Wbg6FVE3b5V4Mg/Wl9O0vMOQcIHBaYu02h1eQWCneT4=,iv:5+QnCeiOOGSn9F2P18HpMUEk1Ksj5ThHqVB7UvJgodM=,tag:IXHja81ehFlSLb8+DwmdXQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFNjTHpsbmUxc1NjbG93
            RU03amlQSEpEK2FQSHRjWWxCa0t0Umk5NkEwCjV5Z1loVVdlZmVDYUdMSTBIekdZ
            Z3UzaWZwbENEWVZDYU9KdE85QlJYY2MKLS0tIFF4d2tPVGE3SStBcDl4NmdTV1FB
            dnhsU0o0dm11ZnNIMzR3UTRFdStIT3cKZ0MCAN9SqUiVdVxzTERzEwFi74TWjkqL
            zxlrkmfyKU3t0WFc57RtfSmOBqxB9DArW2j2PMbBGsLaRvcZUWzQzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUlI5THZXR0ZaV3B3Z3h3
            c0h0aGdRY0tEWlI0T0pVbnhiVDdBNWhZVUd3CmNyQ044bWVwR2kxRi92TVBZQ0Ni
            aWxCeEtqbzdFa2JrbXQ5TEE5aWs2bnMKLS0tIG54bzJrNjVrSW92VGtMc3llbm9U
            dThVeFI0eUVkUGR6c0pJbUk1MEE4Zk0Kj020hhsPZgy0GOFfd8TCiXQ45nge5iax
            Uae0xX7Mh7NMoIa1x7/uEFYsVXUjFCT82LRzsoatAdc8MCpSOpFlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T09:23:12Z"
    mac: ENC[AES256_GCM,data:N4sRJ19b6tBbFtASd/6CbgLfUD0D7vFwvLd+QbEmwNSQPRhad5hRBYmXR8Mi9RFQHMNRPuO9kRDdqdGXgcUhKRBjXUCliifbsNkFtT3KF/oK59k/qAozD7AuluFwCj2UT+lRPkqkEKlWYEXX3xy0sQEwTG6+FfyulMjhCmOhhuI=,iv:WtmXN1C33Huti6ZLJEZEaoJkMNh8TZoqlFUpgwd/bKI=,tag:mdv0ViLJfAYBh/W8qfTwow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:JVPaE/ykhk27lbknvWLpjw==,iv:wxpuqV/sqIZIdkCMF41R+h8fdV1POWbeLvWZ631A+2U=,tag:2DsSC35PLG2YclpaSKp0+g==,type:str]
    applicationSecret: ENC[AES256_GCM,data:bkGvAJX8K3j8gWYrDLg7EG1SnH//pYWpVYBZXKAj0V4=,iv:0O4kLe3Az95YIAmfiE7beXMt9Y5O7oZkXfkCASQ3pLM=,tag:Tf64griTpbS3Q6qupOVObg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:B8p+jWiTm7le92AaLN/CzgNCyyTarMH/U5eNXNUTRGc=,iv:rRrY7dbHuMuS9t+MVwaTTqKu2HawDXLjfpWwN9ag9Wc=,tag:wG0fipRpBkD586CJ/nYAwg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFNjTHpsbmUxc1NjbG93
            RU03amlQSEpEK2FQSHRjWWxCa0t0Umk5NkEwCjV5Z1loVVdlZmVDYUdMSTBIekdZ
            Z3UzaWZwbENEWVZDYU9KdE85QlJYY2MKLS0tIFF4d2tPVGE3SStBcDl4NmdTV1FB
            dnhsU0o0dm11ZnNIMzR3UTRFdStIT3cKZ0MCAN9SqUiVdVxzTERzEwFi74TWjkqL
            zxlrkmfyKU3t0WFc57RtfSmOBqxB9DArW2j2PMbBGsLaRvcZUWzQzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUlI5THZXR0ZaV3B3Z3h3
            c0h0aGdRY0tEWlI0T0pVbnhiVDdBNWhZVUd3CmNyQ044bWVwR2kxRi92TVBZQ0Ni
            aWxCeEtqbzdFa2JrbXQ5TEE5aWs2bnMKLS0tIG54bzJrNjVrSW92VGtMc3llbm9U
            dThVeFI0eUVkUGR6c0pJbUk1MEE4Zk0Kj020hhsPZgy0GOFfd8TCiXQ45nge5iax
            Uae0xX7Mh7NMoIa1x7/uEFYsVXUjFCT82LRzsoatAdc8MCpSOpFlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T09:23:12Z"
    mac: ENC[AES256_GCM,data:N4sRJ19b6tBbFtASd/6CbgLfUD0D7vFwvLd+QbEmwNSQPRhad5hRBYmXR8Mi9RFQHMNRPuO9kRDdqdGXgcUhKRBjXUCliifbsNkFtT3KF/oK59k/qAozD7AuluFwCj2UT+lRPkqkEKlWYEXX3xy0sQEwTG6+FfyulMjhCmOhhuI=,iv:WtmXN1C33Huti6ZLJEZEaoJkMNh8TZoqlFUpgwd/bKI=,tag:mdv0ViLJfAYBh/W8qfTwow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:FxtDlV4E7r6eMHdSRiNovA==,iv:Ae2W9HQUkPdlFQFfBYX8p3yRIWF+/WtA3Canjm/3LnU=,tag:8Lpq1q+YLW0XO/CRWZGRoQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:9MEXHmWD67iv8j1G/0yN4Vb5/d27FlyOESMopaz8y0E=,iv:4Q+p+EESGvJkKZC50lSTJut8ZH/XlvEboSDv/k1wfAU=,tag:LRFGo1TasKmZkdi4YH+9gQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:ocV+exIciyAD94whewWNdK/eloaKok64cmvKvgNL94k=,iv:j89UOPl+8CdQPlJGEWt4ocNM0gPMyWgLc9r9Z1P704M=,tag:GAivKILnE7/CJRF3LJy5Hw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFNjTHpsbmUxc1NjbG93
            RU03amlQSEpEK2FQSHRjWWxCa0t0Umk5NkEwCjV5Z1loVVdlZmVDYUdMSTBIekdZ
            Z3UzaWZwbENEWVZDYU9KdE85QlJYY2MKLS0tIFF4d2tPVGE3SStBcDl4NmdTV1FB
            dnhsU0o0dm11ZnNIMzR3UTRFdStIT3cKZ0MCAN9SqUiVdVxzTERzEwFi74TWjkqL
            zxlrkmfyKU3t0WFc57RtfSmOBqxB9DArW2j2PMbBGsLaRvcZUWzQzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUlI5THZXR0ZaV3B3Z3h3
            c0h0aGdRY0tEWlI0T0pVbnhiVDdBNWhZVUd3CmNyQ044bWVwR2kxRi92TVBZQ0Ni
            aWxCeEtqbzdFa2JrbXQ5TEE5aWs2bnMKLS0tIG54bzJrNjVrSW92VGtMc3llbm9U
            dThVeFI0eUVkUGR6c0pJbUk1MEE4Zk0Kj020hhsPZgy0GOFfd8TCiXQ45nge5iax
            Uae0xX7Mh7NMoIa1x7/uEFYsVXUjFCT82LRzsoatAdc8MCpSOpFlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T09:23:12Z"
    mac: ENC[AES256_GCM,data:N4sRJ19b6tBbFtASd/6CbgLfUD0D7vFwvLd+QbEmwNSQPRhad5hRBYmXR8Mi9RFQHMNRPuO9kRDdqdGXgcUhKRBjXUCliifbsNkFtT3KF/oK59k/qAozD7AuluFwCj2UT+lRPkqkEKlWYEXX3xy0sQEwTG6+FfyulMjhCmOhhuI=,iv:WtmXN1C33Huti6ZLJEZEaoJkMNh8TZoqlFUpgwd/bKI=,tag:mdv0ViLJfAYBh/W8qfTwow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
