apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-cert-manager
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
stringData:
    applicationKey: ENC[AES256_GCM,data:Go5rYySkOgaikdPGkiOQjQ==,iv:ZhIuREu3sghj8Nnu5BVBzbQG6hGiwAT2scJBvhwSvuo=,tag:tBNXfL2NWNVvzEFpyfnoRQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:dORLI2dOKts8V6m4C5Sn8cxVoM2ARk8e3CCH4cYenEU=,iv:w4yB8P2GH/l0gJG0xSPDScgzy7H1yzTuKSDIRBvVxHc=,tag:lZ0M9ObTjjShdVrCwChFVA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:H00Lf9c5iBFk9wZ1AKWEk5XYAKKLB3aVJXC5c0SfuL4=,iv:lPfviYFrIvAMD28ssquyzmj3bd37EYg2qndLBlJAVoM=,tag:xy+HPXNEEmE19LvlTOEiZQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDJMZUJ6MXpIMkt4N2JN
            ZGxRZU5xQWhPTGZkSlkrdlJIdjVjMUExeHhJCmFLcVAyNkJmVy9UbE9RVXNBSXFm
            YWQwSWtkR1AvckFMQnBWUWg1ZFAxZUkKLS0tIEtBcHRwYUg4OGNldVJpZHh4ZW9h
            djdvMnRIbmZET09lU1ZNUDFNNEtSRUEKNtjB+mzyQTFVG0lz+2NYuzJfkeV2Agp4
            y5SUaQK6WZcHhI/kr2vgB5bY7kZLW9XdcOr0QhWVfvQPaH1LdBYDZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRUN4cW04TUJHSVkyeVBi
            VTV4aSsxVUdwUWU4WERYQmFKdUI0WkYyVEQwCkwyWE9WM1JjZ2FaQmUvaFc5Yys5
            RDVPMVZBeitZS1puUGt0MVBLcE5BY1UKLS0tIDhMczdxeW9hNW94UEcvNWhubDJM
            L1ArZ0pyemVjNVBrTno4WkJNV3dVMVEKjWQ6GVjeC5JXBINHrhvFU1nNwOiFbKSR
            qkBcDoeEaCCchbJYp8dpXIGGR/A2IqFnxKCfiHU2Kb+e3ICe+JSDOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:08:07Z"
    mac: ENC[AES256_GCM,data:SAw16WO3dUr27S4J2Q//OqLFW6M2/ssj1Y8x4a30V5jO+KcQr1UJU9ZzdxD+29NEd8kvi5F/S6ynp2sUPlff7KXpAJfU4ccH4uAMJJMhL2kNBkKiH0zQ1qK4gaNbkZTRavLh1oYqe2SyuDVMPwFCPf5xe8MBJHqFnvp/p2mk4lo=,iv:3guFgCC4mQ4SFd8Y0eS8QJ8lzgtkM8YOS/4AU+c4WJI=,tag:2SkEmEGP+Bb8Qy7Dgl6rGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:UU2o73kACt5V5U1O/Ob5yg==,iv:x3BIt+G5mK2Kx7VSbaLaid1Q/MJvWytd1xMW2/ZdNuA=,tag:dwUp8AR7Ez7i6epdRuc8Ww==,type:str]
    applicationSecret: ENC[AES256_GCM,data:mKxZre1Bqd43OrY76fHvxqh0pSAhjWmqnuBH+OEUcPk=,iv:oK42heJ+c1JjfJL643BqLREYXSB0gingK2ZFQFDzuSU=,tag:TOq5uEruuaX4c5UL14oDzA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:liElxMiqbzI/JqclKuSyUd/wPsI+ZTqA2nlAvqssfQ4=,iv:8HgJP9Me71QT0BHIdIx+C/WyNLwV1jV2eC5ZgJxqy6E=,tag:Nz4/24rbUXK6WFoJEtJDdA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDJMZUJ6MXpIMkt4N2JN
            ZGxRZU5xQWhPTGZkSlkrdlJIdjVjMUExeHhJCmFLcVAyNkJmVy9UbE9RVXNBSXFm
            YWQwSWtkR1AvckFMQnBWUWg1ZFAxZUkKLS0tIEtBcHRwYUg4OGNldVJpZHh4ZW9h
            djdvMnRIbmZET09lU1ZNUDFNNEtSRUEKNtjB+mzyQTFVG0lz+2NYuzJfkeV2Agp4
            y5SUaQK6WZcHhI/kr2vgB5bY7kZLW9XdcOr0QhWVfvQPaH1LdBYDZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRUN4cW04TUJHSVkyeVBi
            VTV4aSsxVUdwUWU4WERYQmFKdUI0WkYyVEQwCkwyWE9WM1JjZ2FaQmUvaFc5Yys5
            RDVPMVZBeitZS1puUGt0MVBLcE5BY1UKLS0tIDhMczdxeW9hNW94UEcvNWhubDJM
            L1ArZ0pyemVjNVBrTno4WkJNV3dVMVEKjWQ6GVjeC5JXBINHrhvFU1nNwOiFbKSR
            qkBcDoeEaCCchbJYp8dpXIGGR/A2IqFnxKCfiHU2Kb+e3ICe+JSDOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:08:07Z"
    mac: ENC[AES256_GCM,data:SAw16WO3dUr27S4J2Q//OqLFW6M2/ssj1Y8x4a30V5jO+KcQr1UJU9ZzdxD+29NEd8kvi5F/S6ynp2sUPlff7KXpAJfU4ccH4uAMJJMhL2kNBkKiH0zQ1qK4gaNbkZTRavLh1oYqe2SyuDVMPwFCPf5xe8MBJHqFnvp/p2mk4lo=,iv:3guFgCC4mQ4SFd8Y0eS8QJ8lzgtkM8YOS/4AU+c4WJI=,tag:2SkEmEGP+Bb8Qy7Dgl6rGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:j8s6ppbVGVvbcQivBQMRWA==,iv:a3JmYTvzWOhs83saEBHnA48gFhR5xcXEtSGS4vwRNf0=,tag:+IwZolvowXJN/SJvsoFH9w==,type:str]
    applicationSecret: ENC[AES256_GCM,data:iRAoxlLt+pcNSDxJkYe58LBA+VvrSDKnSvaJl0KVxlg=,iv:TTj51jdBNg1SKIydc3dQtysn1BtQtZzGDahAzsNECIE=,tag:7zn+5xesZGTXUdVixwcxgg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:brAMz7uRnaxit1PXFmsIWUc5JjdnpTYFLKZ+1bbK4iA=,iv:uHutZecn7LGwucVXgsLEht4NVqWKdwLzHQjk3cl9uY0=,tag:9j46CdkSEaMshhBAyV5/lw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDJMZUJ6MXpIMkt4N2JN
            ZGxRZU5xQWhPTGZkSlkrdlJIdjVjMUExeHhJCmFLcVAyNkJmVy9UbE9RVXNBSXFm
            YWQwSWtkR1AvckFMQnBWUWg1ZFAxZUkKLS0tIEtBcHRwYUg4OGNldVJpZHh4ZW9h
            djdvMnRIbmZET09lU1ZNUDFNNEtSRUEKNtjB+mzyQTFVG0lz+2NYuzJfkeV2Agp4
            y5SUaQK6WZcHhI/kr2vgB5bY7kZLW9XdcOr0QhWVfvQPaH1LdBYDZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRUN4cW04TUJHSVkyeVBi
            VTV4aSsxVUdwUWU4WERYQmFKdUI0WkYyVEQwCkwyWE9WM1JjZ2FaQmUvaFc5Yys5
            RDVPMVZBeitZS1puUGt0MVBLcE5BY1UKLS0tIDhMczdxeW9hNW94UEcvNWhubDJM
            L1ArZ0pyemVjNVBrTno4WkJNV3dVMVEKjWQ6GVjeC5JXBINHrhvFU1nNwOiFbKSR
            qkBcDoeEaCCchbJYp8dpXIGGR/A2IqFnxKCfiHU2Kb+e3ICe+JSDOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:08:07Z"
    mac: ENC[AES256_GCM,data:SAw16WO3dUr27S4J2Q//OqLFW6M2/ssj1Y8x4a30V5jO+KcQr1UJU9ZzdxD+29NEd8kvi5F/S6ynp2sUPlff7KXpAJfU4ccH4uAMJJMhL2kNBkKiH0zQ1qK4gaNbkZTRavLh1oYqe2SyuDVMPwFCPf5xe8MBJHqFnvp/p2mk4lo=,iv:3guFgCC4mQ4SFd8Y0eS8QJ8lzgtkM8YOS/4AU+c4WJI=,tag:2SkEmEGP+Bb8Qy7Dgl6rGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:q+YWh7iJK9TZ7IVn02SMqQ==,iv:necHUBn6XU5Za2blG5/CnfejqYO3DJKN940OY7WPxRU=,tag:3iV7FTVVNuNQGBM32GuCWQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:mY1gqp9b6Es+bvCDujTRqRRK1SFM77wI3GAo/vcy+6M=,iv:7op+G/PyZcoyhLwBbfrS6dg4R6hHL9zCU7A5b1KK1u0=,tag:lNB2KQCNY/lZg6X1Udd2uQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:+9zm7z0r/B9oj5ASmuG88pBvPxF759k8pYTCJGG3EeQ=,iv:Nf1sNdvsa7AvLHKYe8uH+8dJW4UAlmaYWEIjFrWBRzk=,tag:LDjIbrsp5jU5TsQI6s3e2g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWDJMZUJ6MXpIMkt4N2JN
            ZGxRZU5xQWhPTGZkSlkrdlJIdjVjMUExeHhJCmFLcVAyNkJmVy9UbE9RVXNBSXFm
            YWQwSWtkR1AvckFMQnBWUWg1ZFAxZUkKLS0tIEtBcHRwYUg4OGNldVJpZHh4ZW9h
            djdvMnRIbmZET09lU1ZNUDFNNEtSRUEKNtjB+mzyQTFVG0lz+2NYuzJfkeV2Agp4
            y5SUaQK6WZcHhI/kr2vgB5bY7kZLW9XdcOr0QhWVfvQPaH1LdBYDZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRUN4cW04TUJHSVkyeVBi
            VTV4aSsxVUdwUWU4WERYQmFKdUI0WkYyVEQwCkwyWE9WM1JjZ2FaQmUvaFc5Yys5
            RDVPMVZBeitZS1puUGt0MVBLcE5BY1UKLS0tIDhMczdxeW9hNW94UEcvNWhubDJM
            L1ArZ0pyemVjNVBrTno4WkJNV3dVMVEKjWQ6GVjeC5JXBINHrhvFU1nNwOiFbKSR
            qkBcDoeEaCCchbJYp8dpXIGGR/A2IqFnxKCfiHU2Kb+e3ICe+JSDOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:08:07Z"
    mac: ENC[AES256_GCM,data:SAw16WO3dUr27S4J2Q//OqLFW6M2/ssj1Y8x4a30V5jO+KcQr1UJU9ZzdxD+29NEd8kvi5F/S6ynp2sUPlff7KXpAJfU4ccH4uAMJJMhL2kNBkKiH0zQ1qK4gaNbkZTRavLh1oYqe2SyuDVMPwFCPf5xe8MBJHqFnvp/p2mk4lo=,iv:3guFgCC4mQ4SFd8Y0eS8QJ8lzgtkM8YOS/4AU+c4WJI=,tag:2SkEmEGP+Bb8Qy7Dgl6rGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
