---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: kube-system
spec:
  targetNamespace: istio-system
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3