
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-cluster
  namespace: controller-dns
spec:
  endpoints:
    - dnsName: internal.${cluster}.${domain}
      recordType: A
      targets:
        - ${headscale_endpoint_ip}
      recordTTL: 300