version: '3'

tasks:


  

  le-portail:alterconso:
    internal: true
    desc: Backup alterconso
    cmds:
      - echo "alterconso"
    silent: true

  le-portail:ecolieu:
    internal: true
    desc: Backup ecolieu
    cmds:
      - echo "ecolieu"
    silent: true

  le-portail:epi-libres:
    internal: true
    desc: Backup epi-libres
    cmds:
      - echo "epi-libres"
    silent: true

  le-portail:dolibarr:
    internal: true
    desc: Backup dolibarr
    cmds:
      - echo "dolibarr"
    silent: true

  le-portail:
    desc: Backup all le-portail
    cmds:
      - task: le-portail:alterconso
      - task: le-portail:ecolieu
      - task: le-portail:epi-libres
      - task: le-portail:dolibarr
    silent: true

  la-bergeronnette:website:
    internal: true
    desc: Backup website
    cmds:
      - echo "website"
    silent: true

  la-bergeronnette:
    desc: Backup all la-bergeronnette
    cmds:
      - task: la-bergeronnette:website
    silent: true

  default:
    desc: Backup all
    cmds:
      - task: le-portail
      - task: la-bergeronnette

  