apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  values:
    wordpressUsername: berjoadmin
    wordpressExistingSecret: wordpress
    wordpressEmail: labergeronnette@wanadoo.fr
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql-version-8-lts.controller-mysql-operator.svc.cluster.local
      port: 3306
      user: ${tenant}
      database: ${tenant}
      existingSecret: wordpress
    wordpressPlugins: []
    extraEnvVars:
      - name: WORDPRESS_SKIP_BOOTSTRAP
        value: "yes"
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: local-path
      size: 7Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: www.${tenant_domain}
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      extraTls:
        - hosts:
            - www.${tenant_domain}
          secretName: www.${tenant_domain}-tls
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    initContainers: []
    volumePermissions:
      enabled: false
      resourcesPreset: "none"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi