apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:eDN/vSvkB1X4Nr2Qm3U=,iv:a5FlQ7BEprnSrwkN21E1FWm3nO1F8ac+3WaB3yUEALI=,tag:5SDBl6c+wJgD7R4gYPJMqQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:F/Sa2n1M,iv:Dd8myQfIF2EvpJ085PYqNn0zow6dsM53l7WmQ9OPqiU=,tag:ct8IGXkYB9Y8/fAJIg2Haw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:RMOfyx+EKfx4zAlibQE=,iv:Wj5FyRv8zzWDCUyLWzj/gs1Nw/nXIZf3QEskCUq2UfA=,tag:wzIAQBUOKi4a+12RYQgcxA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:svYQDD8=,iv:uFfqd2h8Hj3t3694ZrhDkIq0TPfRK+/q1DQMam75WZk=,tag:mBsuP6oabG894zThAYy1dg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:rbgiYQdbwKMNK7oCxoU=,iv:2B3+YrbZF0F50dGb6IfJoRZSpD82+dQo1+Igpi3VkTo=,tag:XujU4aCyaqflrBMhsbAVhA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:cK2zmAs=,iv:vTztO00pC8F7pEW1Qg6Rbx1Wd+8hpQ3Cw6lZfjfHjy4=,tag:JVY9XH3/8j0WmNpsdy1irg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YjdhZ2t4NDlSL3NWczFU
            b0RkenZWRm5pQXdYU01Jc3lKWjJSWVk4V1RzCjRKNGhxeVB5RytERnNkOWU5cjB5
            TXg2dlEwVlVobkg5RldaaGZGWkxmS28KLS0tIEFvNUdzTEdLbjEzMVBjR3dzNXZR
            RW9jNXJoTTg0MTRZcmZZNzNOOE44bTQK7kU4+0y6lksylsX4H/+2WeNjzdMwyloX
            AO6R+jGjRgYCaXfKFgd7ZsTbIPwn2Lg9adCD8rs2MYD8c9eeFpI8iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T10:47:13Z"
    mac: ENC[AES256_GCM,data:CEV6+fcqFgxUxidwyc71jyr6DBxkjv19OceH45D7o9qGHrP7Y672Ne69BObDoFd4o0u8LDv4rfbqHFZ2jxn3mSxcunkmi08q6FoAgpDeMnxPu1MPfaDT/l+3Pk3QMMZiB5H9zF3PdSQ8uXUK8fvL4HofnufjjGU1nywDxPsDCx0=,iv:Sl3gWmT58ikF4Cn3rf2bJEJOlXWD0vNVJq9AtCsHtoA=,tag:4QhccbIcmekCu7PZcglLgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
