

apiVersion: v1
kind: Namespace
metadata:
  name: controller-cni
  labels:
    # Informational labels
    alter-it.org/controller: cni
    alter-it.org/component: cilium
    alter-it.org/managed-by: fluxcd
