---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: la-bergeronnette-website
resources:
  - ../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: la-bergeronnette-website
  - target:
      kind: HelmRelease
      name: la-bergeronnette-website
    path: values.yaml
  - target:
      kind: Namespace
      name: la-bergeronnette-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: la-bergeronnette-website
  - target:
      kind: Schedule
      name: la-bergeronnette
    patch: |
      - op: replace
        path: /metadata/name
        value:
          name: website
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: website