apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../base
 
components:
  - ../../../components/dns
  - ../../../components/tenants
  - ../../../components/observability
  - ../../../components/ingress
  - ../../../components/storage
  - ../../../components/mysql
  - ../../../components/vpn
  - ../../../components/authentication
  - ../../../components/directory
  - ../../../components/backups
