# Configuration Alertmanager - PLACEHOLDER (sans SMTP)
# Pour activer SMTP plus tard :
# 1. Décommente la section 'global' avec smtp_*
# 2. Remplace le receiver 'null' par 'email'
# 3. Re-chiffre avec SOPS et commit
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: controller-observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:N96kO2TQfJ6axsMqIYKhPljBX8ZBTqZjdORCktR30jJ5X//m04ob5Kw7B+CeBTUZM9KVxSyUILhoMQKPy9bO7K6wQmheCn5kSNpQMjczi0Fg7W5j+DI2Z4OdR/qlXJ4wvC85E724xpUhaOMNa0U0cIjcV74tBmSjeH2V+GdoWP8etNTBpnDk3laR/D0DLjCawCqr1DnK9s7MVE1aSvGfCGjiQT5BbjY03WITgA6tReSGtI4ACe9YUcYiFBd5RFIS2kB0iqFLshroTC3lyhKmSe0MEbZVNp/zTdnrRbx7ESL8tb8MRV3ExBgGmFUUy8QSOBc79VTYNMtxScqv73HDZJuxZB6phTcPpKscSJceRTohVyRzgU4bzDsCNf8IiNcEjiFZalYX9bHXc5rn+7e+blb2C2bbsmKePRu/uN5xdphMW769cRqVIAPd73AtAelrfg0/foFXiAj4/CajPkyf7qb7AuUtX7v0HeZj9OWc/McJ1SpObF1DEYM8XT+8u8+vh8tiYKyQBehJlKb1gGAN6on+zzPiVriTGTxSKecBdtNkBSXr5/IPvy3m7IUfEjhVoxF0Y7p3zETCMGinti8RPP2BwLrYlbN4gLSIz19kJM6uHspfUgcwlcheEf8++dXgVEfUyE3N26OgTavEe+mFJJX/GP4bFnM7++OZb2b/U1TZJWq/NuYxQVQgNRAyjIEaTupgw1OKAevnDozYIW9CnPCC8Pf5SXzS4AEfRaof1vGIkyQ7IGM2WA7kh36wMpvd2fpG/PuJwG+Zjxx+AadpgPzTXqylfBTMf70gI5AyIftt+wdt3ExF0PR+V6bSXC11g4PFom+AIDjfQl0=,iv:7TQq7vwZClWV9Aap5PZU0AfK/7ucjenbSLmHSTpQjnQ=,tag:rMiou55qOfYBpSqeJplYwQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSDJyWVYybDRjbVRuSVFk
            VUxhVk9xVHFKanR3MFhWOXZ2K0Njbm9FdFFvCkV4bnRtL3F2bzNGcWcvbUh6RlNO
            YjhTQ2hyeVdWL3o3R2d6VjlqQlB6UWcKLS0tIERoekR2SWdLZnBNZTY2Y3dmUnc1
            MWwzd091K21JeTdsRFpWcTVpbFRBU0UKDRHUArdH5Ojp8KXdpBs3rf1mj3eOTn/Y
            rw1x3RP8msl6nxMCUEIP1fMU7SDVc60oskVq1DVzFd7fduihQIYSRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZVhqcEhsQnBqZy94aHk0
            UC81L2dzTHVDcWJ2M0J0UkdEZytoMnZnWEhJCk56cnVqa1podlV2K0xFT3d6amdY
            K2JFRVFhNHkyc1lQanowQlRpU3VKU1kKLS0tIHkxa2RHbkdKYlBTd0J3NFRmaDha
            eUVCalBCM2xCeEhQUC9YTUtNSTQwbXMKvtDAcbO7tv4WU1C665Ac1HI6BEkjxV2d
            KxgaeG51OYcuSrXw5K6QoHHXcnacMzOgirqseYZ+dB6GRukpuUjqEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:04:00Z"
    mac: ENC[AES256_GCM,data:ErZcygDe1B05YTMByyBwMy6Du56L7MFfmY3jaRCelOku7/kjH9ecNA3LC4SnhfkfMSS5ob/mk4J0+YsXObS/eeaPjdm4plGnjUZGobF+KmAcdcrmwvkmfGA1jB1s9F6VoHAuO/qiRvcg0YTt904CbtS90VOLtht5BgvfWuqg1ZY=,iv:+D3aZU4P6kQQGTAFfRM0/Xw9M74uDLf6zUQ6iwTDZZI=,tag:oW4jI6DeJWbsLeK7D2w8ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
