apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dns-ovh
    namespace: controller-cert-manager
data:
    applicationKey: ENC[AES256_GCM,data:x2LkZpfkLvdvOz8tyZp7NqC2HDAoL83E,iv:NfNCCT4d2bsJSjJAcK2Daj7lX/KzO6Z2pQmwRVpNrVw=,tag:Ii3y0MBso6LC3mgguqBdgg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:ErbLdgaVFLYuums33FIXkp5T7ykiXw4X,iv:LCbM21emsoG0BBus6GNo4j/3deTZS/F30ARd/+dRbmk=,tag:h0vzAHXqpRbTK2Ubhxp+Rg==,type:str]
    consumerKey: ENC[AES256_GCM,data:78LJqiII9Y8lXaAGdeKbCbdIwFkclrH7ZYTttgUVvQwpcB3zz2LbRzTA5Fw=,iv:zwHCE5LauKAGUdgBpYX3yaQtNm3dKCjYeFuUWDwEqJk=,tag:bMKCTM4gkClV5jtd85Op+g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQenc3elBnQXpsUTA1S0xF
            UG9QenBKcDZpamFSakhmcTRFN2c3SWhOVERZCjRBRXVJNG50VEJBd0tremZ2WjE1
            b2E1ZGpzd2EyT0RDdHN6ekt5TGQ3OGMKLS0tIHpiRGtLb0xWVGZaYnlaTTFVdE45
            OXIrbEo3bXBXVUplWXQwNXh5d0FYdEkKEe+E4JrgC+l4zMeHcXqOV+RepThIsaBk
            JTr/B3ZPYzTrR9br20Q4Xbq2h97vXD4ZEQUQus30yzmLyaZikf/wUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOWVTTEx6OWRKL0J3U0Jr
            WmF1ZStpRWNMREEwTmR3VlhpcGd4dllNL0ZFCm1lQlhMZG9kc09DWDZnZlE5UW8v
            OElDOXdFRGxweDhDNTR2MExiTE5rTW8KLS0tIEhKRm04VWFSNjA0UUFmWDNTTld6
            MjlEK2JHNnhqaEZSeWVmQVlyZGloOFEK9BUSaRUV82dSh/EGT1I24aWtifrNODIe
            sIUZnvPf7+UhCwZbJOW8G1HXnsZ/MaMnwXA+n9Wc2Gcmq0CialAZ8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:38:28Z"
    mac: ENC[AES256_GCM,data:gQglAKtXxYkjdf9UX8+XQgr/ggq+gjs9Zvt8GeqnZTS1iXq7Qf6XAb3f2gW8xP0g8uXm4tmXpH/YmS+dwmPiR/0lRiAD4Q3CixKjrdi+dErg6xdCSzBzR+r4uRyi0XDp0VWlXFxxMgsxjJfQW9Evlc4IsREJVa7rVCGWmu4mZvA=,iv:e7m9cgRFYvrs4TCr8GlMVi0rt4Wl4Q/WK8C9Lun7Pjw=,tag:boZ5t+V/drcdyUI9C8iIbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
