apiVersion: v1
kind: Secret
metadata:
    name: dns-ovh-fermedujointout
    namespace: controller-cert-manager
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:GyaDqF3JLqpYqo1VPKjE7w==,iv:fAVUWwaoIWM84d21EGW+JiqMANcupjmccw+ztiZQG/0=,tag:ijbSAYAyglNXz02iT3o0Ig==,type:str]
    applicationSecret: ENC[AES256_GCM,data:pc1tWZB96jGcycaDV2YJZ/1hbCN/Xd1oDvm5bCoZMd0=,iv:qQm1m3xRXLtoRMp7uEACHoiSJHPOirjHaL9O2xIkbEM=,tag:a6d7j+woGHwAl8GysgZL0Q==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:PL3rL7j1wEA7gWDlO4ZdRN0zBEBZFbnsymbA9m8QRQ0=,iv:V8NA5tMEtW7N+ceR6Tw6FbXcJY4A6s23mtVk/YLh2HU=,tag:QbTCk+mCynfu2qk1SThxKw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cXhSVExMbEVpNVZINUY0
            MWVENk1Ya1c4M0FYcFV6WTFabmZwSXdHbDBBCnYvdTFZYnF1Y3RyTWIzUVVYa01o
            TGZLcUxMTGNCR3JHakQ5T2RZY25IYlkKLS0tIEdmcUw5c1dSdHVuM1diczhUSWtq
            VnJHaHl6aC9pb0NwaFhjMUFyMGJBOWsKNlb5QG+3tg7rEeczlY+UyIDaj+mHpqQX
            nXsDB+vzW2Rn/Vynl1CFYLH0wWLJtWhdLt3Q3dBIbb6bNhRb+xzXiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRby8zdW51bkx1aVVaUlZy
            djNsekZMOHdlaWFrR2duNUFrbjdJZjdXQUdjCkhQSlRsVktQazhIOGIyMEgwZzJj
            bmlOajBYMUozdk9ZVFQ0ek53d1k4cmsKLS0tIG05VzQwUlVFb29hREVEbkpJZ2R4
            QTFrM29TaUd1NVUrb1B2cjN4N2JFbEEKc/ZzF5FijF/aL09Y69segcw78Y7hXKOf
            oUTPu75MbcOCApB4oiPfdPKgxAd+hZ2Cu0Aa4ZWzj/wwzwtr1KSg9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:25:28Z"
    mac: ENC[AES256_GCM,data:AP1q38rQD4ddxnwTz54qABSXsK0sE7eD/FHhEKYwjd5GEgiYC4WKVz6fU2kaMJdknnixFj0zlLvH6xjyO13b3yb/JuyaIGQPZUJ2ze4ruZ+ednghK0c9arvPuafei7VshPiuHy4X1l1cdv1Aofsx3aVuHvRR9r05rv9oSdx70I4=,iv:BOTXIC+vrKbOeDp8bkRM35G5e+PvE1as4iOcLOQrejQ=,tag:gCd50VaPj/oovPKNEAk6Dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
