apiVersion: v1
kind: Secret
metadata:
    name: dns-ovh-ferme-du-jointout
    namespace: controller-cert-manager
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:gm/XrdBqN/8aoj1UhJkicw==,iv:yF0EnMRzcjB+FqaVhfD522DtU8gOYTj8yJ1oFbBLYQw=,tag:Rc7Cs9LoGxtkVXl7gwOEvg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:Oo2CWbG8OthlKlN8whuAibWbBM3KDLZo2wzJIKLi2tA=,iv:vuagXL4Ks1O1nH91v1baVa25RQ1srjYOP4iTAqqHFQE=,tag:8+YgfJeHrvZOiHq1ywKi8w==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:bVpka82OdCC9jvQX4RQNiuR8/uAAlmpQiGrUlXrLmkc=,iv:2CDmBMsPt7dTJFQconicH6BoSpBYSswCb2mkINzIZH0=,tag:6+uNum3pzQgi3qcgHy9o6w==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbEhwb0YyelJwYlhWTUNQ
            OU1jY0xuSlJYZ3J6SDBMQ01aTFJid3hwSFY0CmpnRGxnbDhMeDhJb0JvaUM3UUtR
            b0xNMGdEWkU5aXo4K3BBMkdwajRDUm8KLS0tIFZNdEIxS3lIRURhdithTUlUQTQ2
            VHpvWTU5MFIrOFMxeUJYbldMc1A2L00KqHWrytCLc9y1B4ZpU9WZEaVPOu4u5x4b
            motIGd9xf2TalICasyNW8hCsrA+z4s5ag4GMHLCF7UXrpzaH31+Z8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV0V3dk0rUzhMd2tneTQz
            T3Fwc1NjbUMrbHdXT2duL2llRHhseFlMdGprClZ0dmt3VjduVDBwUjRvQTVMbnZF
            VXRhYTRvL2Y5QTZxMFo2MmtxZklXclkKLS0tIEt6ajVjS3ZtakErMGVFV3Flc1Jt
            blNscEw4SkYwRERJSGMxMlNGSWVMOVUKX1YPipLKcJa40S6R89OrTaqjjmAhoeXC
            zSh+E1bRcz3C/gXxjpyt1bzg4Dk7gjTlI/Yflq+ND/VyqCJj15EzvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:49:59Z"
    mac: ENC[AES256_GCM,data:45guGztmoe5hcBBBILDdg9fFpRbkqhyH4tFrKGzfqdiMj4aXd/98Y9kk4/n4+5b0AmxaTpTegAlSKoo+FaRjjd1YCdgN0g1LxTlAuPTc7UTI07H3wg+m8S81peGlaGbtaW/82QuUuwxShkf4k+d1uxIIKyPmKVWYBAN6Ri7L+zA=,iv:cKJT5WmX0lb1kGiIPDbamwJLhoRsOzpKlUjNfo0zA/c=,tag:u5qG0VCqFbiCohsTYqHvBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
