apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dns-ovh
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector-s3-ovh=true"
data:
    applicationKey: ENC[AES256_GCM,data:+JIlzppf1aSmlP8wocnqmQ==,iv:K5YVzJEg/nemkf1i/oJgEUAKEYqvhrYD2UjFJTmAHHA=,tag:JOxSOK8farBoEU72dthwfA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:4asYmzdUqX4CF8aWGgf+bArtoCThL/ebk0Olrd9VO2M=,iv:CI4E1tOwr071w6OdFH2ZAUGLYHO2Wq1/ajmVsOZeyQE=,tag:FHfw/9wC1e2ExJeOWhslLg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:puVXQ48ZSkkimhiL+EqdvnoLrJ3fShLC2PzQUTD4niI=,iv:UdfqIEKZwb//jrW+UFHy8GVwwWioPqkTpv1lQfkX2bQ=,tag:5GIdRg0UzWobAgcwkNmhsQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDBFdXhOZ1c2THN1V2xZ
            MXp5MmhBOXBxcjgyYkc1Nys4ZkVISXNsREc0CjczR1Q0MHgxeHRVMmpsb3N6bDlw
            T0Q1Q0JQbjBFN0tDdXA0WDNwV0J5VUkKLS0tIDhWdllDenZJWXJBU0hISHhhRlRR
            OTh3K2srNEVyeG5qcjN3RnEyakhZR2cKBAbVzx2gNsP3p94myiHNB8K0v3oLoEYJ
            gJlyNbFm6RUB+3SJ0ahtukRINI3c5zT+QXOHcxfJdhkgN4b4ejWV9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNzdVM0RnOEZ4UGVTZXhv
            WlFwdzlIVnEwYUZ6Zkw2WUdWVEpOckpLaFFvCjJoSXZWeE9COXpQN015cDF3KzEw
            ODdXSUQ1ODhyMzJzUVlpQVFmQmxoWVEKLS0tIGNXTUlKajF0N0lsb0FYMEoxdXhl
            UHE3eG9jQ0VPOEsvY3dDQWxpSHNkK1UKka40UlKssXJUd9u7SrmqsLpXSIh/0Fsq
            IzVjD804ncH09V2N9JM8RKHjaWcpp6WMXXegLyeU6xxm0n5Xw0jzJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T11:21:43Z"
    mac: ENC[AES256_GCM,data:Wc+g1Om8sul6VYhc//nGQaW3WD97gnSZtIT4OMRuxedGcEzQuubj+o+6F9IVb+yhnabw2ipTevHC0kWmTvJuIrUHdHN/ng+pHE4xzMLbzcEHDc4tG717AkD5ab8wDv+QOnWJodWx/VqwyVfTyfjzSzaInVFATsNt1LcdgatldgM=,iv:E37yMKlAkbOK8ZbLtr6EP+s0vwjx48avdl6kLl+lrpU=,tag:r1ojHy9FlCjsfWSkCBaxJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
