apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dns-ovh
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/s3-ovh=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:pvrNT1C/lJqTe7+4fJMP1w==,iv:BVrurN5lW/oT6tXOgnKwL0kHS3v8ytKYqeUVQxOzOl0=,tag:FMJ1oMLhVl2bkiqpDS3LJw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:tzxCpgglmmCUCA7guFU4Mf+gBYlcowhLZDqA7Jhr49A=,iv:94ZQf7ebZraRlg49s3WMfLqKZcSj+3kQKCleGT+mlfc=,tag:Hg+8OFsC6TRpLMThWdEkvQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:y4oWRkNgSVKBbRC+uOCEAGqtvIZNr8qWSCrshvUDeUk=,iv:Bdm5R/Ho/dVnM+eSoKoEhbMORa3bqdAyvSuJigopRYQ=,tag:F6moq9t+ByK9RXGh9orG3w==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNTlMU1ZkM3J3RnVCVkIw
            bmFZTGlFV3V3QituR015Uy9rRUVhUWpmK1R3Ckx6VmtzMXlCdTJyUFdFMmlaemk4
            TXV4Ykg4bnNsUWprT1huY3k5U01EaFkKLS0tIFBub0xteXpodXhDcUpaY3J2Ri9X
            MncwOHNXdDNaNFQyYWxXUGJWemhxbm8KNUwEAb2LmTHJtmy2mG0IzV77dqSp6I02
            wzRQMKYwdGdp8PyS9FFzpAzCGxsVXBnWuE+blRGWhVW5dFWgLsmlHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaHJKeG14cVltZzdzbXNT
            a2kvYmtVdVIveUFYeU9nZ2dmc2xMclVSMlNjCnFKMUdkL0RHSnQ4NXE0c2poL2dD
            TmwvWitQVWpNQmtyRGIxcllJREtxbjAKLS0tIFVaYnBpRUx1UTdaWU1jS0NWNXBI
            QXRYd2R3aytBaEFMTXF5N0k2amhSY1kK1wAPm6izy3kSmGiO62oKbF3xaRwAEyQP
            Hs2i5Cshl0/yYwGDBroGhavY30nb6KuV+P6fAuw0GMADB2MZCn8X/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:23:03Z"
    mac: ENC[AES256_GCM,data:4bd4Cutw+id8MG5U1jjqL4/KNMWuGo3r4RpkNKltGNyyRhvW0txpbpH84NY9YbNrF/ralnUNbW/9fggOSWWbvzKeIBojRDQXbmHk/JKAl8jII8wuT2DJbfN+qIzvFPIwsWKwFXR2nQxHBCgO1Oqq0OjylfmAQSYPleBvwIc49t4=,iv:PCLJMpF+kzhZOlhFQC4MY9lxeXzFiYERd/NgiZqhiX8=,tag:rQPuiXFmDO/J2g/gcvRD2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
