apiVersion: v1
kind: Secret
metadata:
    name: dns-ovh-ferme-du-jointout
    namespace: controller-cert-manager
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:t5KxbotacQGheSmQsW42tA==,iv:vCI+sCvzdpMbbXyxxKwLROXdKa6oL8R2MsQx1ufz6BQ=,tag:FtRT1vnFyOsQYp89TsiESg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:ToHjgkpCTsPLq5EQsBgYrP2qg7gA31eJgmQVQ7gVbR0=,iv:88jVwTmNGHAF9kQwiR0m1yWHilx2LNKdHJW6EmcIuMQ=,tag:8pS1bcYlLbt3vhUfjTdM6A==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:ltA8zO95u5p9KLxKhIAOTPAf1RK1yyKn5T3sQPjE+gM=,iv:Av/sghkQFCXNPGnoctrk4Yg3h4VyXmFQCy2IRUFZlV0=,tag:D9H/nImVPS6v+XLsB+Sf4A==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaGJWbkM4QUY0S2FnN3Ji
            dkZoZXduNHh6S2IrK1RweUNWMFpzOHR1K1JjCnlpNDA2QjA1ai95cTc3R2Jua3Rl
            L0d2ZjVFdDdmcDBKVE5BQnpTTTJYZDAKLS0tIDdWWmJpOXlmUWZHTk5mNHo2Uk1R
            VDlHMnlYdWVwNFk1RURPc1BnUnF2cjgKHgpy7cjyHGCFdSRfpo+vXmji2QL4iOgK
            9NUE4EI6cnPpwQbr7dqz67TjubIunmxgL21lb3BFM0frAORaKXuZyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFNlYmtYQ05ReEtic1BR
            WXRnR05HYW16OTJna1dBSEozeGczTWREVGdnCmpxaWhoeWRacUdHc29XVFRWOENV
            bmllbDh6aGVDeVliZ3pUMTFNVEUxNVkKLS0tIFBCV3UzNnBCa0tDdGpkV0I5UFdP
            VU8zeXRwRFFPTzNKWmUvcGJGOXZsYUkKowpT4wLuWjWoNiSU8j241aGZ+rgMTyi6
            v3zdFBpq8/cFQMLm6HPolbd8F97+FsLkcvzu1Us8kF3dymiC8cugvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T17:56:14Z"
    mac: ENC[AES256_GCM,data:w52zG5P7V4PPeo76KsfXPUlNI/rTUtHES5ACE2t8iY17AMVI/h5oJFlhOVPxZ8lngNnjwKfvdFwGLJnn6rJlP2fMY1UIhlE6XnEyoQRAK6hxccGT+EY0IaINJucO6E1XhveWx2CTTRdTCl0um4tRxnsRZu6yBkwTp0CHRC7H86Y=,iv:lDxLuMp+GxnntqT6BH0h3yr6ov/LwsQ3dgfQfF9mfaE=,tag:29xII7JkmYGEBo7+NGiBjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
