
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - s3-ovh.enc.yaml
  - dns-ovh.enc.yaml
  - dns-ovh-ferme-du-jointout.enc.yaml
  - mysql-operator.enc.yaml
  - grafana-admin.enc.yaml