apiVersion: v1
kind: Secret
metadata:
    name: mysql-operator
    namespace: controller-mysql-operator
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: '{"matchLabels": {"reflector/mysql-operator": "true"}}'
stringData:
    rootUser: ENC[AES256_GCM,data:NcePnA==,iv:EJ2yEXhc2zEskay11GGwpCk6zXXSgHaca5VPYESAQ5w=,tag:tIdY34WB5NlTHgG+LyDgYg==,type:str]
    rootHost: ENC[AES256_GCM,data:BA==,iv:PTb6VC8+z2oOxKdZUvyFZQExjuh2AMFBvAKvslvGKd0=,tag:ChImzl5/ttlop2Hh7LW7/w==,type:str]
    rootPassword: ENC[AES256_GCM,data:QEYa8UA=,iv:4g84r4yC5rWfy6L0MK/jD2rNysMFBHKVvNavyA4ekIc=,tag:fPUqKJsCx2N3cnbs88Sd9Q==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVV0RzQ5anU5OHNGRjZ6
            N1hkcDI4MVFtT2NvUkhkbHpYNGdOcGVNV0g4CnlZQVdlWi9WL08zVXpzUFR2ZGVo
            cVExdWdvNkpWbjBkSEVPMEdPY09LUDQKLS0tIDFUU0tKczQrcUdEek5wWHZIcTY3
            WEtPQk1BSUtmeS81SWxXKzh6TjNIQ00KL1s9nzZxBxXGAs8CqdmqD0FaoctLg2EQ
            ZJZevxh4Vn/q9aZ6lcw0CfY0EO6SVIuqhpVitcvVCem6D6ZJgL/McQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNTdpM2tBK1hWd3pQSlJp
            c0o1V0plVytEdjR6bFpEWkp3eTZ2cjZNbERFCmUxMFMwclUvRWc3Qm5RTjhLK3pV
            Y01WbzYySk9ESVBWRHZnT2FuVHlwQncKLS0tIEtZZW5UL2w2UENwRDROY0FXbXMx
            d1hobTlFK0RiK2FWWjI0MFpUQUhGcGsKvGL+U1lnrd1ggZbSj0sArbxLKLztq8ud
            ehUAVrnmKnZqmP7D3NLn32xnW4kwX4UuqUg8AadwS7p0o8NBEOTtbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T09:47:25Z"
    mac: ENC[AES256_GCM,data:Sh8lAzSsKQeLmWQSZclxqiCaJcTfM3nuO9J0TwboZ97Xekw9b0gzp8lAgj+t/BogCvIlGmdE+NU23ZTRNJ2yhUxn2JJLhH6yHuqwn5IYVOA0MPhUYczjPO5JJ/ZvBH/t1xhiCKdMbu8L9Pb4Zw53HtLxj1rmCpC8ozjI02hC4Ok=,iv:sOtJ3Mziax7h6TYQDNg5kYx/qrSOSiq3H3/UajLFnNo=,tag:B25ViJaccmv67xqhX3iyNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
