apiVersion: v1
kind: Secret
metadata:
    name: mysql-operator
    namespace: controller-mysql-operator
stringData:
    rootUser: ENC[AES256_GCM,data:MNyIHg==,iv:9XwucIhIH8MMBg4KbISLiW1jvpgMPSOr0Ft60mPTN6g=,tag:DK9hoLfKg4lxivdXh3nFcw==,type:str]
    rootHost: ENC[AES256_GCM,data:/A==,iv:9vV4vUTf2xucKK/KfIyYZuZGtyjiF0i7TRiTpkxJ+8k=,tag:qPX2q8WzashNKVTcBXBreg==,type:str]
    rootPassword: ENC[AES256_GCM,data:6ZCBPw0=,iv:2/Ir4ehdhFh1Cwnp2Td9/03+1mz/gz8dSTqCP7D999o=,tag:Lwup8iNwhAw8EMD/MGX3xg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMHl5OEtxeVBMd0NUOXdV
            VjAwUU9UMHhLRWZaVEl5dS9wZzFPb2dDRkdZClM5MUJZTGt6Q3FuNUE4TVBjeFhP
            OGg2bnNmdWpLalRoZ2JNb3Q1NnFqb0UKLS0tIHMwTEdOYjgrbzZ5TjhUbCt3K3BG
            OWlaNENWTUpKWXpESGVqUmIvZktMb3cKyvbJC0keWlIClKrokLh4rV241+GO0D8K
            t9+svLya4ZVw4VGee58O1UNMYFftWxQrNVefPQ/uoGD+qWauPuqnIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM29MMG1TckI1OXlEV2pK
            ajJJdGRNT2NrZU5mWlg3VnF3WEtieitwRUNnCmYzZUN0UVFpUW1zMUpVMWt3RUl2
            VjcvZnBkRi9vY01ia3o4ekV5aGVCU1kKLS0tIDBLTUZBTGVzRVhYYThnWEZRNWhQ
            Qi9UdWkwNEUrQ0x4UTZiUCt0UUdPaWMKdrneMR6WTjwq9iVO1XrM94MSMfoatg7B
            eQi51+2saqPutpjqwAKOexCext+7Ms5JYm4uYY89GE9xqXSNFajHTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T08:51:16Z"
    mac: ENC[AES256_GCM,data:LBtsX+uRWRlPK49Wz8GkTZ192sfz8Hjs9tNln/AHyspPletbjEIO/7qq94Rr81YWvriifwtyL1FOB3dWXaFL/N1OKh1d/rQ9BcS3zXkKTHKORqisXUdaLCGm74PCpkcL3Bb8tWnxP3e96v91wu+QymDQc1L6YB/9yXvzR5Q+6ck=,iv:+6/F+HJAs8AfqwDLSerabetAhiryztytGjSydBAXCck=,tag:cs39LhZq1qVmS5E9fOmOnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
