apiVersion: v1
kind: Secret
metadata:
    name: mysql-operator
    namespace: controller-mysql-operator
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: alter-it.org/tenant
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: alter-it.org/tenant
stringData:
    rootUser: ENC[AES256_GCM,data:M3sDwA==,iv:5LJCWpFo4twjZynHt64onrK6U2bKIorhhZqF2MlFYkc=,tag:2cP2uKK8SQmPyY6bEGmwoA==,type:str]
    rootHost: ENC[AES256_GCM,data:kQ==,iv:7CtmtMZsGKZGIV3VY529kMkl3kFFQLvuN9CIutkPBNM=,tag:c3vhy9jq5RKClp6uTy2h1g==,type:str]
    rootPassword: ENC[AES256_GCM,data:n+8Giyo=,iv:RD7CLEgQoDClrHlnF1qmS6ZRyQ/0tLnTpqntmZSrJto=,tag:Aj2SJ1/N61gihwSX4CzHRg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdDIvT252RW9OUzJLcE9i
            d0dxYThPbjZMU2tUejFrcGF2SGgxSHBYeHpZClRLSVZmV2dCYzNuZ1g4TzdFQi80
            THl5WlEyTDV1NXAzV3h5bUpqYUtqeFUKLS0tIEtUQkd3R0hsTEVTSlpKRkJTd1ky
            WHREVkw1ZS9BOW5SS3NBdm9sS01BMWMKR3uGmleHyoLXLLWQAOlY9mu76ejP9AzW
            ui0DpnlWRoZepvmbJpFibBO7VK8iFNyT0Yyz2xxTouwPrW68EGSyMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZk5mUGtDNDNsZUJLLzE1
            VFVRamVYYzUzalNlUGgzNnhPUFI0ZTRORkhJCjhPbWpnL3pMZ00xbGRZRmVndlhU
            N0FLVTZMQUdFSW02UXNXNk1RMHMybU0KLS0tIEVhMno2QnEyZ2JVSHh5cnk3Sm9q
            SFd2QThvVzR5VFBIVWVnYVZlZFh5U3cK6r9yTJhVj/IExbTvmD4YfTY7LW1k3P7Q
            JvTt864ObTnWcmQqTONGf4jpPc0iQu813ZAlkIsfgmK0dn78aHjTzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T16:27:34Z"
    mac: ENC[AES256_GCM,data:kwfmdyjps0AAQfbZjVKwNI5FB9tBgYHtJWebq6NbyJZ9HkTk683u7QrmWzkCIzwgkL4pLPDQoDUCgks+Yc1pawRgUswSzGRUkjcNBNEGYp3at274se+Kj7T9zVAjhHx8Zk3IjX9D/YQ9I6q+b+R5RDF4EdNw2pdFQwcolPomKA4=,iv:rNbhiLa7cqnYU0n/cNzAutMeMTjUfSzZ+18KA4DKNuE=,tag:BXE4xTIyHgP/YPVqCKF3kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
