apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: s3-ovh
    namespace: controller-k8up
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector-s3-ovh=true"
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8G18rLylH2ia/dyodFf/Nsg3Yhjh5sbums43Zb4uGdkuORXclvTVHioZA20=,iv:jto5T9T/uFLGUNdHREopcV0ZIZRwb9KL/ng/bIVlPW0=,tag:l8MS0oJrN/wzDQXsUEyawA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DPiHsEEtzXqLvbdPjsfi482dlabZ23Tw/e9PvvaDDpD1U8e1IPXzJBwvEzY=,iv:7uTxsJfF/nuQcTb+i/lKo/dGiAY4ruqDHODdkOv7ub0=,tag:E09p1NVpP6Y4FyYDK8+GpA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:a3fRnf39Z0RY+JxBZHqX+g==,iv:rPUfV/T52MmRMtiOXz6DVtzNjaG8Yi4DIeG0DK1MOQw=,tag:DrEVxzxl/+4Zq6CbisDt+g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RzVHVG55K25uQlh1ajBF
            STRhN3VaVnhzMFVFKzR0V2JBd1RpYmMzbnhVCkhSb0ZkaXJVSkFoZUd4bmhjZ09P
            MHpBWDh5c3lTdnA5ZmFmYnB0bHhQeWcKLS0tIExjOG1hOFk2SlRnc0FwNDNaUFhS
            QTBjNmtvbVhOMVRydjJvdElMKzZERkkKRovemkabs+1Ai36x8x1Gv0p1EkHzo3vp
            7Rx1tIZKlgLhTSmtix0V7QBvBItuYFy6fLvpP2UF1/3TsP/GPgFQvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFR0MkJYQWxOK0lTTGxw
            RWQyNUxubTBFTnYzYmxEQitvQ3o5Q3RncW13CmI0QVBOdWdEcEd6WUV3eUhkQTZa
            YmRTUW54SXdFelJNTW5NWGF5TC9UYUEKLS0tIEhSVHRmYmxod040VTAxYnNXclBO
            M0ZLMlFCTlZ0OERtM2Q0bHVyVVhwZm8KVqaq4qFJl+GSp2XNge9ls011b6LTj5P1
            /LhAj9jDSdPc14O0KfVPlc8CbabnLIy2fhGpPZbPyr3cdmOohmXA/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T18:41:43Z"
    mac: ENC[AES256_GCM,data:U2VroNvsTPNl5gEAUzW3otFgLaUdHhNJ94TugDiGXmp5aOLvby4HVqGA4IsKVRJL4bNFXJFqVGUFn451vFuSZWCxb2wxHef5mcafLiS6nNzMXI+puKLR1xKzZhvWlH/TevtuxAEABh/Nx0BZkRN4gHeCAuAr26aEo70WKE7jIUw=,iv:F47+KcbEGLQ8VLnjUYPF7a5j0iqnJLvFsGDW8Ei/og0=,tag:S4Q5pmNmsjSWRXenlOeblQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
