apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: s3-ovh
    namespace: controller-k8up
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: '{"matchLabels": {"reflector/s3-ovh": "true"}}'
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vClpQebCenYv7+YPNg85TfMyfe+gr67PQaoqhZLGOOtI1jYVultxkg5ZJyQ=,iv:AEtmZX61xdHgvpXFiTdHY1ALJ89i4UFQimycPC7nKqo=,tag:PS6jFsw5QLmjPPLczyZiwQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:402YoSq9k203jgd8rACs/CVQr9cZ3Xyp8M3atGd2S40yGpCJ4EnvJwSdOjQ=,iv:b1nDLPhdK7hNW9PHBES/n8/jc40Et/43Z7OZH3NAobc=,tag:b/nWGOhSurNJOyylUd/Ruw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:2gPgu6vRdNqnDPxloMfZcw==,iv:4iHSMJZiYYtWzZXeTKfGPDrkA54nUCsz09I7rXJjoUg=,tag:vp0xT2Ofu4G7PYPeQ37EGQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS2tna3VTM25Gc25mcVJU
            Q09IWEFSNGV0K3FZaGd0aFFJUW56UFk5VHlnCm5vK1dwcmhieEJIaHNROHJDYWZI
            ZStjS243aml0dWlFMExYQVB4UW9VMkkKLS0tIGVrNytrTHl2RUE5RE5aQ3NNdUk3
            NHM3ZENhVFZob0g1dit3UW5qZ1UxdDQKRb5pcN9fvXYFb9cT4QH+VOjgBvtaHMX+
            4iPxYN3cjH0hImf3RcpHfCjeXlO0M9d0Bepl/Gf2xmobe/4jfvJ75g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMVdHQ3ZKU3JiMzgzSy9J
            WWNoYmltR3QvOVNoTmk3dExpZURlMU16d21JCktkSE1xc21VM0g1dGxjUGlXS3RB
            R214WlF4ZTVwVGplV0RaT3RNUDVST0UKLS0tIGNlaUNmRVlQZzRtWGsrZ09DR1lt
            Vld0azRKNTlmU2hyN3lLQ09rYVBxZWMK9fynAmwFyxpziSLiyukBYz9YAW5/zJs8
            oOOqQB2eKRrIZBW2UVpaCIOpqPOTpn6rZplxbMdHxrj7ls/q4At+mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T07:56:59Z"
    mac: ENC[AES256_GCM,data:ll815dr8pJUkVqjepkxxB0/0G5caEC9uxsLczZpnDdIjwxLnglKl/mR47kdYuwebZOcRqk/LVVQRxdSvfJut9bRuphZYOm0Bh2dwhKxguw6rpbwFrXvhOndehCmrdxPyXGhgrbjUseQaVwxI24cyuZQbPNXFnZkKF2Lkxj4+EeU=,iv:xG2bqa2z+I99V/i4gmc/9s5a876FYqZC028lDRCI7EY=,tag:yziu2XNvCUR+cPDtOiK12Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
