apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: s3-ovh
    namespace: controller-k8up
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: '{"matchLabels": {"reflector/s3-ovh": "true"}}'
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QmuozEEXKv/cgZR1J5Yqvt2DWbUmIAFYxe6Dk69DfnI=,iv:w3WqGh6b2/Wxstb/O6PsYwXyYZlSZVB9xu/iKkLoBvA=,tag:Vym/WMgRUhu5hxUR5SuUPg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yJrKEv6rHxjyQgv8FjkmomdhnH6OY2rDFwLcWUKQTKg=,iv:t3Pdsu9EKcfjDPaTcv8jOMcaRzj67lpXbSoeJGyFHw4=,tag:fYnDeJTMIOoaRPQ1I5mxPA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HJfUrc6Ml40aDoeFpj/DEY7q2iGSoLhUVGuiQ+/nYEc=,iv:JYjp86u3jbWvDc4hjcSAqUtDY1TpWb0msCsRnP2C5/k=,tag:QiY8vp7Y6FwhG9Y6h6gaDg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTmg3NUtMTTdsSWVHRDAv
            L1Jid1haNUltNjNWTzl5NTVNbWlYa255TXdZCnRaaW9LUVBCYlBrNUJUZ1lDWjFy
            VEd5bXhPeDF5ZE53T2hRalc2YnI4YTAKLS0tIEZmTjNZb0puMVJ6RE9LSjZBUmND
            Z2VNSzZvVE5xVVpsblJ6UnhieVNpb0EK1qQ6QtBPsWInWz8px+lFnYpgh2Puvp37
            sjfQAVGNyHxE819q4ai54LsBv0JwQfgPcxQwohWrgXLHRdsC7Y8VOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb1pjOTNSRk5rZkF0c3pW
            OU1BV1Ywa2daSDdGbmJzTVRxbXRjL3B6bmlZCkNvWUlwRTRUSmtoTU11NUNodjVV
            K2xOdXNoZk1YUXA5ZEl6a1N5ZklsNGcKLS0tIDE5cko5VUhKNE4wMGpBTXdZcVJW
            a2FUYVRuZlpwdm10Tkx6NnM5bVBtdGcKsyApuO/QXGacYnoU7SZsNpiGTGHctVnz
            4J0v8VsibIsz1yR9EEfGem9V84f2HO9la13wJHYEI86X+jyuJBm+4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:36:23Z"
    mac: ENC[AES256_GCM,data:MNTGMehYAq8f8pbBmq/AXwwxemIX64DqgEwIwfP6jm0U6MLnNapXdZkEsa6rwryG9Bc5hJ35WPKS6sC9SEghfFWE0gyZMBISx87T14VhsUnydyS0atr/TbXQ/yNyiub4KLPMPc5b5nrLDEBGGJuQYLgLvC3kYqsnBf/MAeNwiH4=,iv:5qJpzZ2aLANIckZwWcQMY8Em7E/+3WITO7HakmdUESQ=,tag:MaczfMtj8nxgLIwrlTV8zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
