---
apiVersion: v1
kind: Namespace
metadata:
  name: ${tenant}-nextcloud
  labels:
    alter-it.eu/tenant: ${tenant}
    alter-it.eu/app: nextcloud
    alter-it.eu/managed-by: fluxcd
    reflector/k8up-credentials: "true"
    reflector/database: "true"