---
apiVersion: v1
kind: Namespace
metadata:
  name: ${tenant}-wordpress
  labels:
    alter-it.org/tenant: "${tenant}"
    alter-it.org/app: "wordpress"
    alter-it.org/managed-by: "fluxcd"
    reflector/k8up-credentials: "true"
    reflector/mysql-operator: "true"