---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
spec:
  interval: 5m
  url: https://bjw-s-labs.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grist
spec:
  releaseName: grist
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
  interval: 5m
  timeout: 3m
  install:
    remediation:
      retries: 3