---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-templates
spec:
  interval: 5m
  url: https://bjw-s-labs.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grist
spec:
  releaseName: grist
  chart:
    spec:
      chart: charts/grist
      sourceRef:
        kind: GitRepository
        name: app-templates
  interval: 5m
  timeout: 3m
  install:
    remediation:
      retries: 3