apiVersion: v1
kind: Secret
metadata:
    name: mysql-operator
    namespace: controller-database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/mysql-operator=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/mysql-operator=true
stringData:
    rootUser: ENC[AES256_GCM,data:ZbWdXQ==,iv:DmbVAAVlJiw2cYEiGg1rkFSc/OGJfHtNhaQQkmiKuhk=,tag:hnmke3vPqWXrLhp4dbIp+w==,type:str]
    rootHost: ENC[AES256_GCM,data:ig==,iv:diUG8xI9lWNgxbPRbOhhBFnbhthfzUgKiZroFXZdgBA=,tag:kgumWpHrXE8XAPJgAlSoIg==,type:str]
    rootPassword: ENC[AES256_GCM,data:7bKgzlY=,iv:3x2n1J2vE/L+Xx7DdMzoLC9rxcHWgogI9HiwMYWlgWk=,tag:y6HNwwN2EK4hZCmt3YJDDw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWG9vSXZ6Tm5vZlRCUHNM
            UVJQT05yd2JHY0VNaEJVandBWm5LK2VYRTI0CkNkb1RxSTA5ZUZoS3FuYm1JSlRN
            dkFTU2RLdkkxbVN0anhuNk9hVjdDencKLS0tIFE0NVowaGVMdzI1bHY3RFUwVndS
            U2NvUDVzTUE3aHpTVzA4RnA0QWhueUkKhB0a6DhDdO1yIMg01pgxcjlZrzO0ISra
            /S5bi1KeTr18GQwqzE7Poc506WVMuh9m/vy8mDJiCy/WKRpt7kwz6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZjR4b0RhSFFaazh2UGI1
            d25LTnh4UTBSMDFFbmVaNXNrWDZ0R0lvaFhrClNJRWMyRCthTVBDcStndEdhRWFi
            eU0ycllUY3JLd3B2U1hHZUpjMGhRdzgKLS0tIE83OGo1YW1rTE01Y2VZTEEvQUJu
            MG1McUZRVDBjd21UMlUwL0pBMWVrRGMKXwMybuSe0rDYEPr18qL1ETN7nKiKIPRq
            AmIlw87KrEK4Rt4YJNO+inMRowduLnedgmZRReEEXzOcxCUIishlUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T16:36:32Z"
    mac: ENC[AES256_GCM,data:yDQU8aKkqgFoxQApgj7xheiSzL72z1t/uCGTYWSf/hugBt3Ux0JAKbQohJ9D1QQhW6pHPn9K7rgdE8dYMkyzoNVlblSu5+i7um8uCmUj8C1Kw/c/KBxlcXWo7S+5gmCCBjGYmcYY4lyZBd1XtupC2A4SvUU1jDZoe3e4cYsDF9c=,iv:GfUTVcd0+gEZeCiOEEXSUfDQ0PMXfJpnh22xIWqAPeg=,tag:KETfeVV3wSiknfn03mVyaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
