apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:b/fbQGvI7jdxnQ5BZogurKSH6KviKJYoMG2bwAbnl/xOc/3DjXOUv6lLMdHGUFoSCuibOASVTy+5JAfvssnk/g==,iv:JPkUbTm/Hz1A4fxCEnZ5Jq81+K3SBXuKGmO5XwWX1BI=,tag:XkzjMHpK004bekASqBH2ew==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:6fwxTqBoRw+4V16G3hOTlvk=,iv:5e92LLgXn298Gbi5AV8dFj0pSqtqVbM0iVVq/pr2kzA=,tag:Xr7uDFFQFiMtF7QY1THMzw==,type:str]
    base-dn: ENC[AES256_GCM,data:Z/rxFRZipHakT75dbmr6ZXM=,iv:fVtbQaD8i9W6mclUh7lm5f6K5aq5xnqeE+4+ac5fh/o=,tag:V9aVaEdwEZhAa1xN1cqFDg==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:BXOQDoacA+IQXNoNSGEWfTnXxIAxyzrz1cJbpIjK7nEzD5lg9OeeUXGHj8VIs04B/lt1qP1Q4/jstQ+k5JPq+Q==,iv:LI7yIGFXJIn49WbcD60FINZW3quXJMuxY7+Ph+0PkAM=,tag:uguLDa7ximpeI87fBUDH+g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN1dCNmxhM3hwcm03cklJ
            MVZoQ2UwdE1UMzVzVkEwVXFUaTNuQ3BETGdVCkYvTHNUNlE3d2hYT3laakd0QlMx
            dGMzTTJuSTNGUVg0cmxzV3FRdndFcWcKLS0tIGZrN2FsVUVBTFpBTkxtazJ3dDkw
            dGlxUkc0Y0JxMGVSTGdFVi82d1dKUnMKcsWnHton67RQkR8C5CIciCpPfF1ZbZd7
            dcNZ9g6xppmzbpSopEJkqtjRccv3KKW6qnA65J6nJ10B3FEwoCzW6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:39:35Z"
    mac: ENC[AES256_GCM,data:GFpWF4lbcamChimTbKr0ZZUU9daLqXhe2Qx6W36SXnD9FG315frUL2/CDLbQ/+xQxkMu5P1FGQ776dAuMA5Vhp+nkJItHxGtnePq9TrnHDwHUe2TjBPwjF0QhUe5qWRDuAQfFUkmufOoWxFC2KyPbLHvLODj85HQ8KFw8TBH7Uk=,iv:qZPS6XLP0ahvuyKzlkswe+bI/mEXQkWYawRSZXdY1gk=,tag:hzUUnPDLYtxaeO6IV4zxrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
