apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:BswKanIS68xN8mrmVz+0+ac8b6W/2AxUHhwUb4b4D2FMw8kJHMYIjUHqiy+8uCrmz4/Sw55p0rEIJt5cy+7Urg==,iv:kFjsuLKRTOnBeZrCGRgvT9bS+11yKeKLPxIo0xP+6OE=,tag:A7fmuRXCFwEepa/ccwR0nA==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:rwu2KSjSeGeuOlSNXZ3B7Mw=,iv:/oTQBD+nEqtjf/MODJfWNdfeGSQ9PMALk+U2E6XgV6k=,tag:EACDujJpfTiKL+QcNXQz9w==,type:str]
    base-dn: ENC[AES256_GCM,data:sGD/te0cKdvUP4fPW+40YNY=,iv:ipraSIisCTPg5GgnWW5E82KXjU+ZXtv4dVRiXCac1Pc=,tag:yh8JpCoKQy+GwJgOSpZgyA==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:5r8b3DZm0CWWbFB3T7MDT2vbjxmJPyzM+bLpEWXrmm8+QSVZCJxgPxCt+BuILMZX8lf1bjHMC+WIrs0KxrUCPw==,iv:yN1WLk0n2VIKdySGlV1XOlV6/wCjZo5nus+f/15RTHM=,tag:VWVF14mQppM1mJLnMpsGGw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVROKzF1d0tzZUVZekRt
            Mm50aVlvZm9JOXpUQ3pqQXJ0YlZIT2J4QUZvCmxzNnVNZDJQNDhzeVhpNndWN0V2
            ZzBnN2d6OFBOTXBGZUUweVlrcnQydncKLS0tIHlSaWxPQjQ3cDI3K20zSS81TVFs
            TlJuM2ZrUlh0TUdCdWdTVHZPZk1XQTAKKmY1AiCTDbVSBFo3E3s8BYycW1GyE72N
            qh4ueQE++quf/T4o3Vzjoh/vVH0BQbJg8j/zx8c8qZ51+/tx3ZB6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T22:01:01Z"
    mac: ENC[AES256_GCM,data:Cts22+PYbgpH4hXfhqShR9iDK7Us3tPBNmtWrB4VbF0HNEbzhzeW1ApFEEeHgvhl5dzBhDf6FXoTzP3WOBFRfD3FytwFwe3a8z6sQvi8EYLTVYrgVSe28AOCGrFPsG3c5LL8r0UCyLkeG00yXFYWt5rHqp+TT3TBzylWrntglP8=,iv:hZwnC2qp2U2CprYxsLe+nAZ26YF08BSRKC4thuIF6WY=,tag:eNeMOWTOyHLhWb1r3wEaUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bootstrap-users
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:z0ONA8bMhd1KZS+E5WmRtKM621LZmRP7J6ijOuIX/oPqq4lZMlm5HEvT3nzCgJXG7kbtdiAZw8hn5FSB6yfYSrBiXgl2ODmenZ9Uf8TgfTjc7qMasEftRgT2HUjU6FNV2TtdukQxjbOWjxLo2UmoE2RGZGVubBMtAH02Mr/r8kDmISjWYcSStwvKNPj1BcAxLXumr2p1uGBY3FSez4MOZ+Llfs4NTCAalzSCjWeRHQL6tC/hX0vAW56SR6RJaXqG93OGX659HS+cJkfJIiN5IX7QdMIIxAiSJt0=,iv:uE0bgs9iC6p6Zd07LP1cWwPDcSOta6zuJu3vjuo+3ZU=,tag:qRTa+kVlVGJQea/4scc1KA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVROKzF1d0tzZUVZekRt
            Mm50aVlvZm9JOXpUQ3pqQXJ0YlZIT2J4QUZvCmxzNnVNZDJQNDhzeVhpNndWN0V2
            ZzBnN2d6OFBOTXBGZUUweVlrcnQydncKLS0tIHlSaWxPQjQ3cDI3K20zSS81TVFs
            TlJuM2ZrUlh0TUdCdWdTVHZPZk1XQTAKKmY1AiCTDbVSBFo3E3s8BYycW1GyE72N
            qh4ueQE++quf/T4o3Vzjoh/vVH0BQbJg8j/zx8c8qZ51+/tx3ZB6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T22:01:01Z"
    mac: ENC[AES256_GCM,data:Cts22+PYbgpH4hXfhqShR9iDK7Us3tPBNmtWrB4VbF0HNEbzhzeW1ApFEEeHgvhl5dzBhDf6FXoTzP3WOBFRfD3FytwFwe3a8z6sQvi8EYLTVYrgVSe28AOCGrFPsG3c5LL8r0UCyLkeG00yXFYWt5rHqp+TT3TBzylWrntglP8=,iv:hZwnC2qp2U2CprYxsLe+nAZ26YF08BSRKC4thuIF6WY=,tag:eNeMOWTOyHLhWb1r3wEaUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
