apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:SdifopPJKtke+8yH2s7CrEmYMLQptZzjByjAFnu68sQuqXNxSjq8idnp/hICMOvyDH9JeQ39vvHrP98dOuRHeQ==,iv:y0EvjoJhTvVcMfO6ZCKiWlQvskZmSzTgtzZbbNo4GIs=,tag:/Evo8modVvfWAln7oMkToQ==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:9T9O2SBvoZWnZ2WCNSXCgpo=,iv:mSsqQOIOgQod8cgj9IDxH1nWAfs/i+idgOstPiE9whM=,tag:J8TJjWCUgz36IC6nJXUKHw==,type:str]
    base-dn: ENC[AES256_GCM,data:zis4Nie7qIzcC8LbYdU+o4I=,iv:IoISBjOiD157HFD8HHkAMMPWy+aN5p2NWghMbqH3t/4=,tag:0latJHN9lrB0jJYFXrd5sQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:gX16KwoaxD00VDG0BL34EuRVK0ziyWLVwx21VrXcyauBeIK20f+BHmgocElKyMkgYCB+tfRv/R4LU40mVcIHAw==,iv:1Z2JDtowhqTAJw9Dm4yuVtR8UgupQTTIlD/CB1KS6+w=,tag:cZNiHaz/FTzxr5fEEkBnWg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YVFpa0N5b2xrMmh4TFNY
            VERZWVdzYWhDZ2luZFBwN3hFSGN4cENHNFNvCjBlMmp6NkNxL2N2NC9IMU9YRjJv
            eW9lTzFFR1RybSttejZSQ01MZUJqL00KLS0tIGlpOVlRLzlPNThSRjJIMnpmaGhL
            UVVRdjhiYnViK1dGRWl5N2Qra1B3TWMKvYdYtVoK4j1X6gLnBMGvuuobxobNwOy4
            srhHX0+cAlyoOBuyEfWMtVHs1v0AAEMW3VcCZSYiA/GePq3K+ESzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:23:19Z"
    mac: ENC[AES256_GCM,data:QKQNBqJ5uHFeMUBRb+KhK+6rzJWkTcRjWnOb8mF/nA1XXy/GVujydA3cLFaBohv+yYBqdnn4NquMC1vAMWZ1fUE0RYESCoa8S5PHBfHSkbwrvoNBUo2caOM5sOJmgz9QP8NFXILHblMPMSdBQyRmi0WOsr7BR3B82D6XYaIVyGw=,iv:/3MxwzM9efCadbkd+i46QMri6O71jZ2MEXoAsIw/5T4=,tag:lvqKz4fkqN91taOCHGNjYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bootstrap-users
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:cdBfJUVYRPbTm4zY1QFPrRwqJFMrurr9ujW+LkX1fSi3IO+CZvWtVy5EEkwoWPS1rsnFACc/cLziaz9JAmSdgm3ie+vU+nMGAroHf9h8/p5CUO9hp3cm1WH/j9olpekhOkmeP80gLUtLsYtOI4vm6vh2smEiX8JwAC6zJ135WB5oXf3Z9cSocEcUlkf+2aBobFzUFhDMOF2lrjz5AKB+KbCghWUUZygDpJB9MZqdV0pvU5/8kjKdqYtS6bP0cHeY7YWByGHC2zDu2eA2C8lzbi/0R3se2qIuAw==,iv:Ofez3TUv3hLN4J0NAxRK4hLsa666VBwLaVDHtrBfrLI=,tag:Zcj0w63a8oFHYJwTJge0Lw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YVFpa0N5b2xrMmh4TFNY
            VERZWVdzYWhDZ2luZFBwN3hFSGN4cENHNFNvCjBlMmp6NkNxL2N2NC9IMU9YRjJv
            eW9lTzFFR1RybSttejZSQ01MZUJqL00KLS0tIGlpOVlRLzlPNThSRjJIMnpmaGhL
            UVVRdjhiYnViK1dGRWl5N2Qra1B3TWMKvYdYtVoK4j1X6gLnBMGvuuobxobNwOy4
            srhHX0+cAlyoOBuyEfWMtVHs1v0AAEMW3VcCZSYiA/GePq3K+ESzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:23:19Z"
    mac: ENC[AES256_GCM,data:QKQNBqJ5uHFeMUBRb+KhK+6rzJWkTcRjWnOb8mF/nA1XXy/GVujydA3cLFaBohv+yYBqdnn4NquMC1vAMWZ1fUE0RYESCoa8S5PHBfHSkbwrvoNBUo2caOM5sOJmgz9QP8NFXILHblMPMSdBQyRmi0WOsr7BR3B82D6XYaIVyGw=,iv:/3MxwzM9efCadbkd+i46QMri6O71jZ2MEXoAsIw/5T4=,tag:lvqKz4fkqN91taOCHGNjYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
