apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:z01prJhRSvpp29rCufoeJrD4HtAIe3maLoc6OKggb2sDS6uhIYt9GcBaAUGY4OERnypB9TnNWpBMHtdEkBsZJw==,iv:h3in9qNz4SMIM0bsSoqM2D24n0T2HNmbu1QNo495RPo=,tag:Q/EN6xCWgF8AQ84BAeuaIg==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:fF2daXvvlL3mL65Sul8GhAk=,iv:smyWFKbU/245C9znOYadaHXvkHRWCYn06NWfZZYt2tc=,tag:dSLTrTDYSMuWZyvjaL5i7w==,type:str]
    base-dn: ENC[AES256_GCM,data:G0E4j5JMyF8TcWKtnCmA38E=,iv:mt/Mu9WV33v5oINJVmeFiZU+cH34eCa760KJmplgD/g=,tag:8yMy3o7Ky0qyQn+yUXCNiQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:95U7dUEpxOkZqe4IRX6wy+77cuf78EiZ9QEA45K3hXUjqjTynIstUqBb6dNpy9FQcJ4FdZzha/Aj3udL6ZlcZQ==,iv:Bv51f+2a7u39XdGTYKm8EC1j0USh1+NjCJzOC7Xo7Sw=,tag:KUrkX7/Pxaw/khEBwawUCQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEVnUTRCQ0ZHclpGZVFv
            YS9NVWs1VEE0VGRmaC9qb0ZrZ3RIQy9WK2prCmNEUzRWZEhNTkRBaUtKbFhIRVpa
            Q05MdldDTGVBNjY2a1pSSnFaTWcxQncKLS0tIG11MkhTcUhudlpWS3dZKzlCcWFC
            Rmx3aVpRWmZaMEFaTVoxTy9NNVc3c1UKUDxXlPJc0TctfIoKFvflwYUFP5LjWiQL
            UGkVeQMXTx8U1Wqf1+ZQLlJOdXSesPelmWxKI7emATxOsrFypn1jdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:01:43Z"
    mac: ENC[AES256_GCM,data:c0gAA6Uby6qEPjZ5ojvMJkZzuvyiKlTFUF65U8hZMGAS4JzkSYtnLg9ghW+2ew6BzpR3Fz1dyA4+K569hKQaictxn6QqEqiwfBsryV2M5b2Tr/wHkgNsTRT7QkIeOlxJo0E9elGQTEp/fTerkQFfakNcSqje/uoXTjMp75TLqkY=,iv:dWODUKoD17PcKXb6gSFkxRIc/47Tt2UBzdJO+JnT42c=,tag:h7dfZVs5fgX9d9LaHU2rCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:A0ieyPmwFxX+MRsqeTPUwYH/dV9+JV32E3EJFVAiKmiTMc6/jlPKfeIOzfi6emXrZI4rYSZ4+rdLJ/jEPD1I/AOzJyjrf2kvAp1EXzWjWMb85f3q3vyLVhjk09//4/y/jsdvz1PaVYytJZJgRxo+FCJSCA9uO+M5F9oYyhPoCKDZHqgqCSJDVns39WI7RIUEWLXn7iz+M9OUykOqT5PXuRRxV2I94cWn3onnirbU51ra9Zw=,iv:eyUbbTQOh/de1pSFeU4DqDT5QouJPZAZH5gXxjXW5tk=,tag:FzSjxM4T/6jos9Hk1WVPPw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEVnUTRCQ0ZHclpGZVFv
            YS9NVWs1VEE0VGRmaC9qb0ZrZ3RIQy9WK2prCmNEUzRWZEhNTkRBaUtKbFhIRVpa
            Q05MdldDTGVBNjY2a1pSSnFaTWcxQncKLS0tIG11MkhTcUhudlpWS3dZKzlCcWFC
            Rmx3aVpRWmZaMEFaTVoxTy9NNVc3c1UKUDxXlPJc0TctfIoKFvflwYUFP5LjWiQL
            UGkVeQMXTx8U1Wqf1+ZQLlJOdXSesPelmWxKI7emATxOsrFypn1jdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:01:43Z"
    mac: ENC[AES256_GCM,data:c0gAA6Uby6qEPjZ5ojvMJkZzuvyiKlTFUF65U8hZMGAS4JzkSYtnLg9ghW+2ew6BzpR3Fz1dyA4+K569hKQaictxn6QqEqiwfBsryV2M5b2Tr/wHkgNsTRT7QkIeOlxJo0E9elGQTEp/fTerkQFfakNcSqje/uoXTjMp75TLqkY=,iv:dWODUKoD17PcKXb6gSFkxRIc/47Tt2UBzdJO+JnT42c=,tag:h7dfZVs5fgX9d9LaHU2rCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
