---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-alterconso
resources:
  - namespace.yaml
  - helm.yaml
  - image/repository.yaml
  - image/policy.yaml
  - image/updateautomation.yaml
  - backup.yaml