
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod-config.yaml
  - schedule.yaml
  - ../../../shared/components/backup/pre-backup-pod.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /metadata/annotations/k8up.io~1backup
        value: "true"