---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-wordpress-ecolieu
resources:
  - ../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-wordpress-ecolieu
  - target:
      kind: HelmRelease
      name: le-portail-wordpress-ecolieu
    path: values.yaml
  - target:
      kind: Namespace
      name: le-portail-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-wordpress-ecolieu
  - target:
      kind: Secret
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: wordpress-ecolieu