apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:kffc0ekWTcm92Q==,iv:Klummedd3d9YcCWTQyyJTzN1d+t8uKqTtZrO8ZhQh6g=,tag:JGgRk7GPIa3bXuTAmotEAA==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:W0axzvoPCpdUiHJCBwA=,iv:nFxnxe2XkJasajnxwYlatzfuKOKydMyZe1niQ18DPUc=,tag:yhSiHRmJHt0othZ/A7NlEQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WFJ5amRqdW9qSC9EUFQ2
            czIvbUc4RmNqZjUyYis3LzRSb0J2MDNUWEN3CmJoVWJ0by85bTA1Z2pzNXB0UXY1
            NWlBQzcvTVI4c21rQy9sa1lXU2ZrcGMKLS0tIHNKdEFudnA3WDF6TEpXcUVEd1NF
            T2NDZEprME1nRjlLL3pqNnlTS3dMczAKS+JJoqLIavY0qnBqgHumkC0q3vTzcopv
            zjzp6bePjUHk7s+FPN6kU6nIUD6dfJSbIkVDyJoF0JyixR1yi8/jtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T20:26:27Z"
    mac: ENC[AES256_GCM,data:zo8vZlUtX5FCE8x0Wcq8iNcWtVkWmzr+ooZ56qQpsAaKCDUYkt8SrF14KLDQTf7kcpT9bcoFLkF73uN7wy8ciSYgdiVBSG80SDymAboUWuuHKNiTm6bn/Ao6s33kzZ5S1Yd8NPZZsx76fCfXDC/MoTEDEailgT6Tybp0yWXtyik=,iv:ayKAnGofXPUqL82JW2WBl83v/VnItZGTvDQDEtJvoqw=,tag:khz3A+6up9nG9CFerMBUUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:oh7xUEw=,iv:WnAc5g4WybmrA5OMT8fjDUkPiGLJgy5p/xVJuvd3uiY=,tag:QNXsmIARNw4bSx7KC55E8g==,type:str]
    mariadb-password: ENC[AES256_GCM,data:HmITw7+WAzFq7O9nEx0=,iv:53CBSR3mZ6mjmf4hODfyvcpuBOpeHYz42HSrADReKQU=,tag:wFQewdWlV8IlZJuL3iuCkQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:Gnu9k7E=,iv:CID80x9Nubfqgeu8vSceIDKt8sS6IdOdPWn1hA0eDjM=,tag:zszADWWF2e5Wb7IIAAB8pQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WFJ5amRqdW9qSC9EUFQ2
            czIvbUc4RmNqZjUyYis3LzRSb0J2MDNUWEN3CmJoVWJ0by85bTA1Z2pzNXB0UXY1
            NWlBQzcvTVI4c21rQy9sa1lXU2ZrcGMKLS0tIHNKdEFudnA3WDF6TEpXcUVEd1NF
            T2NDZEprME1nRjlLL3pqNnlTS3dMczAKS+JJoqLIavY0qnBqgHumkC0q3vTzcopv
            zjzp6bePjUHk7s+FPN6kU6nIUD6dfJSbIkVDyJoF0JyixR1yi8/jtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T20:26:27Z"
    mac: ENC[AES256_GCM,data:zo8vZlUtX5FCE8x0Wcq8iNcWtVkWmzr+ooZ56qQpsAaKCDUYkt8SrF14KLDQTf7kcpT9bcoFLkF73uN7wy8ciSYgdiVBSG80SDymAboUWuuHKNiTm6bn/Ao6s33kzZ5S1Yd8NPZZsx76fCfXDC/MoTEDEailgT6Tybp0yWXtyik=,iv:ayKAnGofXPUqL82JW2WBl83v/VnItZGTvDQDEtJvoqw=,tag:khz3A+6up9nG9CFerMBUUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# Secret associé
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu-wordpress
type: Opaque
stringData:
    WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:fGwy52LKKoMUpyzikq8=,iv:wkX/lAX4X580iM1gY47z567iF8UR8eE8xeuEE9vT1X4=,tag:m5I3spIsgkNMCoBWbXuSCw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WFJ5amRqdW9qSC9EUFQ2
            czIvbUc4RmNqZjUyYis3LzRSb0J2MDNUWEN3CmJoVWJ0by85bTA1Z2pzNXB0UXY1
            NWlBQzcvTVI4c21rQy9sa1lXU2ZrcGMKLS0tIHNKdEFudnA3WDF6TEpXcUVEd1NF
            T2NDZEprME1nRjlLL3pqNnlTS3dMczAKS+JJoqLIavY0qnBqgHumkC0q3vTzcopv
            zjzp6bePjUHk7s+FPN6kU6nIUD6dfJSbIkVDyJoF0JyixR1yi8/jtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T20:26:27Z"
    mac: ENC[AES256_GCM,data:zo8vZlUtX5FCE8x0Wcq8iNcWtVkWmzr+ooZ56qQpsAaKCDUYkt8SrF14KLDQTf7kcpT9bcoFLkF73uN7wy8ciSYgdiVBSG80SDymAboUWuuHKNiTm6bn/Ao6s33kzZ5S1Yd8NPZZsx76fCfXDC/MoTEDEailgT6Tybp0yWXtyik=,iv:ayKAnGofXPUqL82JW2WBl83v/VnItZGTvDQDEtJvoqw=,tag:khz3A+6up9nG9CFerMBUUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
