apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:p0iEqgBktor/lQ==,iv:5F40TwC7HTG++YJ0Uups8WZ6O3TPbhGMQQdA2PNqu58=,tag:60jZ9eaC4k1dl1q+CHczHg==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:d/GI4cidXSCF/g1xSrU=,iv:E113nTLmzusvLXYVr73Zz3BdU5Lt2LCRFrwZZtXqvos=,tag:vvBZjGIsmZCSEtHz147Djw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTW9YWnFlZndBUmdjVjdR
            amw0enRkLzd1bUZ0N0NacmE5RUVubGRZbldRCnoxVFRCVldiVnNMZmlvb2I0VERa
            YjNDYzUxZ01wa1l1OXFWOHYrTUYrOU0KLS0tIHZJOUhmYXhFK0U1QXluSTV1MHhn
            NGFpOG5QaUtXSFJzWkRmL2wvVldDelEKa9gsaHcAyg/QGKoibuiQrPVkq6F2Eoq9
            awyKkWnVRE5oZfpmEBGtyCIvELmmHa/tbwK5kYL9xmUiT0lmqwQD1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:46:45Z"
    mac: ENC[AES256_GCM,data:ek5ehqgBssSCDyNxYkytf9ckkWvjritR4FZCzrvUKZMnJsYN7SErhFr6FzeBeT4+Nt2Fkk3qLPskZP2h9ehN/16esJgE4BkjZCTl11gS/uoxCAxEHaHvegpVrJhPbTqXD88BPu7QT12cR84stdWSxN5N7lY3dF4GiITjo0hOlp4=,iv:5d7wwVo0eLJz/+ym4XuDVA7fK8s67oovgVQ/PBDjyaI=,tag:pUzRlQhXY3/XYlLDEaoL/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:0TNAs78=,iv:fNMBsI1s5dYVnR4PF8kdewdLK42QEWKJvwz7kS/8AxY=,tag:Ydg3GCBRoeQWqK4Bny3sEQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:kUMQN7kTKkpS1VUjwiE=,iv:Iamdr9Td0NMNLOe4P/6IVIZ67xmx21wzhriaj15/Xuo=,tag:g0uRAsIhJBJnUykkUTRO8g==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:XYhIFVg=,iv:ms8liFhQtLfhthWRn8YdfiTB+vF53QI0gaJrt6+QG34=,tag:8PuNR1GLLj0wxqrI2ILZKA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTW9YWnFlZndBUmdjVjdR
            amw0enRkLzd1bUZ0N0NacmE5RUVubGRZbldRCnoxVFRCVldiVnNMZmlvb2I0VERa
            YjNDYzUxZ01wa1l1OXFWOHYrTUYrOU0KLS0tIHZJOUhmYXhFK0U1QXluSTV1MHhn
            NGFpOG5QaUtXSFJzWkRmL2wvVldDelEKa9gsaHcAyg/QGKoibuiQrPVkq6F2Eoq9
            awyKkWnVRE5oZfpmEBGtyCIvELmmHa/tbwK5kYL9xmUiT0lmqwQD1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:46:45Z"
    mac: ENC[AES256_GCM,data:ek5ehqgBssSCDyNxYkytf9ckkWvjritR4FZCzrvUKZMnJsYN7SErhFr6FzeBeT4+Nt2Fkk3qLPskZP2h9ehN/16esJgE4BkjZCTl11gS/uoxCAxEHaHvegpVrJhPbTqXD88BPu7QT12cR84stdWSxN5N7lY3dF4GiITjo0hOlp4=,iv:5d7wwVo0eLJz/+ym4XuDVA7fK8s67oovgVQ/PBDjyaI=,tag:pUzRlQhXY3/XYlLDEaoL/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# Secret associé
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-ecolieu-wordpress
type: Opaque
stringData:
    WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:ijlvFncAvzZ4Ff/1CX0=,iv:cOVmg405lqLt4IA5CgKitUDg0C4xP3p4cKDyJJa2Cws=,tag:MTh+avFUBvxh6iS+MvrVxA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTW9YWnFlZndBUmdjVjdR
            amw0enRkLzd1bUZ0N0NacmE5RUVubGRZbldRCnoxVFRCVldiVnNMZmlvb2I0VERa
            YjNDYzUxZ01wa1l1OXFWOHYrTUYrOU0KLS0tIHZJOUhmYXhFK0U1QXluSTV1MHhn
            NGFpOG5QaUtXSFJzWkRmL2wvVldDelEKa9gsaHcAyg/QGKoibuiQrPVkq6F2Eoq9
            awyKkWnVRE5oZfpmEBGtyCIvELmmHa/tbwK5kYL9xmUiT0lmqwQD1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:46:45Z"
    mac: ENC[AES256_GCM,data:ek5ehqgBssSCDyNxYkytf9ckkWvjritR4FZCzrvUKZMnJsYN7SErhFr6FzeBeT4+Nt2Fkk3qLPskZP2h9ehN/16esJgE4BkjZCTl11gS/uoxCAxEHaHvegpVrJhPbTqXD88BPu7QT12cR84stdWSxN5N7lY3dF4GiITjo0hOlp4=,iv:5d7wwVo0eLJz/+ym4XuDVA7fK8s67oovgVQ/PBDjyaI=,tag:pUzRlQhXY3/XYlLDEaoL/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
