apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-user: ENC[AES256_GCM,data:uI39oT7VxcZ1pA==,iv:zoqjLKrriSVuPhMK8ABDfemmraVA8aepIJsPeGOxuR0=,tag:K+kYWiGVnUtd5dwVLZ1MGg==,type:str]
    wordpress-password: ENC[AES256_GCM,data:ucS5tmLDqmMzPtuuUB0=,iv:r0qNGBTWLHMCx92Bz+OQrrt/PURLKrs3X8GHVJka9Mo=,tag:BJVsMAaBAUZIBSg0uJK1OA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:8weXU20iLPbj/Q==,iv:12sg4zOgsZKwAm5cbLniIThHi7WGceqC6WNv0S6GKd4=,tag:x4TCTaTRlo7h64FCGZzTBw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:Kg235hsSqGqGMg==,iv:jt+/NQ5z23kGEJtQUFmYZMC8JEmT9usKMfbs8VOabhM=,tag:+zzv2ZmeTO7jN170D91JVQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:49Z0B0M=,iv:29KsXTbSCxgxnVRO5wLv3bT69Q6lKyMBUflgxcQ2KrA=,tag:keFpRNUUAWbsH1eRm1TpkQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:ls3iDkAGJIHOmU6gnro=,iv:3wrvhY3VcinaDZQ2dxPPqZxFA9MQlgCswL+J2KYYwOA=,tag:2L9XfnPyuw8mNK7AdcMxog==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:RFksz30=,iv:zlfu059NruqKs7KKvpnfvKHOobiZlUX6OMe5vLryYFQ=,tag:J6QFB4yp8Th/ozR0czEjZQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWWtMOG9rdWUyTERzUkJ2
            K2hZdFJLek5tZlUwWm1VaDQ0SUpDRzFzK1FFCko4c1Y5ZStSU2FJMmhzRTBYUGs5
            VnFCZmxGSmorSytSTkV0SUlzOHl2LzQKLS0tIE9IQnZGdmFIUW1Rc0w2T1c1VGwx
            dHBWVHVER1RQdllJSGhtdzZZV3BFajgKZmB0ylqh61DGJRswdJTQ0/EZUfkPImt3
            E84ebIGXgYLS57TdFEQBc5SVcu6dc1Vyp81p5WLsFkXAKEt08JynMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T13:03:33Z"
    mac: ENC[AES256_GCM,data:CIABvma8E+fi1Gdg/C21pJHerm4uBpRYxVpkQwvger2Qsz4Wsi4uy357G4yegPrixMdQb8pWJaRpIcXbdsGlI1mFRboiRs103GtBmOIMt1spvd/sh+o3LWjsKI4un6wLpVceZxumBB8UO/DqmNLRYH8ecXeG7mzhXLc1Cxb3QfE=,iv:wt1Ik4c4GlC5fkFTSs6yEoqWDJhm1klKIkPyH1MKu78=,tag:3w9gbfCMkIkdu7hx5bgJIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
