apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-wordpress-ecolieu
spec:
  values:
    wordpressUsername: ""
    wordpressPassword: ""
    wordpressEmail: dugrainamoudre@gmail.com
    mariadb:
      enabled: true
      auth:
        existingSecret: wordpress-ecolieu-mariadb
    externalDatabase:
      host: wordpress-mariadb-0.le-portail-wordpress-ecolieu.svc.cluster.local
      port: 3306
      user: le-portail
      database: le-portail
      existingSecret: wordpress-ecolieu-wordpress
      existingSecretPasswordKey: WORDPRESS_DATABASE_PASSWORD
    wordpressPlugins: []
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: www.leportail.org
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      extraTls:
        - hosts:
            - www.leportail.org
          secretName: www.leportail.org-tls
  valuesFrom:
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: WORDPRESS_USERNAME
      targetPath: wordpressUsername
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: WORDPRESS_PASSWORD
      targetPath: wordpressPassword
