apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-ecolieu
spec:
  values:
    wordpressUsername: ""
    wordpressPassword: ""
    wordpressEmail: dugrainamoudre@gmail.com
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql-version-8-lts.controller-mysql-operator.svc.cluster.local
      port: 3306
      user: "placeholder"
      database: "placeholder"
      password: "placeholder"    # ← écrasé par valuesFrom
    wordpressPlugins: []
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: www.leportail.org
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      extraTls:
        - hosts:
            - www.leportail.org
          secretName: www.leportail.org-tls
  valuesFrom:
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: wordpress-user
      targetPath: wordpressUsername
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: wordpress-password
      targetPath: wordpressPassword
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: mariadb-user
      targetPath: externalDatabase.user
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: mariadb-password
      targetPath: externalDatabase.password
    - kind: Secret
      name: wordpress-ecolieu
      valuesKey: mariadb-database
      targetPath: externalDatabase.database
