apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
 
components:
  - ../../../components/authentication/exposure
  - ../../../components/certificates/clusterissuers/mkcert
  - ../../../components/certificates/wildcards
  - overrides/directory/exposure
  - overrides/ingress/exposure