
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: directory-internal-infra01-alter-it-tls
  namespace: controller-directory
spec:
  secretName: directory-internal-infra01-alter-it-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - directory.internal.infra01.alter-it.eu