
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications-shared-wordpress
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/shared/overlays/production/wordpress
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age-private-key
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
      - kind: ConfigMap
        name: tenant-shared-vars
        optional: false