apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    #ENC[AES256_GCM,data:ozsLR5ShgCQifnrN4eDApN1yBWVXchT/9QO+RicomPzEMOFygwxw4/o3Ylm6qGxl61hC8UTUUBzo7qfPjz26W27zMEVl,iv:L9MZITjUvCv1iN7wplESQUXgJIegZYQy/ChL6AvhDw0=,tag:0jcRtY+OT/b06n34yBfHOw==,type:comment]
    #ENC[AES256_GCM,data:07iSwzlwsP0XV6ruVhyJGWkqOH/pp+ICXcXLF7XSBeg3YaJ9rPIE4znmyOLBmiluvyGnTCE93aKqLm9q/4m8KWWac69lBejGHQ==,iv:QJZq2EXvy97EQ2NbSNjw+rU4c5w7cwETfz8vgp9FvIA=,tag:Qvoxor+H9cN4AVA9o1SbYg==,type:comment]
    #ENC[AES256_GCM,data:Dy9MDJ5jddalh1pRYTaLlU/RjS1Q0g/h0Hu0Y0huiu5T+Msim639sDTU9soyP6EayWRRnxiwCrt/d2pcUNIo1nO3kEeorgym/cY=,iv:AGe/yf11DMHxVQerty5hGofg2/uxoxq04UIubmgNVWs=,tag:RKJCicNLr3mIVg18S4RzEA==,type:comment]
    #ENC[AES256_GCM,data:1KeMzwaESMqhUQaSuVUBLqWAytH8dxbBqM1fFMG2i6YYkS1hjGRjkC298RDjvqMjmP8HYX+AoYTOvfk=,iv:fMzEnrxPFvi+mYwql+pUn5AV5Z4027vBFY+oj8PrwbU=,tag:KpFldGipsxUFDIn9EH+Fyw==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:OVSh3qbZvwtPvH7lQ4A=,iv:zWCaN2Zu8eaFs1fkjypdSVvYCFtd4tFwsekByjfU0Wk=,tag:RGX+2SwzVKzQ57/g/dnLBQ==,type:str]
    #ENC[AES256_GCM,data:U1oGb1/UIMvhGItG4vkFJJu5+qjkO+ZaLcS2Xqm0x18GypSGX8cJjSSmZgl3/Ln6qt4MfiifEpnh82pNespqjII0SzG3VSdjDLCe,iv:Z5T7iUPcrh4AmCOB7TDgUoJQShVdbVcmIkSwGBqTFdc=,tag:7/zGw0VmHxj7ar5knvB8xg==,type:comment]
    #ENC[AES256_GCM,data:pg60C016+ym1xW5Z15e4PlsR/w==,iv:Wpmf+m4nMQKB8op9P3ljxANKUWcrugJbLqTnSvrSD0Q=,tag:DY7R8TXcbEKu3AGyYGMnSw==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:AqJRCb+WZyCqu0zON2RBLPn58bOXOYTLY9X80pfElNeKCWeWetF90NPZT0mwCVr/Tr6XnQJUCi2/Hzc4lSQvCg==,iv:REq5HnNvsZaCN09C1Oz6kOIdMdc2jWeBkHyLAEO8u7k=,tag:2FdEEe41HVG6rv9nyaWXUg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:6drJAXQltHnQVHAZHXCY27PfZb3rEOLtpJde78Qpn+WY6XAnzs5DTBAdRFQXSCTr1Vsp5StPR3yhWff4n+xpaw==,iv:/5+npyRv5ewMIOOENMyNarRPxpz+SJGt31CF/IZEh5Y=,tag:2pl6i2GqwZRjw3EJgPwKLQ==,type:str]
    #ENC[AES256_GCM,data:SnvZWDm48owJAWlNxepKHzMxb+Ymic0TJrQIvhfQY+ZUfuJq4FZ9LrZvy2LWu5BbIMgzdDBurtB6znTrYQQ+Aa+pFi/Ue1YwqQ==,iv:gZMcn/8wzUBAtMXK81bBNv1aANiakUuwxjgmaOHI3/U=,tag:X5yMOms7jak/bZomSHTKYw==,type:comment]
    #ENC[AES256_GCM,data:6QLnLg+qlk6liIBkL1z8ZnijK4t0/9YMA2XOoWLOcdUiF8FVeZAex8xijjzo1mI8YA1a+npVKbFbv2tAa0ZrPaw=,iv:r5jaBsewYcLJLGc/o8Bv4SXv6DW5doU0oiAazLAVqt8=,tag:Yjrm842L9G5a1gAgm3+Pqg==,type:comment]
    #ENC[AES256_GCM,data:xXFAx8c3ZnmoGE7EGCm+e1RFDIiA15A9gjPrxhz6bOIZ6AHtRcUGVqw06SBv/0nNrQvv0Uw=,iv:wVkS9bQxjQP4cE4z0wE57NEE9jgbiGjVV39gp2ViDSc=,tag:lLr16lU5kPK48Q4OhiTldg==,type:comment]
    SMTP_PASSWORD: ""
    BREVO_API_KEY: ""
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3ZiVXczWnpiSStSVDNZ
            bDE1QVRIZnlhMEZoaWh4MG1TajNnMzMxTlhzCm1GMEo1NUhmOEFGNlM4VjYvcFZM
            K0ROZTFpQzh4TGlRRUhKZ2ZRTGg4c28KLS0tIHBMSTFEcXdDR0pSM3NZVnExbzFp
            Syt5TnZTTE01aUJpNXVmNjBKSmVtN0UKOqtnTwusE9dlN76cjFtu02IrZGmxsXjX
            mvjujMFE+oy51+CrRySAH8fx20uMMqgjQNyCjpR+1I5PgMhjEKaGSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T11:03:45Z"
    mac: ENC[AES256_GCM,data:jVO+oKfOqohN+wbyRnbUQALSb3pB/H+EtCrQevqpQifvfS/n3Rwl7XZhZrwAhq4pyETpdYnyO1ObatMzGhdIiistAvZdPgidle1WTz87kX+VFYGAqSpIM2ZSdYL9FbYaKyBXWJ3MN+X0xqRpvMAA+sWphXmVfYBccQ4/ixj6klY=,iv:7agozVWwFIn9SbgYqfnSQFc1xH7WThAH/JEDIXTx2ng=,tag:5G3eYc/nMiDbMm5hBuvX8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
