---
apiVersion: v1
kind: Namespace
metadata:
  name: grist
  labels:
    alter-it.eu/tenant: "${tenant}"
    alter-it.eu/app: "grist"
    alter-it.eu/managed-by: "fluxcd"
    reflector/k8up-credentials: "true"
    reflector/database: "true"
    reflector/grist-oidc-client-secret: "true"