
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant}-wordpress-site

resources:
  - ../../../base/wordpress
  - secrets.enc.yaml

components:
  # Enable backups
  - ../../../components/backup

patches:
  - target:
      kind: HelmRelease
    path: values.yaml

  - target:
      kind: Schedule
    patch: |-
      - op: replace
        path: /spec/backend/s3/bucket
        value: "${owner}-${cluster}-backup-${tenant}-wordpress-site"