# === Zone infra01.alter-it.eu ===

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: controller-authentication
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.infra01.alter-it.eu`)
      kind: Rule
      services:
        - name: authelia
          port: 80
  tls:
    secretName: auth-infra01-alter-it-eu-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-infra01-alter-it-eu
  namespace: controller-authentication
spec:
  secretName: auth-infra01-alter-it-eu-tls
  commonName: auth.infra01.alter-it.eu
  dnsNames:
    - auth.infra01.alter-it.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production

# === Zone leportail.org ===

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: controller-authentication
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.leportail.org`)
      kind: Rule
      services:
        - name: authelia
          port: 80
  tls:
    secretName: auth-leportail-org-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-leportail-org
  namespace: controller-authentication
spec:
  secretName: auth-leportail-org-tls
  commonName: auth.leportail.org
  dnsNames:
    - auth.leportail.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production

# === Zone fermedujointout.fr ===

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: controller-authentication
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.fermedujointout.fr`)
      kind: Rule
      services:
        - name: authelia
          port: 80
  tls:
    secretName: auth-fermedujointout-fr-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-fermedujointout-fr
  namespace: controller-authentication
spec:
  secretName: auth-fermedujointout-fr-tls
  commonName: auth.fermedujointout.fr
  dnsNames:
    - auth.fermedujointout.fr
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production