apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: controller-authentication
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:S1XR4pd56iDCnmFxHqpX4RNPsX1n34d2vLfhprx3VcczQEfYnF5gqFfBWtWtF64oUZO//W+iISFw8MKj0s9FiloFgALt4fKWFSoOH/iQGfRlwqdCD+3ZgRnS+wjdxOPg7kY8cntVlp8+lLbpkq214uS6oOQfPBoilUn8zsu2iPC7Mdt/+/V404Lyr7RrE+i254h/+jbsmb9b1u24SwNnDwqjf5yqUwzqpJRQb2G1+0CkwYBzY3/zeXgi1rJOGLMU6d7L68sfobBUORrJdbp+gZKT5Dgpea3+YRbcoFI5lHJYIapcJEt1ofj8kVKmxv5r6FCEaga3Stf2U2+Yy/cR9AthSeuL0KgZc9R71y8N8b2gVfoBetDe2qKqdgwBnebfAYfA7+xBLQR+nRTbSJykEd7L/gcAIhyxRLEy1FKyoa38cYgyO1dcUxKGPWLuntqUDZEepFgGMyJLVMkpXRmCxtG19atWMjggXL/PcVdkqB3mSz26CXFQHJDB6Wabqenz/wERII7nisFl8E8nB/kG7V2sQL/2lc48gOtCczqWau4cZWzw4jtVL4yDWX6S3ZhMu/VrD3TRiEEZpcga+qafU8zWD0Ruwcd3xV8C9DZ2j38CSt+PVhTvu1p7e+bElEBBBaKZ+ndlAKUFoNW0C4lA6HPjYb48CreIlJWC1XOCgjrFLw4IuLM3F8CPmWxXk4CxOFrxgnOC7LG8bdA2y4ysD5YE0YIsRvFhx1G899Z3xvIOn+MGDcyMC5qDk0kTVzUy0/rEHES0LCBE7KCaq4S3SPr0ux69Ub1E4WkqjlkFufjvrV0fM9QjUSslVcBw0LlWtN/iXbdawtvKaFkcdP0Ebm1JgIdmtvYWWuZT2OeoF44H89MwSYPwQkuSagxNnn//JSQGvFFONg==,iv:JyxUAL8KICi3cDpKMTF+nX0hnvTcVgwaJyHwo8/UZ6g=,tag:0LWovjQD8dCzecTx5SFmpw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWduUzJIa05QMXVpQXBn
            K1ZUU2RNQUwwdWQ5YUlIejRlOXpBVVJRNjNnCjFnSDlDbUxPcGhldG53LytLUU1B
            SHlQU3gwVjVCdS8vaXZnTUVoaCtUV0kKLS0tIHA3QUxwTzExaFVoZUpUR201RGtx
            U3gzTTJVQndDeXFNRXNIaXJ4a1ZuN2sKAOq8bhyjIAuk4Tetk5Ezr10w0KnOrftk
            y4UYoanSOkLy8lkcsHIE5wrLEzVdIlQEikMlFlJmj9mcJ6MlpIFCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T19:58:15Z"
    mac: ENC[AES256_GCM,data:Bp7zMJiRISpgM6tFsg/48+2jhUvWjZl0hTXG9N7odfZEnb6nmpagu8tmHcp/XzbrtlJt4Ndk5Pw0IT8GdCLfcqMiqhYw+xIQUbPJ/MPl3ltBk7HYqMIxC9mzGvpJMcV+Qw/JVChUGTlc2DK2Qr/r7lmgJ/qRIe/ZxQAqloP/37U=,iv:xSVUgVtgG4nj1LMj5SeC1N33wiEVTiQzWRQXSbgJ0do=,tag:qCL1Mgy7YDqoWGnj8xcNcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-smtp
    namespace: controller-authentication
    type: Opaque
stringData:
    #ENC[AES256_GCM,data:VZB2GpyvXeyTi+vsDduNC/dOut2k/rMyLB7X9zOS2XHWJDHmjgwZnWeDWXN7rho=,iv:v+cOgERwnEsEFnAaXZheBYEVUq7nKN+Wr1O2FRizvZ0=,tag:LO/II/UwEzvIkElJsBsfjw==,type:comment]
    password.txt: ENC[AES256_GCM,data:fTXKLy48cfi0BmZrIEpTLQ==,iv:/kdwUqavHMxV/j/dyYvZMJlilnyDCSdoYAnhCIpVZbQ=,tag:41/ORLWtSH81MWckS4N8Mg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWduUzJIa05QMXVpQXBn
            K1ZUU2RNQUwwdWQ5YUlIejRlOXpBVVJRNjNnCjFnSDlDbUxPcGhldG53LytLUU1B
            SHlQU3gwVjVCdS8vaXZnTUVoaCtUV0kKLS0tIHA3QUxwTzExaFVoZUpUR201RGtx
            U3gzTTJVQndDeXFNRXNIaXJ4a1ZuN2sKAOq8bhyjIAuk4Tetk5Ezr10w0KnOrftk
            y4UYoanSOkLy8lkcsHIE5wrLEzVdIlQEikMlFlJmj9mcJ6MlpIFCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T19:58:15Z"
    mac: ENC[AES256_GCM,data:Bp7zMJiRISpgM6tFsg/48+2jhUvWjZl0hTXG9N7odfZEnb6nmpagu8tmHcp/XzbrtlJt4Ndk5Pw0IT8GdCLfcqMiqhYw+xIQUbPJ/MPl3ltBk7HYqMIxC9mzGvpJMcV+Qw/JVChUGTlc2DK2Qr/r7lmgJ/qRIe/ZxQAqloP/37U=,iv:xSVUgVtgG4nj1LMj5SeC1N33wiEVTiQzWRQXSbgJ0do=,tag:qCL1Mgy7YDqoWGnj8xcNcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: controller-authentication
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7lP56ibQeNPNB3xd3a0qs7op,iv:liqDnWLufClNFvod9uaCAhmM5vxHVqaPcOs1gWU++vk=,tag:0IXGPJs6hnp3Ie6h9T4nIg==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:lgL4JMP/lathNDTamJUbPJTyORGi7AgV1DaHY1Ot7SfMX6iMNZCS00lZLgwxcBzGuR/o3L6NHnTIxAvECk+wD6+66IPN+pVzfSCS5zxbxXb7eA==,iv:9pnCfPVPcHOkPTXjlzroCxqg0jGToF5AGBitWvl+/7A=,tag:ubl2jw+4GvbNt2Vlf4C2AA==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:+Tm4E+ZRYCAKC9O/ag9KIcQDyxRKtJzGPXe8rA0OHtazCH4BI4KEYh66jTzMP+Ipu7jRAT+eRm6lA9BBDkZ1uVv5s0e4plmc0wsUeGrl,iv:ECsAKbLA/SPU3YlPN2XEUMYpIJR+PPpApe6H+YVx5dg=,tag:OdAIAaHq93cdvZpxMx9yMg==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:pnV5LK9HUV2X2avs9WLyD1k1+jg/0Wxpk1OE+OyvGU2w3WPIihCPjzqlo7ZAMz8mfA2ahNpcmoVVRbD++G8FtNXo14TOPQ==,iv:EWjFBXPbipuaEQTztVGqr5au8NNbVmHrc064KK7Gu3M=,tag:Dlj2gE4OJf2K4nP8dne8iQ==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:zKOpXE/pAYGWQP98Ehnj7GNstadjpUxqfhh1FenDR7mtYiwMJpmKdnJB/IExFw7X8Ilsv8zxYSaguhrJ1JrA8jTUf77FktoGQGO4JJsVqRLf,iv:VlC2CE0SBC6ggioUakNfj1n0JuS5gkS2WmaQnr85loc=,tag:62pwciKByBZbjZICIFMUpQ==,type:str]
    #ENC[AES256_GCM,data:xRfcc2+AqMw29WOzlIjPUPJDrVxSlvOXDxG7gM/1RKVdyL7xmuf4MuMqmpYYi+QwYqgZCs6jZZ+0,iv:vY4ZaQNKBAMTEfdHHMjrHCjOIqzB+6JWpjcUG52Ojkk=,tag:oHw9u0O8eDoicQZd/I1iZg==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:w8/QeXGdOVcs4GI3P7FiaCH/KPo8UIzURFb5HpWCEE6wa18vz31RzO/yJiuQWaBI3htUPRArctDssZ2WGWcw0ODBxW+wOKidY7+zRzyrjAPjtrHYYRrEMZQk+YD+XP2VtyEk7nl91QU3FMOLZ3QmunqBFoi9HRz1gOi2lz2GlWwcCi+y+ReAHdLUm6Cq+7Mg4dyhOCL/bFmuEJ7HwISaIz4ObTKnbL+hhQ3V/7L3Yn604csJSJ1Km8Jw47yhWUFuXsSRK7nnP3Enrpfdwn30DOK6FX87T9lCC0yVhFFgfGZPVMW+GFWKopqD0o3PIewOIJF4JcWelYxuSTbVWyQs+VWzKKR5WZQSShqgQlpZES/7sv7yIspHX1uKi1kLqYpvULmMw4wSKm+bxYjRn4x0n/3dhrlxEtiPy46lHxfAG4Skh+zeUjyNRk/3g6BRl0/RALeu7hLt6Rh3NeEKdws0Nutya+E5xR2q0S7JJMySkOHg7KTHN28NSbFPYCJZdtHS5u3QvnutVtzxvliWoOeUlEPA4cL4nQuROvO3HK41VmWI0rz8MjVc9luL7PNmzjY5mP/82WfdxVSdR9Kr4ta/aK8/9QvlC65Yua1+PZTAewoaer65k5X5IJeGCwOsgJK/rO8Mg/QVHfUB9TybUEAH3WfiLIGSNMnXk4Nv5brN4toFSpUVUE8H8ZL4kfQgIpkQdCU4IjWdgyQdAFdzOZVWR58ohtaNxIPSHOCdPsxSvgcGbmg9vMHyymplXxwK/klt7+Nq3uousfIE4ca+iOeegPcfGMZG5VYeP3w5Mr8aHl4KU17HQm55O0gNLPY251qCvFIBnPgOueiAoK2YiQQMLZQLeQitw8Xk2XvpORKjv7HQcPhcqLisXBjYmfYZ4D+pMfGDndpAK/5nVNRfESSRfldA579WdhynXpRT4L6PeRvKzUFVkNljfIm5ca5yUqG9wHntEH9D6KXYgVFEpLlmO3Mp7DIYe8WqSlQJgXi/29ue6v8xAkF7w7vkQLCiSWpBcBzLj4S/znSWFrb/opqbBSEK0UDmiEKuUSTF+Wh0+jEgREgn18n8DALi7BXddRDapiGka8DQSlY5Dcq9rSbBtqckRQ9JBuIBEf4GGLiCGxdRivC+DZHcdI3dp3yakgF8w5GxoGKXDpRBaMKFgtVtIjBzX7badDFl0NsvHSLbeIbeJn+BEYFd9ftsvQX9fZh32+JbbMAxLYfoT7EEvM3pcvYyN623lfgH2aS1SzXfPnqgYOvmUTKBOFfJlYcCn0xJFsIpdLHzSyfGmUHd+Xti+5WzGjYlEhjbh62Hab0ESGFkETThWU12oc0SlGv6eKK0M2DlclrJQALbTewE5ckUJcpSESj8/m9rs7aSdxSvQ+ATDDegC4huoLs2Fmu4df89rGzWLZAB1HBtOwqFQq+hUhBid5khdc3eK/h2joF+XdbvxXncRBsXupUidpJTnbOnwSGGjPQfeTYV+bZpSwdg1tL0ygOOFYwO9qIxwrclth3FngUXDNGD5xs9EMNv0Sc+qhBtOqPMuua7O60scYgp19BGJtJBGAYEnVUhGE14JahyiD27Dbji31ybD89AEnl5JrnzJOcK+57Wft/fTAEdqDC8+ozTQv/CA1ddWo0yOfreDjYqyJpVjIF3sjl3gyXpgsuj/PgE3EXsUpUZ9CzlOuLaAG1fUd6Y08PZfY43TuVaDag9eG0XZuH6xG0c/Xm/ojsNlmRDU/nBjqyn+F0N9CkWLvi96xJs/HDT/ZRM/xwqfti8t9pI+ptG6jmjiytRUO9KY3SP7I8CToohbH5gEpRugEwMm0cqaXoKiETY+nRDTSviQjUmbnlHiSho2tiIiMgOzWav6pNXggFhTCgZ1izRnycddLVv5TsA98CX6aiUudyKNGuD3l82qTua8NbrqgWyJaXcnneI/0iz41sHARm/xe1rL5H4mtQvjJ5RSSEFw5wzRzExxffUH/M/p6c0OMscFdQp/BHLO0ATT3ASWwGYO7f7e7zVy3ReeRlEhtci2nBAviF+gyIjReXsphSgSOtuKL+Ah/lvrPDt2y2Q//VcGSzSKlwqnQHAFy3/ZgFawOQgAvVurtyejmo31EErZxYLBO8frNaxtBkruNdGRQcbm4jVSJhSxrfA5fVPxhbfsqSXlxkXahjVkLzQZ5Sg4V+CI+27l0JNlmaNYITS+cmDXCzmkaAK3IR+UZf7uK02k71+6PASe91dk4wz+SnB5ioaFq38P2bDKjEJUAObjLpJ5U95PkPPsVe6D3L8DARqLdhFoJw2tvVmcwZ6U+uf4XQPC/j7uAzSZfyfwurgKnPy786euR0yrka6z8LaYL0MDebgyrH5wPuYn5iAhB9D7ATnwxJO7ie8bQirQdSvNj7d77fjHG0IWOPOWP5TPi57BNp3EElkssApPjMImUjkot3JJXAcK+7Sw3ciPM8iPsV5tG+kjpqGt8L/ZTeMhFCIjeLlJZVMbgeXcVei1wvCASqnd8al5Gh68Q9fVktNnxH9hhrraFSmmv6vAfT5g+hnPqEISMszQtqdxHhramtmi8MWGz03SkyMWcE4b8cBDfDhzfeZeaCt517hqbtqH6Rj2gd8g23KjbdTT8/fmGvpOA4PphOIFTmtrSam6oDVqFrodulqH1J3Bi8WmoiRaDK5Ny2IVNcVu1vlqaiA+eGjuFNJXRyQj6UmJv2/0iDb5snHw0EI8JDYzvriQylmNkg96F410hW03f+VJ2EA0EUuGNh1HwqlfIDrv/WLwIRODpgj4RidcCV4/c77sCkUDosNYKPOYvA8ClNzBB2TUfc9/J5Q0AB4u3gYU5BgXAF5YKnI0By9A0WQXDadU0P8JH06HdajXNP1GNjKmw6OgTbIasTQSKq94hfH845BSkQ9aX+3CEPHWG7qlFDfBI8TTl9+PdWekGZMLA3b9tUb5aBvtuDOlmGHPnBuThb4uOl2wUfkE7gXCWz5uRonBH9Ioixn3UwsK0aoIxuf88v37kskvfIAJ8luMcfBHX7RsNg0LLO9XwIl0KSevH+qMfDNrzvddwV0zS5ROehdJWnbGCYmCinQFT3Xt1qPdnwBcY5yoeyPj9X/QgBjq9rvAC6Z2IGIbuFkZHuRJpHcOS6ub+/Hq7aHWPKu/mCkgHb5xXW0qZHnLBAOwHDMx0d8l4BZFDYzppNeRCZ014WPuQNQDRfmIZnfPzgh9xG8jD35i9el4k5r/3ranv2Pn80L8GT5BF8W41bDFhu7Hu096r2V7sDNbBHhWi4AbtzNNOuNcv6J5d53K1DL8u5UlR5TnFk+0fSx2CsRyZsVjwTWHIQbUfBJfmGz10pLjJ6HEuEiEhgf21ryzVD0FaZ9S0iGHtkXFVKE4BaTDp3vyTpOcUSVewGVR2o04cKTeBeyvXvG5SWSBSHyxNzrSFS9tu7NH1ARj3hj0c12NYBRFbIPH9KUqI0pLBPaNS1Iwon6KPwvjjQiGPSdqJRITW5tZsyJd5fKVJyOoioJccyntNIuTa11kMK/gq45ef0Iv0EtV1TnL0LXJX0JMXb8UMPYD0rXHQBTs/l7PXlfSQOICE8FyVu0+fYG/LouWszy7d5orZQaGHKuVnXPNkFG/Sg5ClY0ghL8bGY+U932O/0n3REBBkafoh5wJKxVegJtUjg+hhmq6czuQrbGj93o61D0JbBwLTgy33E1ydGNsBKU4B6VorEyCYrvV5zu16fjXvirWwhrUT+tKiUa6+h8xNvsBw9h+p5HQUIJ5HRAuQNCCvWwIoDSNSAOdqkq5n5qK9nijpDuGZ1ojXb/jTioh7NPims2S8+VjL2N+DftlcOlEbPdWmnI1kTg8zaHIjNvAfb+rRxbTK7/m3fGRsG4/zkfvENl04y1P8lfQ9gzTEiYYjuyOojF/rjM92tsPQP11pMBKULaSpcTAY++8bgI8p0z/9dgTYxiD9u1FX0RdswXKsL+0rFYIq0TK6rkzvg0sz31i89S4RUYN/YqOMjiizKTt5a4OXVm5sbHhPm3TAjhuyG/tAADLbwVXp/Q9h05LgJCwuhWyoq3uVlfyOLR6sGuctmE35QY6yaQ7I+LqpB8Q2leJwTcpsX6cYEafOexWtV6vft/jZTcuRLHvFYAKtAXE78cCGvvAEMnU/w91MjEdDBG/evtlqygeWjt91oesY8/MSZTl9Oe74hGhELEAI28og6mRXU4ldgzSYYt+QKCL41ui+fFuVOM2roO45LpbYFx6K9Ul8SRm9re0HBZIv5rGbyscDc1P9sOQjmgUO717+uVufHT11STrZD8YXOJhqdDf25gqe3G5dLy++mC8A8JcU/0ONP5z3qTHg4iwqNP+XQQ3qyjdKE/E3mjgzjqrcY=,iv:HY0mXv1zj0Eo9QzReKrCF9keomrKBUsCOjOMOKeCdig=,tag:0MhoV3yhG5A8pAz6pTcWYw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWduUzJIa05QMXVpQXBn
            K1ZUU2RNQUwwdWQ5YUlIejRlOXpBVVJRNjNnCjFnSDlDbUxPcGhldG53LytLUU1B
            SHlQU3gwVjVCdS8vaXZnTUVoaCtUV0kKLS0tIHA3QUxwTzExaFVoZUpUR201RGtx
            U3gzTTJVQndDeXFNRXNIaXJ4a1ZuN2sKAOq8bhyjIAuk4Tetk5Ezr10w0KnOrftk
            y4UYoanSOkLy8lkcsHIE5wrLEzVdIlQEikMlFlJmj9mcJ6MlpIFCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T19:58:15Z"
    mac: ENC[AES256_GCM,data:Bp7zMJiRISpgM6tFsg/48+2jhUvWjZl0hTXG9N7odfZEnb6nmpagu8tmHcp/XzbrtlJt4Ndk5Pw0IT8GdCLfcqMiqhYw+xIQUbPJ/MPl3ltBk7HYqMIxC9mzGvpJMcV+Qw/JVChUGTlc2DK2Qr/r7lmgJ/qRIe/ZxQAqloP/37U=,iv:xSVUgVtgG4nj1LMj5SeC1N33wiEVTiQzWRQXSbgJ0do=,tag:qCL1Mgy7YDqoWGnj8xcNcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grist-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/grist-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/grist-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Vm972TEJytAy79ZdM919yPFSXmPHMzVFdkiYqSKyd+HVWIU+pygt8iOhbth4PRs=,iv:H5HqTOTg3HHRC31OY/AYhYb7I8/e4TME40CAWql069k=,tag:RFBBXwMJdtGQBuTDQmjyCw==,type:comment]
    client_secret: ENC[AES256_GCM,data:eGFDA6LM0q+qygYH9rQzSDuxXCnBdONk4Sz49q3bhyTYG0I1oglMqy0ysDY=,iv:zMF5uK/Pw67p6E/ZzOugpVaC9pHFW2P8k+fA/ocsQU0=,tag:BFWBmRe0Fj7MUcz42yS8NA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWduUzJIa05QMXVpQXBn
            K1ZUU2RNQUwwdWQ5YUlIejRlOXpBVVJRNjNnCjFnSDlDbUxPcGhldG53LytLUU1B
            SHlQU3gwVjVCdS8vaXZnTUVoaCtUV0kKLS0tIHA3QUxwTzExaFVoZUpUR201RGtx
            U3gzTTJVQndDeXFNRXNIaXJ4a1ZuN2sKAOq8bhyjIAuk4Tetk5Ezr10w0KnOrftk
            y4UYoanSOkLy8lkcsHIE5wrLEzVdIlQEikMlFlJmj9mcJ6MlpIFCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T19:58:15Z"
    mac: ENC[AES256_GCM,data:Bp7zMJiRISpgM6tFsg/48+2jhUvWjZl0hTXG9N7odfZEnb6nmpagu8tmHcp/XzbrtlJt4Ndk5Pw0IT8GdCLfcqMiqhYw+xIQUbPJ/MPl3ltBk7HYqMIxC9mzGvpJMcV+Qw/JVChUGTlc2DK2Qr/r7lmgJ/qRIe/ZxQAqloP/37U=,iv:xSVUgVtgG4nj1LMj5SeC1N33wiEVTiQzWRQXSbgJ0do=,tag:qCL1Mgy7YDqoWGnj8xcNcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
