apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: controller-authentication
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:bknp/A1UgBPO7vU/q/VL8Qbi10RvdH+qWkeoZhbAkDreID9E+7D72sQ/ITACMcO3Q6niRBibrzpICuyJFRVCGfddanqijsUxuntzC3tvuLFnDCdkmqM1CGUdFd3JfUbR+GLx2Qerr0qweAdJ9hOHN0h7jnciubcIUUm2h7C9eC9VxYup5eBErISXeP6NWEESz6Kve2Iani7iBpjgIFYvKc1g8QHZjHY2wwTRL2zDKbRsyW/wv03bq0r0AUrpjDZ3eD+bmDnbMIBjiVnjyDN5YOSY2vR0JBVqjBq+xvV+NP/PHeM5pclvE4piXkVFuFbtQI3v2yiInhlCtcxtRB9ctwMObLZC/tnbShsCUtAAF8BMpNfW+FusNfG8WXENi/R2AXQstTijBBN549xAwkDBburyxcLExrJqeO7yjkrvhpPhKlvYbONESFVeQFscqOKx8vC+AscKGHiApxOt4PaJAyYtUbRh7BEjvyqx+++g+lqLZUBS5KKUk+LnCHW9QPWJSPRv3mMMvveD48zXyvKXbCXgpDil4I/RdmxVX37q60tWWrV90e1/rqPorBfyNFad/GFLv+zEo6rjWW9eDhnqyCno1oPlbF9lFE9NtRgtQUBBg77MwGf12Gq4EoTNHmdjmPpcZBDTvIFcHFexGjTS8Eg90XKDkCzAYGLMMaw/eKRZLi6I30h15WIkbQt22Smrl/FBzkCvYj7/F1XDWC/zMyZnTeoEhbQ1iN44mo2+FUUao+1b2Z3lrghMttFAlfvhjghONqINy3O+KdIns8mEgHi2aMNvVjXaC63M4g1uAuoc4f7y8FakGGl719h+2tWVkMvLqmMEeTPQLa97WQ9rvRLKrM7QYpbRhan0k2s48BNA3qC/qoCruSk3I5ILgkxBVe6jPhLMFTAoNhGXkApgS4GYcSYbVqi7RC9k/zOhfemQkJ05ADa2NAZHw+YjTl7IVzY1jKVAAx3AqcD+A/JHBU+jj+el0+iw/YoeFopl5cJhkoQWiQiz3sWdz5kEeuOTlU5KDsXHvXlKpTXz3miH4WnXpdQLghfYdpFrN20DzEFXHnnaPO5kRNl8VGHiUz2FRWMDhVCvZAzkb745i3/MTLlbO2HVeBr8vamGner1imF0X5I8+Dyra68Bc/muZus15YLENU4q9igw4reTOKOM31aT96XpVZ3ty8ybSX82FJ7SYVOF4CDxSGCSf6JGi/Bnmx/9eNqQcsDBSa4iOH6W9YA1S8BFG8FAK8jVMvVLPLcpuMkaofDzUVU3FW5nXPCQ4PC4EuAZLF66TRbfLcEpchtT5lxEnlRj8tpD6zYVdRw+VQGZpIAvBSQpVPx5aW5xc+D9Sa2zWJsoF+AqHDBHlLrg84F2Ntg99bOXedSDFsGqavEjVV773gLgExx0lYjwls0nvaXQvc5M86AeidRf7x3zG4vXVAE2vl9hw/kBpzuMRLHFSyGrDPmBf0ApYaBS7tAfDbrPlvXN7lp1SjEiTyZP2bIlXRjPLHOmAeGChC5/VVOLnTy8kLU5qLcuP1+Wkb0NMOSKcFPF4CTkuzEgY7QUvi6Z2QVfyKUmqcP1E9J4i93rHenclfhph20iyIMl3u8MuFfuSYIFGAisgaMWcfqMiLtoYw6hDK4FCxIDX4vMBN2JybLnSpyzcGjCe7a7VKVMkewlWaRIc+IrwalLKk4J2vlXqSqDJ9TFQCqcR5jTluXdxsG6EA+vdAZ9/16p2KUYfv/XFH+vKD14OrBU1tu3gG6UUVDWNaRN35SFTHKF/JYBVribQVdN+lWpU45rYPpDIZbSMUVKzKh+9DcPJZjX0nHCXLhISIkJR4CFCvgOc5WmHREF14loSSYXKKl97QR0wAgIi/FV4I+gKVCu0XkuziLe0Lz8XkXkDgdbXE+tMLqltqVLPWNyhndXhMKdScG/8SkPrTcZOLkuB3nNRz3CTH0Zi5TlbXw/6oPrVp6nwhu3+dkSHD0RJqidL98ilBoCkEppoOyYfO3pdwNvXQrGhvZBB5VaaDy+9zG9eVCA9h87fhFjJR6msTVFw8ZAltfkAp3r/0xD+wRy1gFvkVFYtQX6y50zaQEvRUkcuOVtWpv4ePaMgC8oLHPv1JhuDcNwkrlwWlcvEVv+cdWh7t4H5yj3nMOYJgsvRdVkItOt7wAN79paNwqzDW1dpVzp+LUgstJ83434KzpxCg8StQZKZqsx6DHYp6oU0UWNNWEpvlqjn0hnsCvM5G9TrEgTWA1pxhmVb90mhD5m/0QtO4MbQSEzQEqSdmHvb33tk180FZj/guJLfBq060zNGofLsdG7qSwMbjf9Kdk0c09hkV2A1QRdAsRywdu1aNwUymrL+ZoJeW74Z0YKW+q+FJUw4WhxKEFfinqhjmiUyRMfCnOBk4wQV8S20jtZNXItE2Y6DZaeYTjnXiaOK0qmODTdrNk9Z3ZWxhUge0H9Rms3BzVx+tr5ikohQ3srBSJg7/1iNbjN6x8UNxrkgCJB/AUjVC0THu4sZm3t0ZHISvw4Gp5hS1BoNrke5uC85ISvsumqQargOFmk9EXS6ZdqHaHdO25bJNvCvr17v2UiiQq2RL5c5x2ZFxC+L0VcjkVnPzPQcQzjb8MfBHhA7C5zNXy6tVrLdB7nsyI9RbFDGs234N9maL3UVE4Bp2OAmfjI88PDCBgFYW5DOdGCfqxKdlKAnQwtaXuu6FQOu583Hz9n7+/vksmEgLP1ZQIpqmIUk5nd+D5vo0nDUTkygd4U5FTiiv7HFDo1R8gwNBQE9+vpv5rcGgaKvbFr9w7eyRzA/wBa2CaXoWPMFzuC21AN5BPILVO0PGzEWyrvDWU4xSOCODvfPWiAtDGqz0nBiEIV/OBXaU9K7FOyzKXQabi0X3M8zlfmuRC6VEUB6zoeOyWu8PFDBmI5rfObYGKTXacd0GxZVvgpSnD6GXI34eGP6KGGl/GX9sr+KNYlEiTFScqK2EGunPOft6ZwQ1d6GA9kOR4RgnrX9VYvEuXduhiP+X8=,iv:kzgLrs/BLm9uBHDgdZrDe5eQ0G5Skn4L3bOWy3J+jgo=,tag:I9pL9gpKWsddpEU4KtyqPg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSTRDQmFTKzBHMzJQR0hs
            NldhU0lhTThoak9pNGJNVnU5TlJPSFZiR3pjCnQya3F0VFFkL0VxM1NXZjY1SUtZ
            NUlQc3pXSUVkM0hLRGN1MXNCeDVrd1UKLS0tIHh5aEVYVnRuWHE3SFd4eUF3REtD
            VW5FeENXUllkQ0k3UEVoUms4Ui9UbEkK3+wvle/0XEgLoHovy0fdgVhlLdETnpmI
            mpkwh7mwPT89lRlsYZMEuCFkz0HhTtWCKppJdxjk50CqLcWMux1lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:55:15Z"
    mac: ENC[AES256_GCM,data:2eEcZvU2eAIfQ3SS2doe/Z4DqTTCdJUKV/kcroj08jz7jg/F16kVcRR9cSp+h7m2wkdP/iPCPoNf7oq2JKwJ1b6wGQBUX64jKJ+b5pu81iMkbfnRcNij9gk18tGQM6mN4na9T294k3dAihM8R33/SjO/54JcucnJJGgxlZNhNeA=,iv:K0Tz3BNpPybQD4/ho+bMNuvIWHN8eIbw4T/uGfUBGfg=,tag:c7BTmdcJmlakLHq6SwwizQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# clusters/<...>/authelia/ldap-bind-secret.yaml (à chiffrer SOPS)
apiVersion: v1
kind: Secret
metadata:
    name: authelia-ldap-bind
    namespace: controller-authentication
type: Opaque
stringData:
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:cYrB2YwrLE6Y7uQDFyAT6kwCNoC1vphPR/2Og+sq/07jUiFL6dS4bsq84Q3vJ/04xeEvHTiD1SqsKufcxUPbLw==,iv:Ll02xCYmlqjS6e/wdLo015gYkGdBnwXnouuzry8WLb0=,tag:EeE84/IjsG5TmnjaFdjP0A==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSTRDQmFTKzBHMzJQR0hs
            NldhU0lhTThoak9pNGJNVnU5TlJPSFZiR3pjCnQya3F0VFFkL0VxM1NXZjY1SUtZ
            NUlQc3pXSUVkM0hLRGN1MXNCeDVrd1UKLS0tIHh5aEVYVnRuWHE3SFd4eUF3REtD
            VW5FeENXUllkQ0k3UEVoUms4Ui9UbEkK3+wvle/0XEgLoHovy0fdgVhlLdETnpmI
            mpkwh7mwPT89lRlsYZMEuCFkz0HhTtWCKppJdxjk50CqLcWMux1lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:55:15Z"
    mac: ENC[AES256_GCM,data:2eEcZvU2eAIfQ3SS2doe/Z4DqTTCdJUKV/kcroj08jz7jg/F16kVcRR9cSp+h7m2wkdP/iPCPoNf7oq2JKwJ1b6wGQBUX64jKJ+b5pu81iMkbfnRcNij9gk18tGQM6mN4na9T294k3dAihM8R33/SjO/54JcucnJJGgxlZNhNeA=,iv:K0Tz3BNpPybQD4/ho+bMNuvIWHN8eIbw4T/uGfUBGfg=,tag:c7BTmdcJmlakLHq6SwwizQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-smtp
    namespace: controller-authentication
    type: Opaque
stringData:
    #ENC[AES256_GCM,data:Sc5Lpu8wg5zPGjqljtwU3LtuLqXclymGiivETv7KUTekD21Z6a/Rhx03OF3Pafg=,iv:VeIVQ/AJ9dMAeLdWk/bPhKHPYdj9IJEyvrXFaxQTPyo=,tag:RbnIHlOMHKxq3Uu5TnzedA==,type:comment]
    password.txt: ENC[AES256_GCM,data:OEpn9l+Kh4X6Pa8V1xr0hw==,iv:foo7uiSmIY1WjwRUIw2PySlFr3NEIVbEo9YW7O7z5yk=,tag:yfIvJxhCqqCOgRMSPQPL5A==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSTRDQmFTKzBHMzJQR0hs
            NldhU0lhTThoak9pNGJNVnU5TlJPSFZiR3pjCnQya3F0VFFkL0VxM1NXZjY1SUtZ
            NUlQc3pXSUVkM0hLRGN1MXNCeDVrd1UKLS0tIHh5aEVYVnRuWHE3SFd4eUF3REtD
            VW5FeENXUllkQ0k3UEVoUms4Ui9UbEkK3+wvle/0XEgLoHovy0fdgVhlLdETnpmI
            mpkwh7mwPT89lRlsYZMEuCFkz0HhTtWCKppJdxjk50CqLcWMux1lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:55:15Z"
    mac: ENC[AES256_GCM,data:2eEcZvU2eAIfQ3SS2doe/Z4DqTTCdJUKV/kcroj08jz7jg/F16kVcRR9cSp+h7m2wkdP/iPCPoNf7oq2JKwJ1b6wGQBUX64jKJ+b5pu81iMkbfnRcNij9gk18tGQM6mN4na9T294k3dAihM8R33/SjO/54JcucnJJGgxlZNhNeA=,iv:K0Tz3BNpPybQD4/ho+bMNuvIWHN8eIbw4T/uGfUBGfg=,tag:c7BTmdcJmlakLHq6SwwizQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: controller-authentication
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0unjCRXTw8Uct7WWZp/k+PV7,iv:YLMuoxG14MmWlEutVfU48VWTsMxHRFs8QU2si0hBUH8=,tag:CMxX5MOt1nhwAhtDubxS+A==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:rMlQTd8BBAquhBUQst08z8e1VLZN8YEhk5M2RK0t6ftXLRa413lWzU6U8lZsnSJnEKHrHtIe9VyGtqsThF3gbKlRO0WSgVyjcZr2pb6+kxdNuw==,iv:Tz/genF/Z1NelWNahYv10Fzd0TwU3j7z+zvWGliY4q4=,tag:4rxybpJKsL/NzPYJOQIbWA==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:aV9fspt9mkiMoXiy0EgKTqVYE596HVKwInx7p7LroyQBELrPlBzifmheWpS45ahm1SM8/xDgFq1Q2UeeeuQM+DedFXIzWltKHHCVFSdW,iv:8w5NTUSOdz18qJgXx7OsWyGXUE9AKRBprm0oeUwARW0=,tag:1vvUuEy45CDAWugKRYxFoA==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:qC7CdBTFnn8PeK2UawYIdFZRvPQnMJpk8hs2a2L92vyKqe1FOHtbBHkMvR0p3RuUiqV8M6VTgwHMM6PPelBdBGwLSRVV+g==,iv:EKlzWz/ZJ+gK5am8vbaUS9wv8t8Dn9rNncmjW8Juw4k=,tag:/qoZ7MDZmgjTknmsGcuSGg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:s/s6knqWCPe/lczs1XB2GDVoSMwCBNF50MM3doousDLLNO2VU9FrrJg8E3dZaEAhP6XbMq1o73Gs387y7TV70iG+vNUwgH8jvjc1h+knWFiO,iv:f7HmK4QtCrz/aXfUStsVFlVJh1dqRtr+Q74LaS80gPU=,tag:BtinXaP8B1m3UOTltQm4yQ==,type:str]
    #ENC[AES256_GCM,data:+NzGR4gIr9qKew3FcYeNKmGnAIni8ebys53Xv9GuDClbihQxbA8UypuaObDm3Ea1RZ7LvB7WNsbS,iv:uvCGjn90FqzdfGv8VWoE9pC0Vf3UuGSXbgoxr+I0knU=,tag:mVBxVbnbsuudqhjbnQrLyA==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:9OKAdaQdGwX6E0IzeTjXP1RYJ98HF7ogRJlhHJnOVvBkokP3CrMRxzf15cvaol1Ql81B+h+Ukpt1zRXXJxBzdYLaRcFPnSwVUqeoYDK5FZtoyF8X5AlVdYNSnMjcLwuIwrGt8XiWq/hlth0uXos8f48dhbS+I2Udyt1Smx9i8eKaOs3+LVQx7dC2qzOlXJ3HBvxwKMsM8uuvHQG1KW5h9z3F8v8Rk+QXUQvN9DBJ1Tj7rAIsMoN31wly99PUp61P6RZfd9Fto7hKxAOrZoVvWkSLMhprHDW6P9CbX0FbOTzLwlmLpr9D0Kd2PuCqGphYHEU6B8ibg2aZ7Oc4mzJFZdrLo+D3JKlhEcA1V15SDL2XQAzVWVUjpvhYXewdQNjBgBFCRMMBY2AtVWPUksJ/4VUN0LOEM6bZVUkbUPZO5OZcr/RGGtb+GCvkbnkvylMaX+pnSG22OoareGI7FB6zvughAePYGdNFLAv+kbct32LyIRn4t78qopybiQU/TYOxfcI6ywDxn9k9o2OEbW+dJyQf+uFLnmh7cBtwk34P5/nzGvEVBmZS3AKSjIBF3RK+06S8xr2pDHkES27oVydLHx5OYNZ/DNgO1oLGJiUB9BB8fo+1eOwYC3Ec45wobPz6oBC0O7LgW1OsvVj5x96m2PVKMhRwXQQF2AoGyKDg4dcMc5bQAZesO1B1aF8HtTad993ppZ6zIqUZTvDkKVBr9+yQdJSQsuzgYB0Brt6XqSQuMj5ryHwGGEKtzNVTJQZH8vYQJG8+bB+uyIoyMAZoFL/mHdtFMGfjk151pfnpBBKjxMwNJWc5vzP19DfDpxyhF0NMtU5O2gVsT0gmp1nan3b3yU7TLYlUos38OOuL0ZGh8YHgA89CQe9aa9vBHLtNmdtfNq59bk0oSIQurjkUxmdKVxjsk5zPfHRnNLzXVIS9Dxi7pZfpbTHVZjddTZmt+xFH5uk1XSt81eFlDnT7rXet3uSN+UT1BBFgpnKiRqni8PYr3uQ/t7MCH8MJTDAEshfwnc3i8s+oPwDfP52VrNm6CHLB5eBBkLtWySsyU3GOPRVHsty51Y2w3uaxclTnxaLTfcX/L4NjQDjGtmibz96V6gpUKwoEjZhUzXke7vMVMvqMz7LqOQx8jeMvf/TxnruW9Mc6ZvI86zTR6al1M8kru7iL5Q21XJ/fTsYkyKXwpxkVWbM1DRw0NxaKjLw3KiOHrfusVCSH75TjkxzoMvt4/g9/YCybc3RjbkeBjpFmTPOtmYlgHZ88NXxCEUneZ6jptuKoPNe3ylwGCrlNvKoquujDvvBkuDp8IXfn58ynOjESs4Eu+VkGfO2H6ATbRXpHMXdZeYORnbqZfmo4+hikTrjO49Wk3N6mLDE4WJbuTLCkAd+2jKlR1ibauu8ooHyEI9u9cCsqibyCaESkd9SIyYSqQQQ6v0ZncQnUeDLKVltDK6P60OmZOCptjogtl9nIUNbYH6IsKK5HNSH7xH8rWzGkSf6GhMBcNySOkEYGlnfuaUOpMcgbAb098wID9KlAvs6s7b71G1nGH5EBBiBcX2BBptUgWfFknbjZtgqZWmWGE7oTLm9ZAZNbGvjFjvjKsMvSCYWhfH9/JuBXB+fEexpmaL0j8RNXMdWnZQehYR3Rpr8Mbkkpeg5cxU7H80CrvkDgZmtOfS4v9X92o40uUd6dKYLobv2TEzE5bAyVd/fzsfceYikYhPXSF6uL86IVJTaGlp25iXZub4w0Pedht3dlkb+v2Z/t64efYKJZSq431FZerYS3S0BiH1rJivAgZuup/Neqyti4duXkqUsJVbe8XfiobrEzjnSJz9JtAzE2SdDhtzSbCO7emQkRcR1UiuXPbH+G28Bp0Cyh/78zXhcETIDQeKwz08q6wxij7Dr8+CvIJfNvFAiCXoPFlO22+Q9hve1Pq7zPKRM8f3yDN8JumNitZxGya4OsXZNxp4Hyuq7+dHwXs33bbHf3BtuylmmjmvXLMdhkpYT1tA3MXiENyPeztAgE4xLCim9bDWquTsaMGsxAnoACbiyfJzg+OMITDnjehZuRPqneYh1HEj8obe4S6ueEr70RyVLyXkjbIuDpUCSZlqOFJpN0xdsZffinAAryqF2o8JKiHatnr+mk/Uh2WM6iwUuEaw4DI5f7EZ0xbQ+ZfoVrF+0GLmgMAcUHe7og5GXjq+MHjxauToFDSQ0ab4+mUEK6OD8fzUcbovo8eMx9oTImzhaDetYxRtxglC+gTTnnyVDMOwhn+3hLRKB9jzMXbVhGFP51Z1ChanVMQi0wI1QfVtU/qE10D0eqrBwTc+4p7RmF45de8p/P3TL2oPc8VBarSAanNlzDTspqYzLzLN+VdAdMDNcztcbM6i0BupOZQVuOjtxVLxP74nW7qdlHQ3yEvo7NSujeplLbZb3UeQXyRFulX9vtnWXWxWmEFRZW4pAMH/EIJO5xdwLecxWCAbjyYbuv4iaKSJOQpEhxVNsM9jPG+mB1OPioQ4AgqKYUNlOu6UjAIrxo8GK6evtcffY8rMPCwqMHi2hyouxZtgOv6MVZIlyufL59krwaFz6QR0qoGSH4zY1Wf5gN9hyNt9NgOrtEVkM9c5aD8TxZ/KqVDAXmnaFfVMQwbfc+6jYLXta+Bu4khuFcexx7/2j4K9R/PeAj46Au+eeaVDEZ1I9yetr5AM3zTVp1GPyZNhoC+ZIUZKd8aUBSt8sOhrDBJgybLPUpQ2QRrqVgxH6B90ZMqTPg8fakEJtudcuxhZGfOB+8hBCk1iMqCtjdyPLXsGS4DtfKNAb8/vj/Z31Oc+XEEcHycviJb3CWoA5hn6AgufJOZQa/mcsqHeGA3p2qM8vQPfffEX4nnRey4duJzN04zxV8Ghy6Bj0ckNz4jPV2a5k15800suPnoUWzkcxULmStT5l2NkJI2b7SdymbCiFM+fVFZkhJogfyk1luDNrWSIRlABr8xHGK+b2X5Xc5gmuP7X/1g0+1nETCtrU3j8pESPH4P6CZjdHLW9+FzNxxdXFlrcWVA+XSBrRD18rLfqwpLfYAVljsuc8mMh5ftKVsfUIJ3lLceKUl7KSFv8c/8v/txF3z/88zdrhA7cm5Lvf/bLSEv8wjNOwWJBQHjXyKXzk13/A4hmWQH1vmhVYPxdOJ715ii5Os7zvr5vdICDCUAzDJThuvRknIDPuEe2MtywWPebRgjdgI+7jnmuMp+1bUwCcdVHnu8VrsRr40qX5r29f6pGEBjs5BM13P7RfCLfbBZCmMpAS4a1ewZxYTGhYP7kB75ADc0QTA0LNf71qt8IOVkgOD+ih/2peKoN1VvqfuZ+w/Pqn4JBEogp8ud7JAWCxd0Q8d9kY6cUOM8ZLVs04NkSjfmcs8oilAwiydN8+ML9nN/0ame0rNrBWVab3k1TB4IlEnC7GgV1Nidi7JYwEGKWLoY35S0I0pw7fDc9lx0viGYRnqletQEq14SbhAcis9kf31aeWQC2DNPjFMNMBbDik/V+QE0AcUhVF7+8jE1N1p7KYLQObaIGiC5MPdhJDiRV9SeH3XuwT25L2bEg8cUUuYhfLTFMMRv4mACG5aT4sYv/87awpEIokBjr85FhJDLct6nUkqTJd2/409Als50o4H64LIXvXuuPKVTTkTiI2ZUnjiJjBGL1rFyYO8ytClVprqeohlrMML7r3PaCreU50K3DVkxljq6CNNlNxipz/hVx4cKAsNyJ2z8Sq5BJ+6TZq3uoPiZT2VKPn7fUyLXrsg+lpIIDkJ0IA0Y1W57Iir8FXNJaFRtHp+xJv1/HCVwazpCjrXbsEYrzCMm1lHLhbNNfQoMOaEDU22TbWl8fSuXCQFDy6zoetcYDzxH9PAjOZQWYGNggeNP3X/zVLoVQwc6gCwzQ11Hz2Bg/UOgp10UgWk+CjDtoMYt3oMlXKDWeLTDIK8sycftpAjcBuC2tLlAkcISq34dpRuYhoVlJ+gIQiKV+ma6BX/6uF/dSjEPy8R/rpXUPKFyCax2KbQoyGuXcLvlNPlV3yZN4fh3hRWdvG0qbUbwnfB/5jeSvRZBbOFF0S/a+lq2cNI06mawKtHtx82ribQk6P80Tq9TRmQlIQofQJSCswdEiRiVyklafh4sBDfnqcz2g3v3Bj8jmV10Q7ysPDzzA8qJBXQuRPVcNjOZkGAqteHkXoOdAI1B/tKxGRd2JmftDqDUn878w4c1Wekh73XLXwsyeJJKhAj5Db6AiXmb9dJ/Pz0IDudp5PyZA/3W0u6ckoESarjcQ1YbO7n3sx1fyFXMBj4eyEM6z/eEdnfArVK5w+KkI2ONfGT8Mz2CY6XzaUiOMezieVb/wtIMjv8H1cJHbt48Jd1HmWq/sc=,iv:IV/mmx+1Umf8rmuPNzwKffCD/ZRrr9uw6nEgs5uhslE=,tag:txzjiqqHxvD5QQzI19AI9A==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSTRDQmFTKzBHMzJQR0hs
            NldhU0lhTThoak9pNGJNVnU5TlJPSFZiR3pjCnQya3F0VFFkL0VxM1NXZjY1SUtZ
            NUlQc3pXSUVkM0hLRGN1MXNCeDVrd1UKLS0tIHh5aEVYVnRuWHE3SFd4eUF3REtD
            VW5FeENXUllkQ0k3UEVoUms4Ui9UbEkK3+wvle/0XEgLoHovy0fdgVhlLdETnpmI
            mpkwh7mwPT89lRlsYZMEuCFkz0HhTtWCKppJdxjk50CqLcWMux1lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:55:15Z"
    mac: ENC[AES256_GCM,data:2eEcZvU2eAIfQ3SS2doe/Z4DqTTCdJUKV/kcroj08jz7jg/F16kVcRR9cSp+h7m2wkdP/iPCPoNf7oq2JKwJ1b6wGQBUX64jKJ+b5pu81iMkbfnRcNij9gk18tGQM6mN4na9T294k3dAihM8R33/SjO/54JcucnJJGgxlZNhNeA=,iv:K0Tz3BNpPybQD4/ho+bMNuvIWHN8eIbw4T/uGfUBGfg=,tag:c7BTmdcJmlakLHq6SwwizQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grist-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/grist-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/grist-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GiHQVAF3ENXMo0p28LyMHc8VVJKoIEyV15IaeqtYHiJFlJiN8qw41gEF262qT9c=,iv:ZBBxnkxi6OtpxXXbLr2Ld60hYzGgv/ec6JdY0x3dRBg=,tag:piQLn4UzmM7s6BJ6VQ11Mg==,type:comment]
    client_secret: ENC[AES256_GCM,data:tjfrGkYn/5UYR3cpsyz/8NfKCznfoypX1nVW96L1wtTkQUe4AzWW+qMt/tw=,iv:zcOHZ9eb8/ca8Ta9ORuMaRtCpJDakUcBcto8nnQ2nCw=,tag:Lj/pcnHC2sKCjzvQlu7zuw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSTRDQmFTKzBHMzJQR0hs
            NldhU0lhTThoak9pNGJNVnU5TlJPSFZiR3pjCnQya3F0VFFkL0VxM1NXZjY1SUtZ
            NUlQc3pXSUVkM0hLRGN1MXNCeDVrd1UKLS0tIHh5aEVYVnRuWHE3SFd4eUF3REtD
            VW5FeENXUllkQ0k3UEVoUms4Ui9UbEkK3+wvle/0XEgLoHovy0fdgVhlLdETnpmI
            mpkwh7mwPT89lRlsYZMEuCFkz0HhTtWCKppJdxjk50CqLcWMux1lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:55:15Z"
    mac: ENC[AES256_GCM,data:2eEcZvU2eAIfQ3SS2doe/Z4DqTTCdJUKV/kcroj08jz7jg/F16kVcRR9cSp+h7m2wkdP/iPCPoNf7oq2JKwJ1b6wGQBUX64jKJ+b5pu81iMkbfnRcNij9gk18tGQM6mN4na9T294k3dAihM8R33/SjO/54JcucnJJGgxlZNhNeA=,iv:K0Tz3BNpPybQD4/ho+bMNuvIWHN8eIbw4T/uGfUBGfg=,tag:c7BTmdcJmlakLHq6SwwizQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
