---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8up
  namespace: controller-observability
  labels:
    # Label libre, juste pour traçabilité dans l'UI Prometheus
    app: k8up
spec:
  # Cible le Service k8up-metrics dans le namespace controller-k8up
  namespaceSelector:
    matchNames:
      - controller-k8up
  selector:
    matchLabels:
      # À adapter si le selector du svc k8up-metrics est différent.
      # Vérifier avec : kubectl -n controller-k8up get svc k8up-metrics -o yaml | grep -A3 selector
      app.kubernetes.io/name: k8up
  endpoints:
    - port: http        # nom du port défini sur le svc k8up-metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 10s