---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${TENANT}-nextcloud
resources:
  - ../../base/nextcloud/
  - ingress-aliases.yaml
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: nextcloud
  - target: 
      kind: Schedule
      name: nextcloud
    patch: |
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: nextcloud