apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:w2JfEBI=,iv:+Yg1T0TgurAy8zf8fPMNBwlnDjNRYz3kvPiQUGE5FjE=,tag:oc3xEij6XVWjJtml/f51xw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:QNzqstCR7bOjitGNjb0=,iv:R17vffxr6P4uHqas4X6sji67tQi1Byl8ARawzAxED4Y=,tag:OPnBAUIZGZJLKXRUxVTcjg==,type:str]
    mariadb-username: ENC[AES256_GCM,data:5AF3IOA18p5a,iv:O4G5G0KYFiwFRXeVLdi5GhgQaTM/9MDeLqNtFTfZ7zk=,tag:6V4z1eB5DXoJdCcAeZdMnA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:d0oDgYP/zdptEuFCe70=,iv:PCK8+5q0TTvSPvIw8qwe8Op7oRuvKvtT6UZ8jtWuIEY=,tag:yJuU+W6HhtnLJ5+jWcEOiA==,type:str]
    mariadb-database: ENC[AES256_GCM,data:qs/ToHkNoCq1QKmwfw==,iv:tERJHCKKoL/JwAsEqUzbKyLKtTdQw+tiNzVFt5zphDs=,tag:KIDn0nuhRYKg9p6tYPgyXQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQW1VYmNWRHlnQjdtU3h2
            TDRhRTAzYlJ6VVYrREVBbmg2ZWI5THNuZDB3Cko5N3FoL1d2bTFyQnB0S0JER3pQ
            cExsTkU2ck5mY1p5RGplU2M2bzVpNFEKLS0tIE1iYTZmYVdVOE1EVElyRWVnZnVP
            TnVsdVQyM2lVVXJIOWVHSk5iRkpNU0EK8kKgf31Lxl71W+slKDpaH2VuIrvstLvw
            nejyaS2gxX6Eap0akagXZLG7v6I4ex4R3CdRyCzY+jmHTqqlkF3yDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T06:49:48Z"
    mac: ENC[AES256_GCM,data:E915p4L2A04drfv6M738giVYNHpPrx7/QRZZMqraYyBIA/TxBCP0CuEto5W1LKqq+vxNFK56h51tzkQCHXZ7vybmNjJ9C7HDmYE2RW187X0XnsSLWwrxY7Mpt3eqWr6jvVLAWCBMMcNxerj0zfOOPPxwZ8IoVjPd+nR4J0cyJsY=,iv:817FlMuVo9D1oaP+1I2wwy8UljHUoC3KafvlSfoHu5g=,tag:tG9mA7fGyguC3wysBOwEfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
