apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:whh/OOA=,iv:3X6rBDPgjJHVboSavASPW1bQXboYm/6wNKSyxCEq9dY=,tag:27NUzgYYj+vrFZAAxVClOQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:VfTYtWHlUFtGJw2wOrY=,iv:80JXLiDzdj9s2yxzsnpcRMsAN477iVTgevCQcxzBLTU=,tag:hssow0RIqUvtrmgvh8APBw==,type:str]
    mariadb-username: ENC[AES256_GCM,data:Sa/CE2kxiKXH,iv:nDCBIiRvLsTeQ7kUfbma+ShuFQ4X6siDOTA+ZfhAPNU=,tag:OZp4BlT9VXdHtfBQ+ra8aw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:hID4WRxrSM1iyTSTQFs=,iv:YkBicY3Hr/yobzK3xxlpgzRvcmVc6fV5gxTYGL3FHUc=,tag:DabSvfxFHXeqNhMq8MKPEg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYTlxQjEwWlJIT0RKUitK
            OS8rQmlpU2l6Zmt3M0ZTb2k1Y2Z4QTJ1V2gwCm1FNmttUWVHZ2w2TUhGVFIvekY4
            eExyem85WjZSRngzUVQySkdRNFRXT2cKLS0tIDJvMFA5WDFaWjQ4T2lOaVlSbVEr
            eGtuMklPQld3cUJPc1ZHNUZab3dEZXMKAAVjrOk5Gd6/AGmZrfOiZj4RxWTyLLFt
            6O/aNYj9FygkPuvBvpBo6heaJCENe9FlJfvlft5FQfCezSfZqrmu0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:11:06Z"
    mac: ENC[AES256_GCM,data:0oP4Yg+5DkWXy91dioNom6anuWmrYxN8z+2dSKGiR1ty/pmsj4nm+uAydeSTjr+Sn/BVVynBVHL8p2Q3WIzygSnznolpiepIP+kD0ZIE6Sbk9dSnUsLHdogYykMqpikrBdGYp/jPDBKvtMxBE4iYBPknLSel3OYdo/iJLon97d8=,iv:48Yo/mEFFh6cZBfunzm6MnPN66wK6uDL6xInIPs1EpU=,tag:JRcwWy0TEvdPOzlRvwy1aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
