---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-redirect-root
  namespace: controller-observability
spec:
  redirectRegex:
    regex: "^(https?://[^/]+)/?$"
    replacement: "$${1}/grafana" # redirige la racine vers /grafana
    permanent: false