---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-redirect-root
  namespace: controller-observability
spec:
  redirectRegex:
    # Quand on tape exactement https://monitoring.internal.${cluster}.${service_domain} (avec ou sans / final)
    # → redirect 302 vers /grafana
    regex: "^https?://monitoring\\.internal\\.${cluster}\\.${service_domain}/?$"
    replacement: "https://monitoring.internal.${cluster}.${service_domain}/grafana"
    permanent: false