apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:QaPkvEN9sqfOUv4wtEOT7lCN,iv:g7bO22Hl5dZe/BrM8An1xtxKX+uxjVlCf4xD6yEqsZc=,tag:oUSL4/TUP1YjAq+8zbOuRA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:N3PY/b61Z4QlYP6+Nt8cww==,iv:hnq02RDMcfvT6O1QefN7IznaLVBIcKCzMhda5kO3TcY=,tag:uK5hj60S4dNqUiDEFCl8wQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:p8kG2wDnJe3mVNS8mBCDrw==,iv:cTT4zQNen5AfqUGn+LCPcs0/YY+5eZg0teBk2ygELt0=,tag:RWm7o3O6r3qJFGT9fQs2+A==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:1IWtLAgKWReBDZ88/yB9S5yVSQw=,iv:ufPvizwcJGFGemr9wfh6JfJd+f+3ZlHuF1nnE06G2WE=,tag:BeTWtOxl3yU8WEnKFphcDA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:3myeRRTSXPbuWsY+wJ+HEzRV,iv:ASgBNkZB0rHhyIfJrS0F8pPEN9ldBahULTydj2NTZ8M=,tag:Ikhi+5vwke6rr8R1tPa/sg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:n2duYaJASVKP0wRLz76pDCiQNfw=,iv:7CeWiJTNBCPogoB0DSE9u4zt52X8GnmNgoYF73nA218=,tag:uvXdBpRD6o+03bJ5i+4sVQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMUNzZ2VmakRndGZUT1lG
            K1lqUTBOTkNGMnRnZ040NUJJMFhTbEVBYVQ4ClFrUS9hUjc1RTcxVXZyQlExYks4
            dGYwdWk0eWpFTk53dERVVW1IaTE4Z1kKLS0tICtOSXU2ZVBTNC9GM1BLbWtPZmY1
            Tzd6UlJvSk51YUhBcm5NaFZXaXRwbWcKY37n3vxl72/BpHRgK+/n7rXpn/33t8rA
            go+RQGUfSS8/sBlgsOm44Lx02PZJGn+iJ0kWup/Nn+yOXGEzgxJLdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:58:03Z"
    mac: ENC[AES256_GCM,data:h/rXBGP7xGSuo5Dd1W/pAB/Uv+1oKHZFh1miZYtM9zDJawlgAtGzUkjWhI/Rp3Ed9e0mSrSuF9/lMcstFmivihHjOWG5FHmK1dj7geO6JQd6/0kLlFPlpZ+uHoUiWSWCJ0jcsRvh0WgULpSi1AsYBJDspmCKIHiSwgWoNAKmXs8=,iv:vvOp6Ojmj+RziuGP6JeHF1l00p66lhNcXcqlQrhNNnI=,tag:Wrrw+SoFn+V4qKtHcpSuzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
