apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: la-bergeronnette-wordpress-site
spec:
  values:
    wordpressUsername: la-bergeronnette
    wordpressExistingSecret: wordpress
    wordpressEmail: team@labergeronnette.org
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql-version-8-lts.controller-mysql-operator.svc.cluster.local
      port: 3306
      user: la-bergeronnette
      database: la-bergeronnette
      existingSecret: wordpress
    wordpressPlugins: []
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: longhorn
      size: 7Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: www.labergeronnette.org
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      extraTls:
        - hosts:
            - www.labergeronnette.org
          secretName: www.labergeronnette.org-tls
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    initContainers: []
    volumePermissions:
      enabled: false
      resourcesPreset: "none"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi