
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restore-runner
  namespace: ${tenant}-${application}
rules:
  - apiGroups: 
      - apps
    resources:
      - deployments
      - statefulsets
      - deployments/scale
      - statefulsets/scale
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8up.io
    resources:
      - restores
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch