apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:IzSs3pI=,iv:U2wWv0T6/Kbyk6wYQ/HjuVgmyO6zFi3YybC9JxFkZqE=,tag:Rw68QNCL7JnJEGf/pYuHRg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:bDx27dd/jWzHwYHbD4Y=,iv:VIOQiBnVUts6DOmAid/LZfMIpDyox0XkOFd9jIp6Q/M=,tag:3RfDvdyZp22wwlge05jL/A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:Jq9UgKJB9sXi6wMXLOU=,iv:xMiI1i7I7I3VJUgTCAPK2+g9KftL6pfJV+BH7DtlJX4=,tag:02UedVcFiF5fboxoF/5qHQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:R7NZh4h0L0WKLJq2898=,iv:LvDbypFpR6O5DBjVc3nre5ftHA/VMJw3CIOL/+dGZ0o=,tag:BOMxB9HZF05zpkSlg13jVQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTjJTSStVM054M0FzNEVX
            ekRxaW1XY2R2V3ZaYVpLeHRWT3NrL2FrbFRNCm40VitlRW5xS3JSV2NuVHBnYjVv
            eG4xZUo4WGVDWmdud0ZXVDg1NHdLMlUKLS0tIFo3ZUFIaTJ6dnF1SkF0K1JDY043
            MGtpMDU0SUhzZ0dZTWhwU0I3MC9JUDgKTpUxgJIiiqXB0dOkE0tlzvFSFhRozRiJ
            jIRRq7UovlaofeCyg+zac7cnSLjHaYVzDdoHWyPpEowEdJOPv9YpBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T10:58:01Z"
    mac: ENC[AES256_GCM,data:GNotgO4vhFHTWViF3EEB+WlQ3JbsrU9Fw+rtovdf4iGcKA4NcIdWcCWZWCQk02F5TFkHlbtaiwLOFDwvsEwTktlEA1NsialZPUBCCXoYMSvj1ZXfpx7nv68AERfgO5zqU8vPItGfsPZ3fBcp/2ZwSZo1AvSwcuAMIV3j0DcpCbs=,iv:axMiueMT485g8OYveQUGlGzz7Fls2xfdl+Pg48eVqQs=,tag:+jk7EWqQXQX8UHfCxUuEYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
