apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:eBck0V0=,iv:cs2RA/9US4H9L0xhMrMKoaleOF0kenHP1CTdy5Drt3U=,tag:j79MDF61KPoEJRSb/9aoRA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:IpTvcgCjllTlgRmycvA=,iv:Np5BkE/WeFBKFr0pH4WXMHX4N1rhJ7areKT/9fThpdg=,tag:Ga73yzfOsyAwLCPqinqihw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:WIQP0eRik9t1xsrjV7g=,iv:asAb2C/YlgmcQNQiEmes88hNONsgM8ASsXKzaeXOBAM=,tag:Ukl6YBjzAOqAIpWNhuJnEQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU2FRc3ZuU3d1ZWptRkpT
            bXZiUEZDNEM4K245ckI5WDRwR2c1RG5xTWw4CjRpbTR0SjlFOE9FeTBUYk8ya2wv
            R1B5N1lrTEFuWDAwWVVjTGxHemFxVEkKLS0tIFRLelVPV1l5YkVKVmpSOSt1L21q
            MG14VjBEblI4bHNMd0YwcEVaZUNFY2MK7X51E1N5QnUaVMvUx4985alRZy7dvPcO
            3OF6LpIYlUOaqVmFcumLm2Ga48sqXxW0jUuTgGQgSW4g796RDrquBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T13:14:35Z"
    mac: ENC[AES256_GCM,data:/ruH9py18b8Hm/v9iOi+s0GLbUHj6rFp5GKo3AD+IjSZb/PO8brWQrU65Y2sPzgUyaOktjRG/Pnk2NQlRfFrylfw66VuMSwbp79VR1oFrzFS+Vq53VP9ykW0rjybdYqNxybFYFZpsLpvZ9NWPKme9kaG4GW1SvkffhR4KEXrUuo=,iv:mrwd4BEoUZSGw7AwHNyy+2T2EEU+Bh37QJ8z6riRyO8=,tag:JJparNqE/49otK/qAzl36g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
