apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:2quJ3f8=,iv:CV5puY4ERXWud9XGj4OTVkcMu2gbkiUgjFBIFNbUQ1s=,tag:k8PBc1QMetcyHIbiDysXxg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:xWRslulW0unwLsT7PzA=,iv:UYJ2YREdV0+P8ZjryBHjfNP3AEvRebwXxOr0+i5pJjo=,tag:tyMsBgJOtAyQ8POfQAmfAQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:cPyMl10LQVVi6nkPJAg=,iv:C2pBQEkgsa+j9xe7jevFA82+N+ich7wsMs2GuKYXO7w=,tag:bnCAgrnRcfn0pRGgwrXI8A==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSHppWHp5NUVtTXhlTXpn
            ZzZEN0s0SXZRVG1RZ3lGc2dLZlhtRHV2Z0Q0Cm1CR3dHcS93eHBvL1ZGemdBcGRG
            c01SeDIyN2Z3SjBUVW82cTlmRHI3RDgKLS0tIDlXSG9ZTzRnZWlDVU1Eb3lxSHJX
            YkZNSTZnOEdnZFRQR1JkMzZ1bkFoVmcKGsGsrw17V9kiRSVDtJQ4SP66cqrq7H60
            MdI7rLfKlR76lJ3os3U/t82WBmSD8w3QiXkDziK9Ka1isGl5x9nwdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:06:52Z"
    mac: ENC[AES256_GCM,data:NzRm9F6t11T1HwYGnYfoC/eO+m+xpM93WT+zTL2D+XnIU33qaxZt4TXDgFUL9UQx/ONIo1BVPuyL2ZFyiWA1vrscXtDOHVC5mzZZw/sK6ixzf3h+wqpUHmR/oOsSTH3sb1a6VRRLoLGLqv1AQCKGIrKvbWF7/6+rLfzYL8jyx9M=,iv:aX1lMYkG+YMxJA6GcO/rS5dl4/Y6yRiJH1h+Ek5fT0I=,tag:oFpmZVShYFhWXCTeCGJJfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
