apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  values:
    internalDatabase:
      enabled: true
    mariadb:
      enabled: true
      auth:
        database: nextcloud
        username: nextcloud
        password: nextcloud
    persistence:
      enabled: true
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 15Gi
    nextcloud:
      username: nextcloud
      password: nextcloud
      host: nextcloud.ferme-du-jointout.localhost
      datadir: /var/www/html/data
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array(
            'trusted_domains' => ['nextcloud.ferme-du-jointout.localhost'],
            'overwrite.cli.url' => 'https://nextcloud.ferme-du-jointout.localhost',
            'overwriteprotocol' => 'https',
          );
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: mkcert
      hosts:
        - host: nextcloud.ferme-du-jointout.localhost
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nextcloud.ferme-du-jointout.localhost
          hosts:
            - nextcloud.ferme-du-jointout.localhost