apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh-credentials
    namespace: controller-external-dns
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:hSr0RUsN13Sx/Fy15A2cLQ==,iv:ntFyOUJo5FYitH4C2fQZqGKSsGG+fGv6JcLJCtai+kU=,tag:lj76xWO6MdPYSkkKMSONGw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:TyTh9heFWdImcsYYjomADzyovnh0/VQxMkG/rqLxZvQ=,iv:/W0gLSJXTgH9X9GwifMcPnjCzNsw39IWq/GO4jtcoxo=,tag:crNrDuYoMvxz/il/AHYjJA==,type:str]
    consumerKey: ENC[AES256_GCM,data:grCPtLzUoHqCTDAhT48LTU9+pNPrAP1z539Ixn19i8o=,iv:HsYO6G5HLmXjXw9JW2x15wDYxLYPjapGq1468dboLwk=,tag:HKdX0Phd/LMKYmnQS+37Pw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL2VkN1kxbzhRV0Y5bHBV
            VFd4dTFDU3ZFd2Q4bnVzRmJxSFUzV20rRG1zCmF6ZkNaRW9mQTZ6ek8ycE45eVp0
            RzRDU3Z4QnBma3dBVjk5dnhsQ2drM1UKLS0tIGN6dElwcEN3TTA3ZUlrZG44K0c1
            dkg5YVN1ZTNJVW9qb3ZaY3NoRWNiRlUK6ty6LpRBNJ5GXj7Gf57Q0vcmZrDTTg/D
            Zfn0pNWOVEwPd1QgsdNeMItvKO8fOhOAzHRyM+sSFVbc6KMmyZtO0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjUyKy9ybGZZWHo3M0pL
            em1hd0EreTQydzVXbllyVzVFdGlkSjc2bVJZCkg3SFk3YW4yYUtuVE5ERUs0ajlC
            aHE3Rnovc01XQjBSTllYRWkvOHVSTzgKLS0tIEQwcC83U2ppZHZnRzFjMElMeFlF
            TTJSS2hjMGJnS1AwTE5ZL1ZqZ0ZVZVEKrdc8vXKYsmra6YiUy1fl7QG4uxWahbeu
            yVjoeHvoeCjrMS4Yj35WNQ+h+JaAdyYwo9Wqt+Ko1xbhLLCoAzj8Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T13:32:41Z"
    mac: ENC[AES256_GCM,data:YYKXbLqQhyZq6dW3Vwf2ts4iZOtfejaz+aQHEC8TANJAxXoAipIA9JoaKB7xK6DZMduyU/Eb73sjHg1vVN4YsNFIh20sSp5hc2maeMvzHyY9mG5agiXEHU51ZqimG1/o+t/XB5o5ULJsZGILKvq3M1czTlsM9fDECa43R2M4EEQ=,iv:AWRho5Tu8hen05N7UZw9ts3K40gsAZPCcq3UORADiOk=,tag:1T0T+987rFEcPZTtSbr0TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
