apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh-credentials
    namespace: controller-external-dns
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:FU+U6FaSno3oYxIRzATzbw==,iv:W3DaOdagI9rzBqNPAEIvOjjGdK9bn6ruz2ccV4m6mJo=,tag:2hSvXLHj9D032oNMUn1MuQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:sm6N7VlxPK4Rz05i6t7JWfSwT6552iypiTZC+j1TS3w=,iv:ZbSizGli882r/xHeViMLCSVwQ04kSqhJqNe0VsArvF0=,tag:5YoEWdyhMJ0hWK69jTYHaA==,type:str]
    consumerKey: ENC[AES256_GCM,data:s1OxABdgx7v2Z+wLKVPkTkDt2WnKDI7V5aa7yTi6khY=,iv:53uLAz9oYoCOH17AKb1jm10a3X/yfmq4EZBOAI/BHek=,tag:S8l9oik7KrvBoMPQg0NPeg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRemFjRWVQQzhrNGJzSm1H
            TXBGcHpjYnZiUWtycDZwNVpnWXNZci9jL1hNClJiWnUzVEdjbFNic3B4UFJMZ1Ns
            bkhjYTNsU3R2dG9EMzNUMm9hVlFzRmsKLS0tIDdSbFV4K0JkS0hKQ2RkaXdKR1U5
            K3J1QU1xd21PYXVCUkdVcEt1dXdOWU0KfsLsXIo2IryAcGO2O4mTs+uQqa/Pzy+X
            HbZBnr6FEWrsSfz3c+iZXr3Rbq4NCNs0t88tsaW4f8A3dmnaSPCxOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWJNRWVmUlFBMGlocU5I
            WmtvbVVlLzdMRlV5aG93d3VZVi9aSnh1TnhvCjE1L1JuMlpXQ3RaU21pR1M5aGxn
            WUo3YWJUKy85WWV3T3RoZHNFa0c4OWMKLS0tIFVQSXNOUmlrNUZ5cVh5R0VTT0tG
            YUFhSFY0d3RGL05MRVlaMUlwNmp4OFkKGu3O8bsbkIy7l6VSNro1zK8kFAxNN0m1
            fVl2+oG5WXEHzuGIueqr/gwImFpIelrLp0TmcSRjsFylszG2pe0Hfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T09:53:10Z"
    mac: ENC[AES256_GCM,data:4A3BdX48iVFAJogPQ1k1eqaLQtXqAiohwnBL3Lh/ZcOKKE5k1wvFbk5OHBOZXfE1NtIFZbjaYnv+gQybuZZRW4dVG3UN866vkGdJ3Br9f0FcwfpMinahWJjGpukjzCwc0Dwt5UtO420iYdspqypeOobjCgbFDagq001yeGJRvmA=,iv:gMWXLTAtaSaXI8/gSxUDf54nf3tRyPbkKgwW6h/rHh0=,tag:/QOvvYWj6ohMD7Q24r+buw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
