apiVersion: v1
kind: Secret
metadata:
    name: neo-alterconso
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:WJLlx7neGd3gJvP4j9A=,iv:MgesIpMSYCVFFZ4oFG8i7F8BZM7YdU00Vd+562TMJ0U=,tag:kqCQ2DxfaMbI6rv9BsPR3g==,type:str]
    #ENC[AES256_GCM,data:YgBDGW4dCCgGplirQaiW2c6QGYwk,iv:+Kym75e7D3iC2EcADGjqEXjbB0lpINrF+h4AXwKXsMA=,tag:ZtdF/EnWcMwt3wLKJkSuFQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:158/AU99kDMAEPIi37rFiVxMvNlnSqHOFKtAkICHPZSzbsuonFIWAH3nSpMtJ2Q1BVvQY2d4Jsl+J2z0RUZ8aw==,iv:FTyJqqkk7HL+RzOAc92tp9twJg9zjwL7XT3XhDg6PXo=,tag:4k//+10MhvH4ehjKswrr1w==,type:str]
    #ENC[AES256_GCM,data:wEAFrgRw4qUYXBkTaGkOMTOozb1u,iv:hMEsigaoa/Cfc9KVqxTQjO5SBfYKmsWnwhbX4Tkimmw=,tag:pSx/bOPxBxCtpc2V4wIsEw==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:eEMI1hCOs3JcFKo=,iv:5gUOk7Ah7QI+hoiqRDYQMV909X93nK22MlEo9MKGps0=,tag:2w6Z+jT3F0SATpQfOIz31g==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:6fXlvFF9vR9rZ2lPIq4+pKO+F3uf+ALwSeb1Vun7+rJeJxpwWivCgnyKtVfUhxF7y6qHgvCHqwm+lPhRParEzW+JCR349GBTB8og/xR4SA/52/tksbvNXn5x,iv:Gbzjysgxe22iXx20YUnn6rQDt2Y5oryc6pdZQtUN54s=,tag:/PxCct3p5PYNdvmwStqmLg==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:qxrXTUOIvsFn/oA1v2AR228KbxNPPOesp+ez6b8G7cbuWkR4ZGmQKtWG156MvpcMdo1emlOQD+nSreiXJApF0KgONhox/oZlMfXEZkAAeMINXcdpKLyKalc=,iv:jm3j8Zuo3Aj4TG/7xvtkeR6j6VlRDZL6EgX5jBlo3ao=,tag:uHu5AHjrEX6NJmPT7zIU2g==,type:str]
    SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:UCigesujKu+D1qKHmNc=,iv:korvBjYaayMkEzG2r4PiDCE9iHBa0plI2WJjTD4w3+s=,tag:H0slfnNL5eX+UpwJqfmY8w==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVDF6UEoyME55a2Z1U2lT
            UjVmRzhaYWd1cGRIdllQU094K2kwSjdRV2tBCklQdUhOYkpaWEtrV0JZbEdhRWl5
            bHJXTVlzeWVENHZEKzlPTlovN0U1UGsKLS0tIFIyS0RvSUEwWUdaU3cvV1lYS25k
            V0sxNEJmL084bnpPTHZpQjFFNVNHcUUKh0JZa5qUzVLhFotkttag3dTBdZ6RoQEE
            o16dp+lTGQnYyMYemMGIksNawnLp3slGgvkw5Q71TyTdfP/CUPa0KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T10:11:50Z"
    mac: ENC[AES256_GCM,data:uU0RXqpwhrBwa1xZs6t/I2Os9qjP5NLZqlJRqZfWcKI9+whh+auV7t6P4pv4+21BGSntGbZ/HP5ZSBFYg2now5CF5YizPOD9cNChebWZNhz0j6VMbHLI44SQqXah6ky4RGSBdih+ZfuRK+JJFmo5d6optCdTfS64pEwJqHjCdpU=,iv:4+CMW2WMv2gJEqxIva5uxCzvoJrMXUm68XGY3EVcy+M=,tag:roL1p3lFQTpYXKTMX3VlDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
