apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    wordpress-password: ENC[AES256_GCM,data:g4tZPz+IMKIMY0Yl3lg=,iv:/UEQUd50hCKyqH4NVk7AIJq8W2vJkhzwbxYCHoltr/4=,tag:9/QD1cxRFV29iVI6Y596IQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:+Ze2eTbbEzo/Cg==,iv:tUyXlV/ox7PVw5ScaqsL0doE06RXkQhp1JSVmF1cN34=,tag:JVAA6FcGcJFZRliMifwYdg==,type:str]
    mariadb-database: ENC[AES256_GCM,data:r7P2gjsNI9QWVA==,iv:KtTKYAdcgUDz8iBagoTadIGDlzVU0h+iViMShA+dGEM=,tag:rBGKACT/5p12WjDNgEgfiQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:CioXmuc=,iv:abo3CVYQKRYDEEE2/ki8n8zyAV1ErsbEr0L1hRQ4wmk=,tag:YRgK3/xN8mVuySS5DN4Gxg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:SFsgs3X1XZfNcnyBWY0=,iv:zC/oad7DAY7dz40fJs6HjVwsBfPCR5CNBVzpdOk+mxw=,tag:HnRt7o28b8W5bSv/mAjocQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:3U9JD9E=,iv:nYIRw4LAA4GwtI4FLOyL2D5cu4aGiFjdBJyaNCpXQqQ=,tag:cWqdisX/A7f1Mksm3yO2pw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZnd2MVBVbTM4VWFqV3cx
            NEFXUm5YekFhSWtCempMRzNxazJDQ0dyWWhrCjZXczVZUEEvdUJrakR3TTBXQ3d4
            SS9lNndWMXErM0FKdjhUREUxeWVtY1kKLS0tIDRRWDZuN1loYkZyWmVPdnVoWG9a
            NE9lYmFyWkN5WFBjdDdsMlIwMlViVU0Kwhn+EkmdNlRd9GHhtqKLplnqzYMwvDi9
            vz54ZZimhPzGkTKJbXEY/kB/FSppUppQe0KwpAIsK8XoWv5I0U1wJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T09:21:58Z"
    mac: ENC[AES256_GCM,data:qsWHkTZPySoJuV1UMerHqC8CGkEWji8dgpTfKtdynywVKIV7gWbgK90haKxyjjfLIgx2KplMOCkC5s/tWslHzxt3k31hZeLM+kBKfIMixFdiDtlfEXGBagbliINevh0O4uMzUndWGbCqRrKHL5UiDqhX2sGdJx3o8rBVen0LauA=,iv:PMNXMmy0CVR9N+DJqmm9mw1rI3EEyl/O0pOPqeBrrLo=,tag:QtAbKEMVnztOq2rXnncCww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
