version: '3'

tasks:
  restic:list:
    desc: 'List restic snapshots (optional shortcut: task restic:list -- 21)'
    cmds:
      - python3 tools/scripts/restic-snapshots.py --list {{.CLI_ARGS}}
    silent: false

  restic:download:
    desc: 'Download latest restic backup to /tmp (optional shortcut: task restic:download -- 21)'
    cmds:
      - python3 tools/scripts/restic-snapshots.py --download {{.CLI_ARGS}}
    silent: false