version: '3'

includes:
  flux:
    taskfile: ./flux.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  # flux:reconcile:
  #   taskfile: ./flux/reconcile.yml
  #   vars: { CLUSTER: '{{.CLUSTER}}' }

  # flux:reset:
  #   taskfile: ./flux/reset.yml
  #   vars: { CLUSTER: '{{.CLUSTER}}' }

  database:
    taskfile: ./database.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  backup:
    taskfile: ./backup.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  restore:
    taskfile: ./restore.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  vpn:
    taskfile: ./vpn.yml
    vars: 
      CLUSTER: '{{.CLUSTER}}'
      VPN_DOMAIN: '{{.VPN_DOMAIN}}'