version: '3'

includes:
  flux:
    taskfile: ./flux.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  flux:bootstrap:
    taskfile: ./flux/bootstrap.yaml
    vars:
      CLUSTER: '{{.CLUSTER}}'
      NODE_COUNT: 1

  # flux:reset:
  #   taskfile: ./flux/reset.yml
  #   vars: { CLUSTER: '{{.CLUSTER}}' }

  database:
    taskfile: ./database.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  backup:
    taskfile: ./backup.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  restore:
    taskfile: ./restore.yml
    vars: { CLUSTER: '{{.CLUSTER}}' }

  vpn:
    taskfile: ./vpn.yml
    vars: 
      CLUSTER: '{{.CLUSTER}}'
      VPN_DOMAIN: '{{.VPN_DOMAIN}}'