version: '3'

tasks:
  vps:snapshot:
    desc: Create a VPS snapshot
    cmds:
      - task: .snapshot-vps
        vars:
          HOSTNAME: "srv1515851.hstgr.cloud"

  vps:snapshot:old-vm:
    desc: Create a VPS snapshot
    cmds:
      - task: .snapshot-vps
        vars:
          HOSTNAME: "srv521992.hstgr.cloud"

  .snapshot-vps:
    internal: true
    desc: Create a VPS snapshot
    cmds:
      - |
        echo "⚠️ Cette opération va écraser le snapshot existant."
        echo "Tapez exactement 'je confirme' pour continuer :"
        read CONFIRMATION
        if [ "$CONFIRMATION" != "je confirme" ]; then
          echo "❌ Confirmation incorrecte. Opération annulée."
          exit 1
        fi
        echo "✅ Confirmation acceptée. Création du snapshot..."
        VM_ID=$(hapi vps vm list --format json | jq -r '.[] | select(.hostname == "{{.HOSTNAME}}") | .id')
        echo ${VM_ID}
        hapi vps snapshots create ${VM_ID}
    silent: true