version: '3'

tasks:
  source:
    desc: Reconcile source flux-system
    cmds:
      - flux --context production -n flux-system reconcile source git flux-system
    silent: true

  kustomization:infrastructure:configurations:
    desc: Reconcile sources, then infrastructure-configurations
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization infrastructure-configurations
      - flux --context production -n flux-system resume kustomization infrastructure-configurations
    silent: true

  kustomization:infrastructure:controllers:
    desc: Reconcile sources, then infrastructure-controllers
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization infrastructure-controllers
      - flux --context production -n flux-system resume kustomization infrastructure-controllers
    silent: true

  kustomization:infrastructure:
    desc: Reconcile sources, then infrastructure
    cmds:
      - task: source
      - task: kustomization:infrastructure:controllers
      - task: kustomization:infrastructure:configurations
    silent: true

  kustomization:applications:
    desc: Reconcile sources, then applications
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization applications
      - flux --context production -n flux-system resume kustomization applications
    silent: true