version: '3'

tasks:
  source:
    desc: Reconcile source flux-system
    cmds:
      - flux --context production -n flux-system reconcile source git flux-system
    silent: true

  kustomization:infrastructure:configurations:
    desc: Reconcile sources, then infrastructure-configurations
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization infrastructure-configurations
      - flux --context production -n flux-system resume kustomization infrastructure-configurations
    silent: true

  kustomization:infrastructure:controllers:
    desc: Reconcile sources, then infrastructure-controllers
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization infrastructure-controllers
      - flux --context production -n flux-system resume kustomization infrastructure-controllers
    silent: true

  kustomization:infrastructure:controllers:
    desc: Reconcile sources, then infrastructure-controllers
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization infrastructure-controllers
      - flux --context production -n flux-system resume kustomization infrastructure-controllers
    silent: true

  kustomization:infrastructure:
    desc: Reconcile sources, then infrastructure
    cmds:
      - task: source
      - task: kustomization:infrastructure:controllers
      - task: kustomization:infrastructure:configurations
    silent: true

  kustomization:applications:
    desc: Reconcile sources, then applications
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization applications
      - flux --context production -n flux-system resume kustomization applications
    silent: true

  kustomization:applications:le-portail:
    desc: Reconcile sources, then applications
    cmds:
      - task reconcile:source
      - flux --context production -n flux-system suspend kustomization applications-le-portail
      - flux --context production -n flux-system resume kustomization applications-le-portail
    silent: true

  helmrelease:controllers:cert-manager:
    desc: Reconcile sources, then controller cert-manager
    cmds:
      - task reconcile:source
      - flux --context production -n controller-cert-manager suspend helmrelease cert-manager
      - flux --context production -n controller-cert-manager resume helmrelease cert-manager
    silent: true

  helmrelease:controllers:cert-manager-webhook-ovh:
    desc: Reconcile sources, then controller cert-manager-webhook-ovh
    cmds:
      - task reconcile:source
      # HelmRepositorys
      - flux --context production suspend source helm cert-manager-webhook-ovh -n controller-cert-manager
      - flux --context production resume source helm cert-manager-webhook-ovh -n controller-cert-manager
      # HelmRelease
      - flux --context production suspend helmrelease cert-manager-webhook-ovh -n controller-cert-manager
      # - kubectl delete secret -n controller-cert-manager -l owner=helm,name=cert-manager-webhook-ovh
      - flux --context production resume helmrelease cert-manager-webhook-ovh -n controller-cert-manager
    silent: true

  remove-challenges:
    desc: Remove cert-manager challenges
    cmds:
      - |
        #!/bin/bash
        kubectl get challenges -n ferme-du-jointout-nextcloud -o json | \
          jq -r '.items[] | select(.status.state == "pending") | .metadata.name' | \
          while read name; do
            echo "Suppression du challenge : $name"
            kubectl delete challenge $name -n ferme-du-jointout-nextcloud &
            kubectl patch challenge $name -n ferme-du-jointout-nextcloud \
              -p '{"metadata":{"finalizers":[]}}' --type=merge
          done
  
  helmrelease:applications:le-portail:alterconso:
    desc: Reconcile sources, then application alterconso
    cmds:
      - task reconcile:source
      - flux --context production suspend helmrelease alterconso -n le-portail-alterconso
      - flux --context production resume helmrelease alterconso -n le-portail-alterconso
    silent: true

  helmrelease:applications:le-portail:wordpress-ecolieu:
    desc: Reconcile sources, then application wordpress-ecolieu
    cmds:
      - task reconcile:source

      - flux --context production suspend helmrelease le-portail-wordpress-ecolieu -n le-portail-wordpress-ecolieu
      - flux --context production resume helmrelease le-portail-wordpress-ecolieu -n le-portail-wordpress-ecolieu
    silent: true

  helmrelease:applications:le-portail:wordpress-epilibres:
    desc: Reconcile sources, then application wordpress-epilibres
    cmds:
      - task reconcile:source
      - flux --context production reconcile source helm bitnami -n le-portail-wordpress-epilibres
      - flux --context production suspend helmrelease le-portail-wordpress-epilibres -n le-portail-wordpress-epilibres
      - flux --context production resume helmrelease le-portail-wordpress-epilibres -n le-portail-wordpress-epilibres
      - |
        kubectl annotate helmrelease le-portail-wordpress-epilibres -n le-portail-wordpress-epilibres \
          reconcile.fluxcd.io/requestedAt="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          --overwrite
    silent: true