version: '3'

tasks:
  connect:
    desc: 'Connect to the VPN (optional shortcut: task vpn:connect)'
    cmds:
      - sudo tailscale up --auth-key=$(kubectl -n controller-vpn get secret tailscale-authkey -o jsonpath='{.data.TS_AUTHKEY}' | base64 -d) --login-server=https://vpn.infra02.alter-it.eu --accept-routes --hostname=gpenaud-laptop-work
    silent: false
