---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-gaec
resources:
  - ../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-gaec
  - target:
      kind: HelmRelease
      name: le-portail-gaec
    path: values.yaml
  - target:
      kind: Namespace
      name: le-portail-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-gaec
  - target:
      kind: Schedule
      name: le-portail
    patch: |
      - op: replace
        path: /metadata/name
        value:
          name: gaec
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: gaec