
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant}-alterconso

resources:
  - ../../../../../applications/alterconso
  - ../../../../../applications/alterconso/components/backup
  - ingressroute.yaml
  - secrets.enc.yaml
  # workflows

patches:
  - target:
      kind: HelmRelease
    path: values.yaml