apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:n6dYhvWvpQhG0Ro4lh8=,iv:iMItHRiRGwC+MqumHLKyLtQgy5UpHsIf/iKd82kS+cg=,tag:cjjE9dxMuL4yv33n7wu3Kg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tLETUETb3p/6MS2Wr6080TVSb+Y7xsSJjnQGxPzeV89C+/EbhuAbLWdvnmsYogrfFTkkwMZPdLzM83zOGz3S8g==,iv:MtFrcFT1Wrl60lyxJf0LOts6fxpkXrJMbgDLdF05VFM=,tag:of9JWdYamwAGS6vaRDkZZg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:3nagMKcWeHRDq8U=,iv:zOFI2XXdbKNCR/x/AwP5pK1O/cZiGl2J50Cx5Os13tY=,tag:wpAnqVDXLN842dFbHpeG/g==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:dZj5IGUid2KkLWm4pt2wW8haWdxUR7dwbJqe4suPcHPmEyr9IPcTLWm/TvkGQj4Hk7+SAjIyKLPs8jj8IWwsvHQZxJM7+VeXQpu30mHEAmHfhjbzBeiSubfO,iv:jE/QtS1TzMypkLB3arwIegzb59H7X0GuJl2U6yIGrFc=,tag:1j0o87tUciRFW2MfnkA8Xg==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:Oo7cQyX7pjyG20q3zcZM5e0JVt7EWMtiRnxFZQzNXeewXOaVvMeEtsBy4KJCHNyqql1phGbaO9IFQ0EvGuOdJHW8ZOFNkWlaB9tvhAOf2xdg2GRUz4Xbqq0=,iv:CfBSFENPgDHdi2LoLeD8IyqqvBNAvmxdDMcyc9RC9hw=,tag:4e3HgnY6c/UrvZoBjw++vw==,type:str]
    SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:K9Dri+5dexl1JdqeMKI=,iv:gGXJVVBIPsV+g9B4KOx9TPOursPIrJjig0caZLbOR74=,tag:PfbigWB6n+38VhH3g6TVsg==,type:str]
    #ENC[AES256_GCM,data:+kWtiZZlaZ9PyQHj4o9AvDMrtNUmbFe7VOJOVwKZZsA2jeXi2K4D6EqSyiqKgcYwOs4/LM//klokvFNokxraMsWgilI=,iv:zkYFtwQvUmxj+NG0opxqnDjrJ6+7AklK3mq6x6DLf98=,tag:datf4v2WDHZKtpYaJdou+w==,type:comment]
    #ENC[AES256_GCM,data:hGo5bC03c5bGipJ7yGl7+1chpSFrGbRM+eYlgzOrnkg1Uuery5d306u0tGlrp7tAOH/jyY0DxvQHa40qHNdANT3KKeQykg==,iv:s/qQikfjHvgVrWxwiDuby4IXduTIln+pCCGc78fGKlQ=,tag:RlTrkwbkp6XYxdeCmkvPAw==,type:comment]
    #ENC[AES256_GCM,data:xVLyV0tlrm4yTOyfBhqMocekebLyo4wn4Zwex1q0+mUprVmWGQQOVuy5LfG7YF7ChQxIbB28fMjcK6a2JuRNcAX4dvat,iv:8HKKnZ0FK0pkZh9SnlprfzH93wa3d9AvHW5C2I1pfnI=,tag:hSTbrMJfdL0vwUqdB8jscA==,type:comment]
    #ENC[AES256_GCM,data:bFqbHW1JSx3QF05ldPx4dxU+Z8yr9+pvpPe2fGfWq2M+U3bK0UYYJ3yr92dwGZvgZKUwGHw5/zk2feiw/yCG83fzVxQwpPxYgLw=,iv:aPSTkMxgh/o6v3lf+BXm50/HCQKZ0OLLkCrScmnZEIY=,tag:k2Z4kZBUYfqci2qrc5wvXA==,type:comment]
    mariadb-database: ENC[AES256_GCM,data:nhM6wpMrkVT7qeXHtg==,iv:+e3BKDAWDBbjOcGbOrIicpNxU8omdAa75MxdWwvNzdc=,tag:tycyBY/bzuiu3weeJfzb1w==,type:str]
    mariadb-user: ENC[AES256_GCM,data:qRJ15s5K+dxq5Q==,iv:Okzl7Ij9BaVsI1Xf2FQrXRTonsjI+jbByoOAsaNuU1A=,tag:lepmeWeH6yk44Z6oZcw71Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:jpJRxECP2bunPYZ0b/c=,iv:Qg1H9Eh8KD0vBD0k4sJ9kFqwsoS6SRFtT4SspPDmyxQ=,tag:Pt5oVF35V8jKu0rUCLiCVw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxODE2RUdQQW95NTVMdlJu
            MlRmeFR5REtwcVUxSmhlMzhaN0N6aUdKd3p3CjJqWnNzTDI4T3Z0cWszY0J6RW9q
            NWpjM1BrSGhLajhNU1BXenR2ZzhGMlEKLS0tIHRoenNOa2I5NEphTUxwWFFPc2to
            bkp0VW9HdTV3TS8zbTVZY21FRXlQY00Ka2IERp2ZlYMGkkkgTeX+hvJkPZgIlyO9
            Sjk9ogz63BjL+hEgyqYfHdWK6h2kqCbnpJm5xqzef6FpYJ1S8eOfyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T10:38:02Z"
    mac: ENC[AES256_GCM,data:79x6YTdfZ4IZ7j+fWYCIbH5YLh3D76R0i+Ufo5I6as4Qwy+OZ4IaupWWhxFCyCjCLziJUOotvVodGrjTTSD6Mm/PEKkF0Qdn+3aPac6vM2M51u2I0kIuQ0wOwYPBxs3/2eQntg9gFa4MYESIu0VSlOTEpoQgQdeZdgeuyajK1OA=,iv:WTw8jProJtWvgsdD6dmo9/z2CX2zBUeuCWk4PAJf2bQ=,tag:lZDjYFL5xPm5yuLGyVci9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
