apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:UK8r+2PYdmb39+s2TMQ=,iv:fR6vNHi++p+c1yy+ZpSpO9S4dWFJW4f9raUtO97vpWg=,tag:9f8gDjs6EQ1Ykjb7s5earw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:SxHnSyqtIKPVvv+APvNNeSClGo/mdIjy4X7Zv+G5/sC9BosiHhvC2+9d6vwhd5yu9FT2l+nfkyY/jkipktrLIw==,iv:XTbM53sgs40OUmyN4lW6c0Sm8BtjIzmZ+Ey1g+KVQWw=,tag:nTOkSZ/dkGOfcBG5u6L+VQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:dcBOACar2uK6CVw=,iv:D4sCI5TucS8B3sxM1ZYx2hwiYD7HyuLux76a6rgodWs=,tag:D2DtUQUCVX3I5lEEiShukw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:LzGc4U+gsSrzPIsGmUSmKX8YRSutDkB9qXuKHRuRM7pAiAEoXTpBaAMXklR8C6QIy0aKmtGca/SD3Q3ETuRZVR5D/XlYnw6j/Rmkg80gD61emtiT7PR3XdvK,iv:zcwU0uUduH8Is6WjOWRTr7N2wT5ajuYWAH/RytVEDq4=,tag:lA7n6hkTisyZA3WLeFmeMQ==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:XokOLFJouyUdwBpZXe9p5arf5ZbTBqwwSQhMjODOUGOWYPUL6NMGwfTqmTU/i/9M7eNMVhiXrmIOUt8XQGs9iDMSVO6VMF459n7VKr/4tSxcHRRUqdwLasQ=,iv:URtKRROsyJif6SudIMH1ClImaRmVZZYPsXml1DgoGT8=,tag:WQUJTxZhfzqjNJ90o7kjFQ==,type:str]
    #ENC[AES256_GCM,data:bHTteUXc/ZlUSCz9JPZ8X+clqle6r8MKW7oj0xr34T9u52i6o5KS9lFbaXM6hI3C1gaqKVopbbiz0gRHEJDFWrNr2tI=,iv:pqiObw0ZDdoexuEQDsIjAEMuj539s255lxK1RRKr02c=,tag:Hu+NGAxtglOKJRXbvoD2uw==,type:comment]
    #ENC[AES256_GCM,data:HSj5VW7ZEMNvQ9r+ROB3EP1Zc5cuuDdxWBPDjkQjymoCBxr8UgZVxyotFZBNrYT+I+lVOG42NnH80J0+N91ykp0dTmDCTQ==,iv:Sleo7eb/QjseS9v6Q1PpYqgCYPYmauCFvyoQsXQNlHU=,tag:TW/YUUMuptIV2Ux3hYFG/g==,type:comment]
    #ENC[AES256_GCM,data:vGhitfDO+2uIaZf7ZcWbgMgIFHp/mkK4oNnewGA36Pw8alg8of7xNcBz/vO3mv38adR02dOBMMbo9C4uo8eR9hGzJH05,iv:nITxuUT6iAgrtAnGR2ZsSioAYwoJl1IiMaK+7X1Qehc=,tag:knPsSNXVKPu36Z49/GqqEQ==,type:comment]
    #ENC[AES256_GCM,data:e9XF6q9QMFVgR0iFgqfvSMmTjbHL8P437S8U3i5phdxCzgGuQhgAa7Xebz/q+YMRXn83aJMRBVFkud24LGNZcFniuEdLAWrYBDs=,iv:PokY5U/mFC1au0rkgsaz3wjSJP1O3NmZ1DQHwxMk7is=,tag:j9LoqeeZbyfuAUf9i8Otaw==,type:comment]
    mariadb-database: ENC[AES256_GCM,data:41LZ1ZEcI9qMNN6+Sw==,iv:h4Jx2Q2tJyc+lCQiYyioj/Hvf8sCQ8MluZcdrKvOj2Q=,tag:YEIuo05ucEh6nUKnnx5HKQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:PZ5bPdYeSnZzwQ==,iv:uagyahy39BHRhvxVhTJn07AoTzDOuJOAJapQ8yARu5E=,tag:gYq0VkjRN8NeGDlpnC7TSw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:2gYfGTgq2m3i89vRrh8=,iv:d/41+aIe6QKmPetiSYe+V2vzngctE3htvmd9ncDz6mQ=,tag:g8zzRo6lDL3u3xy3aBjg3Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cFg1VUxVdjE2RjZ6TDFW
            ZFhYanJneXZ4Tm9wTzd5UWllY3lad3Yzamc4CmZNeG5JZ0ZPTVF2Z2Z6ZDl0Y3ly
            S09Da21BbVhBQWpBNVZzR2dIVGdiamcKLS0tIGZmVmVLdTBuVThhbjF1Wk5Uc0FU
            RlRwRXVHL29NTWNjd0JwOXhNWEtVbmsKMlOn/m+eu7kSfLInj1K2Eb3+zN7beK1L
            nV9aI7skW4fznPFPHb6pKEW1vk/mRPX3YueCsUrXB5pZluB6GDCtCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T21:35:50Z"
    mac: ENC[AES256_GCM,data:MTK4mBSHw/UiqQl5rrOgVtR/pIg5qbS1wEVD/lYrBUMyYJAfFdIasrrmEz5kX0Qd/UnFyj9OXPjzu28LxQUEDMd9D+nMe44cYfW7V7MirlP57qvjqzALEXmqZy8vAPp7AGhbK6f8/AICRwdNIZXr5bRgzwTGg+v/bNuchWq4uTI=,iv:J2xGm77Vldo2J3gYbRjMNgIni+AMhk0X50+caqNNSp0=,tag:hTFIBf3lpld82T+Y8wfmZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
