apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:fhVVvY2MLLo8NzbizHI=,iv:ZnD5zfJc6rtBKKQGHwbuZBPRH3hbLE6WLf+B8Bwrpys=,tag:kmbUuj0IT3cqv+x4qsn06w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:wlAumPhrOCgfIdo9AjQ2By12O7Dh8NEzMfkEkGmYHjQpS0KAveoZwyrxY/gF7hN7R4fQ83B3UXwh0FLyiA1Rog==,iv:ZVVuJssx0uv6GGnumVeAu8cMMGntvTSpcd+DIfiRup4=,tag:k2woXdZOp2VCyQNujbqsyg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:ELuQvjPc1cfvtHE=,iv:ScwbcBi/mVt1HIu6sCFIUkXSdicAdTGsc/j97XUypc4=,tag:juIWYA9HKKcqolNl/hCecA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:DE8RDguMUbwDbEOeZzWvdymGJsScq2RIofdwc9Mmsi/cNUYvHl8/dAfGPVT7Meu2VuU1PxaVR3vGNV5kll1XjUnoGngZ/7mJZKUrxpWd1OfwNW0ieSbeVkWU,iv:ezW9Me3iWN4HyOPNZkyRGJyLR5DJ4SG6bpwgIhsh9UE=,tag:EewoVkPTB5m5rxWbZYBtkw==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:N+HvjufYVxuJsG/M22GzIxZ3ZvEui/YMQr5DWuDbfRVDVHXTlWUMYb7ahUssJX9wdNGPzjLoX7/psittfRusWVYxzQe+FFvvDaDFTEUmCRmiXIqf6xE6wT4=,iv:f26bLwagr4NTxB/5IlEwWpj5OodECQizyP9+f1tUxXI=,tag:O7B+ftyA/UYBvOzCzutroQ==,type:str]
    SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:DbhYBgrHqdXQ3zJTTYY=,iv:ZneW/NouKnxGEoprA8h1SxdJjt3XT+uuniYIkcWUHmQ=,tag:e31TpVXACFuMLB+EH/uXdg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL0ltaVFQV200dGdNWWVy
            ejBPSnZMQnJFK0xXK0FGZkZ5OG1Lc0J6ZHhvCkdPTWtBWnJsUml1NWtzQkxOaTZq
            UUU4clJwWXFWTUhtVW81OUNLZllUZEkKLS0tIDArS3ZERHBPRkV1cjl4Z3BEeHVR
            WjJ3dUtJdm43NHNwSW0yNjhvRXJEY2cKegpFoD9cbqnqM8kTh7K/PgH7qUiWfI4O
            YNBYwDecu5wygdeYZ4gXAd4Fi+iefBzH1QjBV3wpRfJ/Tt8anAfdAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T15:16:40Z"
    mac: ENC[AES256_GCM,data:sz8yJFjUS0/Rr32NNZSAUV4AdnkDi8bMSyyIdYcw60A4OTPR+Jx3CUh4wlvICcpXad1CBvVBXvWeFPeg9EiLFtAxzDkZo2zcfvqxHcjNptJSX/JS6lYdLlxnimn7p75iBE+afXfRnDvA1P4pu1ydTgaQV31JT7FFX0YzprFssQU=,iv:SuThpWwuEcA9MecrJ5obxj4zcJWn9wir8orEMhLMsaE=,tag:kuybvcoiti8UwmnXxJ2ZcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
