apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:lihgw7E=,iv:b53+FTxApe4+5dVB+kqQxg0mYzLsIvpHw3GLunciVNE=,tag:ZVxYNlpVI6jBtZ2g3IhcNA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:cSRCmyMlUC10nnVq+Rw=,iv:m8jyYZwqdet4VJwMbLd/XdBCVGhBhIGIfzQ5Bgg8Vy8=,tag:QDo4vc7IUc3plLiK5vczmw==,type:str]
    mariadb-username: ENC[AES256_GCM,data:qB/oJP8ExcDC,iv:ldWWZfzAXeRJSJ/uecX0FNWc2uAw39xuoWAPd1AwcQg=,tag:WHUgjeYjWjy+Y6QQ910WKw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:TPs13PpIA/6i43B7BdY=,iv:PL1VRzBrJI98WCtDbv6bL165/Wgwq1Eig3WjLzmpkJQ=,tag:q7T5rgSUt5TU6PpCY0sXKA==,type:str]
    mariadb-database: ENC[AES256_GCM,data:HmOVS7Y5zb9ePnxY,iv:qkyJ1P/Ze5ZZtXlvra3H4cJrjG0YOVp0ELvERnO9bI4=,tag:Zo56zNlWYtdg/Hj0BtKI1A==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a2xLUFNxU3IvOTE0bGhB
            RnM0b3FCWFFoY0o4NTRwQitYWWN4akwwbFJZCjJ6WUZyYVNOQ2NzdFFkaHJGSi9Y
            cXRFVHZwMU55NXc3am5rMVA3OGNtTzAKLS0tIEgxR1FGd0cwdlM0b1ltTVBsK2tJ
            Sk51SVdScGlMVHYycEo1THNQZ0o1ZHMK4TjLDFUr0j55m8vgF9c9uToTV69QcnQk
            +YnxqRK1VS5jY3Xs3XObvs+J8lFcZvD0tpkRxFCfl9pTuIgxTvh//Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T08:29:24Z"
    mac: ENC[AES256_GCM,data:J/f8yniYdNZ6wFPiyZ2VRA4djmylsO8r+Y38T8mF1y2Z//FfDiunfqi6/8XFuq8wjNUu/1ZUFa0JWImDuPoQBa86kLHB2EZmQSQGuajD0vnHVzRpyBp1WwrnJ8fmQI57p113N4crLrjNhyCnfZelGjWRjWXD25MHrfJ4ubAXq+s=,iv:H+7wsKRd5VD/5Gf5QtXt0xbiBWFjbtSLMMiFxI6Ml0g=,tag:Mj6EQ4PoNGFsczNNkDpveQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
