apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:r6aPMCA=,iv:8dDxI8OX9voIJpXo8yAS4CN3+ICAyhGdCf07JLh8WTk=,tag:hqzd7ExcCovnwCB/42kbdg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:TJhttg2wCyA2lZAoePE=,iv:TXzhjqx6de+SpWd19f/FIxPozm1jgWqx5jV5Q2Ozok4=,tag:GLy9t3zlgJjYXlYO2NIOVA==,type:str]
    mariadb-username: ENC[AES256_GCM,data:rsmxxQ4P1Pky,iv:C+UO30uSekAYVV1np4O3PiB5uzRCEvGDRK/j/bhtfho=,tag:t5xb0q8fQMDS7wL7c8sWZg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:mpI0vfHyqTa/EbHBaag=,iv:0+G7Q1JIiMSlb1UFI6FQZiXnEvon6kJKZF2E6OEh7pI=,tag:HMQ105Kz8fZU+xnIy4yw7g==,type:str]
    mariadb-database: ENC[AES256_GCM,data:xa2+2qpSKFwhSsY55Q==,iv:s4fZCM04W9BYE0UqDzC15Kf+HZvKN1MZpHBUCHuDn30=,tag:Dt0eVq26NHiLFnbz20hzcg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYnREVFpJQXpRSys1cTJt
            WlRnZURwaWVqcmRLM1dYdmZmNEFYNyt2ODJ3CldWZGkzd1RvU3YvZ3BhOVIzWnI4
            T3FKaElVVXJhSHZLeStVOStDVEU4Y0UKLS0tIFBFb0IrL1hxMnBwaUdpcmVLMFRP
            TjBxc3hkZzhpNnp1U1lsT3R3V0NKYWsKWSwkx+kxcLcu2hM0qs/gaVM3/NP8C0vN
            uh8KT7mzvC8PPKUi0lDQyt1qQxnxmaQCGg5RYnNFGhGn+GUExM4gDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T07:02:39Z"
    mac: ENC[AES256_GCM,data:UTUMI7BFA35fe2L1FWF3I4Ii5DiOU4t9Pz2xDuWkytiKxsgEMLZnXzX2OK0JLZODcW9HBWmV9zkOQgoHcNt3zlhEucfHZ3FoqeMQP62F1m+4Jxr/0t12DqfTK9dxuewBBSf6j8cxUj+RUa08sy3wVJ9MHkgOIG3EeSAnAKullSI=,iv:ejQg4N/siSw51HQGlPfEEX2qieic3aXN7bPmOHHAe/E=,tag:JVBu7CqNajTIQQ2YYQArZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1