
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: pre-backup
  annotations:
    k8up.io/backup: "true"
spec:
  backupCommand: >- 
    sh -c 'mariadb-dump
    --default-character-set=utf8mb4
    --single-transaction
    --hex-blob
    --quick
    --max-allowed-packet=1G
    -h mariadb.controller-database.svc.cluster.local
    -u "$DB_USER"
    -p"$DB_PASSWORD"
    "$DB_NAME"'
  fileExtension: .sql
  pod:
    spec:
      containers:
        - name: db-dump
          image: mariadb:11.4
          command: ["sleep", "infinity"]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${application}
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${application}
                  key: mariadb-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ${application}
                  key: mariadb-database