
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpn-infra01-alter-it-eu
  namespace: controller-vpn
spec:
  secretName: vpn-infra01-alter-it-eu-tls
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: vpn.infra01.alter-it.eu
  dnsNames:
    - vpn.infra01.alter-it.eu
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always