apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  # # storage controller - local-path
  # - ../../../infrastructure/storage/local-path/crds/sync.yaml
  # - ../../../infrastructure/storage/local-path/sync.yaml
  # storage controller - local-path
  - ../../../infrastructure/storage/local-path/sync.yaml
  # # databases controller - mysql operator
  # - ../../../infrastructure/database/sync.yaml
  # - ../../../infrastructure/database/clusters/high-availability/sync.yaml
  # # cni controller - cilium
  # - ../../../infrastructure/cni/cilium/sync.yaml
  # # ingress controller - traefik
  # - ../../../infrastructure/ingress/traefik/sync.yaml
  # - ../../../infrastructure/ingress/traefik/exposure/sync.yaml
  # # secrets dispatcher controller - reflector
  # - ../../../infrastructure/reflector/sync.yaml
  # # certificate controller - cert-manager
  # - ../../../infrastructure/certificate/sync.yaml
  # - ../../../infrastructure/certificate/webhooks/ovh/sync.yaml
  # - ../../../infrastructure/certificate/issuers/sync.yaml
  # - ../../../infrastructure/certificate/wildcards/sync.yaml
  # # external dns controller - external-dns
  # - ../../../infrastructure/dns/sync.yaml
  # - ../../../infrastructure/dns/crds/sync.yaml
  # - ../../../infrastructure/dns/endpoints/sync.yaml
  # # vpn controller - headscale
  # - ../../../infrastructure/vpn/sync.yaml
  # - ../../../infrastructure/vpn/exposure/sync.yaml
  # - ../../../infrastructure/vpn/subnet-router/sync.yaml
  # - ../../../workflows/vpn/sync.yaml
  # # directory controller - lldap
  # - ../../../infrastructure/directory/lldap/sync.yaml
  # - ../../../infrastructure/directory/lldap/exposure/sync.yaml
  # # authentication (SSO) controller - authelia
  # - ../../../infrastructure/authentication/authelia/sync.yaml
  # - ../../../infrastructure/authentication/authelia/exposure/sync.yaml
  # # backup controller - k8up
  # - ../../../infrastructure/backup/k8up/sync.yaml
  # # tenant controller - capsule
  # - ../../../infrastructure/tenant/sync.yaml
  # # observability controller - grafana / loki / prometheus
  # - ../../../infrastructure/observability/sync.yaml
  # - ../../../infrastructure/observability/exposure/sync.yaml
  # # workflow controller - argo workflows
  # - ../../../infrastructure/workflow/sync.yaml
  # - ../../../infrastructure/workflow/exposure/sync.yaml
