apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../infrastructure/storage/crds/sync.yaml
  - ../../../infrastructure/storage/sync.yaml
  - ../../../infrastructure/cni/cilium/sync.yaml
  - ../../../infrastructure/ingress/traefik/sync.yaml
  - ../../../infrastructure/ingress/traefik/exposure/sync.yaml
  - ../../../infrastructure/reflector/sync.yaml
  - ../../../infrastructure/certificate/sync.yaml
  - ../../../infrastructure/certificate/webhooks/ovh/sync.yaml
  - ../../../infrastructure/certificate/issuers/sync.yaml
  - ../../../infrastructure/certificate/wildcards/sync.yaml
  - ../../../infrastructure/dns/sync.yaml
  - ../../../infrastructure/dns/crds/sync.yaml
  - ../../../infrastructure/dns/endpoints/sync.yaml
  - ../../../infrastructure/vpn/sync.yaml
  - ../../../infrastructure/vpn/exposure/sync.yaml
  - ../../../infrastructure/vpn/subnet-router/sync.yaml
  - ../../../infrastructure/directory/lldap/sync.yaml
  - ../../../infrastructure/directory/lldap/exposure/sync.yaml
  - ../../../infrastructure/authentication/authelia/sync.yaml
  - ../../../infrastructure/authentication/authelia/exposure/sync.yaml
  - ../../../infrastructure/backup/k8up/sync.yaml
  - ../../../infrastructure/tenant/sync.yaml
  - ../../../infrastructure/database/sync.yaml
  - ../../../infrastructure/database/clusters/high-availability/sync.yaml
  - ../../../infrastructure/observability/sync.yaml
  - ../../../infrastructure/observability/exposure/sync.yaml
  - ../../../infrastructure/workflow/sync.yaml
  - ../../../infrastructure/workflow/exposure/sync.yaml
