---
apiVersion: v1
kind: Namespace
metadata:
  name: ${tenant}-neo-alterconso
  labels:
    alter-it.eu/tenant: "${tenant}"
    alter-it.eu/app: "neo-alterconso"
    alter-it.eu/managed-by: "fluxcd"
    reflector/k8up-credentials: "true"
    reflector/mysql-operator: "true"
    reflector-regcred: "true"