apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    wordpress-password: ENC[AES256_GCM,data:0ZhKhpat5KDIrSjduw==,iv:tgTxgUJSh0+yuxSAyfeMwNRWxGhC5voEvD0Y0EwFUPY=,tag:utKTeNJRnYI2eBOupITu8A==,type:str]
    mariadb-user: ENC[AES256_GCM,data:NqDKrx6DV1cuyhHUZsFoifE=,iv:p3kkMB3s/AyD7eFU3h94fFHuEnK/aMDQZdW5mrwhnSE=,tag:orJ5PhOtyHZAEHfYyIctNg==,type:str]
    mariadb-database: ENC[AES256_GCM,data:eifkKnZdodQvwUo=,iv:IEsrGUHLGYihM4I9toWxZApd9hUuWjwVr6srJkv/MMg=,tag:bh7B1zUVL16hhuqNizGNFA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:lkCGueraGz6vpNXDzw==,iv:ep1a79BW4uvHjJ6AHZbEsZTBMqj3MeCpfBHjg8Slzz8=,tag:yOfvZ9y11IwAj8GRKr5mBg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:QpKGPDqCZi+88xMFfA==,iv:5ZTfMc+Cfbat926lBBy1XFJws8ti9CVbYvb1oK2pwFg=,tag:xQKM7g1lIRzZLV9X68rrew==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:ChZUGpHcTEV+wAv4MA==,iv:nWW0iHnNwdFjjnmZbT7kvB25QTJ9xKZyMZxjlOpLv00=,tag:aQClCgIn6QDpukZtf2gMyw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NjRKcGFPUXVpOURON3hG
            eG5NMDBYQWtmN2Nac1FEVmZZVEhGWERWbEhvCnYvMDRWT2NpaEk2b09maStkUk1y
            S0xXcGpWbU9LY2NXWXVYcktwejJFckEKLS0tIHNRYlhQcmpoNHNlK0NkU0oyWUdP
            MXNaUWhyZENXQ0pIeUxnL3ZGR1BQKzAKjWiwU5uf/zFev4qzVwGj2xTq3ecl9TvO
            3eW+xbJaJvjEdavsOiXg0q3XbiKTO5e3TLKEPVnQZxzrgUH0T4uP/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T09:59:05Z"
    mac: ENC[AES256_GCM,data:sPw+VPIBFUM2BJQDv6VMtpXWT6GL546MF2jgjwDFV64d0CG+RzPS6oXoAmq52VSZRQRsgAwqLW95ZbxcODniTzJTtqOQb7FKuhNndnHphveIuqBsuAi05fPdmWAz+SAxEyaWYobSHY37JQrFUUR65UkxRNNtJ0DUXSGw5h6LtZs=,iv:RepLoRJRODP7YvzlGva//n2zfpz2DPKr3uKNrb8H7us=,tag:eImViyePekcvxttvhFggQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
