
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant}-grist

resources:
  - ../../../../../applications/grist
  - ../../../../../applications/grist/components/backup
  - ingressroute.yaml
  - secrets.enc.yaml
  # workflows
  - ../../../../../workflows/restore/templates/grist

patches:
  - target:
      kind: HelmRelease
    path: values.yaml