apiVersion: v1
kind: Secret
metadata:
    name: grist-basic-auth
stringData:
    auth-file: ENC[AES256_GCM,data:+jW1DEUTWntADlxxkknZUYcGyUeGx6IAo/Q64es4lk7vY5zOUeql6KSAZajfjr1C,iv:eX0kDvu+MTf6SksqEPEm4tEH79+Vspadzm/WXy/vd10=,tag:gYrKU3Zy0pEnOPfV3r6azg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3lmSjVveGNpUHFBeWtR
            bmJZT0RtSFNGQloyK0NwRG5YT2NBY05zNmxzCkFHTkRvS2plb0N3WU9YU0hNQlFp
            eGE0RHZLS3BlR0VNTzJ4cUF3U3BNTVUKLS0tIDcrWVprNUpBa0s3b0ozWDVlRDMr
            SXJRbG1OK00vTmZiUWdKMmxvLzhXM3MKEqyfS8qx7yyg13B8arYMNFuCNY4gSZzf
            /w3u+zNO8I17WfqHrGsMgNirAsA0juaUrZbrBMXero5aisUpw2gDlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T12:32:31Z"
    mac: ENC[AES256_GCM,data:+pwyrDKIAB3jtg0Ses7EUBJAJw8z5V15j2/KmhjrhnVT6YuFXdGwcJ9XZcvFMf4IPM7KnhkXDjhUsq8XQz1rZyizYBgXoy/MsMFNS26UU8e2pUp02Jt612P57bs0H0SGC5ne8UG3dM8IrJn+72BW2UwLks4Jbj0zCXEsRO4xF+4=,iv:X8aLubCJv3jcqq405YcdFS1AkuNRmAuiO74eCGCeFtA=,tag:NKfWCWnQUfNwH2uqwap60w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grist-api-key
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OA9q0FfwXarU8DTZG7vZQaVihqGYxxqZcUN6k0/ocXSRoZ7QchyM0re1SIWKRDJr8AcTS7c309RHLZxVUBXC+3yBEJcnU/hfhQ==,iv:jNHY1DFyGIdVUxCkUk8yUgtYTxSJYhcAw1219G7QaYE=,tag:foauUma2WDb0XiRCLRbN2A==,type:comment]
    #ENC[AES256_GCM,data:6oZ4zZSjkv4xJ+C/TJ8vQC8i+JlMyXlSyTQ18rq1eeLObbMelYaoDLohki1a4iaiBGj4rTWE0bK2n8aYTqHCLptE6L2ij16vr6w=,iv:UOCMrA+7eJLuqoyWmIhi4jNjHLsDTYcxwF8qV1Odzwo=,tag:VwunyXcZW/27UCHjab9Qog==,type:comment]
    #ENC[AES256_GCM,data:7/vWKGONlDTNuGRpLjd8UqlYsDnKDrjtl1nPwoKOdsOYnXbUjxLhgnUdFlUxJQ4+Iw3XBLgOZxzxtFhx6Y+uE+D4jA9hes3zM8ZknzU=,iv:3lCPaqeflcXcnnP1IwDdNjVtFYEb353RS/LXUKEh4JM=,tag:JsUdBuv3jBQwVZ4xqARtTg==,type:comment]
    #ENC[AES256_GCM,data:TthscreLae02eib+D7Vs4+3DrV1TDPPj53l5cqm+b+2vLRBY++we8N4SdPaGWYwi3Ibtjinq0cL8fgOHBv09wUCvHUHTiA==,iv:B85+/PhZsDfHRBOF8lfJkau+HCwkXBYMlyjWWsUF3x4=,tag:/KFg78D2FI9EYqI4zN6Ktw==,type:comment]
    #ENC[AES256_GCM,data:KcyoKAN9vxvT3coNud5jcXNgOr20PuwQomgFqwotKfwCHvptyPMts2xfPWYJ6ui7VHetNW6ykz+8xqzulMVjOc51zox7dAkA,iv:qhdVDEQyDwUSf+DwgCkPM6QQWOYZw/e3tAtQl5Ezo3E=,tag:N+T/O/aDoESJ4vojwJ0xig==,type:comment]
    api_key: ENC[AES256_GCM,data:IpeJe8dEcX82b1n2fkiYhB9/SkNpUSl8JcGTBNoVCMxfz2AESlkHCuP5gXLnzZz2xHAP+PI1jRYX7hoYKb53/A==,iv:alzeJ9KaEbzMMI3vXLd3hHYsvAEkeaJtTqaCrhWkvFs=,tag:T4NAV0FY4X/mH5jqM9dzCw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3lmSjVveGNpUHFBeWtR
            bmJZT0RtSFNGQloyK0NwRG5YT2NBY05zNmxzCkFHTkRvS2plb0N3WU9YU0hNQlFp
            eGE0RHZLS3BlR0VNTzJ4cUF3U3BNTVUKLS0tIDcrWVprNUpBa0s3b0ozWDVlRDMr
            SXJRbG1OK00vTmZiUWdKMmxvLzhXM3MKEqyfS8qx7yyg13B8arYMNFuCNY4gSZzf
            /w3u+zNO8I17WfqHrGsMgNirAsA0juaUrZbrBMXero5aisUpw2gDlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T12:32:31Z"
    mac: ENC[AES256_GCM,data:+pwyrDKIAB3jtg0Ses7EUBJAJw8z5V15j2/KmhjrhnVT6YuFXdGwcJ9XZcvFMf4IPM7KnhkXDjhUsq8XQz1rZyizYBgXoy/MsMFNS26UU8e2pUp02Jt612P57bs0H0SGC5ne8UG3dM8IrJn+72BW2UwLks4Jbj0zCXEsRO4xF+4=,iv:X8aLubCJv3jcqq405YcdFS1AkuNRmAuiO74eCGCeFtA=,tag:NKfWCWnQUfNwH2uqwap60w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
