
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
    k8up.io/backup: "true"
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi