apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: controller-database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/database=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/database=true
stringData:
    mariadb-root: ENC[AES256_GCM,data:Qfdi//U=,iv:YI66P6kC6LtKUX9wN/hxOhkyip5nz/K6h5FHKwQVj/g=,tag:mcuqd9it/fFYiQMhcN8YAg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZjZJUlNKRUg1VVhFcWNx
            Zk1XTEVYWWptd1R4YnpQMnpMZ0FqM2RGaEJRCnhmOW1ZTkpOdTQ1VGpWYURXL09w
            NDZxNm40ZnVpRldRZ05HNzNVa0tIbXMKLS0tIEVHY2hPaXdoS2RCS0F4MTBLeUJq
            cDBrd1VyNHpkaTBsVDMyRlZjTVR5bWMKT1d0w8e21dt0WYJ1qHLity71IyKmSn95
            HQlwwpbWVQCiIDAtqUGJdgdQZKmdEKBtRpLo8UFWSSxWYlHWjWY+Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T16:30:06Z"
    mac: ENC[AES256_GCM,data:XdlnLCONbRb26Yruclhi35ND/+hE5l07WOYSFJBIkn6fFS31UNoJzE1ugBGNFUSFswdUyX5RBITWRC64HbPvh17Hmc/uKVlMWN2MTr/0l6F4iIq8l4MzkYpkydFRNYGY65cWbPFVUMctzyZZCPm2xZ0zlVjzNV+pbKRq2cdfAHI=,iv:fC70XIpN9YYBQt0kyT5prKbTV6GlXENNukLSx7KVY/o=,tag:2LnXSo4IwKC/x4wm6HSikg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
