apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: controller-authentication
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:tkfilTeCJd4Q0kVi/dVB/w9EPjbL20Qvoo0OPRjYp2ceERYVcPDvA4SWJgU/mo3qr8sEbTHQTX0YI3bNmXwLyVGID5tm0bpeLUBFQ/+y/wff5PJdyzdaD4rK2pHSb2TZ5rbfiY2FPS2sUFMKFPnmTslDsrTkv97Bq61SbyIr5PDaI4C9PPvxyHYtXN2Rn48akrlOC5pyEboWQ/6Ok5ecSMDgwjkUHC08KoVUGUrhPLpBvuXuSESpyAGSvy06UcYgrEJOAYezhP7uxpRF3XekrSQUhdFg/b1ks+A8hxxL3X2BkQzPGLIodcSW7CYv7c+J8jSXi7jJKGm0XWSfas5oyiQGYb9CcGd62mPvG4wDO7CfDxjtZa+HWIYD9x4On36xuj8AzQVIMOIE7TEHsC1TAfgINzklDmp7hhIkQnIBMA323PX4U8JFWH1nOG4z64qB0iOIPsCt1Ri9qVjx/H8uQ4uiGrT2k7eXk0yA/vmd4ZAOakmh6vRimtijKCalbs/asB5LkKyaY2F5sua10OP7UTt1gi/tCZxUWTsgS5YPXe3Izc8T+0OIV/FtsDPCWUHBu+d0DcDavzg8oy3EfJexKUlLWx5uqjdQxNMLNCs84EQoegHTTVFWefPc+LyAwlubNaghEqd0X2KYbK0BBG8RVGmo2W0aMfUdPOBvkrAhypaPtql3UsQQhOSTPlj4zOFYXM6sPUbjfMHNMkdoYdUdSO4PYgMvo/wqnScvHpayQPUYUdU6m6kzgoUYxr5BITJIDK/peqnBYnmIhe9CY9sLwDHqy8/6iU+EGkDgGi0Nmtc69EyuhC+ZaFXcgbfFXG3kXvkFF6CTX+gLTBy2arWiQOOA2FJYVWMz1nppS58HK1CbLHLoBThOaDESoRelgs0MqGsdT/7atO4cMMze4WgxHzK4PZYFHwLpXKjNeEup3frX1m3X23tcxSrHeSAfhOqf0IHO1ovdIw7DY3Gcx6bzbO2Lzo3Md9YJ5tmq4XkZtfiAkAEbefq2B7sU9IELjBVj8tdfDnGL0eSgARSCxbMGnJoBzCknrxpJxi1K+wS/W0CXGxcPBUultEUT91u9HYi9cW/Vh1IiLZimI122xc2mYsadZJoW2trZQLjqkBH7zz5Lon12L5gpfUtTGnxK8cHh+4d5tOD1hUdi5aZ2GqKnf6fL/C9u7KGvipbhGsSVJYB3owdDQTxgzlMRSuBi6M7UmMGXJzznZHQhTnWmUR/ecpJGh4KvzvdlnuEFdPFxoDFlFCeHXFOy9gOdZyLYuGAM4YeLBchILPHp9doVZNxRpBkVjqyMWcJMigk3viLljT/awXTWSpEkzBhLCqlC40Px+27W8CP7uo/mZWmagvozrKnhIVyax3fuls+9hkyvqZdjICPVvB3r7d7FdRNuikOyD8AdtCHKehjpCMVbqUwWUQ7kj4IwQNC4Ufnb0HEHhUbmcMzzDspmCxv0QreUbmEqZ7me7vYn8QnSM5J2AD1Sq+2kQ35ylYp4BljInFAmrkZltrHORBxmWDbWrAgTj4rXQfyXqQQKiyz9qmOILLQclyzj49UzXvJL1hZNgocsJS7tYlYpSIXW0FrlaW3W3IzOUf3cYeyH7EKatnIgrRfP4eWXEYiyLwCND+RXvxjqES+QbDMr92yyr4SiPrJ+aAmyp0cBl0h25z84mmrhSfRC8uYcsuoMQKApR8C1kXuBP978db77tK5q9DfgYZzQaNG9oei6Ddcex63SPI3pa+B/lfCKS0j2NGB/3x0rUnfMmZkQUJRXpk/1NXCwewPN5TvRzrmkx0mJARCaQyj4LXsprJUMKAzOY3zauGJg37RL9/X1q/ySWiRNane0EAQTe2UhZAgdP6AhaXpxi7dFrcs9JeV8+S/i+1j1FcTVSjZnyRLJVRHY5BS/0qtZwMRrkMBq/QD+ymWvOpWFwZlF1oy7S6IFj6jM2RoWCE5292aohrgK+91oDBGyjfGNYQT22acmE9QYeRfOMNcLfnPLCGdZC8EukZhFdNqfNdiK3Ev7YMrPswPni57Qxf+e5v4fiXnB4uiYvLkCn7feND5LycgjxFRT9TNSB7Vg4qnmw960iz9VPigEfRspbgErgNOpnrodDYO8yB9RNjR5jvPuLHSemSMXMLQMzkivLUiSlmfUjI6MZsr+nIFkx0uKeQVuC0Fra88BehGwacTDOpvz80R9s6ZETeVHt4/B3khI/msgw4rdylMGUn1Ua+5j3H9pOIGSftgtZVIGGIfJJ+2iolG7Az8TV8MBTZp62b2eYyKYChZ4ya1FLlOs/35k004E11XouO6Jqxzx9av7YaCPagwpjh+E6bvKlNCdbs/yYwOPHEAn66sjIfP6ElCodbZYUPKHcrflN2nbMqpdC9BY0I7OjqbNJBi3++y/+9FuJ+B016aJ++5mpb/Q2Hc4GDHHaWjMLnvCt3eEEdaKz4yhEOgh6HOfol8cUakY1dgv5v7DnbjfXS0FpWWDPJXm66V2buKmJepx0wAYaA2F8+7pN10AbYFgv4HJP7McOnJ7QabGb4NCd+2ASNgXMdihWmuQycAH1Fc9Gvo3zi6mQntFDTP9BVhIsN1ncgtDCUoznEraBo4Xc8BkkQys+OTxx7koCsczl78EypUNIHEAEWdEwLAmAjxHlhNAkZojEtLhev62COHdZA1yN8ficmCzokDUwkVZEXHC1mC0PCI8TAVuEB5YlSTkqgXDd8YPveExh45zCjLR4cgB6G5QT4LZBElxE6u/Kph1o4rHdxx7FAbIZJ0RYsedN3LtsDSFrVTlRR3OHdK80m7NsMipQc3pKt36MhzO0P/Dq8NFRsWaDaufRF17QpB2QblDVWWGL1GPBxECgxylLnlzQSWOAV6cO4I6N6RP3p407kGCMA9eP30lb2ZcnS+SMo775AEbwKzPMXSflQZfv2ctR6Q7azXkkjOA7+mz2ABPNq1JlhxWGcfJjdNlQOFb1H6Poq6aGi3s7jTESlgzHlwQdDZfrUkQpCTd2hU=,iv:YYpAZtZi3+93aMynyZ9KgGdPzQDO94IfG7rsJ6lhAPE=,tag:Ym1QDAXrlE+74I9AaqhUlw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# clusters/<...>/authelia/ldap-bind-secret.yaml (à chiffrer SOPS)
apiVersion: v1
kind: Secret
metadata:
    name: authelia-ldap-bind
    namespace: controller-authentication
type: Opaque
stringData:
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:G8hxDuKZaqCzM1DWSWVFbkFUvyDYDrZzOVCbGRJmtrzEf13oK10YLwYX/0yBc9ld5TU0CmMrgXf6V65oRBA8lw==,iv:z07j7F7KkItVUkRoYauiQHg6/UPuHTndIkfCsFoB3L4=,tag:nJrHobbfvUfMHhNc1RAyeQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-smtp
    namespace: controller-authentication
    type: Opaque
stringData:
    #ENC[AES256_GCM,data:0fqcoiTC5o7Nr3CvDyxaYaSixd5H6jP9jfsdcBP+BAkaDd2CAttP2TDg+DhDIF0=,iv:oyxtJc3BW2onss2Ueb01QDXCZsWIKbZrAm7t3slDnfQ=,tag:3XHs1kqGySaGcvEpHBK1Sw==,type:comment]
    password.txt: ENC[AES256_GCM,data:eukwQSkrvjcudYSHXOr5AQ==,iv:drhCNB9nkFD7V8TDrw3sUNN1ZM6jUtiPhRqhte2i9Oo=,tag:GrnZG76TQfMPbq4glxLoAw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: controller-authentication
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8G3aiZ+W07vdf8pHnQGHp/iK,iv:22wGi1RDF6Jr8+AA1yPaKcrembv9fszVUa3ewncN7iY=,tag:k+4M79ce1rZTtCAP/ZDPDA==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:39vdO8ac7hJATVv1xkeiJhapZZew+Ds/mDEWPvbrzKuy0eXiDgxJq4XVlQMHfA05ALQ0iP4go4XrkrsxxUPWEwLQNK45lgtY9vcapaPNEzOZTw==,iv:ekbDzl0QKvzKGi0jBVJVyNqS9yOVLOCxwQJz3TtlPCs=,tag:PU/OpjLYDLUz3VoNuhKz2Q==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:2kbg3fzSOzcTkeOMJT2G9D9UTnQbPYA9P3HNN5jPyngSV/i/aGM6PyOQeR1wH6n1vX0r+xxBl0dCXSWL+7U2C0KecTrbJe0aL63rMFkQ,iv:19EsqkMRQRb7pGXWsFmt/NsvtdY0U7ywj+5CEhvFrKE=,tag:M9zev+fM3BwTHQA7pDRVdg==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:7Fin3ICMyU7sRe2bklKO79At/rZZUWW/gKWFWML4qU/cNtrrTYpP/UY12LxPsLm0FtRu5C2SyzmOyZ2NuyRuWr9Fm+96LQ==,iv:pshnNudkf5ZTfIH6C8xpdSTcwEB9vcDUGDMowbGOESQ=,tag:LT7x3b2J5HX8sk42hsWwpg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:ck+saB59CsKJnHjQWALgkokNVqUPoZgcSAHR8qThLQ7Y5QLy/KrgATust3kjCyZRN+9RQ7OAtK5M4YNAfu3cRTPKlwqYdPSxQj6H4pb1qZB5,iv:DRR7NL5I2kX+XLPUruL3zQjqcyKJVTXmgLzuUrEy24Q=,tag:e2ezjKm4W4z148eEMEtH1g==,type:str]
    #ENC[AES256_GCM,data:vPNE2yYAmm5sPTxxuk7cmIfb7YPzwOCXUE2pNv+kpR5yPIzvolaVVxb7DT1r3E+6shZ1mPyrwoxV,iv:OQjBZ3fZJtuW/gcUtzXp+rYJUZGTe5yms9tq9cm3buA=,tag:RYX0BhqKjrKLnlmlAhtYrQ==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:Rq1wI9LsdgWS6Sn9AHB5cUGVE3XlpRThUnXXN+RbWDMTiruiDWE6Pprs/kWPkC13smkrJtHVqQpCLJeQNmkuhaxamCePMSmouz07/PGlIoRif8xusO/KZcdDX8s3gVKSKfGFcyrOIXoKB3QUkYl2MS3wHUh12EQ5Gi+7hu11l1UVyfJ+EtIWDd8J8xNPJbbcPxQCt+OZr6m4V/xnSVUXPt5VTds8lcXmkvyTbKe9yRQsGhkNILUEpQ4YoT+z8SG+Z0LTzDk+s8a+SzcZP+0MFnF+oqpI1JPyygpnmr668WWvV00uzcKgqBzdgq2Q/Yvn0WfxXEU9fRNhydbf5+o3kqbvrdEWFk3SwrKdZSLAzVVEbj0KvgGE5ywEN02p/hwd/GTbXGAUgKxRL7F+cAlIwwPQGPYEImtj+OhfsjU3XHqpm/AkU+SoXVVrC61xZefSE9Jp6x64yypx5IJyTvXH1+fpjkq9Xof/I2dIARpXeubSY0Eii095b9Z8EKO9p9noOEInkzHPePgsAjJPhZ/UOQJB7R48FkR5H7i6/nCy4vtyZJ7M1eCwK6id7NxRrq0E0blq1Plz2ZPpNxhmiaTorV9XbJaUQ6Ia0HtA70fpYeZSAPmljd8FeBQ0626gvuwpTnKBbIp6J3AzYKG93Y5IGTfcByUXA0ctsI8cuXYlisCOSgZSjBg20MOi2f4J70bgybM+N+MObGPQJMIlX294IxwWPy97H9l3tQjEGKgribk0qolCodbQnQUiSEh95sPKnhb/brcN6L3iFpJ7GbK7Ys1/zfvsOr0WtsTrTXfU/kgP/+QrIJ0LqSAawLzQeMUc1v/y/V/LM1SRUse7owTk0T0K2M0taVU8ggahKRBg+iuPPtlT4Mlnv5DXP8eHTIESn7oBGez4sGny6DRjvUP1eWEEuoAk4/5DkMcmcDUMeNL2fHJ8k7aWjZoxjaGZBq9RxNrax/12UdXncOm2MohydA+8ct7CVDcIA35Gi+UqhxUmAcaapYohrw32rGuvUwaUC3d1JuP9tREDKloP6Ds7mm72lcrL37JuK41ovZYEekDEzFFwJRICTmKQw0U9Shx+MFmNh5+ROG3m4Nbj0exnqPIAUllUbDSCrCwxA6Kx+jpKRwe9RPmnGDdCpT+HKEWX4Hc8EMYWxpAP77OuRWZFDgtvTa6j2tdnVepmyjZKYjSUU9lHUXueWaWo5HzDpx0oOqG488i/jIWIpUvJzalaz3em/POQUmCqq5Sj/ytLpDEkSWx/mbCyMzHJUj6Vh7+do1d4pvedXLHq8scstVD64TGujCO6IDYfBMlRdh1TL8Ntm0uMpm6uw7ftw0YLe1snvYDz0vj6WHOnb/3Y/7HX9CLr1RcQPPVaQlv3vwZdfZ2La9h3pCEctoMNlBpkSCUzZsyIXS82xoxOAhoFquIpGJq67x+IPBeXthlrwXx0BeiDmcw7KhP2JUVB8/B4P2J0VtIKlNXZ6Me/u5v/IsEje5J0so3npHdSme6op3bxaepG/+tDgGaUqwrS0xQSMppk3XXkaTk2g58NanEP2LhT8mj7GQSQrSA/EwYVTdwtlt3fOggyiG15mZAwsEE/GCfrGPhsmgY4pFF1ExiXid8O1xhF2XI1gCuJNTKbnb4DJF/cXZC+xf6OzUPN3sp03oOingLFkdpj2Qt1kGMP3Ish0fD67HwlaRD6q+UTUp6PbPxMUqn2iqQeK3QcfZ6U7oxRXsB/mfzRlB7QgzD1RaE+HTqasFmaqUPjzRulyHyc0G/dJfa/DbIlFBK9sYjYMURZBENmin3Vst4SeBb383Z8BBhcSuMrYp6p4k3qO5RQdTSWBxUDBCEWn80rMA5BFzEX2v9Zm06sPqczUX34OVCS1G4SZyimrd2horlwb6pvcT2ZdbIeq8I/UZ9q8tV4JEKildVTDQOseSrZKecqL6fvB9cc7ltn6TMYHyoh5eY6J8N0V6osVVObFubMu3ihOK6wdfobN/UFFM0NaRfNTepdqfLGL510OAthQpG9t17mIY81KdNj/puU8XVVwIY2MNUaEfmFb2PsHkflX7bTz8TUCOxOD45eizelISjPThDcGsq+S1LFp/pvWjeUsHAq7ROtYae+uJ2xZgtUdgGg8ULVDBC9QOcLYTOJwa7IBoMzXHXvDCUm5oqWA3Ltxrb3oefpFlAmLQwG/U2VMfE7F/tlBeBxTNUsw+DSs5egQLif7QGx1Idck+oG3DR2Hm0QH6ilELpJjIogN6R1KmDIoDkVjz8Vxr0QwODzPRRSM4MPh1ij6i1cvAy3qGm69yF69IoKdWqkZLOafeqlO6QWuydL6ZlNHXW+FW45vQRJER6039hB3mpZE1QvmJBakMHWxvC7LtQFvngGAO2blSdifeHd8oNcxaj7umFUv+nV1Ao3vVpCy+uELdxihwnirLDR4Tl36U/DACx5rdgDiHepmDdzbi7s+IaTZKiQfFLMZRem0Qv/2Y18XPj68fWtZ3nyDZ4pyPH2OypBuvgbqtGAmhPqsj8XGJztQP6NgFXiHi8Av36BqnSDz89c8kDb5tY3o9leP542cnpkGroHKVBKAWjNiqMM+TGX2IBq99B/KEBlZcpLMqTlkVuL4+53Lm/1sDW7b8WmeSlFCZEpQO+jn7H0BAxksNxbp702jew4hjuMYrZ/KLvgAjrBF55zNh9AE9emAbM6/6LSsG/pD2GsBILaxNBRjX48nAqaqqrMGgrj/DAYV+6SA1pI7KquTCa4t1q2ZtfuuFmmvvpOxQ1VUiZbFeAQgLHz16bkOHWbZFEgsyRv6ohp4zGtz0Mdqs+HocD0AvRlGhRnmdDa+XxpR15vZHgIOL5RMcf1ugq27Ngq/S0LucPbERAW0VQpbn+eBn2N3O7Zp34YlhwnzsrtDGqJxtc1eefG3AaEH9iUj3elsIB+zwRqfdjsUJAWmCt8enj8YbLMQWwW/2mx9UMxkXJEwX3gvqnS8IBbZQc/7V59O9v8/BaCpAxRvnDvik+AqrNqp33O+Q9Ccl+N6+VFsHE9oHaMmB1MbS56/TdjjcF9KXjp8nAcgjqVy+v8qn1qvQVnhQJZ5cKaTiUz2H9+QcrVuJDhzkyMjR7J0pOu8gQEzsHiXhOnMkUYutjkN9Vne55Tr9XYNlhHoLDWpCaHIZu8h4q0aFPnvQ4aNxot3xTbaTPgQLrwsfwfI2kzKsqHwI6bCA4QRrnf6PuBCNJhUfxoNOmTIRG5kRJlWvRVs192h2Td1kX0winKiemRfYCG32JYyuOvODh2p+uQYRGrCEgNDhm4NyL4k6fVvZQww8bGdbCtVXsa3tMdRQ9l5pISGqVOJaiuoXxJk13axFvp1YOS2AuVFolbYJWDn31URL9KrePdPWiYdLFZ9EbAfqzGmSRNd7EFAubw90fBybD3AKAT855TOb9zNnUpNUlbNs6Im5hV8Tag3HA4dk/xh+bsCIpeNXeaN0OOgA0rLYOygTEHqXLC0ANuModWrw/qe6wbpjjK9LWG95XavJeFBsJfkJrChYrcghDRIbxLre86e8c+STTNvQuFSkfZyztjt/tjyFDjTAmS7At8Lx1gmbVCUrF18aQsFnpDmXkEz6+Rc3TBZ60w6g4OZNezmW6am4szlv4yZ2L6msK5Mr4vbenyl+fEey+y4LU9meUKAakYXY86yjND4NNrHX4v2I02MknIHpMfuBZdkGpxuDs0ij1L+rmQj0ZT9vRMydN/kzx5sTOZLVcUYQNuwKWXzaiUGYEyFDT5+EEXq1hl1YCr3VKOKMnyCOv5+LuJsH2bS69cG3jIGJX7eHCP4GOtrWRptLXsJ5n1/G8mxk0MKXeIax0ilBxwmwoQvVns1xl2JCUq4oMy70+UieTWnWuHraqzlqdolYZYQ3ha6vjlD909kAlnKOyH21wEs8bgs1QEUMDD+hzCvf+xrvU97s1HEQrVE9jcu087h8uWFjtYsoZ6LD0f5FYgBRDovn89JDV4dO4PoCL96Ps+1c88NVzdC4YX8KzWtGUeGLYGRmKZ51AVlnlC/N1O5beeUGtZvYFwdRACrYMHF5KnFO1Qm8zWk0Tc/uk5+zcDUR8gd1Z8Ccu0UBucrJN2pTQbpk1tN+c5ttJTr+rQzpAa1wzplWfFTW1QEWaDbXftPrmmwHXHO3Y8cuqV0gmJq+bgoXCXFOn5lP2M/3JrQ5t8lMek9jaBHW0TDYSBCypVTtrArOX8299tEN6gOzoEw0PaHBG+cTrCNc+0/JDSCmb0LXKhrZL5hWaCudxe7Z54aUzwDWxYRTAEy++GopgWgO3WlIcl/jCS0reIPXnAODlsO+nG6y+ruPyE1r0VMZ2vpUkYVWgp4vdmneXPOlWGRJLl3G9bYy8=,iv:cxNLEDgBcQXizs952NZVqvTuDx+PcFeyQXwX4mO15o4=,tag:SJWetdX4WUx3hFZboxko/g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grist-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/grist-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/grist-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:YPaDer86tm2u5aAyiMyJlrqO4hAHQJz+3g6PCb9nq7zcNRYlyuzQTM3ybvw1i7Y=,iv:QZc7xOWiKxaNZk3rtlt3ghyR6Mq/6e9fzJhg1HNWdZY=,tag:jNzTIvCVD9C3NOr5OLou+w==,type:comment]
    client_secret: ENC[AES256_GCM,data:NaBTbf32r/g6T/Ci6vrEj3WMABzaOk+DtfYLf17lnV46rAA0nlQ2Y3zM/3I=,iv:+2rcSIi4Zsx+iiLvU5IvmpBfjDAjwcwxUYA3t2kbXXg=,tag:qjK/U2pmNmHrCo5C/YENHQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-le-portail-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/dolibarr-le-portail-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/dolibarr-le-portail-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UmEnTgGx/WC81qlJFVBTR0iQ/D/uIPb4ilILEuNoEjB8TjbcddOr8d+OmmyWIB9gRJPp3YZhi8v/Kxd+SpHBBeVk2gcWUclWGBQ=,iv:LmUsM0ib9RdXKVXYpvShQ6PNkwGmPmScOZ7x1EWenRY=,tag:gl81fpEFWN2jViLvIZTerA==,type:comment]
    client_secret: ENC[AES256_GCM,data:/RZDv0NLyrRQegPay5mIAn0F4MS5nSMeWXcD9QbMwS+0FZYebVcBOcekqQVb9Onc5IP05CTSHurrBUQgFsIQRw==,iv:8/JMh37W0UEfOIU1gggVEao5uMsmE9BQT/LNIQl4l0Y=,tag:itV9hkiZzvZb+CyPYpLIhg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-le-portail-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/nextcloud-le-portail-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/nextcloud-le-portail-oidc-client-secret=true
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:3Ug6ZxEoOVfCCQXaXX0wD+DThkqBXJPE3pMbbJ3hcEH/N/9sprpwPNkc7jKGP/bCYM+CLF9eyA0Pi1XD+Cnh2Q==,iv:cyytsrK0e/Q5IGWPckat71K5mMCd3hsjqVMi0pH80fs=,tag:SbuGJlg5FeYWW5Nnj6NyRA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTi9TdS9TVCtiUUZHempG
            ZzUzb0hCQUppV3VOQ2ZlMWpFeExhcDNBT3lnCnNJd3JJTldpMkJhd2NuQkpETjVq
            dmtXa2dNV0NScEszdDkzL1daaC9zc3MKLS0tIDRZQmM5UWlVSlVqcjZ4WWR0a09y
            TFFxaXcrWDhQMkoybkJ3REd1aEpzd2cKx2I8doshQ4HN8ta356lZTsKPS+0JjNUr
            jf9Bk47Vw8zPHVDaLn25m8K/qf3THN8G/itYNKmsy3r4ACYMRoqpBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T13:40:56Z"
    mac: ENC[AES256_GCM,data:kKg7n5GJJoq7O387KuWVd1OgdinpkEoTFFiO1YRUenGpda8adEPovN0JyhmR56VTMHgdoGhXVvoJexazzIQU/fv/HrvZ1oizoAySKJV3U7Zz1c+iOJS14zDqJeqw5S8xVh4/iOnHeLwaUEFxjT1/USXiP2mjtWr0e3B8G1CPqqY=,iv:ZWKcZkU0ny+TEkSAEwP8I+DJORqN8JLMCJU6LFh6Lmo=,tag:IN9RQVZn52oiZOFQaUb4BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
