apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: controller-authentication
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:EfRo2PrcIadDDnq7v5YTDSZMlB6mR4AmaBasW1/86Mg+NeYkRpgfsj7EIQQKDakDRu7g8ActtHd+3sK9eBKX0+BOVsMVjMgrXCtBcR+M9Kx8lisZ1Z6Pt8QN6knqkNAdbbSUUDVMQswMTCXjBKGa1CUoVG0IhjP2vL+j7lads9TyKK5Wbu8/oE09cymX1FdhTjEGWK2H9WRXycAhO/Ynm/9ZHxV5XuA+eFD3pPt7GNVXaRqPZ8OqyVc1TqcEruIJGHKCOq8CoELjzQnQ8O5c14EiA/GSjD9m+Zo/ak/mA4koXhgTQuW4i99FG+GsGNiTodfnSxWjPxcbU4P36NMxxxrnPoY/F1ZzzdQCxpnTps+wJtfGCUyMV+/ndpu7MIkL4WhjVhGzjA910PWIzNhl/RVWo3kQ3W51iGAseWPRfdUiBeZ9mhP/fCPBfHSNblzbUeG/kQxGniLmU0fYvOO2Juw6J/6pd66lq2OUZh6IZWuJxaI/mJF9SV8msqlYmGQaOa5kTrPL3ITgdNDE/g2PSbwiR/1s9Bv+HXppId83p6BaFiz5MAdQ35aIXnQ9DjSjXTK2L55vKyfn6jTMxdBXUjARHxjdpE+BFYZaim6aDBbIY+HFhupiqyMN1HnIvcZja5AROcT4PHQu7yRJAkFfw83Kn0wW4d9lCoPxvhFNFTo6Yz7Wdl3i4HXLBqm6nN7mgCh93AkrZVhqpCM52nb8p24BIETefJiDEpTwtjPkt4Au9JlD/aZ7HsOqp5zIMKT+i8B+1UQND0B0BDvlzkTCScFoFG4pxj/4GMGhpQ3D4kJ6eEZQxgo2h/QJXoVbRnzYyHxOxfUMQhbU3z6fvaLbozx3SG9V4oDe6lSfLDhD2GHl0DaGO6bH2OcstVgUlPk+JOOlD/OBZ5xs6S9KmELddH3UUMX/FtoPninYgRPXvUaULCjMy/nbhGQTczCeTaKydWTFPqPT23dcPAZUkh3fXhwnl5Jrq6aZJRYbcp/iFftqfv1eFVPvh6gyWRmL0qbM+5gi+MpV0EH/0HPwiIl6Ftvrggd6jw9bkaHCWEeqG7hzyRfxsrLWZnI+RvdYzfeHTVXaiihIon2fpkpgN00BOJiBt3+Ya4XzO5LLrEfQ6EWhVZirQAx8c37F5kdbr0qB+NfJQsWo3D/pt2AOOtXSHPn3ttcjSj61BNYmk5COILAdeOgw0T4GyJiXHchIxAAkin6njM4gwv9NIGO487+pvnGS/NW15AubiknBkmm8NsmdPcM5HOjdLt1jPWgkpG+Pal+dBtBmKEnfSigbNEN1p0AHUId941908kieUlZ3iGzqvaCHNQvJf5r9hWbuTn+zjYXPlhq7GoBSnhEcnKELWB/wRRdiFknsHlNLAfnCQzsXRCOCwPx/kr7fqNaLYxhgVkbkQyJFIIktpZjQxiyYX77Sa9X8lzMFB94srsBPJGtL0xQihkWLldeUVkP4iagqwRD7Y3EUhZO7qxB+2nQUBB8QtTN3dXKQi4ECvjSEsY99ET+GpqU9zOhTH6joHNxEmEcySo6Qw2VwWxV3DYapmnaaxWwEiByLbalv4UbnbkL+5zMdqSe12GCc1+GY6uhF7150bD9ym16oQ9wTVpvt2w/HraYQaniYJUwKnK2Uj6oBpzDyz5pFkVappWz2k29/IbhvekMTblDsuEEVbSZS33xoacpF0rh3y/268c/eSfupB2JB+HESfbRAKNBh/OkzNQm4AcLnJTXVyY/qRneFteCHoBoiMN/FJ2DqyaSNZzEppAw2JjOYctsx+EwDLdvI93WmZoM9B2mzxAp+CSPIBAQDIh8Z2SyIMwbSOS6hr3enyVld1RgmgJ64R6G7GuIHoELaOVOH9iyi4FBZrTDWR/XJh+S6ec5bB12Hn967yDvqKvsgMKSqnR8+lEzncuR+bvj6DQAEa6WGhAJ74nzkAMDYtR+SHwcv+A1znHcpRqHsl5V8mqyF92d9MXjMMkYLLydlb+2P142sLyAJ6cvmKaQvQ0SSOV6/pUb4RN19niZMIkBuRHjt2fePBBpym8cFwh7/1Gu4/dlJ5lgK4Hflq2yh58XzgQHqpYKISPLr9DADHFrN0EljB4daxN2znn4X4zZOw0j64roRKEyeJ2CMuXEjwI+ajx8F+zcphgpHYfbr3g5Sd6bdXBxUpdzmXDlhxaeDmtq3g05TRrjixNHdwXa+VZBWkoJ9f/RsmMgsv2bL47apTs2IvHGNFqUAlmAoNrJehV5tBls8xEkTeuOsOKhj4IXGyjheq/LYs36z8XpDKKxpXJtW1aBs1qwLFSNa7wmhJNBkrBVkMqS2W0RMZkmDveUCnOl3wv9X5WDH4vCUj6woqLNq9Qxhd9rIaUGFqS4Wsd2UblPM2iYCl3nqj9vMPFRH58waKOwh3jQcUlYzTGG19J+G+dGrAXEMWHAMgnQH9u8rNs5fHJtewkA/ISP7woYRNG9Pdib4J2yS89M617cNNemgbWcbzAAsbSGZnsXbo7NOezs9w/tANdRonns5ZfZuvRcBRq7eqxKR1RqH/n1OH0HznQWZtMwjAa3dFut0B7y97cU5UFawBn+VSbksqd0hp5j0mM+ruDygkSG85hwtZ47MU1Y1IIuqbn+5DznaJ07iyat3+3xWS5n0OYCLi19BoYkAgSNgalr0IiLm/V3ycqfI1AsKozu7zCRf4iv9sDrZmKBMZ5GRKHdAHHa0wJMKRrmMO1ltrhwyaurrsvO+gApm245E0gH6816OYCON9URbip1Dhn6o/V2awRV+bWaU8imX17q+Wq0UhORbbYMbAb+QKDFq8TWbWRq85m6PcF3g8hosSuW8Q8NVGQanQTUFYu9HradNdkWQw9l1yQ5K+gT8mWtDiJ1KGc11ENyItQV8B8zQFekWUsx0Ai9SBvox+Fh4CYJeBDgqw9/q3WjLPDyzZWFCdeCGWNzdcrRdsR53T+501m/q8MEOIfFqUgzO8OAosP4ZpUX8RwP554qgPD2QRzRkh4Mp5ME=,iv:0bEi1Wwz8DE5kRme+gebEVc6dMvcim9a8OOHboFGr/o=,tag:I01mpbJnyieRUPEu0YodXQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# clusters/<...>/authelia/ldap-bind-secret.yaml (à chiffrer SOPS)
apiVersion: v1
kind: Secret
metadata:
    name: authelia-ldap-bind
    namespace: controller-authentication
type: Opaque
stringData:
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:8RnUTDDwGTAa2FcP86TOimElHXoMcudQPbKEnV1Kzq2+n0PZY9eELunLp0iAuVTxfMUs4wKLxc8J2wUHM9aHfQ==,iv:5dF0DFnC2o5H/ONaeG5CjrTSNyP8rZMg7XMbrzcsSwU=,tag:J5GDvvTGrRcOIvZ4EFpYmQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-smtp
    namespace: controller-authentication
    type: Opaque
stringData:
    #ENC[AES256_GCM,data:2243gOXdnqHGSG/j7ExLMdvH0uyq5uWpdlS+yfMqwUoR0uX8cTilCdWieslwmjw=,iv:DuAbsDd2jPvbSABiJoFjB86JhMjnf0VBKCSlAa9z2s4=,tag:wazTol83Fs08wkLgbxbjlg==,type:comment]
    password.txt: ENC[AES256_GCM,data:OPAuitgHh9A4Y7EKGH9HyQ==,iv:n2OxF2LmtMpyDEplKmkbQcTJYVUT7iA7oGtJE5B5sWM=,tag:lKgcbk31hp8QGW8DKeohSA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: controller-authentication
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jagOGlEQW4jpUa/DD8vZ8CqK,iv:rCx+46PKMoO1as8V7jwf/xHcZj77tVwKHM3VFheDuxk=,tag:fK5jZ3nPXC0PRYZZv1BkrA==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:yXvEFFooP+mLqC6BOsug2tIh8zJMFjnmbEkQpIlWgwjoDvevdQPscz6W2wVrNC/0tdC66eBeuwCyinN2ijvFBcZxdOvYXn0+TzqFvc9e7L9o8A==,iv:4ce/LJLgspicu+VPFrq8180M5ITxmu3re+zs9sudrS8=,tag:yzW4l7NL0ON6RM8Ju9yjnQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:oEkjWFSq1IPtB+25tX/zBMkDTUotMDC2uH2BL5Ru0OWgU9lqsH/HaUW6GPD1hVNwISL1RkzobITrhZnocwUsTVIdJP6uAAZadJzG6xSb,iv:GYBYJp2K3v/6PdAij2yJQQMgPJlrT/U9Y+lq/G8Oy14=,tag:j4ZZGwsn3e9b9zLJReHC1g==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:zH/zSTVFfUf+TCiJ/OWXpU4wW1xDDTlitGg/mhN/ykJVr5BNqw1EMwjtgnbAE5Xx7HSgnPEdGtzRyPxV7NU0jEFZLHrK0A==,iv:MdO2zwzG0ZhnuR9jCedVJfoI8T1E2tOOQnLt7ckZ6h8=,tag:PpC+ukZBqsCD6BmhfPAAnA==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:a/N3HFkp7q7VEpyScQNz5uznPYMzIWopdOE62ZOEHaReEIttraiu+jO4txdg81zf2L7zYesF+dp7L0Cn96yO4n+eqzZXjfV0s+oBfpqykxos,iv:oDtUAsypbOUuXqjDN23zBOXWFfGpZ+r7YX8cxCH3HZo=,tag:hSVTjsO7kSE5xC7C90TqAg==,type:str]
    #ENC[AES256_GCM,data:eIei0/qokvSPWi0e6B9fcqcrr88v2PhuAtX205b3P8fLpXkAyF2VjXDMfH5/LwZwxWflyBx5nVhS,iv:HGA973end56GMjYK1tldHqIgS8n1Yaq6jJLdymgrIRc=,tag:TAuhp1I88OkG7JUat8UcbQ==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:LHetbPKisTeDLlHN6GaAYgZABYHD61/R4KfUxuo7S6cPc8LYHdjQPG9euuI1Rv7q5wJ2To1eNgVS1vrrLf03vKexoy4aLkSAktJlp+klBLG8ceX8gDjnAqcCPpkF7dVt4XS7IvpgsLedFQE3NFCEDEmi1gPLqrni9VJSeYiL/+g2WYn8tGCpcRnzOoOOqBOiaCRKcv6sx7wlFxkPBuCc/oShqvh8WLX2LNYsirA7tjKuqZnKoeWQeHthiX7Qji1VMyKRk2rgHf+Pz3qzx1AgkxWcpAV43SB+UEzdG4rtkjJNcrNOb59OhNS3LqgjGk4RpNNSAGhT8V0F51QIp9z3QtVfZL5373b99Y++fEeBSe6kDfq/d811B4AHhWca1bcGF9OvRvTRd/qOHooHiM3zgCMmVZ43F3KI1xzRMH/URKzoOPkGw5U4M4X2z7lGCuGPGrMMI4fmGo910XtDtpFZ+BsJC5HI7+Y/NvmVbdK/zpSzadlrsbiOdR2uIx9/OgsD9tHmQ6E6Z7HYmNblaX35pk4lDcSf6frVCCydNKM/g1T6T4FdCyK+N+DULXQe4yToFkK3UDIvB/gvkJ/zzbwhCyYMej7+AzvyZQB/507bQCZHRWSygC8V/r7jxdujbmR9EHsbeP3xn7ynYl3jSKwy64fJOC99b8/oxPRowO40tbO/A4i1D7B6AGY6Y1PkO55aOodqaPlxqaxVnNOMXp/0/NOWdDekg8FFCAIPv/co0cMj3mko+X2xzy8grbbn+6iOoTL13DkabxLJ8Yx7G7rGyi1hKBZJi73EaHkU2S08n/5pLnuKysTxl5z7Eqdhx1apb0H8536QvwjUcI6ggfRg8CNTI00g+qMfCeJNP2EZTnYG/5bomYemDFb9As7rGYG/A9r1US0lRUdQcxitSeT1JkmxbUx+rSXsvUVwngf0rwiL2RP5FyZ2TQmMedtYlp0birn9qbdsNuJ/jsEpWYTWxKtQkoGcMqnJrxzJeQtXKOzIiiM7wogMv40Vti16jddHhiOrnzMVxFFVXw/WNPTgWJsKtqDlJM3IxPVzUMemfAVayVMoSDmjAW8gxVaQrlUS4XPbUtbHFVLotf7HIytzu186Zfe8/M76ot1ov/9IoLrqXhcHO5rl0pIscSQCBAyPn8k8jk7Xvtp4XHPcHrMy5hSnZ6Ea9BufVRGUas6K/IplDrQUCIRbfP0k0m0ajh2igNlKZua7Fy1UIASKAR2UU/eQsB75hL3eT8NCQT26rCk51LSppvuhgcXAI577YtN6rfK9JeiOYLa4MMp4fNHlwoUXA1KT+Dp0yOyUL1OAn71XanP/reMRpgVge+aahz1g9mw7D8iH5f9RW5FNxqG0lkpeYFkeNNlqS0LTIGPknCScAbEhT9KyzXjRQ3jTgY01cYrDUwCciZXak0rayI0yMEZqj7359ubWZsKTyFL2E20yFKt0d+2MWb+Ia2SnmgWZlyi7MTeb87yJrxBdAdKpwRYqKyt3hTTwYES4FxQzyxf9sA4F/OTZQF9Qn7PocGciFiuKVu2VsxIerIHMwE956tuwwSErq/tbAMfAmNQjC4dOtb5zCXfnM5bsTrIndqWRkzFTQYXumG8K4tYBINO/vfEV2A4RmhWdcS99syy7dzTuGBMLTZLScSvFI319Z/pCsMTYhsMVTlvhWkdlTcw0AsGHgDsPKtA89si3WpI7nZhPfOQKib8kc8YtBhAqqcqDNYKGHtbfKrLSdRopKjO7KZCmaVnFyH22Q2UWGVYt7VFTAxVcZE8Q1arJbiTW22Z3n4s1EyYPI/gpI80WPSrdG1IBe2Wx7CtDXq8+dT8j8MHJoG/6puaEOElci1MKuv0ytIsIkFYIn6RL8RQT7hU46tKyeoSKH2V2J6uuBgZh3fieqv/EWADG5QXrBFpdEDob+495+s8mirVdCqJPvWAwcJJA86P8ez7bsRBnAienwNdbrD1wxSfHF8KdDXBZPD4z23OP/2/eyQS6VCYkOY0VYN2CWEeyuOV+jnpVhAu7TpEfSCjkFgA7tp9s8ngrrf5dfrNfndplDFK/cGOuvXCHpNdiQ7hbR81pEnk0ukpal9BkaIG7lpDLIh8373S3nTgAEIz0NiShZisag8jYxJvfYqv9FHJWmaCFxYlO2/D8QZsjfazWH9XvIHva1Ql+fp4MMgz494hXVRzr/f1bl1vsxnpAcKjUI+lY/fZku460QwX+/9aXoPYRd2PYt89NpXQmenLTZvF2jg+Fdu0SNKGDv/tpEMnG+Kthp+IcJtOvwMN4Q3VJKoTYXXh0Rc8WveTBr5LYaMy41bKcfRHoT2riqgZeLg0XVkzZOyb3JLgHsAeZx0gG0CtvEVSSolqi/q38AgiXahfXcFZsqYhmPuPNCqVvumnIFagEPH+BE2VIGcAWju0JoggTMgHfSQncWTJbfnxaaV2udORcPaLbml9RO7XCwxfjnXLmpU4qqG0yKYf8HO2JBKM3NlFU6tziwoYBqLNeMDModxwqnYzyqnWRantaryOTjZ86jGyvyy55xeyr23ssWdAPX3VNsGw5DhrF8u0LOz2HdFxd/XaQaKVecOF4LHcnjnnvXy+Fgvz19I8UC5r5+WBgwVyTlNeKEjs/JlVch8VTlJm9IFpULvK00CvUjsnNSy609cJNV6+4B7qDQ9JvIQY3MpQsjW+rpSsS7mBZAxZDAal6wgJ1KCSrTRHRyivOGWzNrqlxeMi565H8Fh8WkmNgSFWo1FQjTHCbC/JEtpMtmmBMri0vzCsp9iDqw5UZr0i3euJT4PFRbJJTrVrWkT0L+pJMIZizQSR6onznbN9JajtVjqaBhNmOStD/i0h6+uNFOvdCbh6dNNbDsQjCVQB1F/ETM0TzVQpdTWsPtMPzFZGp9t7GiDi4wc8kKGRwdcara8hR2BALFl/N+XBUSQr913gjQDutwZd61KV4NTn/qkU+/ra/cOtDVJqxLypKr8pVpFxLPEbYf7caE+77zTcf5EBchXLdldMcqZNncbQuHddzcVonO3b3i3G2wV/06m1s2W5AI1yalOgZ9bqpG9lpAe5YxgWBv37T86lfp+C9+ib5xmgq8ppXPprVISFzzAVXfJPUqZ1i3ODmrEo2T02EVC90UpYUwDYzjWlhNoe2QaGElu1sMDaieGG+2/lSECpum3cwI69AmCvkY6EyflfW8Ag9qO28zLvZd09MzzqAVx1YdenLsN+hH3xGx+OacH4pqz85gIWSg3SDpnwEcuIVBiNhkukeoWiC0t/CAbL4ArIfdbfKgOPnXN82s7guEfpdF9PHAnExqhYyWsM+NFaVeIZfhRcrkt19B/N7sZtO4QiVwlUDaSR6Xab4Zi+I97De8col7lx7iq6P5RdNOW83yrAkEeJg94omrs2CD3Aq82u0KEM7y2KQ8jmJr2a8OplK7cR7kWJsyXt7yrVHN3x2KPEopo5PoJaSdnQo/l9Ybp7iPvrtCuzNPzH8z9YW/D5OFkHuRAWLs5EYuDfWljhLTwUT1PqQq/9emed77J54GsIx4FS7bEQqhmtQDhcD8Pf/DiyIUJIeezaC9eshtjsGu2r1RXbFRjTcrkcn+6HacRBffGzEjn8rb6Oy0CwogUPl9uf993S4ybPUZKg6+gPCzRunZ+i0t7arYiB49TNp8nGGljD1aTQWL7C1LIRCmUjRe8DoNTcZTN0MYkbJPHHVpD/xkSTO1C8Qco2zJSoKNz1MqHh/iecLIaLRJ7iA48XtH+n8hdJ7CBMLC/JzrFR3HthWuOnrtqm+ARIsseyB/pv1kb9ZoEgcCQWxelstgw1XfczSaQmtgSqNAdZ6rCoQENxv7mXS6+M9IBFtkJfIUJzB8viAuA9P39IS+4vpDmUXsCjspQkLTkvNbpHyqFDtWmypu2yIgHKj7zVtTFfMRXoqcpLif+DpL8ynwjN3xQE2yU+XEiIEwIfhBeaY8ms//BJGzWfYufh+aWV0eXhlIIfhV5UKQjm5QFADQyS1kBrgtb/DtmBnVWm6+E3aq8yGY3QPYtSaHwAluddU08+hmQATb+FA3+KzmGL8NG0Mmq+Aerm6+/H+/LUTjgGGF2YqF0pXLJSsueVPvXJAdRSeSlKGCbXJe1dB4C51MkD/RYfnRibBAfUPfh/F489tUwJGZivM4e2sNEx8vZ4GbYNkXU09MNtzxUzj4z5XOGsMV0j8cq8n2syVomoArozDIcyJCLFqZmIuXdECUhxIDeJAMLv+BiIn2Jtl8v/KvPniUY5frHRW4i1g0xOv2SHZkropzJlcCYCHeFSTK2zcOEvJAzBz0wW3i3t9Dp+I1/70FsddBXgSkDlj/+Tw5pNVgMpXAuT4TXSFksHJBKDzyqwYkOA=,iv:wvIAemamPSOFzIAPAdU7CLD67VDWxpOFc9HBgfkSuh4=,tag:vnMQGU7wUsVeuGuhlHo7zg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grist-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/grist-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/grist-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:62D+WN4bct+mZUqvI/Y6MmeYYqaDxazE7KiPZhYiCyKQN2IqRo/fK5xfrSiaPy4=,iv:Owe/loFBGECNjjmAT89XRFDIXORWweb58zXhApKoDyA=,tag:toxGjYr0HEQrhfPASdIxqw==,type:comment]
    client_secret: ENC[AES256_GCM,data:T26CIh9SVqAIRBlICmMnJSXJPR4PTYr19150VT8/jZ+AWtmlKRoGgg4iNe8=,iv:t/5OE+AxTWFlT7S8iKzxb8sXIrXvjDB6QKCUP45/Jmo=,tag:TyjVhlcL4StN+9ECQ4GUbw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-le-portail-oidc-client-secret
    namespace: controller-authentication
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/dolibarr-le-portail-oidc-client-secret=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/dolibarr-le-portail-oidc-client-secret=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:g75CZWGZbgLXW+bsi5pYwNxedK+4S3PKqVZtKY7wncCXvHVrSQo+6cTXW6/0tuhuV2xQNcIjF9qrCsrMmhLG5/c214AFYH0CLec=,iv:5jgV2YwgENVJXjBYMAogtKnEJP373LsZdI2KIQ1dh9I=,tag:lh25rPYtpF8g/tQEUUh+ng==,type:comment]
    client_secret: ENC[AES256_GCM,data:hMlM6HI3HcJcC9g+Xgm0oXgm98vK4SC2C97Z91q4KgZlkJZLe1gVceNZcFmAt3J3q3Eg6Uxrke2Qg9uFJbOvGg==,iv:Pq+7TR7joNauongZNxmWiwefkTEWrrZLgbpZADFQHNE=,tag:XEWDiPzj9lDsWGNXveZ9pg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVJPcmNIaWxmejZ4M1NH
            aVlwdUZhSFRTNlgwU2pOS0VsMEJ5VXVCNXkwCnJ3UVF4ODZycU1UbnlqNTV0UVFX
            OHYzWG5hZ1NINTM2QW5RMlNMUHlReUEKLS0tIHJ1SGpLOWlpS0Q0OGJ1TEpyUW9L
            enlKQ3kvTXZIbjQxUXVLTGM3L1lUcW8KO315Ts6kDBHAuyCHNSo0C0eq/gW+nEaZ
            V8E36IKqJ1pTRfiuhtWfMCIF9Z2fGD+/r/FQOR/CMt/vXgGTKeSkUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:01:27Z"
    mac: ENC[AES256_GCM,data:FkkHP/a0SgBTvKcQfG3cqlYVnINVxPwC1li7POEoimA6QBmQEykGu4fymfobHfnAod4egpPMTm5v0ffa6vawydrvPxqawld58CFR9K2ogfAqVaYChPuz3QxblBQp6agLngEf5nAYQTT83HNdyNb89S016CcIsKhvvw93CmEmxMU=,iv:xcduul8y0tFXmA9ddaYw6rBMkwkkBdATnyFADCX55Vw=,tag:tvW/OVCbMZuKQCNLVe+H1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
