apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:kpWG+1c4D4MGgQQhdfA=,iv:lZu+4LHE0jpLyM0ZuVWBATEqmbKWNUlGI18kW/omP38=,tag:4czakaLD7k/GM4ETbe4vQA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:RXmv6DA=,iv:6DlytKbScVUOc1JFCkupLip5b6cAYoPPxh43fdZGRQ0=,tag:Tn4nPxkf504k2WQ0XsacsA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:+Ee0eSLTn97NUA/yQVw=,iv:HSYA1Nq+g7BsV1kKN6l8uTTaljFrh/KhBv4A/yt8IgE=,tag:j8NRKtjlBNxrxcRmi6gXLQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:PJ2R89s=,iv:twVsj5tlRsoSXFXJPMWOcoIk7pb9lJTtzXnDD0h3WfA=,tag:j+O8AQ5VDZq5WnM/bgf8JA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YlpFUzdBKzFQZnhmdlhp
            WU02aXFWd2g1bVMzcTM2Y2dFYmdydXlEVEZJCmJyR25OdDZ6VkRJa3dGV1F4OXIr
            UlBnbHlWTGQrS25rOE9uSEd3QTN3bzQKLS0tIFcrVm9qV2tPQTB3dm93Nkp2bllp
            bTlQdHMvNk5LSU90UWIzcVltbWFlMEkKJO7hmGCI7woPpphnS/ALGQxo6GjTpGhu
            JGY2gq4/6AjY3byb9DHtH9IGcDn9cWwo+eTi71+DHSJc4fMKwpKlSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T16:25:58Z"
    mac: ENC[AES256_GCM,data:UPUTYXaOStzxTILRZPLSgtdJ+pGHCsnWwrDmzF2qZrpljUxE6hnlMlRzgyq0wvdCK0ej9n5A5YjpnocLGRSeGyoTGgqcGmViYTsg7MrkiPnwvIpjCO0UDlaMDXforkmC1nEbnFl/i9IrTlv9ERpAei7NomljbDh38+DRKYBVgpE=,iv:Vx9Sd4oPAQ6uLJ44AOe43vesYou4ZV6W4N7B1qqlxt4=,tag:3pPUt6hByS3Bfiilnr36zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
