apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-user: ENC[AES256_GCM,data:cGeSpAJX7zJHiQ==,iv:eihj0NQtRPJN7qCBhz+eRBSbsR0+c28p4ZZVNrobwL4=,tag:lU9GiLgxnY7H7CSRevmR1A==,type:str]
    wordpress-password: ENC[AES256_GCM,data:tn6l0X4Ac6e/Gh2EopQ=,iv:33HlEpqneqKj+n1RWhJuRiAnyjvKLyb8Rh0S3//tr/o=,tag:Bru3mbOiTVq5t/+apZtHwQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:Wj6PCn+o2LlrQw==,iv:gv2C/ZNXYEPCl6IlJyEuIkIpc1lxdBjrBlB3AmoVMro=,tag:zgK+e9L9U58DMP8ZSPyIiA==,type:str]
    mariadb-database: ENC[AES256_GCM,data:5gJuy1y9RiIA9Q==,iv:v42N60dUz1W6iUPWyTgdSdvJc9E5HjjP1rWnr7dcM/U=,tag:0YTNtTqsRdVFthA3lOzLEA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:KPNWzrA=,iv:0B8JWj1A02uaOEYZoByez9pg/BEBQ695RPBLw2QkeiM=,tag:IkROBsdm5+PCNa8eeKfZKg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:6acoznumJGqQBsv6RgU=,iv:0iqmGOWcs4iLW1xHRFVoHmGsr6hZcmDmPJwqHa2InSk=,tag:1HMMTVXu+m2jki6nxStFJw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:U3Np+z0=,iv:LdOfvUmIJr6pcg58YeCQOy8e6Nsk/yi45Qnlf/xRbkI=,tag:6Xc2PEN2A0phO2qF0WQyag==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UjZQREdRcHV2ZGdhQ1FQ
            Z0Y3UFlFS3pHOWsxekprUVkzRlNDV3hXS0hBCnYzZW5PMXVNSWM5clhNZHRRcDFJ
            NjRRb2tOc2V6WHFlZVBoZ2l6NmdBeDgKLS0tIEZWb2Zlemw1b1lsbnMxV3hsNzF2
            VThmRVovS240STVIVUtyeGgyN3ZyNDQKjLAC5TmGiPTeqOpC3zdKYW6KJDqQ7Ka8
            5OiNdsRZizwjmQX31qU9WlOEArj/lCY+oJYdGN3WW4wSKnil1d4g+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T14:33:04Z"
    mac: ENC[AES256_GCM,data:imPJdlzb+IGUL9ATpnLE3OHz3Kri1gCAT7BgvzNQj3f8Nx8yxQ7F8eFG+8tzm905bSNSA2NS6tnlP4ud2NRgNfMWgmrf8Gi2KtNY9nkAiHGOXrq/2rEKwHSzgP05DV2gxIKg66Je1CZW2nYhJk4GwQ8T2l5IOcJwQVVfiwExyeA=,iv:9+r3QMvENOIjzwfPkdX2pL4eD2/ZkInLxMwQbKstFnM=,tag:sEOct1ATXTZVJneAFIdfmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
