apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-user: ENC[AES256_GCM,data:OsDcYWF5HN7vaw==,iv:YYJIijEd1Pj+bxzj5BTT3Px5P4PY9n4cjCabCzuFhJI=,tag:cNJPp/+2vUiKo+APyA8p2Q==,type:str]
    wordpress-password: ENC[AES256_GCM,data:TH+UM0XfYif+KxEpOGk=,iv:0/D3ndJTEPrgO8RUEiAB3m9AvCICcqTquyems5keDpI=,tag:zZBEzijsMYhpViGtKrWHWw==,type:str]
    mariadb-user: ENC[AES256_GCM,data:N2TiR1K+gBKnbw==,iv:aXk+Yt3c27+jmOBe6GQyTsvX44hRBKVak+mvfuy75go=,tag:e7ckdzaXbRvdDT9GO7+mEQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:YEQhTugmk1ve4w==,iv:Oi3+saDvQMIti13SE0S6a0ofLOjJJX3wzxlu6g8LTDE=,tag:aGvM98A448lbz2ay0T6hPg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:AhTymyE=,iv:faONc7kN04UnoJBghb/MFOPrkxWTl/QUYRhbHsB4rVE=,tag:e2jLLpJedkgc2no18BBWwA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:4yQSumRJ7WZMk+KzGZI=,iv:VElFQAikGLDxkCXpP81L1JRTW4FPEWlzTdaBI7kwHcc=,tag:8fZc01rZFMBbbTjCRcZ+cg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:mMLWBqk=,iv:7bqTI3NvPgQGH0JSRapDdjTZZua4UXfVb+o3LJRnXtA=,tag:Ukl/bY3fF2sqvpFOEiltlw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUlJvMVUrb0JIN0JOUkF5
            b1AwbWFBdUN3S1orY0ZiM2dIdDg1Z29KdmhvCjNiUFJ1K3J6OWVhWm5JY28zelZq
            aGdwN2JneXFsTElvR2xyWThwcTF6dzgKLS0tIFZncjk1NDY4OFRGeitwbUdpcUlr
            bVR1R2hOekIzQVhjRk9GWDVUcDU5dUkKN4P2XiZdPxK+x3ohOeGr35b+XdE/WbnP
            sTzExpWF6Rt4E79rJ/W7ZMM0RVFDhwM/gbvvP2tDdw7KjwRO72/CHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T13:15:33Z"
    mac: ENC[AES256_GCM,data:YukMmB7oXakzQTblWXvlYF2a+AzR2Wf5J4Sd3p44mmKAYxEGJaM861Pr/F+M06DUXzlQvij4yhKp0n2d+p+z8D1JhOVmmLYUePEfTPJ+R6yL0kwdz1cmpnuZkTBa/H5VpQKPJErpACgecAorKmPsKfHbXgiNenJLFYeUaXfP3ts=,iv:QcRmsnzyTizVI9DTtVUKXagY4tOTBbdXerw9NJhnTpw=,tag:0wAPJKlHjUtUDUs61KL/tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
