
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: le-portail-subdomain
  namespace: controller-dns
spec:
  endpoints:
    - dnsName: ${domain}
      recordType: CNAME
      targets:
        - "${cluster_endpoint_ip}"
      recordTTL: 30