---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ferme-du-jointout-wordpress-site
resources:
  - ../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: ferme-du-jointout-wordpress-site
  - target:
      kind: HelmRelease
      name: ferme-du-jointout-wordpress-site
    path: values.yaml
  - target:
      kind: Namespace
      name: ferme-du-jointout-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: ferme-du-jointout-wordpress-site
  - target:
      kind: Schedule
      name: ferme-du-jointout
    patch: |
      - op: replace
        path: /metadata/name
        value:
          name: wordpress-site
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: wordpress-site