apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:W693gC1c3rMhJFqbUQ==,iv:bk7U4fzRe0Q6TdzXHh10tSsdRtd2ptctdiidmjWq6Y8=,tag:q73yp4hMSXbB5P2R8EjC4A==,type:str]
    mariadb-user: ENC[AES256_GCM,data:lqO11I4hpt9bKdrRNds6uc4=,iv:fp9AQuzHKuzXcQxdcKeIOwT3RgKy+qY+hJCfTuRMHdg=,tag:/obOGxJMg1hI0AeZ9OnHUQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:234KN+F+GWma0UU=,iv:vEtQIXxbi+KkLjGwGuRQjs1j8gEDXjlHEyUrCeq0Ehs=,tag:5GAQUGPmrTRSLg0kheK55g==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:UAn+8K8meIu4gP/5yQ==,iv:tzq5Pz5xzfnGtqbEJ9fVFw3jjPt8KjLEAyV56z4gXRk=,tag:QtT7OH5/WDhnwDxkqZqmbQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:OVtH/rYyW652cThdbg==,iv:ZqQizajs7ctmTe7FpzIZ35kpevSWOou7NZnseI6eoXU=,tag:tHDltD452r7EZNasdWNWVA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:nGoP4hULx9jT59zb0Q==,iv:H8f2gT0GscP0ui3Pyy/gCF9MR4mcGnU3bldd7V/uV1I=,tag:9GHUSzwaUn+zfLOK/e6HlA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRWZ5VWpIQk5wdmdkeVhR
            QkU2RVROZUswbmVmbDdJRFYvTkVJSUgyMFNBClBWMXdsRkt5Zy9oK2UzZXJQa0lZ
            QWFSeE5QZGF2S2dSNnhOSWRaMVNweG8KLS0tIGNCelpRMGg2S0NFVWd4R2NzQSto
            eFRBSG5OU24wbkEvYTVRc3l5QVhnUFkKZJgJaKEuWmh5EkMJW/v868BBSnmq8lcE
            CBqWfpdnJ9KE2kGnM+6hsx6mxu6DIz1IAJYbHSFVwPksWMXozQZHfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T09:09:13Z"
    mac: ENC[AES256_GCM,data:Lohsamy25rFrtopQwrJURb4yHlqUfTEVHR/2G8nhW8UusEgd2JLW/IvLJnjy5NHvznl9EI3IczFp7syzQ4T6rxRn4RgrtJ52yl93vy3R9nXWuLCoXIVrvgjkvh1OOYZYFK1fhcpwek7zEI+KjJg4WLA5oLhOAG/tbqJnwFFU2js=,iv:+x6+qC5Q67JOKYhmVYA3N6SmgRgUdJvN1PBx4m/bqwg=,tag:cKygDqGNF0mKvW4po6uxSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
