apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ferme-du-jointout-wordpress-site
spec:
  values:
    wordpressUsername: admin
    wordpressExistingSecret: wordpress
    wordpressEmail: contact@fermedujointout.fr
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql-version-8-lts.controller-mysql-operator.svc.cluster.local
      port: 3306
      user: ferme-du-jointout
      database: fdj-wp-site
      existingSecret: wordpress
    wordpressPlugins: []
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: www.fermedujointout.fr
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-staging
      extraTls:
        - hosts:
            - www.fermedujointout.fr
          secretName: www.fermedujointout.fr-tls
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    initContainers: []
    volumePermissions:
      enabled: false
      resourcesPreset: "none"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

