---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared-wordpress-site
resources:
  - ../../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  # Rename the helm release
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: shared-wordpress
  # Overrides the helm release values.yaml
  - target:
      kind: HelmRelease
      name: shared-wordpress
    path: values.yaml
  # Overrides the namespace name
  - target:
      kind: Namespace
      name: shared-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: shared-wordpress
  # Add the k8up backup annotation to the PVC
  - target:
      kind: PersistentVolumeClaim
      namespace: shared-wordpress
    patch: |-
      - op: add
        path: /metadata/annotations/k8up.io~1backup
        value: "true"
  # Overrides the k8up bucket values with subPath
  - target:
      kind: Schedule
      name: wordpress
    patch: |-
      - op: replace
        path: /spec/backend/s3/bucket
        value: "alter-it-infra01-backup-shared-wordpress"