apiVersion: v1
kind: Secret
metadata:
    name: shared-wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:+drAb8fV4rOkUfeMm/g=,iv:a1wrCjHN1OQuVeJeeKJl14008bDGGKvGSHF1QW9TVB4=,tag:nIbO5SkxcQBW6IZkdAMqZg==,type:str]
    mariadb-user: ENC[AES256_GCM,data:zfMXQMYz/BH/Fzbl4Cff,iv:BwRx1PtU+eTu2KaDgm5K1gHCeH8mdLtLpaIfatg7M+A=,tag:yIOLKt6KtKCf3IoA/YJvsQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:eTiBtK1VN/P8,iv:2bBOYHjYn3qhMGEnKXrJLPWAKUOyr/zYZZLyAH21ZhM=,tag:dAa19agHGU4TjkPQtykiug==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:33jISQA=,iv:8U9YfHtvWoQlqLc54msQB5S2aPLSTr2np6pOwBIaxvA=,tag:vu+dexFkk4iptszOYBrlGA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:388OS16Ww3dpgEEy8c0=,iv:KT/piLoxJs0pjdJjeMNTmdHmUTnYlRREfG1VD0gc7po=,tag:+I0Xg/gpnZQxhcL6J1k9uQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:Q0R4bvQ=,iv:tUOoiwB09+1O54L7Lp0CLPZUjFEoSZX7qdmfXYT7M7U=,tag:Zed3g5gOFggk28ZYlg09mg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRCtiQXYvT0FzakJNNXgz
            akNqRGNuc1pxSXczMC9HWEFzUmFzZm5pUlNvCjRMVDJtSjVIWFd6SFFzTXlIRUs0
            MGY1clM2bGlTSmE1VFpaNk1PRkM2djAKLS0tIE1ITW9XWkpYbklpTStiK015V2li
            UmgyZS9FZUJ6SEpqZnM0bUJrTVovUmMK7e/gtWpHL/zch6xOsce2RiELCbWTL2PR
            vNtqGEqNxN5SJJoEiT3WpGRZXPa3rZfPqCpe4Ney1/+/k8gdrDbK0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:02:39Z"
    mac: ENC[AES256_GCM,data:4PgXCMDq95+crD9RsY8uLWvbhgU6inzEc9Dg0skC1w0qwOywJUN3DQsAqfqEhzj5U05nWkrYh1ffj5/bL90cknorGKtjMBVVlXHualyr8oLPFmg5ZddmEv+0DucJH+u8Vgx3heAWohPOJf+N49KL+oDR6simRcXqqaChEcgoC7g=,iv:6uaGs4bTUMbMpsruofU529Cmg+vY3ueIsdTun2Ff+fU=,tag:JJW12Hxp1yIIgafHSPD2hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
