
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: controller-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress.internal.${cluster}.${domain}
    external-dns.alpha.kubernetes.io/target: internal.${cluster}.${domain}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ingress.internal.${cluster}.${domain}`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: tailnet-only
          namespace: controller-ingress
  tls:
    secretName: ingress-internal-${cluster}-${domain}.tls
