
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-internal-infra01-alter-it-eu-tls
  namespace: controller-ingress
spec:
  secretName: ingress-internal-infra01-alter-it-eu-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - ingress.internal.infra01.alter-it.eu