version: '3'

vars:
  LE_PORTAIL_PATH: applications/le-portail/production

tasks:
  le-portail:alterconso:
    desc: Backup & import alterconso from production to production
    vars:
      MYSQL_USER:
        sh: sops --decrypt --ignore-mac "{{.LE_PORTAIL_PATH}}/alterconso/secrets.enc.yaml" | yq '.stringData.MYSQL_USER'
      MYSQL_PASSWORD:
        sh: sops --decrypt --ignore-mac "{{.LE_PORTAIL_PATH}}/alterconso/secrets.enc.yaml" | yq '.stringData.MYSQL_PASSWORD'
      MYSQL_ROOT_PASSWORD:
        sh: sops --decrypt --ignore-mac "{{.LE_PORTAIL_PATH}}/alterconso/secrets.enc.yaml" | yq '.stringData.MYSQL_ROOT_PASSWORD'
      MYSQL_DATABASE:
        sh: sops --decrypt --ignore-mac "{{.LE_PORTAIL_PATH}}/alterconso/secrets.enc.yaml" | yq '.stringData.MYSQL_DATABASE'
    cmds:
      - |
        kubectl --context le-portail exec statefulsets/alterconso-database -- \
          sh -c 'mysqldump --hex-blob --no-tablespaces -u root -p"${MYSQL_ROOT_PASSWORD}" "${MYSQL_DATABASE}" \
          > /tmp/backup.sql'
      - kubectl --context le-portail cp --retries=-1 alterconso-database-0:/tmp/backup.sql ./alterconso-last-backup-from-production.sql
      - |
        kubectl --context production --namespace le-portail-alterconso exec -i statefulsets/alterconso-database -- \
          mysql -u {{.MYSQL_USER}} -p{{.MYSQL_PASSWORD}} --binary-mode \
          --max_allowed_packet=64M {{.MYSQL_DATABASE}} < ./alterconso-last-backup-from-production.sql
    silent: true

  ferme-du-jointout:owncloud:upload:
    desc: Upload owncloud from production to production
    cmds:
      - |
        kubectl --context production --namespace ferme-du-jointout-nextcloud  exec deploy/nextcloud -- sh -c '\
          php occ config:system:set password_policy.enforceNonCommonPassword --value=false --type=bool &&
          php occ config:system:set password_policy.minLength --value=1 --type=integer &&
          OC_PASS="Jointout2018$" php occ user:add --display-name="gaec" --password-from-env "gaec" &&
          OC_PASS="Jointout2018$" php occ user:add --display-name="viti" --password-from-env "viti" &&
          OC_PASS="Jointout2018$" php occ user:add --display-name="youte" --password-from-env "youte" &&
          OC_PASS="Jointout2018$" php occ user:add --display-name="cfppa" --password-from-env "cfppa" &&
          php occ config:system:set password_policy.enforceNonCommonPassword --value=true --type=bool &&
          php occ config:system:set password_policy.minLength --value=10 --type=integer
        '
      - |  
        kubectl run rsync-upload \
          --image=instrumentisto/rsync-ssh \
          --namespace=ferme-du-jointout-nextcloud \
          --overrides='{
            "spec": {
              "volumes": [{"name":"data","persistentVolumeClaim": {"claimName":"nextcloud-nextcloud"}}],
              "containers": [{
                "name": "rsync-upload",
                "image": "instrumentisto/rsync-ssh",
                "command": ["tail","-f","/dev/null"],
                "volumeMounts": [{"mountPath":"/data","name":"data"}]
              }]
            }
          }'
      - |
        # Copier les fichiers de chaque utilisateur
        sleep 15 # Attendre que le pod soit prêt
        for user in gaec viti youte cfppa; do
          kubectl --context production -n ferme-du-jointout-nextcloud exec rsync-upload -- mkdir -p /data/data/$user/files
          kubectl --context production -n ferme-du-jointout-nextcloud cp ~/work/backups/owncloud_data_backup/$user/files/. \
            rsync-upload:/data/data/$user/files/
        done
        kubectl --context production -n ferme-du-jointout-nextcloud exec rsync-upload -- chown -R 33:33 /data/data/
      - |
        # Supprimer le pod temporaire
        kubectl --context production delete pod rsync-upload -n ferme-du-jointout-nextcloud &
      - |
        # Scanner les fichiers
        kubectl --context production -n ferme-du-jointout-nextcloud exec -it deploy/nextcloud -- \
          php occ files:scan --all

  ferme-du-jointout:dolibarr:
    desc: Backup le-portail dolibarr from production to production
    # silent: true
    vars:
      SSH_PASSWORD:
        sh: sops -d tasks/backup/secrets.enc.yaml | yq -r '.SSH_PASSWORD'
      MYSQL_PASSWORD:
        sh: sops -d tasks/backup/secrets.enc.yaml | yq -r '.MYSQL_PASSWORD'
    cmds:
      - |
          sshpass -p "{{.SSH_PASSWORD}}" ssh root@ns381126.ip-5-196-71.eu \
            "MYSQL_PWD='{{.MYSQL_PASSWORD}}' mysqldump -u root Dolibarr --single-transaction \
              --disable-keys --no-tablespaces" > ~/work/backups/ferme-du-jointout-dolibarr.sql
      - |  
          sshpass -p "{{.SSH_PASSWORD}}" ssh root@ns381126.ip-5-196-71.eu \
            tar -czvf - -C /home/www/dolibarr documents htdocs\
            > ~/work/backups/ferme-du-jointout-dolibarr.tgz
      - |
        sed -i '23s/^/SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";\n/' ~/work/backups/ferme-du-jointout-dolibarr.sql
        sed -i '26s/^/DROP TABLE IF EXISTS `llx_accounting_system`;\n/' ~/work/backups/ferme-du-jointout-dolibarr.sql
        sed -i '3603s/,$//' ~/work/backups/ferme-du-jointout-dolibarr.sql
        sed -i '3604d' ~/work/backups/ferme-du-jointout-dolibarr.sql
        kubectl --context production -n ferme-du-jointout-dolibarr exec -i statefulsets/dolibarr-mariadb -c mariadb -- bash -c '\
          mariadb -u ${MARIADB_USER} -p$(cat ${MARIADB_PASSWORD_FILE}) ${MARIADB_DATABASE}' < ~/work/backups/ferme-du-jointout-dolibarr.sql
      - kubectl --context production -n ferme-du-jointout-dolibarr cp  ~/work/backups/ferme-du-jointout-dolibarr.tgz $(kubectl --context production -n ferme-du-jointout-dolibarr get pods -l  app.kubernetes.io/name=dolibarr -o jsonpath='{.items[0].metadata.name}'):/tmp/backup.tgz
      - |
        kubectl --context production -n ferme-du-jointout-dolibarr exec deploy/dolibarr -- sh -c '\
          # mv /var/www/html/conf/conf.php /tmp/conf.php &&
          # tar -C /var/www/ -xzvf /tmp/backup.tgz --strip-components=1 &&
          # mv /tmp/conf.php /var/www/html/conf/conf.php && 
          # rm /tmp/backup.tgz
          rm /var/www/documents/install.lock
        '

  ferme-du-jointout:wordpress:
    desc: Backup le-portail wordpress from le-portail to production
    silent: true
    vars:
      SSH_PASSWORD:
        sh: sops -d tasks/backup/secrets.enc.yaml | yq -r '.SSH_PASSWORD'
      MYSQL_PASSWORD:
        sh: sops -d tasks/backup/secrets.enc.yaml | yq -r '.MYSQL_PASSWORD'
      LOCAL_WP_POD:
        sh: kubectl --context production --namespace ferme-du-jointout-wordpress-gaec get pod -l app.kubernetes.io/name=wordpress -o jsonpath="{.items[0].metadata.name}"
    cmds:
      - |
        sshpass -p "{{.SSH_PASSWORD}}" ssh root@ns381126.ip-5-196-71.eu \
          "MYSQL_PWD='{{.MYSQL_PASSWORD}}' mysqldump -u root gaec --single-transaction \
            --disable-keys --no-tablespaces" > ~/work/backups/ferme-du-jointout-wordpress-gaec.sql
      - |  
          sshpass -p "{{.SSH_PASSWORD}}" ssh root@ns381126.ip-5-196-71.eu \
            tar -czvf - -C /home/gaec .\
            > ~/work/backups/ferme-du-jointout-wordpress-gaec.tgz
      - |
        echo "Restore mysql..."
        kubectl --context production --namespace ferme-du-jointout-wordpress-gaec exec -i statefulsets/wordpress-mariadb -c mariadb -- bash -c '\
          mariadb -u ${MARIADB_USER} -p$(cat ${MARIADB_PASSWORD_FILE}) ${MARIADB_DATABASE}' < ~/work/backups/ferme-du-jointout-wordpress-gaec.sql
      - |
        echo "Restore wordpress data..."
        kubectl --context production --namespace ferme-du-jointout-wordpress-gaec cp ~/work/backups/ferme-du-jointout-wordpress-gaec.tgz {{.LOCAL_WP_POD}}:/tmp/backup.tgz -c wordpress
      - |
        kubectl --context production --namespace ferme-du-jointout-wordpress-gaec exec -i {{.LOCAL_WP_POD}} -c wordpress -- bash -c "
          mv /bitnami/wordpress/wp-config.php /tmp/wp-config.php && 
          tar -C /bitnami/wordpress/ -xzvf /tmp/backup.tgz --strip-components=1 &&
          mv /tmp/wp-config.php /bitnami/wordpress/wp-config.php &&
          rm /tmp/backup.tgz
        "

  .wordpress:
    internal: true
    silent: true
    desc: Backup & import wordpress from production to local
    vars:
      SOURCE_WP_POD:
        sh: kubectl --context le-portail get pod -l app.kubernetes.io/name={{.APPLICATION}} -o jsonpath="{.items[0].metadata.name}"
      SOURCE_DB_POD:
        sh: kubectl --context le-portail get pod -l app={{.APPLICATION}}-database -o jsonpath="{.items[0].metadata.name}"
      DB_SECRET:
        sh: kubectl --context le-portail get secret --namespace default {{.APPLICATION}}-database -o jsonpath="{.data.MARIADB_PASSWORD}" | base64 --decode
      LOCAL_WP_POD:
        sh: kubectl --context local --namespace {{.DEST_NAMESPACE}} get pod -l app.kubernetes.io/name=wordpress -o jsonpath="{.items[0].metadata.name}"
    cmds:
      - |
        echo "Backup mysql..."
        kubectl --context le-portail exec {{.SOURCE_DB_POD}} -- sh -c 'mariadb-dump -u wordpress -p"{{.DB_SECRET}}" wordpress > /tmp/backup.sql'
        kubectl --context le-portail cp --retries=-1 {{.SOURCE_DB_POD}}:/tmp/backup.sql ./backup.sql
        kubectl --context le-portail exec {{.SOURCE_DB_POD}} -- rm /tmp/backup.sql
      - |
        echo "Backup wordpress data..."
        WORDPRESS_POD_NAME=$(kubectl --context le-portail get pod -l app.kubernetes.io/instance={{.APPLICATION}} -o jsonpath="{.items[0].metadata.name}")
        kubectl --context le-portail exec -i "${WORDPRESS_POD_NAME}" -- tar -C /var/www/html/ -czvf - . > ./backups-data.tgz
      - |
        echo "Restore mysql..."
        kubectl --context local --namespace {{.DEST_NAMESPACE}} exec -i statefulsets/wordpress-mariadb -c mariadb -- mariadb -u bn_wordpress -p{{.MYSQL_PASSWORD}} bitnami_wordpress < "./backup.sql"
      - |
        echo "Restore wordpress data..."
        kubectl --context local --namespace {{.DEST_NAMESPACE}} cp ./backups-data.tgz {{.LOCAL_WP_POD}}:/tmp/backup.tgz -c wordpress
      - |
        kubectl --context local --namespace {{.DEST_NAMESPACE}} exec -i {{.LOCAL_WP_POD}} -c wordpress -- bash -c "
          mv /bitnami/wordpress/wp-config.php /tmp/wp-config.php && 
          tar -C /bitnami/wordpress/ -xzvf /tmp/backup.tgz --strip-components=1 &&
          mv /tmp/wp-config.php /bitnami/wordpress/wp-config.php &&
          rm /tmp/backup.tgz
        "
      - |
        echo "Cleaning up local backup files..."
        rm ./backup.sql ./backups-data.tgz

  le-portail:ecolieu:
    desc: Backup & import ecolieu wordpress from production to local
    cmds:
      - task: .wordpress
        vars:
          APPLICATION: wordpress-le-portail
          DEST_NAMESPACE: le-portail-ecolieu
          MYSQL_PASSWORD:
            sh: sops -d "{{.LE_PORTAIL_PATH}}/ecolieu/secrets.enc.yaml" | yq '.stringData["mariadb-password"] | select(. != null)'
