SSH_PASSWORD: ENC[AES256_GCM,data:3/S1KzKvCux1Wg==,iv:udW5on9NPJ3Mn5DlU8fObY/65B2w9Y8LtKSd673y7P4=,tag:ruDEpYI1cm+V1u6UQDMzmA==,type:str]
MYSQL_PASSWORD: ENC[AES256_GCM,data:XlXNetm8BPaFvymjvA==,iv:C5TMI89GcC47bgvju0BS132f27T0WNed5+2BtEw3QBc=,tag:CVJORim6p1MEpvECWLsezQ==,type:str]
GAEC_WORDPRESS_USERNAME: ENC[AES256_GCM,data:Z0NtI4v7yrNX,iv:sF1C9zN3r/KOKD1cuWO+929D9mhF7UrYC0UxHC606B8=,tag:SCYle1tAK/NLKgC0ZcThaw==,type:str]
GAEC_WORDPRESS_MD5_PASSWORD: ENC[AES256_GCM,data:GEdgc4WxwS6ExSCqYVlVyPBDNTCaGE8dH9HHbT2xQNyuCA==,iv:TsO3S6+W77XXjLq7REtxH/zWb5T9qqE1qzIPxmIfJF0=,tag:grFQRyau0cJaTwBHkZXR0w==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RXVKRzVZaVIxUlQ3V0Nq
            amZrTm9PTmJoK3Z0Q2R6UEZVcHpaT1BEakhnClhlU1Z3Q0tEOVZWcHh4VTJTb0pt
            VGkzZzQyUS8zRFkzR0dxME5PaVN1QjgKLS0tIE9lR1FLdDU3Yzh1OFhSYmV3K3ZU
            bzdObkZFbmdHb2M3aVlodnJQOERYNzQKhfoYO0Xv55GQKzp1U8Y3CyAVHIhw0zCH
            W37mXh6gkgZFFMu3JRV05Wzu4waZePzczH3nqy8FRn5P0gaUZwcRVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T07:17:49Z"
    mac: ENC[AES256_GCM,data:oU6ZD7Kkcr0Zaim07r92R4gkbQbIygkkUGXS5NNnm2yP89wvmbQkVlfkGvTGMW1Jkasz77Fk3a+LS1i1BQ3uRk7fLuisqLcTdCX3q+MIpRy0gXxy7iDOKwTjHsVBbpYhZ3qYcxk127B1ehIo4t5cmHnHMMO2h4dwIRDC+vUgs3Q=,iv:495XrS/0mfvT5ibHCJp/Q+5zRVL1g8LTcHzhK1/ss44=,tag:5cvnoD483XSZRWkiJHlR+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
