apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:MdoFM6Ytdff+dA+HCBeSBuDjQeHHsAVlUw9ziXdj1gwZo0fWC8fVEaz67T9gIW/9+KHJp8X36QCuvWj/1CGUVA==,iv:xJjLAPEvvHrQT8t6Tv/xQXtBtjVVdCPS+o4tedK9vic=,tag:8GhIaKYCOhu0u47tjC16MA==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:OQoz40s6DeTDj3MQfMNAlvo=,iv:LbTAZ7M5nzdPNhaZwIzU7C0IlMf51I8GJuDNssjE1t4=,tag:tpMwcfPD6/IoAuc6FZsgqg==,type:str]
    base-dn: ENC[AES256_GCM,data:3mJPFImGCXQTQ3mhDL8pUUQ=,iv:yPsxOvQmdoPm5W99Xyj4bUArDGKIQpDXBH87EyBYAiw=,tag:yY8zEEgZgGzwBORvHhm3Ew==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:Sosd83Z3R70uUlYmH5Vjbtwumced2HMtZrZd7j2Bn3Cs93iO+HQriS1dHg2ndjxm4qhzESOQH+7ogA81Z2ftPQ==,iv:IdhQmKlETrO+UxbUFeuRVQDhvNSDnmQK2NYdgkvKpNs=,tag:cP5zq6ETR8bfBjhEHzV6Ww==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSHBSZngxcHJ6ZEowQkw1
            V1JyVXJ4c3ZMeGRTOCtHNjZrd3B0ZHNFV1I0Ck5ZTkdkUEdhRkxWamtBdDdKU0Rv
            WVdkQzRsWW45cmZOUmlhbzFpN1Vqb3MKLS0tIDRic1IrdWlETXFJN05ZTkZoQW9o
            anFQb21hZDEzNFpxS2wyWVZ6L1lLbHMKEovN3K2pmjeGIuKR12CEY+rVJz/Q1L2f
            YmE91hJzM2kRrqiYE2lqmsTNbnewQLeEzerdomsYLY+7bwrX7Y1igw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:03:29Z"
    mac: ENC[AES256_GCM,data:+zGcv3PzFFqFsUsnSRANZJ+zCfoXPk6ziwpD7FmdFjaelfi6uE8r4lo3UlYfvXKbNBh/1s19/3j4n4iNkAYvCK+CLQN6IcjI2c7tgABLGIk64rnVYeTs8ayf+9AAxGG5nzACH/HTifdI4xXtUs1QkHB1BW9cMhuPwu72F7s6w/s=,iv:RGId07+RetaK5uQvWCS3W8pEx+g0jID4jAWsh+g3y5A=,tag:slbHkmJQbo07nWgFj7nIQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bootstrap-users
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:SWOS7hyzQgJ2ki9ec2xv1wb9bWLeTUfbq3E1xPFqi81kyiLSiehg+5q5623m/lVnrcz0u5uQJ3OgPHwk30B4PqRqt9Y7+kHo8r/178LeZHBT/UsckkLGFmlIDeT3PgG5bmDkcyRLxCzCEX5Mf4DqEmJlgu/Z6yQEbrGeM77WOgvL76MtLoajLYoHOouJokNYZa4AF4bXRli9XSaIr3XFzR6WnyI12Oq6cl4368rrcx8TUkOma9VonYdRn0MjSebWBSQ+adJPU0XVk30W8il1D4gvb8b809hJgwyxEZkQRPL2pw==,iv:pF4DQgqldKAQpcBapXzil490aKyUsYxJfRe0cU71sTY=,tag:2CRXjJK9VkyKcXcrhNronQ==,type:str]
    dolibarr.json: ENC[AES256_GCM,data:dmEVautccIcXkl/X4MtrAA1jfOx8HYNKqAZw1u+I5/Xh/9S8+SmCJnjxIPAHsd92+vG+rtH0MSzTM3KlHuqcMw2doPW9b6jasKdDELZnNUk22Jxh6Z/+rTD/lpX/Nnd6QsJnY7WBnBfW0HBAVsK6A606VnJXxPHUOVCjTikMDQOofW46c4I1Z+51p6j6yDlUU0GqAchvSRCtr0Ct9plQ1hYIxtIPKbABvHg8Q7jtgWygcBUrkH2vO9QX8riByZGYKobC+OoDwI764XOl,iv:XKsaQrj6vDg/wFq7tQtb4hPSIylV53T5j3l7nmbHNpQ=,tag:aUT+e54RSdnAHI5kLZxT6g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSHBSZngxcHJ6ZEowQkw1
            V1JyVXJ4c3ZMeGRTOCtHNjZrd3B0ZHNFV1I0Ck5ZTkdkUEdhRkxWamtBdDdKU0Rv
            WVdkQzRsWW45cmZOUmlhbzFpN1Vqb3MKLS0tIDRic1IrdWlETXFJN05ZTkZoQW9o
            anFQb21hZDEzNFpxS2wyWVZ6L1lLbHMKEovN3K2pmjeGIuKR12CEY+rVJz/Q1L2f
            YmE91hJzM2kRrqiYE2lqmsTNbnewQLeEzerdomsYLY+7bwrX7Y1igw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:03:29Z"
    mac: ENC[AES256_GCM,data:+zGcv3PzFFqFsUsnSRANZJ+zCfoXPk6ziwpD7FmdFjaelfi6uE8r4lo3UlYfvXKbNBh/1s19/3j4n4iNkAYvCK+CLQN6IcjI2c7tgABLGIk64rnVYeTs8ayf+9AAxGG5nzACH/HTifdI4xXtUs1QkHB1BW9cMhuPwu72F7s6w/s=,iv:RGId07+RetaK5uQvWCS3W8pEx+g0jID4jAWsh+g3y5A=,tag:slbHkmJQbo07nWgFj7nIQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bind-dolibarr
    namespace: controller-directory
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/lldap-bind-dolibarr=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/lldap-bind-dolibarr=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:cxfOx1jcB91EiqMq4FLGqoM+NGbI83NccO1fTc4ZUxkg1Ep5iKDg+X7nlzLTao5b/rru6oPZeXBNUaCh9R1FiI48iSsnfQ==,iv:9Bnfnldn5pEay/2SxJRElq8wZQNt7aMuQehEDx2FoUw=,tag:HJClSlUOE0qUBEosCI/Qxw==,type:comment]
    #ENC[AES256_GCM,data:Gqs/9YEHd83iw21bS1VBgr3lvDYW+6nl3XF6ckGFmWw6Cdj7WJTsaLfMfC6kEFm6FUMZEPK6K5C312sDUNzgwnxq9kR4/JapScI=,iv:Q+/muew11n72ucXOOUrt3ihkpKA/jG1LTOWm7QMEnl8=,tag:Kt1MxUlFyynG0ontbcJRDg==,type:comment]
    password: ENC[AES256_GCM,data:8ggFbdWoeHNSt9ZEHE4DAQk7+luDReGtQdI+gyqmoG4UlvVPBBJCku64xA==,iv:Se04/JXvSIcAydO4o/Vhr9ya52wEkm+tNXEihJeuQG0=,tag:p4M/j3a1kx30Lypp7QHH7g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSHBSZngxcHJ6ZEowQkw1
            V1JyVXJ4c3ZMeGRTOCtHNjZrd3B0ZHNFV1I0Ck5ZTkdkUEdhRkxWamtBdDdKU0Rv
            WVdkQzRsWW45cmZOUmlhbzFpN1Vqb3MKLS0tIDRic1IrdWlETXFJN05ZTkZoQW9o
            anFQb21hZDEzNFpxS2wyWVZ6L1lLbHMKEovN3K2pmjeGIuKR12CEY+rVJz/Q1L2f
            YmE91hJzM2kRrqiYE2lqmsTNbnewQLeEzerdomsYLY+7bwrX7Y1igw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T07:03:29Z"
    mac: ENC[AES256_GCM,data:+zGcv3PzFFqFsUsnSRANZJ+zCfoXPk6ziwpD7FmdFjaelfi6uE8r4lo3UlYfvXKbNBh/1s19/3j4n4iNkAYvCK+CLQN6IcjI2c7tgABLGIk64rnVYeTs8ayf+9AAxGG5nzACH/HTifdI4xXtUs1QkHB1BW9cMhuPwu72F7s6w/s=,iv:RGId07+RetaK5uQvWCS3W8pEx+g0jID4jAWsh+g3y5A=,tag:slbHkmJQbo07nWgFj7nIQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
