apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:Aa5rmAvbkIn5aa1lVW9lkUjj7rbz2HgRGcUWkVBq+e5ru/TQbpZysVUkUe6bX4JyFDaCGwgl2kxGzpmr9uLMwA==,iv:l4MJcWVCjBNdWc0iyQQNWs5BxzmFkVxzua7nYhBTirQ=,tag:wOF7PyptIQG55g8yk+yOKA==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:HHn/A+czGYcuWXpzgH1C1TA=,iv:5NtMfzMqV4fHx3OaH6ny/bNexOiW/woeGzRf+Okt5z0=,tag:jQOpgx1Q03J0LHMLfaaWQg==,type:str]
    base-dn: ENC[AES256_GCM,data:60rdPHZ4CvmvSqfNB7hqZeA=,iv:csV0/4mm1pjT4nG21t4elwcEPu0OFHu+422JUImK8vU=,tag:nVX0ZcLaGYcbzdUa+rTJSQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:NG/FjRbcREMDzLSoD+X+IEDBv18VGs/glXShr9RuDg8qFweNhqcOvOEvCXT08iKKKdbaojJrUQkw9puZiIXwbQ==,iv:O9fECWFTWpNGtMz74djVNOf7D5iiYn5/IsPOtig4npA=,tag:Ik2jubV+FDr6qDDY/36LDA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNDhidGExdlZTUXZ5emM0
            dGlrL3FXVkJRcEd0WWJ5TVpvak9yZWxlVGg4Ckx4MzVZUGdtOFYxeG9GR2hOenFG
            TTM5d3NpMVhrOWlYWGVqUmNVUU0yK2cKLS0tIEdlcFVUQzBESDljbm5Jc3JVVXhr
            eU1tSUNEOG1nU2hNQS96UTVjV0lRWncKIDl6IDuc5XdOiS9nr/DaeWEkGkJ92gf/
            tWcEHvqtR5I1Sqj9MIoCu9Ayx3cEbKvIee5QmSi4PxhiXheDBDN8+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T10:45:39Z"
    mac: ENC[AES256_GCM,data:dMYRa+JVpHqi7JzeIzZbH28ofLwF7V7YSmsQvBbIE+Hwz8iKBtdpDauHjn0qm3iUc+sBe0FkrW08I3svnI+3iORbFEMVHOTriD3ijJrX2DiKW8PUxl0kQ9YnLhuwLIKIgmrJbbcWUV1AKlqJVCzrsazHZyMAWGp40pcqeAnyLHI=,iv:sXPVhztnXGXI5YKJieLT0776Vhq+0dOK5yQA/tTUW3Q=,tag:0uoRphsVkf3aYe66pLBcUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bootstrap-users
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:76Rrwcys4fvRMHLRQLKtv+hEVfZ15oBIL5LgP0zZ6F4S8mNVXSdCW6SQM/lVx6+fOPzBw5cpNlZ/fOYPrR8iNMPy7LFxR2jcIdk1M3JZQncauxmycnXqqhrqZfayekUt4jOsqetDmrcI6Luf/u6Liy/WfjrlQ9FHslZICEVT4fMdv4Gr9hWdOP8lmhtrNnTOsxs/fH8RCFNjJeTK+r9jzIwG5sDMnpnJZ3M+9tToJcHZhYDLTya4EONxoiF3ZlQHXEpJb8lO9LhCqbDrR3F71Yme5Kr+iaR/fuImzNsL8st2pg==,iv:LQcBLj6baoqcJeZDOXU7K1eBWmJ8qHu2PfV+15A9rIA=,tag:QvSkfDXccux/NhP4LeQsjw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNDhidGExdlZTUXZ5emM0
            dGlrL3FXVkJRcEd0WWJ5TVpvak9yZWxlVGg4Ckx4MzVZUGdtOFYxeG9GR2hOenFG
            TTM5d3NpMVhrOWlYWGVqUmNVUU0yK2cKLS0tIEdlcFVUQzBESDljbm5Jc3JVVXhr
            eU1tSUNEOG1nU2hNQS96UTVjV0lRWncKIDl6IDuc5XdOiS9nr/DaeWEkGkJ92gf/
            tWcEHvqtR5I1Sqj9MIoCu9Ayx3cEbKvIee5QmSi4PxhiXheDBDN8+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T10:45:39Z"
    mac: ENC[AES256_GCM,data:dMYRa+JVpHqi7JzeIzZbH28ofLwF7V7YSmsQvBbIE+Hwz8iKBtdpDauHjn0qm3iUc+sBe0FkrW08I3svnI+3iORbFEMVHOTriD3ijJrX2DiKW8PUxl0kQ9YnLhuwLIKIgmrJbbcWUV1AKlqJVCzrsazHZyMAWGp40pcqeAnyLHI=,iv:sXPVhztnXGXI5YKJieLT0776Vhq+0dOK5yQA/tTUW3Q=,tag:0uoRphsVkf3aYe66pLBcUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
