apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:MpoVkrxpODT8l767a5+kGt3Nsg1wCvgbD997DChHq2xT0JishyVt3vsmWILCtvTXwFKB5Q9EuJK0peuJRJA8tQ==,iv:g+8Ye2wpCCEeOpi3nXXlN6+KrPkLETa9oX3aUwOa0mk=,tag:W5mYNDyy0ez6bzx8IpC71Q==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:DF30z4Tp0cdOhakATVe4KUo=,iv:zStfvdeazbW5rpvvLV3k8ZsGFKB3l1O9fbtTE/zbBJc=,tag:eCkCHqUGp/LE9RSmVt4r6A==,type:str]
    base-dn: ENC[AES256_GCM,data:6LLcynnFuAAQmc423IGTqKk=,iv:N5mzFiInqW7bn5MYMWyDSowUq0DfZwjbvvOeuh0QVkI=,tag:wkpEEzfaL2ef1F0mve1hkA==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:Yyu8RSmXV+EQWWxN7yZTbEg7j2AzT6MULTLl+e3coUldEEkmgTSmZlp/aSr7ILQSvrG2OlaRzAHKIBhi2eWAAw==,iv:8onurB9aUkX31Be9CRObKXIxa7KNOZZ+C1zuYenA9mo=,tag:zpq1DZh1bX4XlOcIAPPArA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY25ZSVBWSTc0YUUrMGNm
            OXU2TjRjODcwN0pTcGNheG9NZDVEdlRMV2hzClRxTlMrUFh1bFJtT3lxL1J1K2xR
            TGRwUnJxREZpeW1IRTBZNDRpM1VBS00KLS0tIDdmL1dhMzAyMHRSZ1BWbjlUeEdk
            K2lua2crVXdKTmd5T2t3ME9VTmZXelkK9plFHfjfExHxlq4zVl8l2U1eUacP4T8I
            ZYwQgnv5OKW6uC4kWJooDsLJHaqqXy7sZQxC/y6w3p/NaRKk+nuV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T09:47:58Z"
    mac: ENC[AES256_GCM,data:V5a4E/jHMMCNjUrbwPYmIddnnwwxCWXdZWQKMOCCos1eAVNHuEr0m3Zy2if5bfRIECyQceXPDpIZXyVK/xuY5YMN+BP1vCT0XVOR6TbfRwz4bOzxEAbtJb7BGdf14CofWBUNv3rmt+2vEJR03ZF4NrvLEwcjRWGjCFDPFPHtjiQ=,iv:bMHj7qyIBu1rjmwRpUyAiB4c9ejGHdVZ4wFSc+iEBKM=,tag:DsvGopQ3GJop0mLNa4Xe2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bootstrap-users
    namespace: controller-directory
type: Opaque
stringData:
    authelia.json: ENC[AES256_GCM,data:eEH5yei8HZLSF+u0Z/rE4NU/PcRCiH6tMrx9e93DjgmGIuJk7gSt8KBpCQAdkU276r+Mv+HE3VX2os3hJR2LStgx35NxRORN+mne+zUGm4e16d92XNWq12xp0uAENAzct1UC6ZjJ3D+0p01w+amhvqINIIzhwXpNE8jNbRFOh8V+EcAQw2JdGvobC3OfVThDN9n/kp5EFXDxtBdIBASISnyeImCbB07Px7j3pkQO0MJ7V6JZTNndjE7o2ZIsv4dFJfddxBJh5+HoAph5axCnVNIfcd2IF+Awmy45vQ1RIx8jqA==,iv:kEF9pLYI8PEHuFh3TZ0KOP75N6z4ndzCmmRWouj0Eds=,tag:kcy6BImczFYLM3Z97HSunw==,type:str]
    dolibarr.json: ENC[AES256_GCM,data:EejIawnDUFs9Ig3XcTu7eiSpmgCKWQaDMZEsUDViJ0opmyTyo09ueDRAPQPgN9ZA/T9zTaMR31OTlXH/O9JIp5HQa89gCBB7CPYFlRk6lVHnZDJmpNPR8At1Zf0osIuxfuFWZr/uVCSlpOwQXpqksNAYMTYQ7P3ntU+KqMgFPZlxY8U92ZWo8bmHMwcxlqUeXXDhE8vwxZXsWBRT8tfJwiudeUN95ypwamJhaJJptOWPROLjpWhx6lJoMUqFnY7NR5xraxlfzu5h21sP,iv:ACsOLyuuUqas5Wj/gguh6dger2yO//1Y2Zoxglj6taA=,tag:0dY+7d2LUweYH4k9X/E2ZA==,type:str]
    grist.json: ENC[AES256_GCM,data:dvv9u1Zu7DPDR4MppcpVN6V5Eh0thSF6sG8DIQaVRsLVb7BZ+e+Yn3eftX97NpG6IkiyWBATzQNbPSfoL3Zrkvsmny79jZKIyojnPFIH7zNxvZeo6o9rYfFaiMVj7jVc/XsfjwGn32RJZXl2VdiA/DdAEe9kbgpCJmr8LAeQjACi3J6suMX2bhh0Xc8t7JlkosKHw2LatEtqEwj972CUZJcNO39KhZqwzWxhYxHWoL/FzJxe+HV25TfPTHf0pe+rEz1A,iv:/JfYLvAOVeTf0iO/u25XGPgCZI+tEUtjhRfR/uQx/qI=,tag:k8/UKkoIav7orEplzD7z0g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY25ZSVBWSTc0YUUrMGNm
            OXU2TjRjODcwN0pTcGNheG9NZDVEdlRMV2hzClRxTlMrUFh1bFJtT3lxL1J1K2xR
            TGRwUnJxREZpeW1IRTBZNDRpM1VBS00KLS0tIDdmL1dhMzAyMHRSZ1BWbjlUeEdk
            K2lua2crVXdKTmd5T2t3ME9VTmZXelkK9plFHfjfExHxlq4zVl8l2U1eUacP4T8I
            ZYwQgnv5OKW6uC4kWJooDsLJHaqqXy7sZQxC/y6w3p/NaRKk+nuV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T09:47:58Z"
    mac: ENC[AES256_GCM,data:V5a4E/jHMMCNjUrbwPYmIddnnwwxCWXdZWQKMOCCos1eAVNHuEr0m3Zy2if5bfRIECyQceXPDpIZXyVK/xuY5YMN+BP1vCT0XVOR6TbfRwz4bOzxEAbtJb7BGdf14CofWBUNv3rmt+2vEJR03ZF4NrvLEwcjRWGjCFDPFPHtjiQ=,iv:bMHj7qyIBu1rjmwRpUyAiB4c9ejGHdVZ4wFSc+iEBKM=,tag:DsvGopQ3GJop0mLNa4Xe2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bind-dolibarr
    namespace: controller-directory
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/lldap-bind-dolibarr=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/lldap-bind-dolibarr=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3KU/DJk4/YylwSPWYIfKzgsqCApl6YgWg0OnvMBdCWSF0TtTiAi/fp27Q9qZLpMZoAB1XDtAAE4yY4ImaqW4KwT5VZ0KsQ==,iv:zbvXTCEbNOEYgH+/YnawewSIQLcZbFuotRxqlBs3gP8=,tag:uaVvG8O8nUL8GSuyqbqt4A==,type:comment]
    #ENC[AES256_GCM,data:t6+mt3Fxm/6sm44q5hUaDCkHA1gJwSjscfwT1mZOSnVw2gNqghfzVHaZj7f1X5mUetQL4zIIl3Rw2t9S3I7i7tU1/s8vIFBLgiA=,iv:+E6fqbxhNmJvIqWDrKdxINupKoluouOwQCGm8mx6OSI=,tag:vVM1UfQypcaskFHhaUsjPw==,type:comment]
    password: ENC[AES256_GCM,data:1P9l39KWCc9WNbe6JCo5UAmIvKR4aOY4/XCMI1JIyXQi0mvaR7FjxbXr+g==,iv:VQDOJIbZ4xgn5p6MfCIIOsuXrYqavT+I0YcECQ/D55M=,tag:BaMvqNEjmLJEaKp/iS/vnA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY25ZSVBWSTc0YUUrMGNm
            OXU2TjRjODcwN0pTcGNheG9NZDVEdlRMV2hzClRxTlMrUFh1bFJtT3lxL1J1K2xR
            TGRwUnJxREZpeW1IRTBZNDRpM1VBS00KLS0tIDdmL1dhMzAyMHRSZ1BWbjlUeEdk
            K2lua2crVXdKTmd5T2t3ME9VTmZXelkK9plFHfjfExHxlq4zVl8l2U1eUacP4T8I
            ZYwQgnv5OKW6uC4kWJooDsLJHaqqXy7sZQxC/y6w3p/NaRKk+nuV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T09:47:58Z"
    mac: ENC[AES256_GCM,data:V5a4E/jHMMCNjUrbwPYmIddnnwwxCWXdZWQKMOCCos1eAVNHuEr0m3Zy2if5bfRIECyQceXPDpIZXyVK/xuY5YMN+BP1vCT0XVOR6TbfRwz4bOzxEAbtJb7BGdf14CofWBUNv3rmt+2vEJR03ZF4NrvLEwcjRWGjCFDPFPHtjiQ=,iv:bMHj7qyIBu1rjmwRpUyAiB4c9ejGHdVZ4wFSc+iEBKM=,tag:DsvGopQ3GJop0mLNa4Xe2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-bind-grist
    namespace: controller-directory
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/lldap-bind-grist=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/lldap-bind-grist=true
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FxTSwVhgXqHEmtkWUAt0xTHlCV1aYodeoOaol/T2z1ENwl8kNtFLkR+TGKz5u1ccUqZom/p1iuWwwuv7USlbw454dA==,iv:1zE+ZL4VjguQr170HFPL6poo7I2IUdur60YcNb1HAio=,tag:vL8hMQESGK2WBGraVD4uZQ==,type:comment]
    #ENC[AES256_GCM,data:COMrrpREhl/lkYEU08SkL/peC7j27PlnbLN9gSsrwNzvchzvlFUyyG2hJDZgppZD0PkrDo63sM244p/0wng9bEWoLx3q5jtX,iv:7mUoiX/9Pj7l6eWAJDniATkcLRfqBV3B+GLlz5/d8Fw=,tag:4ff8WU18YgQBhQSuLjjO7A==,type:comment]
    #ENC[AES256_GCM,data:rJ4G5qt+SpE5wZcsfIpv5U3IctjDBw==,iv:SsEgIacPqjLVDNcd+t+BZLIjyG1aGitWV1q7O0Ucx94=,tag:JkWjsWkpmQseRXjn5RVzJw==,type:comment]
    password: ENC[AES256_GCM,data:VjU8wsEGzzo2Ys+jfDg/w4IhTsy1u5tzrKYQwjZNymsomgLhIb+Sakj1Aw==,iv:V4br6kFLSIlg6cr5u3Pm9TS4n5yBT/D99ppmi9nvUxU=,tag:Y6ROmRq/qaudDmGO9ZZiXA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY25ZSVBWSTc0YUUrMGNm
            OXU2TjRjODcwN0pTcGNheG9NZDVEdlRMV2hzClRxTlMrUFh1bFJtT3lxL1J1K2xR
            TGRwUnJxREZpeW1IRTBZNDRpM1VBS00KLS0tIDdmL1dhMzAyMHRSZ1BWbjlUeEdk
            K2lua2crVXdKTmd5T2t3ME9VTmZXelkK9plFHfjfExHxlq4zVl8l2U1eUacP4T8I
            ZYwQgnv5OKW6uC4kWJooDsLJHaqqXy7sZQxC/y6w3p/NaRKk+nuV9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T09:47:58Z"
    mac: ENC[AES256_GCM,data:V5a4E/jHMMCNjUrbwPYmIddnnwwxCWXdZWQKMOCCos1eAVNHuEr0m3Zy2if5bfRIECyQceXPDpIZXyVK/xuY5YMN+BP1vCT0XVOR6TbfRwz4bOzxEAbtJb7BGdf14CofWBUNv3rmt+2vEJR03ZF4NrvLEwcjRWGjCFDPFPHtjiQ=,iv:bMHj7qyIBu1rjmwRpUyAiB4c9ejGHdVZ4wFSc+iEBKM=,tag:DsvGopQ3GJop0mLNa4Xe2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
