---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rbac/serviceaccount.yaml
  - ../../base/rbac/role.yaml
  - ../../base/rbac/rolebinding.yaml
  - workflowtemplate.yaml
