apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: restore
  namespace: ${tenant}-${application}
spec:
  podGC:
    strategy: OnWorkflowSuccess
  serviceAccountName: restore-runner
  entrypoint: main
  arguments:
    parameters:
      - name: snapshot-data-path
        value: "/data/${application}-data"
      - name: backup-cluster-source
        value: infra01
      - name: workload-kind
        value: "deployment"
      - name: workload-name
        value: ""
  volumes:
    - name: ${application}-data
      persistentVolumeClaim:
        claimName: ${application}
  templates:
    - name: main
      dag:
        tasks:
          - name: scale-down
            when: "{{workflow.parameters.workload-name}} != ''"
            templateRef:
              name: scale
              template: main
              clusterScope: true
            arguments:
              parameters:
                - name: replicas
                  value: "0"
                - name: workload-name
                  value: "${application}"

          - name: resolve-snapshot-id
            templateRef:
              name: resolve-snapshot-id
              template: main
              clusterScope: true
            dependencies: 
              - scale-down
            arguments:
              parameters:
                - name: snapshot_path
                  value: "{{workflow.parameters.snapshot-data-path}}" 
                - name: source_bucket
                  value: "alter-it-{{workflow.parameters.backup-cluster-source}}-backup-${tenant}-${application}"

          - name: create-k8up-restore
            templateRef:
              name: create-k8up-restore
              template: main
              clusterScope: true
            dependencies: 
              - resolve-snapshot-id
            arguments:
              parameters:
                - name: namespace
                  value: "${tenant}-${application}"
                - name: restore_target_pvc
                  value: "${application}"
                - name: snapshot_id
                  value: "{{tasks.resolve-snapshot-id.outputs.parameters.snapshot-id}}"
                - name: source_bucket
                  value: "alter-it-{{workflow.parameters.backup-cluster-source}}-backup-${tenant}-${application}"          

          - name: wait-for-k8up-restore
            templateRef:
              name: wait-for-k8up-restore
              template: main
              clusterScope: true
            dependencies: 
              - create-k8up-restore
            arguments:
              parameters:
                - name: namespace
                  value: "${tenant}-${application}"
                - name: restore_name
                  value: "{{tasks.create-k8up-restore.outputs.parameters.restore-name}}"
       
          - name: scale-up
            when: "{{workflow.parameters.workload-name}} != ''"
            templateRef:
              name: scale
              template: main
              clusterScope: true
            dependencies: 
              - wait-for-k8up-restore
            arguments:
              parameters:
                - name: replicas
                  value: "1"
                - name: workload-name
                  value: "${application}"



