apiVersion: v1
kind: Namespace
metadata:
  name: controller-traefik
  labels:
    alter-it.org/controller: traefik
    alter-it.org/managed-by: fluxcd

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: controller-traefik
spec:
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "39.0.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: controller-traefik
spec:
  interval: 5m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: controller-traefik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    api:
      dashboard: true
      insecure: true
    logs:
      access:
        enabled: true
      general:
        level: DEBUG
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    
    hostNetwork: true
    
    service:
      type: ClusterIP
    
    deployment:
      strategy:
        type: Recreate
        rollingUpdate: null    # désactive explicitement le rolling update
    
    ports:
      web:
        port: 8000
        hostPort: 80
        http:
          redirections:
            entryPoint:
              permanent: true
              scheme: https
              to: websecure
      websecure:
        port: 8443
        hostPort: 443
        tls:
          enabled: true
      traefik:
        port: 8082
        hostPort: 8082
      metrics:
        port: 9101
        hostPort: 9101
      tailscale:
        port: 9443
        hostPort: 9443
        tls:
          enabled: true
    
    additionalArguments:
      - "--entryPoints.tailscale.address=100.64.0.2:9443"