---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: ferme-du-jointout
spec:
  owners:
    - name: ferme-du-jointout-admin
      kind: User
    - name: local
      kind: User
  namespaceOptions:
    quota: 10
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: ferme-du-jointout
