apiVersion: v1
kind: Secret
metadata:
    name: grist-basic-auth
stringData:
    auth-file: ENC[AES256_GCM,data:zO6+e7zMhLFHwpwZ+w6FyZRqWcnT4b1SZYyV13nlOls8XykW840g7tMIt09czUCc,iv:jezVyzO1xlR6h3evkTQN/CMfUYsi8VHQYaTfFZ9IhS8=,tag:7Rrmn6Vor7qT6M7Z94aumg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTjI2eG9rZllEbXJjZEps
            WU9xMFphekpNcUdkZ3AyTGlueW4yUVlQd2xRCmYrVEI4eEo4UFpFZWEvRFp6emt3
            ZHFkUG0xRGJJT1p0ZUVXdllpamdEeWMKLS0tIEpqaDJKTUVLaEpRUUI5QnlFYUo1
            N3Q3Ni9jd0hsV2tKNDZncS91WEluUTQKvmFJ4JxSslrujKsF/OFC5ddGswn7m8wy
            JZrB1SFanMDzAmUYZE5+A4hDY341dxAj5EqEdeV0PEhSq0qVlutaYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T15:28:29Z"
    mac: ENC[AES256_GCM,data:KgKSQzltGRDu6rKrkGiOYkO4xrt5LflkHXDJ5owhgtUHCnYoPsvT8mY3OQW8ME9esE6ZnK0rKhZEXG+3cDEgfpDhozp3Lr5JMMvF2TDtcw1PY4AF7kkfhkSrdXwUQdk/NmPXs8df/lsIx4LsPHG3NryPnpSCusma4+Rwxj9ropo=,iv:42s66nT6KlHu1q8pbgzGOc5UCseTyB3YbfseIC2RfW8=,tag:Pr9sAAUv+51ZWYCL1aIaog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
