apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh-credentials
    namespace: controller-dns
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:FitwWZ3MKwQ31IxpTqik2g==,iv:d4YfBi5Lj+Fkg788AvSY5cheLLoAFBLUhdwd2jOV5nw=,tag:QdDCYMlbYBX6+2JbEtw8Ug==,type:str]
    applicationSecret: ENC[AES256_GCM,data:ij9sxohLLJzrF3qVbxXVVnBJdn0SpSqORmwyUoibBfE=,iv:vHJc8QJ7vzbWJ4yI/Mno6vsH2SwvNT3QiWWMVIi15dA=,tag:+bvYkSaQdEdZNp0cTq5Lbg==,type:str]
    consumerKey: ENC[AES256_GCM,data:elNrmIxdQeIJcgCzfH+Rw8xN2bVKIFBrO3AC72IfrUU=,iv:ilUj8DiJFEQ+1F66biY4jzgGQhTakU0zJtF4SvecEj4=,tag:eA3AxwmvGVtVuezX8HL62w==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSytKeDJDK0N2WTZRSmFn
            MFFLb2IrQ05MQjVrN1c1bGFHQVphOWFhRnlZCkxhZ0l0bStTejB6cmxHL3NjRkJ6
            cnl0a3FLRVduT0pBTDdCVm1tSVhHNWcKLS0tIHdwMUZrV1diaXp4V2E4ZUFRdGFV
            bklCUlY0NzNRZnBwWWFYMTl6OUhvbVUKndMi+/GYHlnDKvmxWIVOB36Z84zRmDyG
            KCLIbl5LK8efgFsuMQDMeucGg1Gyz5OCB/aVO6pCRaE0j6FRVfS+8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU2wvNzB3OS9lK1FrdDhI
            eFJ6Vml6ckdnUnRrelVGTDNBL3RIRUhiTUNnCjFoOVBOblhKVVdFRUdSZ2FjbmtY
            cmRMZFI1TUYyb3VEdzdmdDNlZmFxZFUKLS0tIFZhVW5OZkFyRjRmWUhWS3h3OXcy
            WVh4L2pGWlRNSkRpbkJxZGY0WTdUbTQKQW6wwKqccfUtXpDEdoG5fMariSYVDbQA
            5c5Ye7aXxiI6WMd4z2TYb5KKYEZZHbeMxqaH0iUEaLJld0G5XE8f3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T13:50:51Z"
    mac: ENC[AES256_GCM,data:bkygoKzH7XxOjpyycOM3JaRqosPrGW6+kiMUUzlgng/pore2Lpb8yCsmRp7mX8/ull+CU4oLJmZJVGm+POmb5XHD3f7Scm98oNJ5K6wMZlvuWL8vpEmnL7l86YSL2Jl64UcGHOCKbAxXMoHmkJ28s61VesTUJ2RgBcbTFGYm6z4=,iv:uy6ChraOQokwzVmYWUpCXYlrYFi6Iv/y78w6wxaftmY=,tag:oufNGkLidXWzHsdX+jWmHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
