---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-wordpress-site
resources:
  - ../../../base/wordpress/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  # Rename the helm release
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-wordpress-site
  # Overrides the helm release values.yaml
  - target:
      kind: HelmRelease
      name: le-portail-wordpress-site
    path: values.yaml
  # Overrides the namespace name
  - target:
      kind: Namespace
      name: le-portail-wordpress
    patch: |
      - op: replace
        path: /metadata/name
        value: le-portail-wordpress-site
  # Add the k8up backup annotation to the PVC
  - target:
      kind: PersistentVolumeClaim
      namespace: le-portail-wordpress-site
    patch: |-
      - op: add
        path: /metadata/annotations/k8up.io~1backup
        value: "true"
  # Overrides the k8up bucket values with subPath
  - target:
      kind: Schedule
      name: wordpress
    patch: |-
      - op: replace
        path: /spec/backend/s3/bucket
        value: "backup-srv1515851-le-portail-wordpress-site"