apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:JXJ0TzmhkkAWniMXIjQVHoo6,iv:z/FTbL8ySvD6n6pu3BKCp1ZWfTIal4hZfQO2Uagf6r0=,tag:1JOrqyAnmTFpUG+jNUHesA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:60XbD4NvYWEBwg==,iv:1SPxl1/oO/YPtImHpd3MGHYqUra7jsdHXmjPe3pw0UM=,tag:WwmHTBuNj/ScjwSc3GeerA==,type:str]
    mariadb-database: ENC[AES256_GCM,data:91bLseguIB1i0A==,iv:23rcoGEs8HxzV1nu+kQdVjJ600dIGnXKr9U6xe223D8=,tag:RNlguC0DWUl00UKN4O40/A==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:/I2SozFOBXY2YKAQFMfVjGxC6EQ=,iv:80oaxcqrwZYXd068Knggh+RcdTIYoiyoxsWF9bYANxg=,tag:E0nSVW75hIQJnSnfFyAHKA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:26eMdTSa0tBD3vwe8j6ytLpu,iv:1RitdPbyH4YQvTJOonhKQBTe7o7lIkPNX1m7mczaTE4=,tag:FinR/eQJk38Efhzqw8KC4w==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:OT+wF9KvFMxKcixU9gm3rJ6/jIA=,iv:KKLCT1Tw+Nyj9I9oxA04Fe/N6WMtDtpmJsHIu9kVc0M=,tag:vl2Yk8W2KmGli851KMH2eQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDExbmhuNHdkTXVtQllh
            UnVtUnprbWxFUU5adkJjY1gzcjM3MGYwOUhnCmp4N3E5c1dlT3dBMHBDUm9DRDhH
            Qy9EUGZEbzkxSzN5V01WTDdnVFM1dzgKLS0tIFZ2Q3diMTNqMnFXTXlKeGI3VGlq
            anJsbGF2TTVoVjRXdzMrczRPdmQxMlUKZueaa28gZzU6szQ/rMhnEtcNKK2p4qCG
            B3ZxxdZcB55Q3e9/0mRzcJpDxDuhdM0XGKZs1eGwB6ynxC62kxXsWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T09:08:04Z"
    mac: ENC[AES256_GCM,data:AOBoqYUhyZOiua7gECkcXnXCIvIDTIJ860lR8zAZ80/K5XKeWzje2jCSD7RtvWERZgGk6IK3tJcyFwoPigjQDXIsCuKpoGnDy2Ipvocbm1BlFUpxM+XrIrUDS0oAPMabRsU+1eL8nmnD7PoZs26zNu4UIsP4yAynFdHvQOrpfUw=,iv:YQIwflMRnWkughxfCDaCWDP9ICBWaiRTJgFSkw9T0BE=,tag:/mRkqR6yFlfQ4gtujWXK9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
