apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:2AgXAunYZbQlAPKWgu/ijtFl,iv:L8zj9CayXyB9Q80kup6wpro/cwRsE2lFKTWODU/gTrs=,tag:Pp517U++kvfInNhUKpwikw==,type:str]
    mariadb-user: ENC[AES256_GCM,data:S+Sw6WXrNfjvNA==,iv:nX9BsCGYNR2xRrSqxwc/jwibte90UOqTr5vL8ujc9sk=,tag:xnJ6WSoye/cZokswYXJjtA==,type:str]
    mariadb-database: ENC[AES256_GCM,data:QyBeA58kUTV89Q==,iv:gO9LjrfJHST7jFiR8FkUEuDXioNNWmxp30QQMIJEhig=,tag:K3fa5L26u/NhdTtJHsa42A==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:iBlj+Xcqu1E5yF9u9ebiTO6RaFI=,iv:Jc4ORbqNsceLcDSVYevOecqlKPNmhnLECQua5/Uoj2M=,tag:Ih+8MHXKkuLwizRluRiStg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:tCmfYB2AGW0iNXncU0UlVJKG,iv:mPRNGtyKntgpKsCYJvcGBM7yEEjUlKpi1775T9Zfs9A=,tag:gidAoDNkPoueMACVTqAlTA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:YxTbLgSPQDY+PKqkb+705Do1QAY=,iv:gg70nqKryAH8up8pPPSk9+h9visCGZTOcQJvV55mEVs=,tag:sE50BaopBwK71Gr1vlTAWA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ajhROTdxbGM1bnJsT3ox
            ZExMM1Z2aER4bXNGT2FiTEVDU1lYVHBpSlhRCjJQZnV6ZmVCZ2xaYUJjZDhLYkxQ
            VmZvNVVrVm14VVlUMGQ2QkdhWnZrU3cKLS0tIE5OK0tnN1NyWEEzSC9TT2EvNHJ1
            akJOM3dscjlWNzZUUk1wUnkzVFIxd1kK3+O18l30WppOR6MSTHm89Bk9ATOvfYxi
            WsswTqE9GzTA3TQXGx8IRBi4ifAKoIHrllZ96t0L4L2D9xdcNoRZQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T09:01:12Z"
    mac: ENC[AES256_GCM,data:JWDjmEJriLYH9607lFipWiNjh5rxTLrQl2KFvF7C4iGK7ZEs/q0XZGlsxYZyjqGyfV3jloLgz2G9OdVziAwlc3vUD/oDiBUMI+bBQ8yVtDlzaAPFGmeEdgo7XWdzFcEESxizpoJCffrXqU/GSb8mw4YFcZaenjy6RBgMAkTi0ZM=,iv:xp3BF6VCQRGrdUMhP+hBwjpryNQ9IwLtEJvwCzSIdlo=,tag:cmql0Z58RzCLJkPBkok0DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
