---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant}-dolibarr

resources:
  - ../../../base/dolibarr
  - secrets.enc.yaml

components:
  # We do want to backup dolibarr
  - ../../../components/backup

patches:
  - target:
      kind: HelmRelease
    path: values.yaml