apiVersion: v1
kind: Secret
metadata:
    name: dolibarr
type: Opaque
stringData:
    dolibarr-admin-password: ENC[AES256_GCM,data:Gma1rXEXNCDjGEjrFg==,iv:EjYGgtO54CpPp1LV5vaYGPCz1dOnzMTPCImlTUWP3uU=,tag:uwSKxoCvrN6m2Ux5ek5JYQ==,type:str]
    dolibarr-cron-security-key: ENC[AES256_GCM,data:dZcKNQ107J0Bb7l3PA==,iv:REC9E5gieVHBST69QSAq196S2+y4FUMJB9LGuKX/C8g=,tag:0kdM/IRlUJehPmXdmd7MBQ==,type:str]
    mariadb-user: ENC[AES256_GCM,data:u149oEhdOLs/tSizR39eTtw=,iv:NtLwTbyNf55gk2gopw+xlXmFBhMp21ekvACHe+6hYVE=,tag:c0NONjqJx8YejWMoUz/1tQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:635nQLogi2nXJPeL,iv:p44b+npuUD/uf4+KBjPuDA4oGpL0P5fgxGRXE3buaPA=,tag:/Tp+4cxAJKLIWgjFYfg2Bg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:LPNu8C2lMRmtLWCh0g==,iv:Sh8JuwJZBB/Fz91/4UmfDIjgV2xY/tSf5hfC2UIdJV4=,tag:XWU1xNOQvIaQv1ui0QSYEQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:KVfJkgCoGjRTJV8+9g==,iv:KX/nM41IW6MMz+mmrlpnz0IVDYbLLmAeynHgH5cTnWg=,tag:YcUlsS9lLPy79ZtsaxiK4A==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:gb4nGX3cr7KmPNoYgg==,iv:2LUFsa928dA3UPfXb4WuYW4+tNkluS3pU4KM818y/vE=,tag:tCDmZr1499OXaP0ukJS4FA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaHJqMmxpN2NtN3ZrL0xk
            OXZNOUtWY05CMnRlZC9ka0hDeTlkbExMelFjClB4Zk55a0VCbWdnQVExdjZPeGJy
            UVl6WlJRS2toRXFOT0YvTmorZjk0QWsKLS0tIEhGRDQ1d2xOK2k2eXUxS1ZwL0JG
            RWVudmJYbzRQL0tBWDF6cFVlS1IzWTQKQD3/yJ7ts2Lz12QNBtkvl05V/RR/dymm
            bhJ3TF8KaNE/iEJwtVi90pTo1QToA671Fn/I/kQEJJarqm654VmlWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T11:28:10Z"
    mac: ENC[AES256_GCM,data:0jjwhl6jK5fEnOqTijSM0MGhzlCQTs80BLwqkeuf59nPAVVjfsz/r/ZKKoZ0w+/zQVsONAlF8n5fDUDX1cAkOdOQeMLUr4OYBEIBTzsgkqpzahn5nI6LUhh3LwiON73lu3vDhKfXfeCuQexO0H3gS4SB/EygsWHUISndFrZSXns=,iv:2/w+ODl34rkeb3rEtLBm2Y/6eRwQ33EYMBWIb5KiNnk=,tag:rkBgaHsIgGphaHEud9QOKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
