apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  ### 
  # Shared
  ###
  - ../../../tenants/shared/sync.yaml
  # zone & subdomain creation 
  - ../../../tenants/shared/components/subdomain/sync.yaml
  - ../../../tenants/shared/overlays/production/wordpress/sync.yaml

  ### 
  # Le Portail
  ###
  - ../../../tenants/le-portail/sync.yaml
  # zone & subdomain creation 
  - ../../../tenants/le-portail/components/subdomain/sync.yaml
  - ../../../tenants/le-portail/components/authentication/sync.yaml
  # applications
  - ../../../tenants/le-portail/overlays/production/dolibarr/sync.yaml
  - ../../../tenants/le-portail/overlays/production/grist/sync.yaml
  - ../../../tenants/le-portail/overlays/production/nextcloud/sync.yaml
  - ../../../tenants/le-portail/overlays/production/wordpress/sync.yaml

  ### 
  # Ferme Du jointout
  ###
  - ../../../tenants/ferme-du-jointout/sync.yaml
  # zone & subdomain creation 
  - ../../../tenants/ferme-du-jointout/components/subdomain/sync.yaml
  - ../../../tenants/ferme-du-jointout/components/authentication/sync.yaml
  # applications
  - ../../../tenants/ferme-du-jointout/overlays/production/dolibarr/sync.yaml
  - ../../../tenants/ferme-du-jointout/overlays/production/nextcloud/sync.yaml
  - ../../../tenants/ferme-du-jointout/overlays/production/wordpress/sync.yaml