
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
    # - name: infrastructure
    - name: infrastructure-storage
    - name: infrastructure-ingress-traefik
    - name: infrastructure-database
    - name: infrastructure-certificate
    - name: infrastructure-authentication-authelia
    - name: infrastructure-reflector
    - name: infrastructure-tenant
    - name: infrastructure-workflow
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/infra02/tenants
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age-private-key
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false