
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi