apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-grist
spec:
  values:
    image:
      tag: "1.7.12"
    loadBalancer: 
      enabled: false
    homeWorker:
      envVars:
        GRIST_DB_URL: "sqlite:////persist/home.sqlite3"
        TYPEORM_DATABASE: "/persist/home.sqlite3"
        GRIST_DATA_DIR: "/persist/docs"
        GRIST_FORCE_LOGIN: "true"
        GRIST_SINGLE_ORG: "le-portail"
        GRIST_OIDC_IDP_ISSUER: "https://auth.alter-it.eu"
        GRIST_OIDC_IDP_CLIENT_ID: "grist-le-portail"
        GRIST_OIDC_IDP_CLIENT_SECRET:
          secretKeyRef:
            name: grist-oidc-client-secret
            key: "client_secret"
        GRIST_OIDC_SP_HOST: "https://grist.leportail.org"
        GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: "true"
        GRIST_OIDC_IDP_SCOPES: "openid email profile"
        GRIST_DEFAULT_EMAIL: "ops.gpenaud@gmail.com"
      extraVolumes:
        - name: grist-persist
          persistentVolumeClaim:
            claimName: grist-data
      extraVolumeMounts:
        - name: grist-persist
          mountPath: /persist
      probes:
        liveness:
          path: /status?db=1
          initialDelaySeconds: 10
        startup:
          path: /status?db=1
          initialDelaySeconds: 10
    docWorker:
      replicas: 1
      useVolume:
        enabled: false
      persistence: {}
      podSecurityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      envVars:
        GRIST_DB_URL: "sqlite:////persist/home.sqlite3"
        TYPEORM_DATABASE: "/persist/home.sqlite3"
        GRIST_DATA_DIR: "/persist/docs"
        GRIST_SANDBOX_FLAVOR: "unsandboxed"
        GRIST_FORCE_LOGIN: "true"
        GRIST_SINGLE_ORG: "le-portail"
        GRIST_OIDC_IDP_ISSUER: "https://auth.alter-it.eu"
        GRIST_OIDC_IDP_CLIENT_ID: "grist-le-portail"
        GRIST_OIDC_IDP_CLIENT_SECRET:
          secretKeyRef:
            name: grist-oidc-client-secret
            key: "client_secret"
        GRIST_OIDC_SP_HOST: "https://grist.leportail.org"
        GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: "true"
        GRIST_OIDC_IDP_SCOPES: "openid email profile"
        GRIST_DEFAULT_EMAIL: "ops.gpenaud@gmail.com"
      extraVolumes:
        - name: grist-persist
          persistentVolumeClaim:
            claimName: grist-data
      extraVolumeMounts:
        - name: grist-persist
          mountPath: /persist 
      probes:
        liveness:
          path: /status?db=1&docWorkerRegistered=1
          initialDelaySeconds: 10
        startup:
          path: /status?db=1&docWorkerRegistered=1
          initialDelaySeconds: 10
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: grist.leportail.org
          paths:
            - path: /
              pathType: Prefix
        - host: docs.leportail.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        enabled: true
        additional:
          - secretName: grist.leportail.org-tls
            hosts:
              - grist.leportail.org
              - docs.leportail.org