apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: controller-observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:KOmK5hA=,iv:fPkBVaASjZ4RfsMqykK5TwACwkhNfJSlzKZYpzF22xs=,tag:JHAB4jLW1+1OyhlkXCxJZA==,type:str]
    admin-password: ENC[AES256_GCM,data:v32y3ZG99/GGnlP435kacpnxw5Oi2YxErfFF0GOkWZE=,iv:a98ZODt1nPJhanZWLTxufZ5bFiFbHz4oMBsonzl0CBc=,tag:KG02SJ5dKumJ1/qxLAV5bA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTGl4L1o0WENzMDlnaTNE
            M3g3azg5UVEyMHVOcldSZDJZbTljaFFsZGtZCjBOcUt2SnF2bTl1dlNVb3JTQllZ
            cjZMOTh1QWQ3VGxobG9rKzhGdzBhanMKLS0tIENtZkJUeWxPWHlEVUNBdjEyL21H
            VVFSZ2RWVENmcy94NkF4SW5La3lySzgKblXFfrJNYL2WulrlS3TNfuxQVKa44DPk
            NWHgJGBpOYuTIsZO53Twal5HPpCI6h/Cq0b7HLPDuhHevOzXOPUi6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMjBMck5xeEVKTWsyMzlH
            bDhLMEt5SHQ4WmFwbzQyRmI4bjFENmtON0FVCjRLRm51ZkVKU3YxSjgxZkdZNzYz
            Z3RGL1VRMzNRQlVhbGFZeW5EUjhWeEUKLS0tIFJmTmRuVUtzTDFNc1QwYnNBRndn
            SFpWdUtIUmtZcUcvU2M3SCtwVFhFb1kKWrRZSyso9lhNaJyMNMddb8Bq/TYLKbCD
            pGbpNONK24jHrK9uDZsePTCY82EzFYHcx59ibXdXwzFE683R/86rHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T09:32:11Z"
    mac: ENC[AES256_GCM,data:wFheb0wIPr6xVniVGjvja7DQ51oEksn8GZjKCyRFTmKdJCRILkf28iQzjLlvALzfWentAI7PyDHXk5I3aEvMJtdIcRDRtGvZLb8sq3VYJKcInm31Ieazqr3+tVBgGD+ZO+s9ayg2uvK2THbNZF5+/TBK5JW1mrfkQo+KGZJ/1v0=,iv:0QNs7AFfx8ziWXVNgmeARU7EGNgGm+FFlkhA3hQM0hE=,tag:5ynTpEDW1XnVBv1MtW1KXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
