apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: controller-observability
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dBTvSELmcg5pJ0a/tdmYJaDvFSjBmvnRDWXESHBeWZc=,iv:+IyjSAq6X4Mvu4MmbLCzirMuayyR3ikderugQgrXhDY=,tag:y3hjqVK8FSHNokzyQVK2Hg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mdc6nP4+aCjaW5UKBRgCZsfmNsMGCeWLH6y3SqAzShE=,iv:r8qeQ6IXoeCgF2Ka6hKmfytIwpfndYSLR4ZXKGLBo1c=,tag:LAt+XzXRP3hC9/Me/HIECQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLytIZC9IRm5XRW1IMWJH
            U0ZLVEhaazd4WWJXVlFmVWJ0aUhmTTh3OFM0CkZRYmVFU2h1aStFRVBIcE5MOHEr
            YmE1ZDUvTjNiZE8wczNLYkIxczdEbUkKLS0tIG1iT1FxYmtqb0xrT3JRa2RzY1lv
            WjNLbkZMLzFZZE5FUFo4c0NHNHl4ZGsKJHQakOD0eqCdnBnI0BZ3CwS0Qcv45Xh1
            fda17x94cLCaya15V5fWVziDO0tHtzFUWI7SBphGYyuwuqxUGzP3RQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd2JiU2FVbFR5MmREWTR5
            RjJQV0l2U09tVkN0SzRPNkRNaEd3UW42bm1zCnhDakozVEFiakRCSExEZ2ZRWTV5
            Y3hxQ2R6bzZtQTREelBRY1lRRUVBYkEKLS0tIDBTUG9ndjVkUGFSUTF5Zkg1WTY3
            bXcxUmw2V1d6aUt3MzkvT21aaW51ZVkK659L8PpFzyxzoCicyj1J4L49VxzZB2/i
            KhILA2S8RgVrbgXCPrKfMpzdL8JUTxTOrPLcqZmTIPP8sC0mLQobAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T10:56:42Z"
    mac: ENC[AES256_GCM,data:JQww0bZeZ42PGs7WdXkkmE+09sj8jPZ7kg7YRzgZ8u7d//40yJLLHIRpeY6Qe8iNSc9uS1XGKVMI1VKQmlei7QocFfASUS5f3/T7NDIpSiB9RgOvj3LWcDUXC+s4+xWBUmzIiIh5i1UEfCH1GrflTm/N73a8GSk4Y37nxQbOD04=,iv:QJPFSONyWdlI4kRVBFMwU5UfyWyKnTOSG97Gh5ypNz8=,tag:qAXOFvL0M/oySLrimRxz1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
