apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: controller-observability
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:grXYZgV/Rpu1CCROq0gHYrE9Q8BaDf5+mHTBHhG/hc8=,iv:aSLQBKaNRLmwx14vmeA8Ff+QbQuXIHhk4XsdNI1Ep+o=,tag:Mod6tQU8cdlMo3f5EwHhkw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gqh7hF5al0XCQxkARtVuBeBK5nNl4iytBxQmTaqjETk=,iv:SzeTivvoutuzYi8HUbFjWs+VqiITirZ5OUpyWbauj5Y=,tag:Xc7ZgULrVkLTNgAmjTI7ew==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT3N2bi9Udmt6aGN0ZDVX
            R2RBQnYzcVE1alhaOUtDd244NmZ6MVZtcUJFCitpaEp3S0hTNWE2QkYyOGVTbmpX
            ZUZTc05rcGFFUER4K3FlUzNtbkExSWcKLS0tIGFlemdPdFl6S2NYWHhDSTViSEJa
            ZXhLdU4vbUFxc3pjaVlLSXl2UlBXZTgKqiWiQfx1Wl4g5TlDx1+fX3Cd88yMFSE0
            8x8GEG70j3z/dq/l6hJX/fid8QxrGF/b90F74gJn89jwuXlcAhsZEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bFJZVjZVZnlCQy92YlVC
            MlY1QzNXNzcyOGJLdEdiWUNzR1RjMTFpM0FFCmkwZlJ1ZU5NWVpMM2VvaXEyUldH
            bTBUTkFNM0ZPR3hFZStSVDJ5N1R3clkKLS0tIFlKKzhQM2tGV3NuZnQ1S3o1OWtG
            L0dzRUtrc0lRYjhjUkdpc3M5T20zWXMKOGB+6pk89uxEPJgreo3XWWQmPa8a7c/w
            3hYodcB6QCFuOrQ//O6cNF/CbDSJX5zF1oshUL14YzUWKYQrylxVvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T11:35:55Z"
    mac: ENC[AES256_GCM,data:meUJdA6ydmxT5PvA2ymL+U5uwDX66k0OlI/IJx3w874OEte6L1VnCrKt0AtwxqGVfpRQ1CJF8uW2zAVuSJfcmu9YyJV/lgKtCkQWV9/dcaj5JvvQlM9i0Pbd+8mx3w/mlE+Z7pQ5dHff1x/0aiKAIJXhubKf+1FZOmS1l5lxuYg=,iv:/sDTd8dTx8Yvjhlo+j/xrX09/b+KUkSRi7AvQPNPTjs=,tag:I28WuvnQ7eEBnmpwW8eFmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
