apiVersion: v1
kind: Secret
metadata:
    name: monitoring-basic-auth
    namespace: controller-observability
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:qmS1r+ejnHGpLF9nSAkrBNC7aL8rQdcTII1ecvilyTkwWxxwSHKLUjHHtIK6BsQ/lCwtDEyMLdv0lPrht/npQswReY8N7Mk=,iv:3cpXLsUwkUxDS1zGLgYDrScv2Mlqie1nyyiuQmEf6p4=,tag:FBlLu6xmWBNEVQ7njSM4sQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UFpzZTdJMW56WVplR3pp
            ckZrdWpSM1lhbEZiVU9pTHMwVzA3dEhHZDIwCmFNdjFVV0RYRkFiNnJ3V2JpQmEw
            ZnhDR3U2VjN0RFBuaXR6aEYzcTBIdlkKLS0tIGZRZndBZUo4OGV2QW00K3ZJa01Q
            S21GOVIweHg0VXFSS3BSYmkxdnFsRTAKVv9hLawBWdY8Qo4SjZPRfwd1sVpiX7Y4
            vHVWMAcJBHcChW7VUUAy7YACwL3O2NGVItsRtv6Q3f3xpGSOq8N0nA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK2VOVGlOdkR5QlJINVRC
            SUdIUERmN1dYTmpMTTgxcjQ0UkozNjJRWUFRCmo2ZkpRdi9BVnYrUmpiMEtGZmpw
            bk1wMUlLRjlaVVVMZlFYZ2lGMktOZ3MKLS0tIEFIeTkyVWFQQkgrSk9oK1FjV25I
            dk1DbHBKelBtcVA1RGtwakswcWFpazQKUjKFNJgmn+fXcVHr52K9X0udHVlXK6vM
            tT2xiKsj6Bz21w8hjTP8JlBwdi8QXRtB7vZgGFoP9vAloZD9wicigg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:34:32Z"
    mac: ENC[AES256_GCM,data:GO9Q3pU0uidPieZvkqvv/KFO4iTrAYWuhAJbO7MeCo4ka1ZHl75ZP94zpZWBsH+jYYEay29XcOXVfzDPpdiWV3dV8/suVr5EmRZ3c0rrSrrBx1hxNbVrWBcRqNbY83ZI99bP8IMGRkVYgQAfVD9xK8FOt39H9u37GT4EXydEKXQ=,iv:S2W/japC6hd3bZ0M7gpoyO/lpXFVWflE8TO8U3hE288=,tag:AvI1vF5HpvztOOUWgOspSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
