apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: controller-observability
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:bUHeVMIl+E67/jYlX+YwS9Q4969ubvVOwHPXXXzmCt6Xv2rziUYed3xkajvL16rlMceLc+Pg0AJVcrvNuETiF1uEeadFTko=,iv:uJU0rU9od25Iq+m+aKdZ0e+CHN4l/t+xsxJwQKK0u8g=,tag:HIdEtqHtetI5HjJ0d0StVA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaitSZ2JwTGJkTVFiQjlo
            SjBjL0xxVFdpQ0NUbmdZMmNTRkVOWnd5MlhRCncwTktLZFkrRjBwT1lidVRSOGtD
            c0xqV3dSLzU5T3hza085OVFUa24vZkUKLS0tIHJKYkZvbE5neUVvYmcybjJFTU15
            eW5VLzFzSlVsd2JOVnVCQUN4NWJDdTAKYSz2Z0AF+5lWkeEzaoCW3j4uO1LBC0at
            zhEtB6280qPlyQdi8yaxw9xtfmWgihpjK22TiM3bc6GthqEHIL3uTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdzJReURuT2VvSjZsQnQy
            Y1VTNXJtTHFJY1Vua1JXZXM3bDVuMU1RNXdJClF0bG1rRzRFUjJEaUk2VWdjL2la
            M0pKOTZxYTc0Vi9qVk5KcFlrM3d3S00KLS0tIDhWTVVmK2RRQzkxSkJ6WWthSjQ4
            Wk9JVkJvd2hVRGlkbzZMdW9YNzJ0dGcKbSxve/do5UxXBropSrlCcnwHdmiFBfQN
            CIL3+qAxEbmgVn3JueWSzxn+bWcjM/RI8JX/ZCsMMCRSRRheTMw1Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:57:27Z"
    mac: ENC[AES256_GCM,data:tAxarKciqzO0F2MM8slhQV30Xioln+LegL7O7NYU9VZg96AJJZ3DyAuYsjQVXQ6Z1o6TLur+SY3KWGcvstogx3UiSA/cBr5tt5aF/wtbpK3dahUhdBlH1UEK4oMQrP5ujnunv+PXgj5XUHqQ8KeWynVknDDPuSEnClRA2B0BDmQ=,iv:zH11165/5LwLu23BEBKxYfOhd71M9j6kHp+Gt8SFShU=,tag:P4xXTbMTe3D3wKw7MtXOfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
