---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/alertmanager-config.enc.yaml
  - secrets/grafana-admin.enc.yaml
  - secrets/monitoring-basic-auth.enc.yaml
  - secrets/loki-s3-credentials.enc.yaml
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
  - alloy/alloy.yaml
  - alloy/rbac.yaml
  - dashboards