
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: controller-ingress
  labels:
    release: kube-prometheus-stack  # doit matcher le serviceMonitorSelector de ton Prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
      - controller-ingress
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      metricRelabelings:
        # 1. Drop tout ce qui est controller (services d'infrastructure)
        - sourceLabels: [exported_service]
          regex: '^controller-.+$'
          action: drop
        # 2. Drop tout ce qui n'est pas un service Kubernetes
        # (élimine kubernetes-crd, internal, etc.)            - sourceLabels: [exported_service]
        - sourceLabels: [exported_service] 
          regex: '^.+@(kubernetes|kubernetescrd)$'
          action: keep