---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ferme-du-jointout-dolibarr
resources:
  - ../../../base/dolibarr/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - target:
      kind: Namespace
      name: dolibarr
    patch: |
      - op: replace
        path: /metadata/name
        value: ferme-du-jointout-dolibarr
  - target:
      kind: HelmRelease
      name: dolibarr
    patch: |
      - op: replace
        path: /metadata/name
        value: ferme-du-jointout-dolibarr
  - target:
      kind: HelmRelease
      name: ferme-du-jointout-dolibarr
    path: values.yaml
  - target: 
      kind: Schedule
      name: dolibarr
    patch: |
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: dolibarr
