apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-credentials
type: Opaque
stringData:
    dolibarr-admin-password: ENC[AES256_GCM,data:jgBiLoE94sDmJ7qOlVU=,iv:BT4+zdrj69zx2nYfeWMfEcSkT1DpB7KAz+yTvjDlMVA=,tag:/mu3m+Ucq7o0VfQ2BYoOMA==,type:str]
    dolibarr-cron-security-key: ENC[AES256_GCM,data:3/dg8qE=,iv:rh0r9oOEfsPDvlVj+FSrAbaWQdzf3ThdAFS07V0UTEk=,tag:HRx/t5wCub2b3qxwVSnwzw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Nk9HdEFSdFh6UXlzTUY1
            NzhpVUNMT2k2NG53MHgwenMyTVoxbG1YcjBBCnNpQ3VWZlB2a2FPN1puTmVvT21k
            RXlDa0lYTG05dDZQTzRyTmJtR1lJdEEKLS0tIFA4a3pnU09Pc2drRDNxdEc2eHU1
            bWhtY01tNWc2QWNjUmtjMDJkalRQdTQK0UtSV+RVzj+ukxpSiHyAxWlBi8MtH3Nr
            hP1EDmNs66vijYC1LTZe5e/zHTQBs/vDj5X713wGyp8AVVqzAs/w0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:11:35Z"
    mac: ENC[AES256_GCM,data:TQWqTkXHPcJ8xcpTmzm0lD3C/cjdxStDrMkknctQ3NQbV1kpF4K0cYRavAMKZxuKmVS4gRNPMuHZfIym/1D2zLaX6hV7QOE1MJXvzyw5NPhKNhYOtQwqjiXQKW18ldYQiH4uFkguGh9oJA09xW2PJQHPwopBT1ZZH5L1sAB0RAM=,iv:k9zF1A+TVXlFpC49FegktXv81PY8LUdsJrn250gJIuo=,tag:y20epKGGeEpeYuYg36bI+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:6mRczXU=,iv:E5/UCi4j/zt32J1eYbNBme8ywxhmsKzESQbkGQupL2Q=,tag:3/jdn358ZjvL+UdE+9jDFQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:cnqQBT2RoEoXHVo8aoI=,iv:aLuBHwEW5ySLrePWTQWfffFLmd79uW48uvYUWKtIWy8=,tag:F2rSgKIQHIDecA5BQL5Bbg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:ypE6IYM=,iv:VfKxCe+F8iPDumo4USbo8yyQHjoQq8PFCr2NBccLgek=,tag:/LK54tMu7b4PrVB2GJ7imQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Nk9HdEFSdFh6UXlzTUY1
            NzhpVUNMT2k2NG53MHgwenMyTVoxbG1YcjBBCnNpQ3VWZlB2a2FPN1puTmVvT21k
            RXlDa0lYTG05dDZQTzRyTmJtR1lJdEEKLS0tIFA4a3pnU09Pc2drRDNxdEc2eHU1
            bWhtY01tNWc2QWNjUmtjMDJkalRQdTQK0UtSV+RVzj+ukxpSiHyAxWlBi8MtH3Nr
            hP1EDmNs66vijYC1LTZe5e/zHTQBs/vDj5X713wGyp8AVVqzAs/w0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T13:11:35Z"
    mac: ENC[AES256_GCM,data:TQWqTkXHPcJ8xcpTmzm0lD3C/cjdxStDrMkknctQ3NQbV1kpF4K0cYRavAMKZxuKmVS4gRNPMuHZfIym/1D2zLaX6hV7QOE1MJXvzyw5NPhKNhYOtQwqjiXQKW18ldYQiH4uFkguGh9oJA09xW2PJQHPwopBT1ZZH5L1sAB0RAM=,iv:k9zF1A+TVXlFpC49FegktXv81PY8LUdsJrn250gJIuo=,tag:y20epKGGeEpeYuYg36bI+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
