apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-credentials
type: Opaque
stringData:
    dolibarr-admin-password: ENC[AES256_GCM,data:MAtz1Y237AsH8/AgNmc=,iv:7N+FzVGPzt0trUz/jh/5ppNYKV8Mj9eNsaUsbq/2lZA=,tag:jPSMS8gvK3lMiVwON7SKUw==,type:str]
    dolibarr-cron-security-key: ENC[AES256_GCM,data:BhFv4Xc=,iv:3W+gNz0EIeCQr8r6ix5rNQCA2hOAwgrC8Gr22LKf/j8=,tag:smR/qBjQ5PeMbzhLPXa8iA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbnBqNUZLbnhFTUlETm8x
            Y3FOTlpoY2RxandFUTFOU2xoUjZQQ0kwUTNVCkc5QzZoWmJrTGxzTHZnc2tFVkxt
            dUMwa29BcVFVQ0l4dFlXRVlFbUVnYjgKLS0tIGxSWmV1OGNVTFdHcHNCUUdmREVB
            bWZuZGRCVXdPb0lNZkdHQ2xBdHFQWVkK1uNsDyUEQMxZL36jzGqHNmJtZQfSi2k4
            mGFF7X2QVsiv8q/hbUN7YcYeJkypVsJthFyORYBbIXOWYt99CQxi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T13:59:04Z"
    mac: ENC[AES256_GCM,data:ZV2iEu9MnxsASGMH2yuHA9vWspqjoXBtZR9X84rRovZ7F8z9O6UtWYrmWH32+GvhvgOsx6GEP9ojDy4dX3W4Tmi2N855+1wIKzAPDKIZdja5FTDCHqV8cS8nnNLOdpiUzib332Yjj/qoNEqgk23BBl+In5PvdwsTUNlEilBLzJo=,iv:Xyjv6hkefF2rxpfEYoxeF3t0W52PcgG2SdD0Xml93MQ=,tag:HRqJ2Z0g/h5LeFRnJSAwPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dolibarr-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:8/BzyEI=,iv:LBLa+QNHq5lJ1VuRjBkTDM9EkjkZyudtCpVlFzGzUaQ=,tag:ixZnyIIChcJsqVReR6T3+A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:DuTkHIxmRG3wToRDuKQ=,iv:C9NwxRyPPBhzsi+V2UDiihUWWn5C+jM/wYX6sqnpm4c=,tag:YsaZ62jMuuHqZy6UZcjlUw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:wX4rBHw=,iv:AlcsimseM+v9Tk8iXWxR2FMdH5d/XQ7iSDZcbhm5aws=,tag:T0KrkjbyNNpOdp2qN+m7fA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbnBqNUZLbnhFTUlETm8x
            Y3FOTlpoY2RxandFUTFOU2xoUjZQQ0kwUTNVCkc5QzZoWmJrTGxzTHZnc2tFVkxt
            dUMwa29BcVFVQ0l4dFlXRVlFbUVnYjgKLS0tIGxSWmV1OGNVTFdHcHNCUUdmREVB
            bWZuZGRCVXdPb0lNZkdHQ2xBdHFQWVkK1uNsDyUEQMxZL36jzGqHNmJtZQfSi2k4
            mGFF7X2QVsiv8q/hbUN7YcYeJkypVsJthFyORYBbIXOWYt99CQxi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T13:59:04Z"
    mac: ENC[AES256_GCM,data:ZV2iEu9MnxsASGMH2yuHA9vWspqjoXBtZR9X84rRovZ7F8z9O6UtWYrmWH32+GvhvgOsx6GEP9ojDy4dX3W4Tmi2N855+1wIKzAPDKIZdja5FTDCHqV8cS8nnNLOdpiUzib332Yjj/qoNEqgk23BBl+In5PvdwsTUNlEilBLzJo=,iv:Xyjv6hkefF2rxpfEYoxeF3t0W52PcgG2SdD0Xml93MQ=,tag:HRqJ2Z0g/h5LeFRnJSAwPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
