---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: alterconso
  namespace: alterconso
spec:
  image: ghcr.io/gpenaud/alterconso
  interval: 5m
  secretRef:
    name: dockerconfigjson-github-com