---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-redirect-root
  namespace: controller-observability
spec:
  redirectRegex:
    # Quand on tape exactement https://monitoring.internal.infra01.alter-it.eu (avec ou sans / final)
    # → redirect 302 vers /grafana
    regex: "^https?://monitoring\\.internal\\.infra01\\.alter-it\\.eu/?$"
    replacement: "https://monitoring.internal.infra01.alter-it.eu/grafana"
    permanent: false