apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    nextcloud-user: ENC[AES256_GCM,data:/wBT9NQ=,iv:tg+4VpCxvbRGwfsNnxTRdzKlna4Iuz3xHWbp4ZfGX6I=,tag:YvOoSpr6i2KBMMXyUv3u/w==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:IriAVRNNV65nmFoO2mg=,iv:pmS2ywRB7bJP6UbWv67umpvYcaykXDLp8UsP/bjVdYE=,tag:Yj43UeuRPZhSjn4jeP5McA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:S7a+rmOdE7jB,iv:GjB8Bzblc8Y8XhZGVdqMPZULsZFCT8x/xsaykzddY60=,tag:4AvJezdoR5ZjrKU0E68m8Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:e8RG7cOvSM6U4NMxL7I=,iv:UxZv2bBxp0hMbBp2M1c8QuOABpHNxXhaEytGuqKv9Qs=,tag:T8N/JxtcsLHxk8zlc0ghJw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:R89HBwOCGxOuJddiLA==,iv:O4tf8v4o0tW9+fHIk2/xyw4FSpkFJRWhaILpRDNdyIg=,tag:zwJMGsRa/8OQPNTDsCXzNQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEFaT1F2UmhNZjJzM0xC
            UkhJSWJzOWNSYzB6OHB1ZHh2TkZKcHJRc2swCkFFS2dFaTFzR0Y5enVtTW1jQ1pJ
            cXB1MVEzbWlNQTdWQ2hWZmR3UE1mRzAKLS0tIENvdnBFTlZob1Z0VTU1Vll0Skla
            VFpFMVZtaG1PNHN1R05rM2kzUDhtbTQKBxceBZxuJvCPY6mJNBrvY1yu4tU3ybpq
            s867s1rx/YyRYeBMiGCZbedsi/LdMxYnx4XkaqxMRl3Dz6BEyMpKMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T07:12:36Z"
    mac: ENC[AES256_GCM,data:WaVk/N4lxF8HBX9/JUDuPNIXGlZxZxy0xUEkfi2SJvL9+MyqlhUVd2z15mBPTODBAC7tCXmGQxL4MXb2YirAqYv0TjkOH/pSL+u1VW63PtS/5x+I4cOgu+HwZ8cSKoU4bEdFCdgkqhSvaIsRwzZIthJRJ/i07bJwJtyFB+ThD+s=,iv:WkE4Q5I/1AyZYUsZT8EDMBnAGj6J6eAc1rT6MAhR6Jk=,tag:0RxbgcK3LsCqtQ2cWnEr4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
