apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  values:
    internalDatabase:
      enabled: false
    mariadb:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      host: mariadb.controller-database.svc.cluster.local:6446
      database: fdj-nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: mariadb-username
        passwordKey: mariadb-password
    persistence:
      enabled: true
      storageClass: ${storage_class}
      accessMode: ReadWriteOnce
      size: 30Gi
    nextcloud:
      host: nextcloud.${domain}
      datadir: /var/www/html/data
      # Important : trusted domains
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array(
            'trusted_domains' => [
              'nextcloud.${domain}',
              'cloud.${domain}'
            ],
            'overwrite.cli.url' => 'https://nextcloud.${domain}',
            'overwriteprotocol' => 'https',
            'dbhost' => 'mariadb.controller-database.svc.cluster.local',
          );
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
    ingress:
      enabled: false