apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    nextcloud-username: ENC[AES256_GCM,data:hEDpZZE=,iv:nooB7hYHr5gJ6SxcXUU5+o/npNXXG+71J3joH//cRnQ=,tag:0+xVOlpIr8LVngdsFb3qDw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:Q5/8Hfx7o6txKfmFmXU=,iv:005dQe+7ahmModeGMT5z9zPT5RUZRra9bgL3pI1/wA4=,tag:5fQ6Oo+3bZLyOPHU+ARewA==,type:str]
    mariadb-username: ENC[AES256_GCM,data:BnmjtSIXtW+j,iv:iWZKGDopO9lPcY52YGldNMvftqounGFfcJBEhC3iEbo=,tag:TZg8ert33W8cuNtJQc5aKw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:9Ot+zCKFheJEhFgE2TU=,iv:CXTF/kFRGKBClyj6j00OhSnarfpGWp6cHhy0iMQEjLQ=,tag:fciXqUfYI2bxBZvMeg52Uw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:ANQWDOmCxd7I95kA,iv:sRYhqdm9gSfZkWccZkm2L7jvKh/1IPmjjI+2chCqndg=,tag:GFU8MG9U2t99ZyKPEcNmpw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYUJJai9SNVZlOW1WdXRX
            L0o3MGhZUzlzTnFBNHAya1JZS294OC9aMm53CkV6Ry9LNFpnSXd6WDIwYlZXeGda
            YkREUW1wdCtiWlcvN3B6Q0IrVUwxdVkKLS0tIEc2UFdqQzZYN0lsNklpUS9SZGE1
            ZHBtdlNMZjdpSXlkZ202eTcrcWt3K2cK3HMruNPz6+O0C9qxDq5wrVuoUS37kB+U
            vy9o3bcL/A6IEcnIpBpdv6ZUkjasXuOWZXTse+9M3cuL8hvxBmmLlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T08:02:50Z"
    mac: ENC[AES256_GCM,data:xCoGtkOD4J7jSMr78x0XOfu8wisYs84wDiELx3ei6DO89Kpag5MzdaCnE5puCRL4X5C7B41JQdGE7atyZPvn1ZEtC8IU9lLjcxU121v4SQ93zfoSTGaFHVs+OUWjQ3FqEDJ507yHB49ApTcrCGp2kK6yKvMymtA74LgGNo8/qy0=,iv:wgz2GRj4ZTwsJJRu/gpJsHyEJBtxxtFHO2Y2UgdXhkQ=,tag:bOkuzz4az3W43MUvDn5T9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
