apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
stringData:
    nextcloud-username: ENC[AES256_GCM,data:DtEUJBU=,iv:5o17t5nK+xAtOhHfIZrUfY5IMSPj3d5LBrXGmoVLdw4=,tag:rQJqkl58Q2mL3YnmWlqRNw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:0n+IwGymmQmrqiQCFUE=,iv:HB8mo/twnPTks3VnSuu6W0tVKCNa9YCoeVRAWySJYIQ=,tag:DHpLV/qS689Q8I1C3e/pXA==,type:str]
    mariadb-user: ENC[AES256_GCM,data:WS5gT8Puw3B8,iv:H61j6zgRdF2IgqluxZ2pEDlOTQpVjoV8Fxwlg+wX7hM=,tag:yBtc6SkibkJvzZcyaJ6eDw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:Xl4NPvN8BDpVqAzB1Vo=,iv:1KFPOqAiWiWH5KfrlRuPc58ljCWnvEOcansdLupzzFo=,tag:298ThRVFqTRUBxWiGppXbw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:BL1WEzk8CNC9PiuX,iv:xhfgUObRDJTO1WtKXXzLEj0M9u2uTZpPI8mK1wRJYVc=,tag:+XoPsL7K19nQlaejq3bT1Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eE5GWnoyTTNxRU9abXJX
            Qk53ckVBemdEWldoaCtIUHk4emdUdk9KblJzClFXaEFDcC9JcEttRnQ2TnVLNkVG
            ZmRkakIySXRDdDVrK1Q3VnRhVndGdzgKLS0tIHpkMUxNc2hUaUw1bER3WWIySXAw
            OHZVbEdJNEhIMklxSGU0NS9LOWF1Wm8K26nh8waOmKAapLPpKd0NKmGwuXnwPREE
            V3QMEIEAKBdMWw29jz16MOUM88BvrKb+niNaz1XDcKYX64Mz3HMsyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T14:11:21Z"
    mac: ENC[AES256_GCM,data:MGFhpzIgxRTmyHvedC0pHwvi5DyUUGIEsiYxbbvZznBnZE1nF3JWJtQesgUi5YYnPiAtZkJ8+oS7FXgr0X98Xth2jjLqA3dMqSOYmVFIYgxU0fo7QB2sWRe7t+zOBB1jo9JlPNDAOkaQo4Gg/saCnzBDke3dEOKF3JFOI7sNtlY=,iv:konCGIXyzcLdGf8xUmv/r1mNpb0eFH/ImB3W6RSzd/E=,tag:DKZQaJZWuUGSmxNxQ+xD9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
