
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: workflow
  namespace: controller-workflow
  annotations:
    external-dns.alpha.kubernetes.io/hostname: workflow.${cluster}.${domain}
    external-dns.alpha.kubernetes.io/target: ${cluster}.${domain}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`workflow.${cluster}.${domain}`)
      kind: Rule
      services:
        - name: argo-workflows-server
          port: 2746
  tls:
    secretName: wildcard.${cluster}.${domain}.tls
