apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-alter-it-eu
    namespace: controller-cert-manager
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces-selector: reflector/ovh-dns-zone-alter-it-eu=true
stringData:
    applicationKey: ENC[AES256_GCM,data:M5ckXRajY8NYJAx67VJfQg==,iv:iCmztotFtYvjBkvbWjputWFAXASKW7VR6EMjHLV3HFg=,tag:YGbx2W97nE7bIobIYxEFkQ==,type:str]
    applicationSecret: ENC[AES256_GCM,data:y15u9aU7oEqj7CZpfqW9rFD5XF+7lmczAST3qyWVajw=,iv:Xlvlm4LicaDpQIbuUrErywgy9lAD+sf3kyntLFHPSyU=,tag:G7PkHWiRxAOOLp21Y+D/YA==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:yNTkbWhnNQAYDxG7BtKTEkOjcnNSzGicraJTcxukUow=,iv:aUukpHy1vlTrbor+G63hYKQTXw6WJcCAfIZRWuH8Y4A=,tag:v0cuH+eIc+ahDGSui0YMBQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteHI0b0Jic1BJbzNvVEQw
            a2FSL29EUHUzd1FDSk16Q0RTZTVDWGJ1WUJjCmIrc3Y2dk1rZ1hiNTR0eHJPTGlk
            RXpIVXFQUHZpaXpLR2FpQVRabjBEY3cKLS0tIDZwQmlZbEYxOXlWdi9IMEtQUmlT
            LzNoQm1WZ0Y5NEJMSHovajZjNlBJRVUKVAxgZXFuQlCyhbJsX+xzVl7jLuIfDDyR
            Qm7S8B7VDg3HLlnSSaLyHfWmprh2tOGs4IvUJdD38PIE/tQKlSlh4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVRMYjhnL2RJcGEvRElu
            NmVsOVVYYUtzOVR0T3JFcDkwcjQycCtkWFE4CnpuYXR5ZmxVT3hQWnd6VXhOb1Bt
            azIzdGlsZmlOT1JxUkxEemxpMHVHUVUKLS0tIFVIM0kvN0FsZUI1cjRBYnNUVHBw
            SlNtNjJlQ25BMWpBQlhRTFVuTVl2Qk0K4OlXYnm/aZZ+kXm/aLLRJ5owuGk+pLdL
            H6V3Iz9M3jfGL4VAjsqN5cZAkHjUu0osB57D8QWHh5Myflp+skhn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:20:32Z"
    mac: ENC[AES256_GCM,data:WwgSqbk9jBGZZWHNKT01kbu95bIxFnVnSFYpcn5k4gi29xqvcpoLsqyQjbZ95IYTgAD2Fwh7N//YLFzjWegX1RaimCiL1MKLmImsfLFuGjEXUE7gExE8fCnWoUAQC99hJhb4qxbITWH4oKlTDttduchLI04jsEYbOlWaLRr9OAo=,iv:8hY7/myvnbNVBcbQBS2eXoz27sN7Cwjf7pFOSjVDySs=,tag:ZpO1h26ZbHlAtKsQkldQng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-leportail-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:Tkg5RPyjFY1Z++TA3EXRkA==,iv:BZNfKCQHJ3AtP76G+8NxdeNLocabFQm2F3D8rLVDQn8=,tag:zZl/h4DlxOb97Pkw/KnEgA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:dEXBynj5uy8Z8hr5peDnsD/pVouHnei+XNZj+TDhJ4A=,iv:ouicd5eBlNZmvF6rT8L1YI5nS0aAGI64RY/4rwMBlCk=,tag:FoS6Op39phylumB33hixPg==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:uGNFFHiPGeOsE4UE0h8uWjfalrCokSlhnjlHvAppxTE=,iv:x94EpZED8bge7uGfYb85pIvGT/KP6qXZedCjoFvlf68=,tag:oTiUy1ab2GuGOFxJg7rwyA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteHI0b0Jic1BJbzNvVEQw
            a2FSL29EUHUzd1FDSk16Q0RTZTVDWGJ1WUJjCmIrc3Y2dk1rZ1hiNTR0eHJPTGlk
            RXpIVXFQUHZpaXpLR2FpQVRabjBEY3cKLS0tIDZwQmlZbEYxOXlWdi9IMEtQUmlT
            LzNoQm1WZ0Y5NEJMSHovajZjNlBJRVUKVAxgZXFuQlCyhbJsX+xzVl7jLuIfDDyR
            Qm7S8B7VDg3HLlnSSaLyHfWmprh2tOGs4IvUJdD38PIE/tQKlSlh4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVRMYjhnL2RJcGEvRElu
            NmVsOVVYYUtzOVR0T3JFcDkwcjQycCtkWFE4CnpuYXR5ZmxVT3hQWnd6VXhOb1Bt
            azIzdGlsZmlOT1JxUkxEemxpMHVHUVUKLS0tIFVIM0kvN0FsZUI1cjRBYnNUVHBw
            SlNtNjJlQ25BMWpBQlhRTFVuTVl2Qk0K4OlXYnm/aZZ+kXm/aLLRJ5owuGk+pLdL
            H6V3Iz9M3jfGL4VAjsqN5cZAkHjUu0osB57D8QWHh5Myflp+skhn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:20:32Z"
    mac: ENC[AES256_GCM,data:WwgSqbk9jBGZZWHNKT01kbu95bIxFnVnSFYpcn5k4gi29xqvcpoLsqyQjbZ95IYTgAD2Fwh7N//YLFzjWegX1RaimCiL1MKLmImsfLFuGjEXUE7gExE8fCnWoUAQC99hJhb4qxbITWH4oKlTDttduchLI04jsEYbOlWaLRr9OAo=,iv:8hY7/myvnbNVBcbQBS2eXoz27sN7Cwjf7pFOSjVDySs=,tag:ZpO1h26ZbHlAtKsQkldQng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-fermedujointout-fr
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:6ydE7QlW5z9cY+yzgsmjAg==,iv:ldmF7GaxJwv0E2O6eeH8571OXhhiega9zUuuXbFgTZQ=,tag:UtAFYuVHBHrgG31kmVXdXA==,type:str]
    applicationSecret: ENC[AES256_GCM,data:Zg61YNnFFtvIWNfJT58zHjjyb7ANFt11RM9gsgMD2OY=,iv:Vl/CbD0EFEVNd9oN9gN2Zyq/ZH/i8t0I5pLImp8ClrA=,tag:XEHlV1zWAbIKRGjq6lCWNw==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:B2v7Y2fXq381mBCEYCLk0FZ0CBtSwxT9nQulFOUg5/c=,iv:zdYMvd2BvxuiJfTdjztWZr4BhbkUKIRW/tYHsBcOhSk=,tag:usleeh5PctMWyWYY0lwlbw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteHI0b0Jic1BJbzNvVEQw
            a2FSL29EUHUzd1FDSk16Q0RTZTVDWGJ1WUJjCmIrc3Y2dk1rZ1hiNTR0eHJPTGlk
            RXpIVXFQUHZpaXpLR2FpQVRabjBEY3cKLS0tIDZwQmlZbEYxOXlWdi9IMEtQUmlT
            LzNoQm1WZ0Y5NEJMSHovajZjNlBJRVUKVAxgZXFuQlCyhbJsX+xzVl7jLuIfDDyR
            Qm7S8B7VDg3HLlnSSaLyHfWmprh2tOGs4IvUJdD38PIE/tQKlSlh4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVRMYjhnL2RJcGEvRElu
            NmVsOVVYYUtzOVR0T3JFcDkwcjQycCtkWFE4CnpuYXR5ZmxVT3hQWnd6VXhOb1Bt
            azIzdGlsZmlOT1JxUkxEemxpMHVHUVUKLS0tIFVIM0kvN0FsZUI1cjRBYnNUVHBw
            SlNtNjJlQ25BMWpBQlhRTFVuTVl2Qk0K4OlXYnm/aZZ+kXm/aLLRJ5owuGk+pLdL
            H6V3Iz9M3jfGL4VAjsqN5cZAkHjUu0osB57D8QWHh5Myflp+skhn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:20:32Z"
    mac: ENC[AES256_GCM,data:WwgSqbk9jBGZZWHNKT01kbu95bIxFnVnSFYpcn5k4gi29xqvcpoLsqyQjbZ95IYTgAD2Fwh7N//YLFzjWegX1RaimCiL1MKLmImsfLFuGjEXUE7gExE8fCnWoUAQC99hJhb4qxbITWH4oKlTDttduchLI04jsEYbOlWaLRr9OAo=,iv:8hY7/myvnbNVBcbQBS2eXoz27sN7Cwjf7pFOSjVDySs=,tag:ZpO1h26ZbHlAtKsQkldQng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ovh-dns-zone-labergeronnette-org
    namespace: controller-cert-manager
    annotations: reflector.v1.k8s.emberstack.com/reflection-allowed=true reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces=".*" reflector.v1.k8s.emberstack.com/reflection-auto-enabled="true" reflector.v1.k8s.emberstack.com/reflection-auto-match-labels="reflector/k8up-credentials=true"
stringData:
    applicationKey: ENC[AES256_GCM,data:60QShpDHAIXnHxqIyLK1EA==,iv:EKo3W601MrcKe5Mvu/k6PkZZSPn6/1i/9BlIvnAaQmA=,tag:5dqnZZMTsGjyuPxbCfjdmw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:gy0jvBFcAG95g8c1362i2panNMOzWA/2Tfht/kHVmLA=,iv:WC0MPsaL53QHyNh7TJgAD6SACzFs3Cj1epbYSJsCoyY=,tag:wK+gZvwwWKaJnIXQSkTTZQ==,type:str]
    applicationConsumerKey: ENC[AES256_GCM,data:1eTGfydxs8qUabxs7ynhJq+QAr2wP6TzNqZNCieDFj8=,iv:Ida9kcyfPUlBni2TIi6Vl+M35Y+bCewcyFP3M0Xfia8=,tag:dOqHcTlATrR+ZnybFTVSgg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteHI0b0Jic1BJbzNvVEQw
            a2FSL29EUHUzd1FDSk16Q0RTZTVDWGJ1WUJjCmIrc3Y2dk1rZ1hiNTR0eHJPTGlk
            RXpIVXFQUHZpaXpLR2FpQVRabjBEY3cKLS0tIDZwQmlZbEYxOXlWdi9IMEtQUmlT
            LzNoQm1WZ0Y5NEJMSHovajZjNlBJRVUKVAxgZXFuQlCyhbJsX+xzVl7jLuIfDDyR
            Qm7S8B7VDg3HLlnSSaLyHfWmprh2tOGs4IvUJdD38PIE/tQKlSlh4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVRMYjhnL2RJcGEvRElu
            NmVsOVVYYUtzOVR0T3JFcDkwcjQycCtkWFE4CnpuYXR5ZmxVT3hQWnd6VXhOb1Bt
            azIzdGlsZmlOT1JxUkxEemxpMHVHUVUKLS0tIFVIM0kvN0FsZUI1cjRBYnNUVHBw
            SlNtNjJlQ25BMWpBQlhRTFVuTVl2Qk0K4OlXYnm/aZZ+kXm/aLLRJ5owuGk+pLdL
            H6V3Iz9M3jfGL4VAjsqN5cZAkHjUu0osB57D8QWHh5Myflp+skhn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:20:32Z"
    mac: ENC[AES256_GCM,data:WwgSqbk9jBGZZWHNKT01kbu95bIxFnVnSFYpcn5k4gi29xqvcpoLsqyQjbZ95IYTgAD2Fwh7N//YLFzjWegX1RaimCiL1MKLmImsfLFuGjEXUE7gExE8fCnWoUAQC99hJhb4qxbITWH4oKlTDttduchLI04jsEYbOlWaLRr9OAo=,iv:8hY7/myvnbNVBcbQBS2eXoz27sN7Cwjf7pFOSjVDySs=,tag:ZpO1h26ZbHlAtKsQkldQng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
