
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  labels:
    reflector/mysql-operator: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/force: "enabled"
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 30
      activeDeadlineSeconds: 90
      containers:
        - name: mysql-init
          image: mysql:8.4.3
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-operator
                  key: rootPassword
            - name: WORDPRESS_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-user
            - name: WORDPRESS_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-password
            - name: WORDPRESS_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-database
          command:
            - sh
            - -c
            - |
              mysql -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u root \
                -e "CREATE DATABASE IF NOT EXISTS \`${WORDPRESS_MYSQL_DATABASE}\`;"
              mysql -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u root \
                -e "CREATE USER IF NOT EXISTS '${WORDPRESS_MYSQL_USER}'@'%' IDENTIFIED BY '${WORDPRESS_MYSQL_PASSWORD}';"
              mysql -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u root \
                -e "GRANT ALL ON \`${WORDPRESS_MYSQL_DATABASE}\`.* TO '${WORDPRESS_MYSQL_USER}'@'%';"
              mysql -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u root \
                -e "FLUSH PRIVILEGES;"
      restartPolicy: OnFailure