---
apiVersion: v1
kind: Namespace
metadata:
  name: ${TENANT}-wordpress
  labels:
    alter-it.org/tenant: "${TENANT}"
    alter-it.org/app: "wordpress"
    alter-it.org/managed-by: "fluxcd"
    reflector-s3-ovh: "true"