apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mkcert/cluster-issuer.yaml
  - traefik-dashboard.yaml
patches:
  - target: 
      kind: Secret
      name: mkcert-ca
    patch: |
      - op: add
        path: /spec/metadata/annotations
        value:
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cert-manager"