
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # rbac
  - rbac/serviceaccount.yaml
  - rbac/rolebinding.yaml
  - rbac/role.yaml
  # steps
  - steps/create-restore.workflowtemplate.yaml
  - steps/resolve-id.workflowtemplate.yaml
  - steps/scale.workflowtemplate.yaml
  - steps/wait-for-restore.workflowtemplate.yaml