apiVersion: v1
kind: Secret
metadata:
    name: dolibarr
type: Opaque
stringData:
    dolibarr-admin-password: ENC[AES256_GCM,data:Q3szLMK6QysDcl2zHDg=,iv:bIaGtAjz7w5ySqetunH+/RqX9cqdxQChlfGUCh5AAzQ=,tag:D0TFvZHPDjErKxYBt0AWKg==,type:str]
    dolibarr-cron-security-key: ENC[AES256_GCM,data:rJfLJHI=,iv:i09GT93R5bSyq3LqvSjFrOI0Edc203w0Xz4zzcqX29Q=,tag:Q/rvsjrQiSeFBnMJe0Zcew==,type:str]
    mariadb-user: ENC[AES256_GCM,data:iR8J5ZijmB5aMA==,iv:f+GqjgYkAWp7QfTv4MGOU433/aeA3jTJ9XlcPDQBTdk=,tag:mIoDrBIzvB9FfBikzCtNHQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:a+oL5D663/aY2rc=,iv:F8O0lEuMCH2qSA8z91LhAWSZIWGppxXmYzWlAR6VZdA=,tag:3BThoVDYCgvHIVn2P1ukWQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:FgyiHis=,iv:clp83CPoJRnTCVgqc8mOvOjBMC2avxaKp+o5wMTiGSo=,tag:tBLQed5szmLfScFr734r5w==,type:str]
    mariadb-password: ENC[AES256_GCM,data:2mR8vlSj893zogiRxNw=,iv:k+aJ3WTFCw75dA66D8Tflb+j3nT4BAOQ176btHGAHWM=,tag:aS0uYGidnzze4t5ji+Pk5A==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:auVcIWY=,iv:emn6UadZq+ZBPNvuSsKfxM4yvHOEmlx0j6pyBEXZCXY=,tag:WM9ZxRcrNISfRdvZkM9kDg==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXI5VjgyU0pBMmRKeG1l
            bUpWcjlzS2FZRWNkVVhXRGVHUUw0SDJ5WUMwCmx6d252S2dlOUJLaWp4eEx1a1V3
            eC91Vy8walBzMjdOSENXay9JNXFJdzAKLS0tIG9wa2p2Yi9uT1dRa3RoYk5oZW9R
            OEZJQTlUallSeENJRnRjY3ZNTDlSeGsKMLQlQgQv76EbQfBJ58sQGaOJHoD35MTn
            nMOoLTYoUMqX446HA8QV6ecOOH85+nk1MDeKTordjH7YStbKoWLkZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T21:47:05Z"
    mac: ENC[AES256_GCM,data:3gG0H01ky2f+GNJxkVJD9h8NXIrbRj3F9zojyJGAVGUqdOPJqi78VpKaSGN2sxVrvsrdFslr+8ekmCoamnCXokXX9qQRcJKRNCB3n+bq/JgPkx6b1I7O4a11du9YdW86f+17XC+ESbcO21TtD+YckrvBH3Sr7U9B6M81J2YMWj4=,iv:iH0jG7g7SsKXjFeagnH6seKUuV3Vvbv1661a54RNkDI=,tag:O6kuQUWaqyE7rp7MOuExUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
