apiVersion: v1
kind: Secret
metadata:
    name: alterconso
stringData:
    MYSQL_USER: ENC[AES256_GCM,data:KtTYcIxf56UTSA==,iv:yGUdTFNAC+Ef4U3eGCu62XaI4vOl+rUm1+m8ENEePbE=,tag:9w6c+DglXtQ//yBlR5CFvQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:1zQpe5G9Uj5UrgcwZLs=,iv:w+l4MbMcO/lOrAXx3UIb9xZhS6h5NYNf+UBi23qGLGg=,tag:9Qc2aK2R7jeghFNw+QKLRw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:YN80i6c=,iv:G8YxP9S8f2kti4Vzn6lu6/eY1arYAZZnhzosRaRuKUI=,tag:WDTE7AsBVYiaSI3QQpYpqg==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:iVZ16Hca1DEqNw==,iv:E2nULAH+V10rz1D128epVkkVMNSsOdKPASNd7/iCbek=,tag:ruWpqKwhn8eYQO9NMZROOw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlRiQll6MXloQ0F5bjQ1
            NzZ0TjFJLzhmY1lEbExqT01TRGMyUjdveUVzCkxRM1RKTGtKcXRESVZudVppNmY5
            aEprRCtFbjBITGl5RWRud0h0Tkh4NlkKLS0tIEd6T2R4TUo3SFM5dVhDYlBBZ3BX
            NTc3RUZQbEtoUm5UU3NUeWR6aURVWHcK80bit6H26XbzmOWjQArJy+jowNcs6YpZ
            J42Lm3aYa2M44CXYyUnVnt4sdcjwmVPAmqFhqnpMYqTuSy+MehJV6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T13:10:09Z"
    mac: ENC[AES256_GCM,data:9G56Wb7/WnzpxBCpn64cB5NTGNhMxOHaPA/zL5SkC9peNUGocX8BP3ZzqLH6qfzDgUHU02ffY87qSUmhFLeUa9J4cd1X2phKmch3axdnwhupKe5mrx0lx9vAIqNjphpzQCwz5u5+zdCknwYwNmUfv2dcmq8hl66vYrBm3XEoBMs=,iv:wM8Fm+r1OOtgqlHcbpIupoZi5rE3kV926JK81RnmyKI=,tag:CJynpTf9cqMN8moArVkJqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
