
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  owner: alter-it
  cluster: infra02
  domain: alter-it.eu
  domain_prefix: "staging." # only for applications, not used in cluster configuration, can be empty string if not needed
  environment: staging
  tenant: shared # default tenant for shared resources, can be overridden in by-tenant kustomization
  cluster_endpoint_ip: 46.225.39.175
  internal_service_cidr: 10.96.0.0/12
  internal_service_ip: 10.96.0.100