version: v2beta1
logLevel: warn

vars:
  PENULTIMATE_SNAPSHOT:
    command: set -a && source ~/.config/restic/restic.env && set +a && restic -r "s3:https://s3.sbg.io.cloud.ovh.net/backup-${SERVER}-${TENANT}-${SERVICE}" snapshots --json | jq -r '.[-2].id'

pipelines:
  deploy: |-
    create_deployments wordpress
  restore: |-
    kubectl --context local delete restore ${TENANT}-${SERVICE} --ignore-not-found || /bin/true
    create_deployments restore
    download_sql_dump
    restore_mysql_dump
  purge: |-
    purge_deployments --all
    remove_pvcs --all

deployments:
  wordpress:
    helm:
      releaseName: ${TENANT}-${SERVICE}
      chart:
        repo: https://charts.bitnami.com/bitnami
        name: wordpress
        version: 30.0.0
      upgradeArgs:
        - "--wait"
        - "--timeout=5m"
      values:
        wordpressUsername: ${TENANT}
        wordpressPassword: ${TENANT}
        wordpressEmail: ops.gpenaud@gmail.com
        image:
          registry: registry-1.docker.io
          repository: bitnami/wordpress
          tag: ""
          digest: sha256:3d0856ab22dfc62095a7991445258609f29f7a2655580d114c5a6370bc943fa0
        mariadb:
          auth:
            rootPassword: "bn_wordpress"
            database: bitnami_wordpress
            username: bn_wordpress
            password: "bn_wordpress"
        wordpressPlugins: []
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: traefik
          hostname: ${VHOST}.localhost
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: mkcert
          extraTls:
            - hosts:
                - ${VHOST}.localhost
              secretName: ${VHOST}.localhost-tls

  restore:
    kubectl:
      inlineManifest: |-
        apiVersion: k8up.io/v1
        kind: Restore
        metadata:
          name: ${TENANT}-${SERVICE}
        spec:
          snapshot: ${PENULTIMATE_SNAPSHOT}
          podSecurityContext:
            runAsUser: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
          restoreMethod:
            folder:
              claimName: ${TENANT}-${SERVICE}
          backend:
            repoPasswordSecretRef:
              name: s3-ovh
              key: RESTIC_PASSWORD
            s3:
              endpoint: https://s3.sbg.io.cloud.ovh.net
              bucket: backup-${SERVER}-${TENANT}-${SERVICE}
              accessKeyIDSecretRef:
                name: s3-ovh
                key: AWS_ACCESS_KEY_ID
              secretAccessKeySecretRef:
                name: s3-ovh
                key: AWS_SECRET_ACCESS_KEY

functions:
  download_sql_dump: |-
    set -a && source ~/.config/restic/restic.env && set +a && \
    restic -r "s3:https://s3.sbg.io.cloud.ovh.net/backup-${SERVER}-${TENANT}-${SERVICE}" \
      restore latest \
      --target /tmp/restore \
      --include "*.sql"

  restore_mysql_dump: |-
    FILE_PATH=/tmp/restore/${TENANT}-${SERVICE}-wordpress-db-dump.sql
    kubectl exec -i ${TENANT}-${SERVICE}-mariadb-0 -c mariadb -- \
      sh -c 'mariadb -u root -p"bn_wordpress" bitnami_wordpress' < ${FILE_PATH}
    # rm -rf ${FILE_PATH}

  remove_pvcs: |-
    kubectl --context local delete pvc \
      $(kubectl --context local get pvc -l app.kubernetes.io/instance=${TENANT}-${SERVICE},app.kubernetes.io/name=wordpress) \
      $PVC_NAME 2>/dev/null || true
    kubectl --context local delete pvc \
      $(kubectl --context local get pvc -l app.kubernetes.io/instance=${TENANT}-${SERVICE},app.kubernetes.io/name=mariadb) \
      $PVC_NAME 2>/dev/null || true