apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin
    namespace: controller-vault
type: Opaque
stringData:
    #ENC[AES256_GCM,data:71OTPV7mM4QEWC8YxVOkH+4dslXHs+VWtLRZNfgNq8340kafQ6xd7MC2ugwYHpMnohz/cxeoP0nCJ/pb9r6iAhMbzfkloA==,iv:mKk7kQkY+ipbP5D0OiFIfYMEZO2bG43T/psp2QTWnuI=,tag:CEabFjKZiklaUzBmagZTEA==,type:comment]
    #ENC[AES256_GCM,data:KU696/aTBj/Bstls27eYeu/oAuP8FGiyfwNRuDwtunNN1jc04LBAyWDvQ6a1JRu3qzP1k+RTxXTbDW9a3SEvQf0HI0USN50=,iv:E227G4v+Bjh/5D3koftiO1UtZQ1R9yZP8kZhfY4EmMI=,tag:d1G2+iMLxb+8Fznb82N0ng==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:aE22MJutbhNHQwYGNRMn8AclXpFUD9UOwSVRapbnmkimcI9zn70Y0aFlmROX2Sg/TAl2iCutMMwl+wpkXfkVVQ==,iv:Kv9Dv2DhlP6tf17I2S9rQ8yyFogULKQMgO86bBm2WT0=,tag:cW9JVzip0fQ6okGyeyRiRQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b3luaDZERmRzaWVQR1Jp
            OXAvUGFXYUlsRTljOWlMUXA4TjZqckp2STFrCk0yRWVqNEdlTVIzN2wzREFpZUJP
            SlBWNEpRZ3VZdGFJaCtBd2lFUFNmOUkKLS0tIEUvMWgwbHF3OE9lT1V1WERyaEd6
            aW1ueDllNHM4TDBEbjd0RDBRaWFwKzQKtMsTzn6gJBcHLIBMaMLp/6ZvqmKzIYvt
            ywa3gIa9CTHbecMmmtJHT12bVO2NNk8V1Erj3kVWy+2MSNcQbD3RSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T09:03:29Z"
    mac: ENC[AES256_GCM,data:9QvE/pGr2D+lRKXxWrPdrbJKT0P8Ytfn2eWfbUzKi8vU9kw1k61HnO4ctrF8FarkY7wKGS++vrijSIcpZRPtiriQ9Ph4EEMsNlweNaPnktaUA1R0y/o+tTMJQQyPmU+jwswbh1tnSA4Pu/CQYzXDfOggWq0AezPO7szYSDT9cno=,iv:P324tF8U7imEWBXQRsUbl55+3KCrVFSgZZ77idkoyBk=,tag:AbnERL68ZvUr6aXnHUaDFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
