apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: lldap
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:IO0PuyNTwyUtr+cDHRPPw3c2lsg4ishF9mB3b/hIPLdFdtz35ViWXVHm6mPTbhLgztPzREvemqwbYU18riQtwA==,iv:E954zrAM+Wic5YO8BydhKdTMsDvexHXYwMh8cb3Nxog=,tag:KVFL1BdOK7nnOUePvbPBVA==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:hYQxZaNv0cB/5mpkph7D8Bo=,iv:gN7YgMfhVHxwy5MYDnAgTDwAikqwPHNDNfW+FYmOsls=,tag:47VhGARiiB2KJw9f+N1R7g==,type:str]
    base-dn: ENC[AES256_GCM,data:pu0mYPb+MdFU76R6Vj7dbWM=,iv:CMEyvq7sepDJFHsVZIFQW0OdaAbrvmvBZDdN6eVrstc=,tag:QPv2uJn+eECEzdUJIMfkcA==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:e8Ui1ZH+4h7SLqWST4IiV/qbDZqmGl2vC3bGdgK4UO4FgtwDxAWt/1oYtBAo3GTK+f9OQ34iLkSWajoIn4liQw==,iv:2+WQiXj2kFxttndFKhO7IpFM6QGNjXfCCE9szhD4bCo=,tag:7SB8urHFXfxlCHn+83Q17Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM2R1dmIydlRKT2pNMXFS
            REwvVCtIekIzTjdYOXo1RWhPYys1ZHR3QWpBCnBINjNrbVhTbm45SGtTWE52VGds
            MGhjT1M3ZlppMXBLU29pTndFMnZzZXMKLS0tIGR2Q09iNkd6L25pbnduejJ6bkdt
            RnVoVE9Gdm02TFpQZGl1UFU1ZG85dDQKT1pidV6o8fsQ3sKQ5/bbtZdSlfgYlBdn
            /ay6EEpgI10Yt9fEbUS/Yo0MwXObHMvJ3keFBNNYarL5zGkAheMNiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T08:55:56Z"
    mac: ENC[AES256_GCM,data:gc+p5SzSWdOBQSASuHOiEGv4V7KGi3DU59RS2q3WBjzdcKjfYfS3Q125OksLAHwG5gARIzDEaFQDjTg+JvvxtUVqF7cLgYAY28SIKuFzfrSxXBVDy1xVtXHhZNI7Tcf1XFhcNB0a5wTvdiufZ1wOUsFjM75ir5nQZiiPS+XXB8I=,iv:OukgGEHVVYUFyopPBnFAm76kgG8Uf4OqyrWWkVx029o=,tag:AnFL9yuieFPlHQuEwkGfzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
