apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: controller-directory
type: Opaque
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:MZLzeSCeFKx4p4x6TX9QQKEIoSPFKSug9YiK8Wb/iTNdIXPsdyH4PAF8cNbA6ulNSiHnTDmsimS2jEdAubn4VA==,iv:AGj8KlYAy5kMk9rCDQagdR4UXuruYlqSZM+CwRepLfc=,tag:EDaKNWzJqcS8at6tJ50S+g==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:8kUcDVeLTPcHsWeSnBVAV54=,iv:CoH+XxsYhAUuRWnVJtRXcJg+kd3y7voK6LcyrUoG5wg=,tag:DEnOnjHlED7/b75M6NdYag==,type:str]
    base-dn: ENC[AES256_GCM,data:CTyp/PH8/TZx8ocwSw1wa2k=,iv:g22sOMov7A2H+ewLtlc81AD9Y5GJ/y/48Ciek2Ng67I=,tag:r8JGCvnm1Ih7A8zqyfOD8w==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:fxyHvFhdqjE3RjYxF/+6mlMkGPMZi3jS+gaH2CFGVTlpqW0JduM8rjrXsgJ6RCJm8aWDALxW13xlpRyNShrNtQ==,iv:FrlLEa/ZGpgnE7YZtBjR8zDWkgP3W+8/GCrAWP6BPJM=,tag:/VVY+cAe48GQcT/7VIFz4g==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTkZGQ0M0amRqVHFPWnBw
            TU95LzdNR2UxdmtCRnA2ejVsOVNaUGwvMkhrCnNCbE9WNjgyMURuRkRROHFHOUdL
            NnhqV25aUkJLYmpBY3hEa3YyTVBtUm8KLS0tIFNNSjM0NkVaZ2dXUkZ2ZEVuN1I1
            K25PbnZmRTI1MnZQamkrRUpCN3VtUXMKG06z+xGvf1KDwp64LqJEvTyXdDy+MUvN
            OV4pkW4nrUyHWg2rMZYyXiQq9gSG9WmfnT80F88DLHhcC0L8wpD03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T08:58:10Z"
    mac: ENC[AES256_GCM,data:E9XQKcQEodRRQdv7F0fW+7Yplilv4RL8C1DONCdCaGLRRhd3Qt0pozRzXGCJUgmBGj/XnQhtscb/j7QI2QSUK5kFGqDahGPFuB2vwAwHSqgImTKj3BlzkFjdiPFlYuVNypkMY6cuu8yd6m9ybXz1zi88mvNY8OyAe7i0V5V7bWI=,iv:pl/YHQNMx+pdiro2IpKhhnt57k5yIxqh5Ygw94gDHGw=,tag:1MM+lzqxwbXZG4pisVOBiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
