---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-infra01-alter-it-eu
  namespace: controller-observability
spec:
  secretName: monitoring-infra01-alter-it-eu-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "monitoring.infra01.alter-it.eu"
  dnsNames:
    - "monitoring.infra01.alter-it.eu"