---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-leportail-org
  namespace: controller-observability
spec:
  # Nom du Secret qui contiendra le certificat (cert-manager le crée)
  secretName: monitoring-leportail-org-tls
  
  # ClusterIssuer existant chez toi (DNS-01 OVH)
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  
  # Renouvellement : 30j avant expiration (Let's Encrypt valide 90j)
  renewBefore: 720h
  
  # Le DNS demandé
  dnsNames:
    - monitoring.leportail.org
  
  # Durée du cert : 90 jours (max LE)
  duration: 2160h