
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-version-5-7
  namespace: controller-mysql-operator
spec:
  secretName: mysql-operator
  instances: 1
  tlsUseSelfSigned: true
  version: "5.7"
  edition: community
  router:
    instances: 1