
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-version-8-lts
  namespace: controller-mysql-operator
spec:
  secretName: mysql-operator
  instances: 1
  tlsUseSelfSigned: true
  version: "8.4.3"
  edition: community
  router:
    instances: 1