
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: controller-mariadb-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "26.6.0"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system