
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: pre-backup
  labels:
    reflector/mysql-operator: "true"
  annotations:
    k8up.io/backup: "true"
spec:
  backupCommand: sh -c 'mysqldump --no-tablespaces --skip-set-charset --set-gtid-purged=OFF --single-transaction -h mysql-version-8-lts.controller-mysql-operator.svc.cluster.local -u $WORDPRESS_MYSQL_USER -p"$WORDPRESS_MYSQL_PASSWORD" $WORDPRESS_MYSQL_DATABASE'
  fileExtension: .sql
  pod:
    spec:
      containers:
        - name: wordpress-db-dump
          image: mysql:8.4.3
          command: ["sleep", "infinity"]
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-operator
                  key: rootPassword
            - name: WORDPRESS_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: mariadb-user
            - name: WORDPRESS_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: mariadb-password
            - name: WORDPRESS_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: mariadb-database