apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:2cRxRdrOvMHs,iv:jOcF60pSEVRdfAqSZbBnv9vd9PHvQDAKSaXyCbjaX0o=,tag:uqqNxnoAL0sXyWoU1U2nWA==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:xiCcoRi5edWxbMfuco4=,iv:gRP9kATWyDAStAuHYOejYZ7OKoHTNWosVqrnqXnesVY=,tag:JKXj1P7RzmNpWKRLPtjpmw==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDFuZGR2STZzSktqb0NP
            OCtGQzZnZGxrWnZmNUJ6aDVyNUE5YUw2cXdNCnkwaWxqRXZFaktId3hFLyswaWNP
            NVlKTVljYVhyMnpuUlNaSnhDTEdqSGMKLS0tIFBmR2ZLU2dHYXh6emF2RmhGcmxu
            YWpMWVJUQ1hRTFFPa3QyazlMRksyNVkKnFZCQdRBEYoM1qEDF9YH/8eyD1DSgomz
            9sx5f9014aOIjMN5xLnFcLmNHHB32QZYbxNxA8OgqrDtixnSc5eIig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:29:12Z"
    mac: ENC[AES256_GCM,data:lHYUpSXXSUiGlPxf8w7dAYfosOE+PD2T5HdOPhq9CXmo3hU3ewkPixlDDwz6wMPznIcoh6DSpYPR+bssGLX+irQCTlY8/znYZ9eruqHcPnz29u170NK64YeOb4bOD4StkS+H/8nfv0dYYiev+16QOmC6rrRsjWVJ+vYnjiLJPYI=,iv:Z+qK6ooxCqDHAf2/VSOykHwrjwGwlrYFAii8UWHnQYo=,tag:d0I0U6NnhKV7Egwxy+yWVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:ElIgPrM=,iv:qHMRa/qz2ooqvlBqSOMtock9/kL9KNyG1w6vbl8Q8ZI=,tag:L4Ph4z8penKvoJnZZ12VCA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:SKzCwEJq2W0YTxQ7tAw=,iv:D/S7TjbEICjdCQZLc7cu2yNt+Fzq9SbTklPwpubiZxQ=,tag:l4tTxJjS3VXOcKA4fqnpSw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:LSDo0dA=,iv:HGYqikaRiObplt4OsQ0JjLrEt2VfiHVdfAWuj5luX4c=,tag:3RFqGXjGL75SPRbUAl0Q/Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDFuZGR2STZzSktqb0NP
            OCtGQzZnZGxrWnZmNUJ6aDVyNUE5YUw2cXdNCnkwaWxqRXZFaktId3hFLyswaWNP
            NVlKTVljYVhyMnpuUlNaSnhDTEdqSGMKLS0tIFBmR2ZLU2dHYXh6emF2RmhGcmxu
            YWpMWVJUQ1hRTFFPa3QyazlMRksyNVkKnFZCQdRBEYoM1qEDF9YH/8eyD1DSgomz
            9sx5f9014aOIjMN5xLnFcLmNHHB32QZYbxNxA8OgqrDtixnSc5eIig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:29:12Z"
    mac: ENC[AES256_GCM,data:lHYUpSXXSUiGlPxf8w7dAYfosOE+PD2T5HdOPhq9CXmo3hU3ewkPixlDDwz6wMPznIcoh6DSpYPR+bssGLX+irQCTlY8/znYZ9eruqHcPnz29u170NK64YeOb4bOD4StkS+H/8nfv0dYYiev+16QOmC6rrRsjWVJ+vYnjiLJPYI=,iv:Z+qK6ooxCqDHAf2/VSOykHwrjwGwlrYFAii8UWHnQYo=,tag:d0I0U6NnhKV7Egwxy+yWVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# Secret associé
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec-wordpress
type: Opaque
stringData:
    WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:lt95CozwO5ua3TCisOI=,iv:gTJd4uNgWFQTvKvOqjPQ10QMblhB+czAzZ+YagUvgzk=,tag:kBQwGdYNbS4+T+zEtPnV5Q==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDFuZGR2STZzSktqb0NP
            OCtGQzZnZGxrWnZmNUJ6aDVyNUE5YUw2cXdNCnkwaWxqRXZFaktId3hFLyswaWNP
            NVlKTVljYVhyMnpuUlNaSnhDTEdqSGMKLS0tIFBmR2ZLU2dHYXh6emF2RmhGcmxu
            YWpMWVJUQ1hRTFFPa3QyazlMRksyNVkKnFZCQdRBEYoM1qEDF9YH/8eyD1DSgomz
            9sx5f9014aOIjMN5xLnFcLmNHHB32QZYbxNxA8OgqrDtixnSc5eIig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:29:12Z"
    mac: ENC[AES256_GCM,data:lHYUpSXXSUiGlPxf8w7dAYfosOE+PD2T5HdOPhq9CXmo3hU3ewkPixlDDwz6wMPznIcoh6DSpYPR+bssGLX+irQCTlY8/znYZ9eruqHcPnz29u170NK64YeOb4bOD4StkS+H/8nfv0dYYiev+16QOmC6rrRsjWVJ+vYnjiLJPYI=,iv:Z+qK6ooxCqDHAf2/VSOykHwrjwGwlrYFAii8UWHnQYo=,tag:d0I0U6NnhKV7Egwxy+yWVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
