apiVersion: v1
kind: Secret
metadata:
    name: wordpress
stringData:
    wordpress-password: ENC[AES256_GCM,data:lSdCslQYYgBaYA==,iv:kpF3jNEFSJGd06A2+7nt/ay9iKT9rVLrZOAneQjDpNg=,tag:784FcHaX6r82uLZKGfst2g==,type:str]
    mariadb-user: ENC[AES256_GCM,data:ABrwAQ1nqmyWqP17O1pRlg==,iv:8YLka2xN8ZXQxNiil4a0lZQ91aQOuAbSuTJLK1BCw4Q=,tag:OqjDFg1nh2yuciWtxjuPGw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:OKP7EHv38Q==,iv:rioaoNwJ0PvF6LtpN3zo7k181cIcpXK+Hio3n8KiEkM=,tag:Xlmd+0/A+xw+dgAxSl/toA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:ym+en19g5DGH,iv:KW4StRE9OdPhx+lCeF/l8UCBfmq2wJdPJUg3lofSiHQ=,tag:96caaBwjfYnERYAQYu2VEw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:GMGCzX4zesupBQ==,iv:3Zxn7O//3OGOvOXNV98VCubB5KfPxXVXU2S+Q66BZSc=,tag:jlL651NOinM5LERdb42k6g==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:ic2/MGOBFXkp,iv:vd0DjB/JuO6mJPrm2LZYCxYviKNC7jwurNban9cMmj8=,tag:joIRYlfKa73OS8Kj+E69TA==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZVFTWTNWUlA0YVoyQnUx
            NzZuellNREsyZGV1bGMrS1FIQmlQWGZIOUJjCjBkSXVPdGJ3Ymtlek44MStaQ3A0
            bkNGOG05U3BvbEdtejVjRlFOTzdjSUEKLS0tIEk4YVYzdXpuTEpPQU80ZnRxYUtt
            dldjTWlLVmZGNU9Td01zM3grcnFHZncKLfJti+zgua4vdFfeGCiamuxdw77N/gDk
            lccTjk6CRMEr9HXScmz+1L1iRmQXdhmU4Ch/cku4LH1N7vCTk0dQng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T20:32:06Z"
    mac: ENC[AES256_GCM,data:oTPp9EHMNEr5XWCF3epPVE4yQqghtXitdTveK9VAjXgO6OKnvttB0dapG7Q7RKRpVJ87t3s55VB4/TB+abfuX6BBdn8So7ZVXRtRcE/4Xq10eCCNNIcZmL58AN8aRmGIBzk6jAkJ7DYSaMUgKs4NiQ/3uZXQgh6PwPpFXxUV5Aw=,iv:ZcM1jMB58U+P31vYsWV4YOiO+3j1KtNd8+3P4FXXzRo=,tag:n3Ul2bjvhTUcPZVIn5Wbcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
