apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  values:
    image:
      debug: true
    wordpressUsername: la-bergeronnette
    wordpressExistingSecret: wordpress
    wordpressEmail: contact@${domain}
    wordpressHostname: www.${domain}
    overrideDatabaseSettings: true
    mariadb:
      enabled: false
    externalDatabase:
      host: mariadb.controller-database.svc.cluster.local
      port: 3306
      user: la-bergeronnette
      database: lb-site
      existingSecret: wordpress
    wordpressPlugins: []
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: ${storage_class}
      size: 10Gi
    ingress:
      enabled: false
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    initContainers: []
    volumePermissions:
      enabled: false
      resourcesPreset: "none"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

