apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:rI9wumONpdFj,iv:GNBb/V76oANsvkhH4km7XZ5+/CgMgzISXfVCUCqW650=,tag:nK9EewzwsEjhVyBoBeHpfw==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:CuDjIo4oPThcOJGdM+E=,iv:PbwIomDRXtReklKh0+6EE/CaNVVkIN7YR9SNAuirSUI=,tag:Z3zDtQ6r0k5XwkNlM/9zVg==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUnJSL3R1UVRaTUZxWVZT
            cUdRc2Z3QnhDa29mL1g1NjdCblB4QzFMMkdRCkJaTTc3b0I5Q1NFNWxuejF1OC9B
            ckdnTnY2V2E2alVZNEpjQ1FnYUdsaGMKLS0tIGt6S0tuOFRnTHc1RUx0aVBVZUhG
            U3VkcUU0dDZ0dmNzQjMzYnFZbFRmM2sKPcbXO4Woeu21b3Wc4wlyWcB08/pbigXs
            WNCcBTrQX0fMQ9001K1vJhFajQ9jGBGX4GiF+uK/aRhNSRjeBkqILQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T07:29:00Z"
    mac: ENC[AES256_GCM,data:MWG4VufxhB+0sNYRMGDX88xAVW81U+Yus8F0ZjOqZW5j0jmPPnVIMNLgbc5fdOEJNSiLslfP3ME+bTp6NzTToweFrrYRRDgW0N7WX+5l/TSVlgz/HOw48ujIPT+ndNBuHFNgUiTq6zE57/3o6mkfQ5PZ7KX3I+73eL36/ff7eVk=,iv:1ma7KwQe0wTNOVrHIM49QP2mu3t1LQxtxPvAf+RA5ME=,tag:8GQy8IdpDqdW1mciAnks4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:4JzpMJw=,iv:PYF70iBaSoK+XrNbG9rFjGh0+GI6z8SmmsoeBb8XBHU=,tag:rRKEf2wS0ljRTZ79MUa66Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:yFfdhMcSK2E0ahoqABU=,iv:b8SP6O2csmghVpQ6JkYSef5QUNuJRO6HvTpfPwIfmSA=,tag:eWSMIE8AaQxO0hIqXXgEvw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:TFRLurA=,iv:++7hVBTH9e8LSqtG3mOagcCK5poW7EJYMo/2d09Ht9E=,tag:35fXr6UkJ7MkCpygSKvhFw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUnJSL3R1UVRaTUZxWVZT
            cUdRc2Z3QnhDa29mL1g1NjdCblB4QzFMMkdRCkJaTTc3b0I5Q1NFNWxuejF1OC9B
            ckdnTnY2V2E2alVZNEpjQ1FnYUdsaGMKLS0tIGt6S0tuOFRnTHc1RUx0aVBVZUhG
            U3VkcUU0dDZ0dmNzQjMzYnFZbFRmM2sKPcbXO4Woeu21b3Wc4wlyWcB08/pbigXs
            WNCcBTrQX0fMQ9001K1vJhFajQ9jGBGX4GiF+uK/aRhNSRjeBkqILQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T07:29:00Z"
    mac: ENC[AES256_GCM,data:MWG4VufxhB+0sNYRMGDX88xAVW81U+Yus8F0ZjOqZW5j0jmPPnVIMNLgbc5fdOEJNSiLslfP3ME+bTp6NzTToweFrrYRRDgW0N7WX+5l/TSVlgz/HOw48ujIPT+ndNBuHFNgUiTq6zE57/3o6mkfQ5PZ7KX3I+73eL36/ff7eVk=,iv:1ma7KwQe0wTNOVrHIM49QP2mu3t1LQxtxPvAf+RA5ME=,tag:8GQy8IdpDqdW1mciAnks4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# Secret associé
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-gaec-wordpress
type: Opaque
stringData:
    WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:bx/boSl6q1Jy4ZnIvmQ=,iv:mpgWjQ3qhIwsI9qc5mQTeOoRrvPMAsCER4K+1K22J2g=,tag:09jPEpa+m8PmTh1+HiCnmw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUnJSL3R1UVRaTUZxWVZT
            cUdRc2Z3QnhDa29mL1g1NjdCblB4QzFMMkdRCkJaTTc3b0I5Q1NFNWxuejF1OC9B
            ckdnTnY2V2E2alVZNEpjQ1FnYUdsaGMKLS0tIGt6S0tuOFRnTHc1RUx0aVBVZUhG
            U3VkcUU0dDZ0dmNzQjMzYnFZbFRmM2sKPcbXO4Woeu21b3Wc4wlyWcB08/pbigXs
            WNCcBTrQX0fMQ9001K1vJhFajQ9jGBGX4GiF+uK/aRhNSRjeBkqILQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T07:29:00Z"
    mac: ENC[AES256_GCM,data:MWG4VufxhB+0sNYRMGDX88xAVW81U+Yus8F0ZjOqZW5j0jmPPnVIMNLgbc5fdOEJNSiLslfP3ME+bTp6NzTToweFrrYRRDgW0N7WX+5l/TSVlgz/HOw48ujIPT+ndNBuHFNgUiTq6zE57/3o6mkfQ5PZ7KX3I+73eL36/ff7eVk=,iv:1ma7KwQe0wTNOVrHIM49QP2mu3t1LQxtxPvAf+RA5ME=,tag:8GQy8IdpDqdW1mciAnks4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
