apiVersion: v1
kind: Secret
metadata:
    name: ${application}
stringData:
    wordpress-password: ENC[AES256_GCM,data:hN0hzMNU+p6WQIaa,iv:ZUaf0scPNs3/MrHItDQ7sq2e6lSGXoK+LaoZ17CYHos=,tag:OPVGwadOMXoehFzvruJVig==,type:str]
    mariadb-user: ENC[AES256_GCM,data:lomf6GxJ7QsDRm08,iv:hG74oZfCLJcqK8Cnrn1lBFnoQ4OxowXX0LWd5NwBOtE=,tag:QUsobodxYMDlf7ah3i0rxQ==,type:str]
    mariadb-database: ENC[AES256_GCM,data:jvgEfmprYA==,iv:LgDebu73g1lrUwgwyN8U7Ar2NcqdLgYqurdhGDSHbjQ=,tag:b2WNcE/pzMJvwjxtTg2NAg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:8CbpZqm09FPTAqpF,iv:Z11wHRZ2uz672pNzWcZ6CsKOGZqz/emht1LlrDo7TvE=,tag:kPrbzZ7+LuuFTGpDOP9tKQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:vKoAzh1lbpmJcvZ4,iv:auqTm/0zF/2RMEmXxy3CYFRZLmA+V6LeKUcgYiyGsRM=,tag:bVoDQpLGwpklcdn+klAE/Q==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:6E0EKP46wvBQz1iI,iv:jlDjUcNL2/OhEPRCwWXYo0WPEYfwAo6g3+KTvqTfat8=,tag:LdQqqMCJ8rc8FvNMvi4NfQ==,type:str]
sops:
    age:
        - recipient: age1jhryunagv39ar3p9x4zcssh26qnyeqsfurjrjnn59y0g949sc9ms34ljlp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMlRiN3lZRmo2eDJPMGND
            Mm5DcHNxN1N6OEQ4ampuN3RrWVdXOTB0ZDJNCkZRay9ta0NMOFA2V3FBQXIxMGhv
            K1cwWVJ3Ty9vNGZCQlI1Mll1b1RRYVkKLS0tIE80ZFZzMkZ1bXVtL1RQbXNxbm9G
            eWE1ZXBUSU91TjdZREVHSlZiZWZ4ZlkKp1FHcNy2CeNa+uOrFTOLSNR9BPRBCxpF
            Vj9/2Muf8QTsOyn+5PMuM51lo0nOWY64FUYJZoZAdP3zax5NHuigTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T15:18:32Z"
    mac: ENC[AES256_GCM,data:JRyF6sluK1KdbxlFZPk236BJ6GOY9DPCZ4TgoSM4Uoje6xqPkDzIQ8lqsUmT8zwBSv0t74ciurnVqs1BSgLqiwOKtOUM6/VbnmzkcL/ahh2BMz9ky4w09S5+elLJ78XiFl1K7SUvagWZif4wzfKV6NNPIF4/J2L3sUvGbifMN10=,iv:+Wga0E+fz1hVhRBXOG3V0OESoPHvk+IhCda3f1UC7fU=,tag:NZu1elkS86sPLqPpAFBG+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
